### PR TITLE
Check added for organization id with toast telling the user if org-id is missing

### PR DESCRIPTION
**Pull request by harshkumarkhatri**
**What kind of change does this PR introduce?**
This PR fixes [issue#561](https://github.com/PalisadoesFoundation/talawa/issues/561).

**Did you add tests for your changes?**
Yes

**If relevant, did you update the documentation?**
No

**Summary**
I have added a check for the current organization id. If the id is null, then the user will be popped out of the add event screen and a toast will be displayed saying "Unable to create an event.\nJoin an organization to create an event."

**Does this PR introduce a breaking change?**
No

### CODE REVIEW

**Review by Sagar2366 — APPROVED** [review]

**Comment by Sagar2366** [comment]
@harshkumarkhatri one of check is failing on your PR, please have a look.

**Comment by harshkumarkhatri** [comment]
Hey, I tried running the tests again, and mostly all them were passing as expected. I have attached the ss from the tests which I have run.
I have tried going through the greeting pull_request which is failing after 34s. I can't find much info over there. After going through some threads posted by some other GitHub users facing this issue, I figured out it could either be occurring because of some tokens which are missing or the repo is not accessible by me/my pr.

image
image
image

**Comment by Sagar2366** [comment]
@harshkumarkhatri Can you open new PR with same changes ? Looks like there was some issue with Github action.

**Comment by harshkumarkhatri** [comment]
Added another PR with the same changes which are made in #627

**Comment by Sagar2366** [comment]
@harshkumarkhatri resolve the conflicts on your PR.

**Comment by Sagar2366** [comment]
Closing this PR as you opened new PR https://github.com/PalisadoesFoundation/talawa/pull/679

**Pull request closed without merging**
