### PR TITLE
Updates on registration screen UX refinement

### PR DESCRIPTION
**Pull request by CyberWake**
**What kind of change does this PR introduce?**
UI refinement in registration page with updated autofocusing text fields and removal of deprecated material widgets in registration screen and create organization page.

**Did you add tests for your changes?**
Yes, tested rigorously on android and iOS

**Summary**
To enhance User Experience I was compelled to make this certain changes so as to satisfy the end user.

**Does this PR introduce a breaking change?**
No, This doesn't introduce breaking changes. I tried to update the image_picker dependency to the latest once which caused many more library to break hence will we updating those changes separately in different PR.

**Other information**
#220

### CODE REVIEW

**Comment by AniketSindhu** [comment]
Please create an issue before working on a PR. I was also working on the same,

**Comment by Sagar2366** [comment]
@AniketSindhu @CyberWake  avoid duplicating work. There is so much to contribute to this project. Use your bandwidth correctly.

**Comment by CyberWake** [comment]
@AniketSindhu  please reply to the issue at least once so that others may also know who are active on the particular thread. @Sagar2366 I'll make sure this doesn't happen again. :smiley:

**Comment by AniketSindhu** [comment]
@CyberWake No problem buddy you can continue on this. :)

**Comment by Sagar2366** [comment]
Closing this PR as these changes are already added in https://github.com/PalisadoesFoundation/talawa/pull/239.

**Pull request closed without merging**
