### PR TITLE
[GSOC] Add functionality to Edit and Delete an Event

### LINKED ISSUE #906: Add functionality to edit and delete an event .
**Is your feature request related to a problem? Please describe.**
This is for the code rewrite. App with the new UI does not have the functionality to edit and delete the event. There should be functions for the same.

**Describe the solution you'd like**
In the old UI, the options to delete and edit the event were shown to all the users. But only the event creators are able to perform the actions. The option should be visible to event creators only.

### PR DESCRIPTION
**Pull request by utkarshshendge**
**What kind of change does this PR introduce?**
Added functionality to Edit and Delete an Event. This can be done only by event creators using the speed dial.

**Issue Number:**

Fixes #906 

**Did you add tests for your changes?**
No

**Snapshots/Videos:**

https://user-images.githubusercontent.com/57677520/124155363-081cb680-dab4-11eb-938e-14050df59e59.mp4

**If relevant, did you update the documentation?**
Not required

**Summary**
- Now only the creators of event can edit or delete event.
- Added edit_event screen with MVVM
- Added  flutter_speed_dial: package

**Does this PR introduce a breaking change?**
No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by utkarshshendge** [comment]
@palisadoes @DeltaHarbinger  please review the PR.

**Comment by utkarshshendge** [comment]
Please note that the event does not disappear from the UI after deleting it. we need to reload the app for it.
As for editing the event, everything works fine.

**Comment by utkarshshendge** [comment]
> Please note that the event does not disappear from the UI after deleting it. we need to reload the app for it.
> As for editing the event, everything works fine.

UI now updates on event deletion

https://user-images.githubusercontent.com/57677520/124966545-13865980-e041-11eb-96e7-be633124a2c9.mp4

**Comment by AdityaBirangal** [comment]
It would be nice if we add popup to confirm before directly delete
like "Are you sure to delete ?" Yes/No
@utkarshshendge what's your thought ?

**Comment by utkarshshendge** [comment]
> It would be nice if we add popup to confirm before directly delete
> like "Are you sure to delete ?" Yes/No
> @utkarshshendge what's your thought ?

@AdityaBirangal yes it's required.

**Review by DeltaHarbinger — APPROVED** [review]
Everything looks good

**Pull request merged**
