### PR TITLE
Restoring functionality to analysis_options.yaml

### LINKED ISSUE #1512: Restore functionality to analysis_options.yaml
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

**Describe the bug**
As part of PR https://github.com/PalisadoesFoundation/talawa/pull/1510 for upgrading the flutter code upgrade to `v3.7.0`  we made edits to the [analysis_options.yaml](https://github.com/PalisadoesFoundation/talawa/blob/develop/analysis_options.yaml) file.

**To Reproduce**

Run the current suite of tests and they all pass. This is because some checks have been disabled

**Expected behavior**

We need to re-enable:

- `depend_on_referenced_packages`
- `avoid_dynamic_calls`
- `deprecated_member_use`
- `lowercase_with_underscores`

Run the checks and fix all the resulting  errors 

**Actual behavior**

The code section in the file to focus on is here:

A clear and concise description of how the code performed w.r.t expectations.
    ####################################################
    #### Added to make things work for now. Must be ####
    ############# removed in future PRs ################
    ####################################################

    # Advises to explicitly install any plugin which you are using
    # in your codebase. At many places in our codebase we have used
    # things of a plugin which is not in our pubspec.yaml. Say we have
    # installed plugin A, which in turn internally installs plugin B, as
    # A depends on B, and then we are using functionalities of B, even
    # though we never installed them explicitly; they just got installed.
    #
    # To fix: Uncomment below lint and check for warnings it creates. Then
    # install the dependencies one by one.

    depend_on_referenced_packages: false
    
    # This new lint rule advises to use methods on dynamic objects
    # only after properly type casting. It's quite good and will avoid
    # null errors. 
    # For now, it affects the whole code base; wherever we have done 
    # something like 
    # 
    # ``` 
    # var obj = json_data['obj'];
    # obj.fun_call(param);
    # ```
    #
    # To fix: Turn on this lint and type cast the object of your file as 
    #
    # ```
    # MyObj obj = json_data['obj'] as MyObj;
    # ```
    
    avoid_dynamic_calls: false

    # deprecated_member_use is turned off for file - test/helpers/test_helpers.dart
    # to suppress returnNullOnMissingStub deprecation. 
    # To fix: Remove the lint suppress directive and update to latest API
**Screenshots**
image

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by Amogh35**
**What kind of change does this PR introduce?**

bugfix

**Issue Number:**

Fixes #1512 

**Did you add tests for your changes?**

NA

**Summary**

In this issue i have enabled:
- `depend_on_referenced_packages`: for which i had to referenced various dpendencies in the main pubspec.yaml file, as well as the one in talawa_lint  to solve the resulting errors.
-  `lowercase_with_underscores`: the lint rule for naming source files using lowercase_with_underscores is now known as `file_names`, which I have enabled.
- `deprecated_member_use`: this issue was fixed in a previous PR, but not updated in analysis_options.yaml file.
- `avoid_dynamic_calls`: Enabling this should be opened as another Issue, and treated as a high quality problem, as this involves manually type casting over 72 variables throughout the codebase.

**Does this PR introduce a breaking change?**

No

**Other information**

I reccommend opening another issue for enabling avoid_dynamic_calls as this is a huge issue in and of itself, there are over 72 errors, where you need to manually type cast the variables depending on their use case.

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by palisadoes** [comment]
@literaleval Comments please

**Comment by literalEval** [comment]
@palisadoes looks good to me. And @Amogh35 is correct when he says that `avoid_dynamic_calls` is a huge and very sensitive task in itself, and should be fixed in separate PR(s).

**Comment by palisadoes** [comment]
@ayushs136 Please open a separate issue for `avoid_dynamic_calls`

**Review by palisadoes — APPROVED** [review]

**Comment by Amogh35** [comment]
@palisadoes did you mean to tag me, maybe?

**Comment by palisadoes** [comment]
Yes, please open the appropriate issue. Ask to be assigned if you are willing.

**Pull request merged**
