### PR TITLE
Unittest for pinned_post_screen

### PR DESCRIPTION
**Pull request by imshivam-gupta**
This change included the Unittest for pinned_post_screen

Issue Number: https://github.com/PalisadoesFoundation/talawa/issues/2165

Fixed https://github.com/PalisadoesFoundation/talawa/issues/2165

Did you add tests for your changes?

Yes

Summary

It is unittest for pinned_post_screen.

Does this PR introduce a breaking change?

No, this does not introduce any major changes to the codebase.

Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?

Yes, i have followed the guidelines.

### CODE REVIEW

**Comment by imshivam-gupta** [comment]
@Ayush0Chaudhary  @noman2002 Can you please review the request.

**Comment by Ayush0Chaudhary** [comment]
Please solve other issues first.

**Comment by imshivam-gupta** [comment]
Ok Sir. I will solve the other 2 issues assigned to me meanwhile you review the changes

**Comment by noman2002** [comment]
@imshivam-gupta Why the coverage has not increased?

**Comment by imshivam-gupta** [comment]
@noman2002 Let me check this.

**Comment by imshivam-gupta** [comment]
@noman2002 Since this was quite small code that's why it didn't increase the coverage but the the pinned_post_screen is having 95.2% coverage.

**Comment by imshivam-gupta** [comment]
Still please give me some time I will check how to increase the coverage

**Comment by imshivam-gupta** [comment]
After checking I found that when I check individual file coverage for pinned_post_screen then it is showing 100% but when checking it with all other it is showing 95.2%.

**Comment by Ayush0Chaudhary** [comment]
@imshivam-gupta add code coverage ss

**Review by Ayush0Chaudhary — CHANGES_REQUESTED** [review]
@imshivam-gupta add code coverage ss

**Comment by imshivam-gupta** [comment]
Single File Coverage

image

Total Project Coverage

image

I think it will increase when the pr of pinned_post_page and individual_post testing will be merged

**Review by noman2002 — APPROVED** [review]
Looks good to me

**Pull request merged**
