### PR TITLE
Bug fix: Add event button is overlapping with the event cards. #1653

### LINKED ISSUE #1653: Bug Report: Add event button is overlapping with the event cards.
**Describe the bug**
Add event button is overlapping with the cards due to same color of both.

**To Reproduce**

1.Install Talawa, Talawa-API, and Talawa-Admin as per their installation guides.
2.log in to the Talawa app.
3.Add two events in the events section 
4.You can see that the add event button is not visible properly due to same color overlap.

**Expected behavior**
Add button should be clearly visible in both light and dark mode.

**Actual behavior**
Add button is overlapping with the event card

**Screenshots**
image

**Additional details**
see above

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by indresh149**
**What kind of change does this PR introduce?**

Bug Fix

**Issue Number:**

Fixes #1653 

**Did you add tests for your changes?**

No

**Snapshots/Videos:**
Before 

224532321-9d4de034-199f-4861-b77e-f39090b0034d

After 

after

**If relevant, did you update the documentation?**

No

**Summary**

Add event button is overlapping with the cards due to the same color of both.
I have applied different colors to the floating button background to make it properly visible.

https://github.com/PalisadoesFoundation/talawa/issues/1653

**Does this PR introduce a breaking change?**

No

**Other information**

See above

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by CyberWake** [comment]
> **What kind of change does this PR introduce?**
> 
> Bug Fix
> 
> **Issue Number:**
> 
> Fixes #1653
> 
> **Did you add tests for your changes?**
> 
> No
> 
> **Snapshots/Videos:** Before
> 
> 224532321-9d4de034-199f-4861-b77e-f39090b0034d
> 
> After
> 
> after
> 
> **If relevant, did you update the documentation?**
> 
> No
> 
> **Summary**
> 
> Add event button is overlapping with the cards due to the same color of both. I have applied different colors to the floating button background to make it properly visible.
> 
> #1653
> 
> **Does this PR introduce a breaking change?**
> 
> No
> 
> **Other information**
> 
> See above
> 
> **Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**
> 
> Yes

@indresh149 in the after screenshot attached there is a rendering issue on the same page is that assigned to someone else or is it yet not reported? If not please try fixing that as well after updating the current linked issue.

**Comment by indresh149** [comment]
@CyberWake It is not reflecting now I have checked by running in both an emulator and an android device.  issue is created yesterday and someone else is assigned, but I think it's resolved now because it not giving any rendering error. I am attaching the recent screenshot.

image

**Comment by palisadoes** [comment]
The button is too dark and it covers the dates of the last event in the list

**Comment by indresh149** [comment]
@palisadoes may I decrease the padding or size of the button so that the date is visible?

**Comment by palisadoes** [comment]
Please use your initiative.

**Comment by indresh149** [comment]
@palisadoes okk sir . Thank You

**Comment by indresh149** [comment]
@palisadoes okk sir . Thank You

**Comment by indresh149** [comment]
@xoldyckk @Tajcore @Kevoniat please review it.

**Review by noman2002 — APPROVED** [review]

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
