### PR TITLE
[Enhancement] Dialog enhancement for iOS

### LINKED ISSUE #270: [Enhancement] Optimizing dialog box for iOS
Every Dialog Box until now is created with a Ui interface displayed on android. This issue deals with the fact that dialog box can be optimised for making sure of the iOS experience on iOS Devices.

Following dialogue box can be optimized:
1. Logout Dialog
2. Leave organization dialog
3. Join Organization dialog

The enhancement will be great thinking from iOS perspective.

### PR DESCRIPTION
**Pull request by sumitra19jha**
Closes #270
Motivation: Better Experience for iOS User displaying their Dialogue Box
Snapshots : Unfortunately I don't have iOS snapshot as it can only be viewed on iOS device or simulator.

I have added in the below comment snapshot for android device.

### CODE REVIEW

**Comment by sumitra19jha** [comment]
Android Images:
|WhatsApp Image 2021-03-14 at 9 19 26 PM-2|
WhatsApp Image 2021-03-14 at 9 19 26 PM-3|
WhatsApp Image 2021-03-14 at 9 19 26 PM|

**Comment by Sagar2366** [comment]
@sumitra19jha, not sure if we need this feature based on target audience.
@heyjordn @DeltaHarbinger what do you think ?

**Comment by sumitra19jha** [comment]
I didn't know that. 
I would love to hear the suggestion whether we should focus on iOS user or not

> @sumitra19jha, not sure if we need this feature based on target audience.
> @heyjordn @DeltaHarbinger what do you think ?

**Comment by jordanliu** [comment]
> @sumitra19jha, not sure if we need this feature based on target audience.
> @heyjordn @DeltaHarbinger what do you think ?

I don't think the cupertino dialog is necessary, especially since we'll be doing a UI overhaul

**Comment by sumitra19jha** [comment]
Ok @jordanliu 
Should I close both PR and issue then?

**Comment by jordanliu** [comment]
> Ok @jordanliu
> Should I close both PR and issue then?

Yes

**Comment by Sagar2366** [comment]
@sumitra19jha can you resolve conflicts and use latest master to fix the issue. Send PR for review again once changes are done.

**Comment by sumitra19jha** [comment]
Working on it sir

**Comment by sumitra19jha** [comment]
Done sir @Sagar2366 
Snapshot are same as shown above

**Comment by sumitra19jha** [comment]
WhatsApp Image 2021-04-09 at 9 56 19 AM-2
WhatsApp Image 2021-04-09 at 9 56 19 AM

**Comment by Sagar2366** [comment]
@sumitra19jha issue is related to IOS, can you provide video visuals showing you have done proper testing on your end.

**Comment by sumitra19jha** [comment]
Yeah sure. Actually my exams are going on so that's why I am very inactive currently. I am sharing the video visuals as soon as possible

**Comment by palisadoes** [comment]
Please fix merge conflicts.

**Comment by sumitra19jha** [comment]
Yeah, right now I am working on this

**Comment by sumitra19jha** [comment]
@Sagar2366 I have done the testing on android device

https://user-images.githubusercontent.com/35868598/115912094-85142a00-a48c-11eb-8fc5-a5f10308baac.mp4

Screenshot 2021-04-23 at 11 22 15 PM

**Review by Sagar2366 — APPROVED** [review]

**Pull request merged**
