### PR TITLE
Trying to fix ios github action error

### LINKED ISSUE #1043: Fix iOS tesing error post Pull Request merging
**Describe the bug**
We are getting the message below after merging the `talawa` code. This could be the cause of future problems with the app.

**To Reproduce**

- [Follow this link for the full post PR test suite with the error message.](https://github.com/PalisadoesFoundation/talawa/runs/4537806166?check_suite_focus=true)

**Expected behavior**
There should be no errors for iOS testing.

**Actual behavior**
See screenshot below and link above.

**Screenshots**
```
Run flutter build ios --release --no-codesign

  ╔════════════════════════════════════════════════════════════════════════════╗
  ║                 Welcome to Flutter! - https://flutter.dev                  ║
  ║                                                                            ║
  ║ The Flutter tool uses Google Analytics to anonymously report feature usage ║
  ║ statistics and basic crash reports. This data is used to help improve      ║
  ║ Flutter tools over time.                                                   ║
  ║                                                                            ║
  ║ Flutter tool analytics are not sent on the very first run. To disable      ║
  ║ reporting, type 'flutter config --no-analytics'. To display the current    ║
  ║ setting, type 'flutter config'. If you opt out of analytics, an opt-out    ║
  ║ event will be sent, and then no further information will be sent by the    ║
  ║ Flutter tool.                                                              ║
  ║                                                                            ║
  ║ By downloading the Flutter SDK, you agree to the Google Terms of Service.  ║
  ║ Note: The Google Privacy Policy describes how data is handled in this      ║
  ║ service.                                                                   ║
  ║                                                                            ║
  ║ Moreover, Flutter includes the Dart SDK, which may send usage metrics and  ║
  ║ crash reports to Google.                                                   ║
  ║                                                                            ║
  ║ Read about data we send with crash reports:                                ║
  ║ https://flutter.dev/docs/reference/crash-reporting                         ║
  ║                                                                            ║
  ║ See Google's privacy policy:                                               ║
  ║ https://policies.google.com/privacy                                        ║
  ╚════════════════════════════════════════════════════════════════════════════╝

Running "flutter pub get" in flutter_tools...                       5.0s
Running "flutter pub get" in talawa...                             56.7s
The plugin `social_share` uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.
Warning: Building for device with codesigning disabled. You will have to manually codesign before deploying to device.
Building com.example.talawa for device (ios-release)...
Updating project for Xcode compatibility.
Upgrading project.pbxproj
Upgrading Runner.xcscheme
Running pod install...                                              9.4s
Running Xcode build...                                          
════════════════════════════════════════════════════════════════════════════════
Xcode build done.                                           17.3s
Building a deployable iOS app requires a selected Development Team with a 
Failed to build iOS app
Provisioning Profile. Please ensure that a Development Team is selected by:
Error output from Xcode build:
  1- Open the Flutter project's Xcode target with
↳
       open ios/Runner.xcworkspace
    ** BUILD FAILED **
  2- Select the 'Runner' project in the navigator then the 'Runner' target

     in the project settings

  3- Make sure a 'Development Team' is selected under Signing & Capabilities > Team. 
Xcode's output:
     You may need to:
↳
         - Log in with your Apple ID in Xcode first
    /Users/runner/hostedtoolcache/flutter/2.8.0-stable/x64/.pub-cache/hosted/pub.dartlang.org/video_player-2.2.7/ios/Classes/messages.m:8:9: fatal error: 'Flutter/Flutter.h' file not found
         - Ensure you have a valid unique Bundle ID
    #import <Flutter/Flutter.h>
         - Register your device with your Apple Developer Account
            ^~~~~~~~~~~~~~~~~~~
         - Let Xcode automatically provision a profile for your app
    1 error generated.
  4- Build or run your project again
    note: Using new build system

    note: Planning
For more information, please visit:
    note: Build preparation complete
  https://flutter.dev/docs/get-started/install/macos#deploy-to-ios-devices
    note: Building targets in parallel


Or run on an iOS simulator without code signing
════════════════════════════════════════════════════════════════════════════════
Encountered error while building for device.
Error: Process completed with exit code 1.
```

**Additional details**
None

### PR DESCRIPTION
**Pull request by nishnatadebnath**
**What kind of change does this PR introduce?**

**Issue Number:**

Fixes #1043 

**Did you add tests for your changes?**

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**

### CODE REVIEW

**Comment by palisadoes** [comment]
@nishnatadebnath The `PR Workflow / Testing build for iOS (pull_request_target) ` check is failing. Please review and se how you can fix this.

**Comment by nishnatadebnath** [comment]
> @nishnatadebnath The `PR Workflow / Testing build for iOS (pull_request_target) ` check is failing. Please review and se how you can fix this.

I am trying to work on it,but a notable observation is that the pull and the push workflow which is quite similar ,works fine with all thw cases passing in my own forked repo but fails in the Talawa-develop repo. @palisadoes

**Comment by nishnatadebnath** [comment]
@palisadoes Sir I clearly feel that the last merge which was done ,is bugged and causing PR Workflow / Testing build for iOS (pull_request_target) check to fail.If feasible ,if we can revert back the merge and check if the IOS github action is working then it would be great.If its still not working then we can again comeback to this head by merging again.

**Comment by palisadoes** [comment]
@nishnatadebnath  I spoke to @DMills27 (Dominic Mills) who has seen this issue with iOS testing in his job.  Please contact him for the possible solution. Apparently it is version specific to to the MacOS you are working with when developing code.

**Comment by palisadoes** [comment]
@nishnatadebnath Please comment on this issue so I can assign it to you. You have been working on this for some time.

**Comment by nishnatadebnath** [comment]
@palisadoes Okay so after much debugging and inspecting ,I have found out what the issue actually is.So the workflow file which we are using for pulling is pull-request.yml and push.yml for PR and on push has a big flaw as it checks the ios build of the current repository which is already merged that is 'talwa/develop' and not of the pull request.This is the screenshot where I first made a testing branch in my forked repo 
Screenshot from 2021-12-20 13-15-30
Screenshot from 2021-12-20 13-16-21

As you can clearly see it did not run the new ios-build commands instead it ran the commands from the last commit made to my  develop branch.

After further inspection of the code I found out this ,
Screenshot from 2021-12-20 13-24-14

and,
Screenshot from 2021-12-20 13-22-45

This clearly indicated that it always refered to the last commited branch of 'talwa/develop' .
Now coming to case of push.yml,since this github action takes place after the PR is merged and pushed into the main repository ,it truely shows if there is any issue with the code or not that is merged.

This problem happened with #1035 when my fellow contributor made a pull request ,all the checks were passed but then when the PR was merged it failed the push workflow as we all can see in the develop branch.

Solution- We have to make changes to the code or try something else for CI/CD so that the PR codes are checked instead.

**Comment by nishnatadebnath** [comment]
@palisadoes After much inspecting and debugging I think now I know the reason of the ios build failure and why all my tries were failing. So we have two github action workflow files inside the project pull-request.yml and push.yml are flawed as it checks the ios build of the current commit which is already merged that is 'talwa/develop' and not of the pull request that is made by the contributer.
This is the screenshot where I first made a testing branch in my forked repo with a simple echo messages assigned as flow-action for pulling and pushed.Then I made some changes in the echo message and made a PR to my develop branch to see which commands are being executed . Below are the screenshot,
Screenshot from 2021-12-20 13-15-30
Screenshot from 2021-12-20 13-16-21

As you can clearly see it did not run the new ios-build commands instead it ran the commands from the last commit made to my  develop branch.

After further inspection of the code I found out this ,
Screenshot from 2021-12-20 13-24-14

and,
Screenshot from 2021-12-20 13-22-45

This clearly indicated that it always refered to the last commited branch of 'talwa/develop' .
Now coming to case of push.yml,since this github action takes place after the PR is merged and pushed into the main repository ,it truely shows if there is any issue with the code or not that is merged.

This problem happened with #1035 when my fellow contributor made a pull request ,all the checks were passed but then when the PR was merged it failed the push workflow as we all can see in the develop branch.

Solution- We have to make changes to the code or try something else for CI/CD so that the PR codes are checked instead.

**Comment by palisadoes** [comment]
@nishnatadebnath Do you think it could be caused by the use of `pull_request_target` instead of `pull_request` in the GitHub Actions YAML file? We changed this because students thought it was causing another problem with PRs. I wasn't 100% convinced of the validity of that assessment. It seems that this problem may have started after that change.

**Comment by palisadoes** [comment]
@nishnatadebnath Please ping me on slack. I have some time to work with you  on this.

**Review by CyberWake — CHANGES_REQUESTED** [review]
Please review the changes made in the .yml workflows I find them that they would always work only for your fork instead of the origin talawa on palisadoes. Plus am not sure why the ios build command is changed.

**Comment by nishnatadebnath** [comment]
@CyberWake @sumitra19jha  @TheHazeEffect @palisadoes  this pull request doest not need to be reviewed as this is only for testing purpose of the github actions and contains bugged test code assuming different use cases. Me and @palisadoes  are working closely on the github action issue to make it more safer and reliable to work .As a result there might be affirmative negative testing of the github action which will result in failure . We still cannot close this issue out as it is required for further testing .

**Comment by CyberWake** [comment]
@nishnatadebnath please mark it as a draft PR till then.

**Comment by nishnatadebnath** [comment]
@CyberWake Sorry!I made the change

**Comment by nishnatadebnath** [comment]
All the errors are now handled properly.

**Pull request closed without merging**
