### PR TITLE
Upgrade dart sdk, Add lints at required places, fix IOS build problem

### LINKED ISSUE #1043: Fix iOS tesing error post Pull Request merging
**Describe the bug**
We are getting the message below after merging the `talawa` code. This could be the cause of future problems with the app.

**To Reproduce**

- [Follow this link for the full post PR test suite with the error message.](https://github.com/PalisadoesFoundation/talawa/runs/4537806166?check_suite_focus=true)

**Expected behavior**
There should be no errors for iOS testing.

**Actual behavior**
See screenshot below and link above.

**Screenshots**
```
Run flutter build ios --release --no-codesign

  ╔════════════════════════════════════════════════════════════════════════════╗
  ║                 Welcome to Flutter! - https://flutter.dev                  ║
  ║                                                                            ║
  ║ The Flutter tool uses Google Analytics to anonymously report feature usage ║
  ║ statistics and basic crash reports. This data is used to help improve      ║
  ║ Flutter tools over time.                                                   ║
  ║                                                                            ║
  ║ Flutter tool analytics are not sent on the very first run. To disable      ║
  ║ reporting, type 'flutter config --no-analytics'. To display the current    ║
  ║ setting, type 'flutter config'. If you opt out of analytics, an opt-out    ║
  ║ event will be sent, and then no further information will be sent by the    ║
  ║ Flutter tool.                                                              ║
  ║                                                                            ║
  ║ By downloading the Flutter SDK, you agree to the Google Terms of Service.  ║
  ║ Note: The Google Privacy Policy describes how data is handled in this      ║
  ║ service.                                                                   ║
  ║                                                                            ║
  ║ Moreover, Flutter includes the Dart SDK, which may send usage metrics and  ║
  ║ crash reports to Google.                                                   ║
  ║                                                                            ║
  ║ Read about data we send with crash reports:                                ║
  ║ https://flutter.dev/docs/reference/crash-reporting                         ║
  ║                                                                            ║
  ║ See Google's privacy policy:                                               ║
  ║ https://policies.google.com/privacy                                        ║
  ╚════════════════════════════════════════════════════════════════════════════╝

Running "flutter pub get" in flutter_tools...                       5.0s
Running "flutter pub get" in talawa...                             56.7s
The plugin `social_share` uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.
Warning: Building for device with codesigning disabled. You will have to manually codesign before deploying to device.
Building com.example.talawa for device (ios-release)...
Updating project for Xcode compatibility.
Upgrading project.pbxproj
Upgrading Runner.xcscheme
Running pod install...                                              9.4s
Running Xcode build...                                          
════════════════════════════════════════════════════════════════════════════════
Xcode build done.                                           17.3s
Building a deployable iOS app requires a selected Development Team with a 
Failed to build iOS app
Provisioning Profile. Please ensure that a Development Team is selected by:
Error output from Xcode build:
  1- Open the Flutter project's Xcode target with
↳
       open ios/Runner.xcworkspace
    ** BUILD FAILED **
  2- Select the 'Runner' project in the navigator then the 'Runner' target

     in the project settings

  3- Make sure a 'Development Team' is selected under Signing & Capabilities > Team. 
Xcode's output:
     You may need to:
↳
         - Log in with your Apple ID in Xcode first
    /Users/runner/hostedtoolcache/flutter/2.8.0-stable/x64/.pub-cache/hosted/pub.dartlang.org/video_player-2.2.7/ios/Classes/messages.m:8:9: fatal error: 'Flutter/Flutter.h' file not found
         - Ensure you have a valid unique Bundle ID
    #import <Flutter/Flutter.h>
         - Register your device with your Apple Developer Account
            ^~~~~~~~~~~~~~~~~~~
         - Let Xcode automatically provision a profile for your app
    1 error generated.
  4- Build or run your project again
    note: Using new build system

    note: Planning
For more information, please visit:
    note: Build preparation complete
  https://flutter.dev/docs/get-started/install/macos#deploy-to-ios-devices
    note: Building targets in parallel


Or run on an iOS simulator without code signing
════════════════════════════════════════════════════════════════════════════════
Encountered error while building for device.
Error: Process completed with exit code 1.
```

**Additional details**
None

### PR DESCRIPTION
**Pull request by SriramPatibanda**
**What kind of change does this PR introduce?**

- Refactoring the code to add lints: remove trailing commas, noop lints
- upgrade dart SDK
- fix ios podfile for buid issues.

**Issue Number:**

Fixes #1043 

**Did you add tests for your changes?**

N.A.

**Snapshots/Videos:**

N.A.

**If relevant, did you update the documentation?**

N.A.

**Summary**

Solve ios build issue, upgrade dart SDK, add lints.
**Does this PR introduce a breaking change?**

No

**Other information**
N.A.

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by SriramPatibanda** [comment]
I really am not understanding why this isn't working on pull request. It is working on my fork branch though : https://github.com/SriramPatibanda/talawa/runs/4573173465?check_suite_focus=true. Maybe one of the mentors @sumitra19jha @rutvik11062000 can help me with this. Sorry for the inconvenience @palisadoes .

**Comment by AvneetSingh2001** [comment]
@SriramPatibanda Have you tried to run the app on iOS Simulator?

**Review by palisadoes — CHANGES_REQUESTED** [review]
@SriramPatibanda Why are 96 files being added to this PR? What was wrong with the previous linting scheme?

**Comment by palisadoes** [comment]
@SriramPatibanda You are not following the protocol. Please get the issue assigned to you as per the issue here:
- https://github.com/PalisadoesFoundation/talawa/issues/359

You are also trying to fix too many things in the single PR. 

- Upgrading Dart SDK
- Linting
- Fixing iOS errors. (This issue will be assigned to @nishnatadebnath who put in a PR to fix this a few days ago)

I'm going to close this PR. It is too complicated for mentors to evaluate. Each PR must fix one thing.

I praise the enthusiasm, but we have had great issues in the past trying to get the code base reliable, and consistent.

Please open separate issues for each of the things you want to fix.

**Comment by SriramPatibanda** [comment]
> @SriramPatibanda You are not following the protocol. Please get the issue assigned to you as per the issue here:
> - https://github.com/PalisadoesFoundation/talawa/issues/359
> 
> You are also trying to fix too many things in the single PR. 
> 
> - Upgrading Dart SDK
> - Linting
> - Fixing iOS errors. (This issue will be assigned to @nishnatadebnath who put in a PR to fix this a few days ago)
> 
> I'm going to close this PR. It is too complicated for mentors to evaluate. Each PR must fix one thing.
> 
> I praise the enthusiasm, but we have had great issues in the past trying to get the code base reliable, and consistent.
> 
> Please open separate issues for each of the things you want to fix.
> 

Hey @palisadoes , I'm so sorry for the problem caused. I'll follow the protocol for sure. What happened was that the project wasn't running without upgrading the dart SDK. Even a person talked about this in the slack channel. After upgrading the SDK, these lints were default in that SDK and hence I disabled them in the previous pr but since you told that it would create a problem for maintainers while reviewing, I solved the lint errors in this PR. So without upgrading the dart SDK and solving the lint errors, the app couldn't run. Hence I did that. I'm extremely sorry for the trouble caused.

**Comment by palisadoes** [comment]
> > @SriramPatibanda You are not following the protocol. Please get the issue assigned to you as per the issue here:
> > 
> > * [Student Internship Programs #359](https://github.com/PalisadoesFoundation/talawa/issues/359)
> > 
> > You are also trying to fix too many things in the single PR.
> > 
> > * Upgrading Dart SDK
> > * Linting
> > * Fixing iOS errors. (This issue will be assigned to @nishnatadebnath who put in a PR to fix this a few days ago)
> > 
> > I'm going to close this PR. It is too complicated for mentors to evaluate. Each PR must fix one thing.
> > I praise the enthusiasm, but we have had great issues in the past trying to get the code base reliable, and consistent.
> > Please open separate issues for each of the things you want to fix.
> 
> Hey @palisadoes , I'm so sorry for the problem caused. I'll follow the protocol for sure. What happened was that the project wasn't running without upgrading the dart SDK. Even a person talked about this in the slack channel. After upgrading the SDK, these lints were default in that SDK and hence I disabled them in the previous pr but since you told that it would create a problem for maintainers while reviewing, I solved the lint errors in this PR. So without upgrading the dart SDK and solving the lint errors, the app couldn't run. Hence I did that. I'm extremely sorry for the trouble caused.

@Simran1604 Don't worry. The intention was not to scold. We are just trying to keep things sane. 

Earlier this year when we were awarded GSoC acceptance, we had a huge uncontrollable influx of issues and PRs. The process was created to keep things manageable for the mentors and regular contributors.

As I said before, we welcome the enthusiasm.

**Pull request closed without merging**
