### PR TITLE
Fix/event calender screen bug

### PR DESCRIPTION
**Pull request by AVtheking**
What kind of change does this PR introduce?
fix the bug while opening event calender page

Issue Number:

Fixes https://github.com/PalisadoesFoundation/talawa/issues/2328

Did you add tests for your changes?

yes

Video

https://github.com/PalisadoesFoundation/talawa/assets/132201033/5bdf148f-6cc0-4777-96b6-b7370808d1a1

### CODE REVIEW

**Comment by Cioppolo14** [comment]
@AVtheking Can you fix the codebase error?

**Comment by AVtheking** [comment]
please review it

**Comment by Ayush0Chaudhary** [comment]
can you add screen shot or video?

**Comment by AVtheking** [comment]
Ok sir

**Comment by AVtheking** [comment]
@Ayush0Chaudhary  I have linked video for this fix

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
