### PR TITLE
Muhammad ali raza dar/flutter testing guide

### LINKED ISSUE #1481: Write a tutorial on Flutter Testing
Recently I have seen a couple of test PRs which are
- Not covering all the cases of the file
- Importing unnecessary files
- Not generating/using mocks properly
- .....

**Describe the solution you'd like**
I would like to write some sort of documentation on testing with Flutter so that
- Beginners will get a decent resource to start with
- New-comers will get to know about the existing mocks, stubbs that we already have and can you them

**Describe alternatives you've considered**
An alternative could be to document/comment the mocks and stubbs themselves, but I think creating a webpage/documentation page would be a better idea.

**Approach to be followed (optional)**
- What are tests and why do we need them ?
- How to cover all the corner cases ?
- How to start with Flutter testing ?
- What are mocks and to generate them ?
- How to stub methods and classes ?
- What to do if you find a bug while writing test for that file ?
- .....

### PR DESCRIPTION
**Pull request by ALIRAZA17**
**What kind of change does this PR introduce?**

Provided a full flutter testing guide with every necessary features required from adding certain packages to writing tests for a certain file to testing that file using the command flutter test.

**Issue Number:**

Fixes #1481 

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by ALIRAZA17** [comment]
@palisadoes @noman2002 @literalEval I have written everything in the new Flutter Guide file. Can you review it and tell me if there's anything missing so that I can add in it?

**Comment by palisadoes** [comment]
@ALIRAZA17 Please close this PR and open one in Talawa-Docs which is a more appropriate place to have it.

1. [Details can be found here](https://github.com/PalisadoesFoundation/talawa/blob/develop/DOCUMENTATION.md)
1. Something in this URL would work. https://docs.talawa.io/docs/category/talawa
    1.  The markdown file can be placed here:  https://github.com/palisadoes/talawa-docs/tree/develop/docs/developers/talawa
    1. The image files will need to be placed in the appropriate directory location under `static/`

**Review by palisadoes — CHANGES_REQUESTED** [review]
Please close this PR.  Follow the advice in the comments.

**Comment by ALIRAZA17** [comment]
> @ALIRAZA17 Please close this PR and open one in Talawa-Docs which is a more appropriate place to have it.
> 
> 1. [Details can be found here](https://github.com/PalisadoesFoundation/talawa/blob/develop/DOCUMENTATION.md)
> 2. Something in this URL would work. https://docs.talawa.io/docs/category/talawa
>    
>    1. The markdown file can be placed here:  https://github.com/palisadoes/talawa-docs/tree/develop/docs/developers/talawa
>    2. The image files will need to be placed in the appropriate directory location under `static/`

Ok I'll open one in talawa docs

**Comment by ALIRAZA17** [comment]
> Please close this PR. Follow the advice in the comments.

Ok Ok ill open the pull request in talawa docs

**Comment by ALIRAZA17** [comment]
> Please close this PR. Follow the advice in the comments.

@palisadoes I have added my .md file in talawa-docs repo at the required place with image in static folder. Now the main issue im facing is that the issue im assigned to is in talawa repo so I cannot render that in my pull request in talawa-docs. What to do in this case?

**Comment by palisadoes** [comment]
Open an issue in Talawa-Docs. Get it assigned to you just like you would here.

**Pull request closed without merging**
