### PR TITLE
App localization test was created for increasing coverage and reliability

### LINKED ISSUE #1530: Test app_localization.dart
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

The Talawa code base needs to be 100% reliable. This means we need to have 100% test code coverage.

Tests need to be written for file:
```
lib/utils/app_localization.dart
```
- When complete, all methods, classes and/or functions in the file will need to be tested. 
- Our `test/` folder has the same structure as the `lib` folder. Place your test file in the equivalent folder under `test/`. You may need to create the appropriate directory structure to do this.
- [Current test code coverage for this file can be found here](https://app.codecov.io/gh/PalisadoesFoundation/talawa?search=&displayType=list)

### IMPORTANT:
Please refer to this issue on how to implement these tests correctly:

- https://github.com/PalisadoesFoundation/talawa/issues/1217

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base. This will be clearly visible when you submit your PR.
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide.
- You can verify your own code coverage by creating an account at [Codecov.io](https://codecov.io)

### PR DESCRIPTION
**Pull request by Kushalrock**
**What kind of change does this PR introduce?**
A new test to check app localization utils was introduced

**Issue Number**
Closes #1530 

**Have you read the [contributing guide]?**
Yes

**Summary**
As mentioned in #1217 talawa mobile app needs to be very reliable and is slowly inching toward complete test coverage. This issue solves #1530 and adds tests for the app localization file in utils folder. 

**Screenshots Supporting the PR**
Screenshot (429)

### CODE REVIEW

**Comment by Cioppolo14** [comment]
lease refer to the PR_GUIDELINES.md document in the root folder of the repo. It tells you how to automatically close your issue when the PR is merged.

**Comment by Kushalrock** [comment]
> @Kushalrock Please refer to the PR_GUIDELINES.md document in the root folder of the repo. It tells you how to automatically close your issue when the PR is merged.

Thank you @Cioppolo14. I have already linked the pull request to the issue such that if PR merges issue will get closed. Anything else that I need to add?

**Comment by Cioppolo14** [comment]
@Kushalrock My apologies, I misunderstood something. I will assign reviewers.

**Review by CyberWake — COMMENTED** [review]
@Kushalrock I think we should also have test written for the usecase where initial language was x(supported language) which later on  was switched to y(supported language)

**Review by TheHazeEffect — APPROVED** [review]

**Comment by Kushalrock** [comment]
@CyberWake I have done what you asked you can go ahead and check. Thank you for your review.

**Comment by Kushalrock** [comment]
@CyberWake any update?

**Review by noman2002 — APPROVED** [review]
Looks Good to me

**Comment by palisadoes** [comment]
We have a new check in place. All Talawa mobile app methods, classes and functions need to have suitable comments. Please refer to this issue as  reference for what is now required. The aim is to help us improve the quality of our automated documentation on docs.talawa.io.
 
- https://github.com/PalisadoesFoundation/talawa/issues/1479

To fix this issue:

1. You will be required to remove a line containing `ignore_for_file`
1. After doing so you'll be requested to update the comments appropriately

We have also tried to make the documentation step automatically update your IDE with a custom Linter. If you have any comments, please contact @literalEval who worked on this code.

**Comment by CyberWake** [comment]
@Kushalrock please look for the code coverage why it went low by 0.05%. Resolving so would allow us to proceed to reviewing and merge upon success.

**Comment by Kushalrock** [comment]
@CyberWake I will look into that also what is this linting issue that I git commented by Peter. Do I have to do anything about that. Also I have not made any deletion so how can I reduce the code coverage?

**Comment by Kushalrock** [comment]
@CyberWake Merged the branch with latest pull now. Can you please check and approve.

**Comment by literalEval** [comment]
@Kushalrock please add `/// None` after the `/// params` line. Don't leave it blank. Thanks.

**Comment by literalEval** [comment]
@Kushalrock and remove the extra `///` at last  :)

**Comment by Kushalrock** [comment]
@literalEval Done again 😅🤣

**Comment by literalEval** [comment]
:) Thanks.

**Comment by Kushalrock** [comment]
@literalEval Thanks I just skimmed through linting section. Shouldn't have done that😅

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
