### PR TITLE
Fixes:(#1107)

### PR DESCRIPTION
**Pull request by sunnyok03**
What kind of change does this PR introduce:
Removes the "Help" tile from the profile section and also removes its view model from profile_page_view_model.dart

Issue Number:
Fixes: #1107 

Did you add tests for your code?
All tests Passed.

Snapshots/Videos:
WhatsApp Image 2022-02-07 at 3 18 06 PM

Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?
Yes

### CODE REVIEW

**Review by palisadoes — CHANGES_REQUESTED** [review]
Your tests are failing because no tests were written for changes you made. 
- Please get the [main_screen_view_model.dart](https://codecov.io/gh/PalisadoesFoundation/talawa/pull/1199/diff?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=PalisadoesFoundation#diff-bGliL3ZpZXdfbW9kZWwvbWFpbl9zY3JlZW5fdmlld19tb2RlbC5kYXJ0) file up to 100% code coverage.
- [You can get a better view of the current state of code coverage of main_screen_view_model.dart here](https://codecov.io/gh/PalisadoesFoundation/talawa/tree/develop/lib/view_model).

We need to ensure that our % code coverage does not decrease. It's a key part of our coding strategy.

**Comment by palisadoes** [comment]
Are you still working on this?

**Comment by sunnyok03** [comment]
Yes I'm

**Comment by palisadoes** [comment]
Are you still working on this?

**Comment by sunnyok03** [comment]
Sorry, I tried learning writing tests but not getting properly how to write, so if you wish you can close the issue.

**Pull request closed without merging**
