### PR TITLE
Bug fix : Unresponsive UI of App drawer (UI Improvement) #1669

### LINKED ISSUE #1669: Bug Report :Unresponsive UI of App drawer (UI Improvement)
**Describe the bug**
The UI of the App Drawer is unresponsive and shows irregular padding behavior on the bottom side in different screen sizes.

**To Reproduce**

1. Install Talawa, Talawa-API, and Talawa-Admin as per their installation guides.
2. log in to Talawa and open the App Drawer.
3. See the bottom of the App drawer, it has different padding on different devices, in some devices, it is showing zero padding.

**Expected behavior**
The Bottom name should have some padding according to the screen size.

**Actual behavior**
It is showing zero padding on some devices.

**Screenshots**
image

image

**Additional details**
See above

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by indresh149**
**What kind of change does this PR introduce?**

BugFix

**Issue Number:**

Fixes #1669 

**Did you add tests for your changes?**

No

**Snapshots/Videos:**
226350022-33ccd4ee-ec90-4e95-86aa-6b1aa20f0a9a

**If relevant, did you update the documentation?**

No

**Summary**

Talawa App is already using Media Query for responsive Ui. I have just added a sized box and decreased some heights to make it consistent.

**Does this PR introduce a breaking change?**

No

**Other information**

see above

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by indresh149** [comment]
@palisadoes sir please review the PR.

**Review by noman2002 — CHANGES_REQUESTED** [review]
Can you please try to get the coverage of custom drawer to 100%.

**Comment by indresh149** [comment]
> Can you please try to get the coverage of custom drawer to 100%.

ok, sir. I will try

**Comment by palisadoes** [comment]
Please fix the failing tests

**Comment by palisadoes** [comment]
Please fix the failing tests

**Comment by palisadoes** [comment]
Please fix the failing tests

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
