### PR TITLE
Update TextEditing Controller for handling hashtags while making post

### LINKED ISSUE #1583: Implement the "Add Hashtag" Functionailty
**Is your feature request related to a problem? Please describe.**
Currently the "Add Hashtag" option does nothing; we would like for its required functionality to be implemented. See the video for a description of the issue 

[Steps outlined here till 2:41](https://www.youtube.com/watch?v=ix3eSReJj2k?t=124)

**Describe the solution you'd like**
When clicking the "Add Hashtag" option (pictured below), allow the user to add a hashtag . Currently, it does nothing.  

Screenshot at Feb 27 06-21-01

**Describe alternatives you've considered**
If possible, write some functionality to detect if a hashtag is present on a post rather than having the user select an "Add Hashtag" option. If this route is chosen then remove the "Add Hashtag" option altogether. 

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by sumittiware**
**What kind of change does this PR introduce?**
Feature 
Made adding hashtags in post easier, rather than having to add the hashtags separetely, user can now add them in the post as well, just by adding "#" followed by the keyword, just like twitter/linkedIn.

**Issue Number:**

Fixes #1583 

**Did you add tests for your changes?**

No

**Snapshots/Videos:**
[Checkout this video](https://drive.google.com/file/d/12Z0LMAcutjvQGVN5ABPKk-iQSVPpft1Y/view?usp=share_link)

**Summary**

Initially there was a seperate Add Hashtag button in the Add Post screen, users needed to add the hashtags to the post seperately, but with these changes and updated TextEditingContoller users can add the hashtags in the body of the post itself. Users can also get the suggestion of the hashtags based on the prefix they have already added.

**Does this PR introduce a breaking change?**
No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by Cioppolo14** [comment]
@sumittiware Please fix the conflicting file. There may also be failed tests after you do so.  

We have a new check in place. All Talawa mobile app methods, classes and functions need to have suitable comments. Please refer to this issue as  reference for what is now required. The aim is to help us improve the quality of our automated documentation on docs.talawa.io.
 
- Refer to https://docs.talawa.io/docs/developers/talawa/talawa-lint
- Also refer to INSTALLATION.md and CONTRIBUTING.md

To fix this issue:

1. You will be required to remove a line containing `ignore_for_file`
1. After doing so you'll be requested to update the comments appropriately

We have also tried to make the documentation step automatically update your IDE with a custom Linter. If you have any comments, please contact @literalEval who worked on this code.

**Comment by noman2002** [comment]
@sumittiware Any progress?

**Comment by palisadoes** [comment]
@sumittiware 
1. Please fix the failing tests.
1. Resolve the conflicting files.

**Comment by palisadoes** [comment]
Please fix the failing tests and the conflicting file

**Comment by noman2002** [comment]
closing due to inactivity.

**Comment by literalEval** [comment]
@palisadoes @noman2002 The changes done in this PR are very useful and significant. I think we can use the changes in another PR and get the change to merge if @sumittiware doesn't mind.

**Comment by palisadoes** [comment]
We can reassign the original issue if @sumittiware doesn't respond soon.

**Comment by literalEval** [comment]
Yeah sure. And then we can use the code changes done here maybe, if you think that is cool.

**Comment by palisadoes** [comment]
Let's wait another 12 hours so that @sumittiware can respond. That will give him 24 hours total.  We can reassign if not.

**Pull request closed without merging**
