### PR TITLE
Flutter code quality improvement

### LINKED ISSUE #869: Flutter code quality improvement
**Describe the bug**
Quality of code needs to be enhanced to make sure strict restriction are in place for enhanced code quality for development

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to terminal
2. run `flutter analyze`

**Expected behaviour**
Code quality restriction should be followed

**Actual behaviour**
Currently, it only shows a warning instead of an error that fail to compile the code

**Screenshots**

**Additional details**

### PR DESCRIPTION
**Pull request by sumitra19jha**
**What kind of change does this PR introduce?**
refactoring

**Issue Number:**

Fixes #869 

**Did you add tests for your changes?**
Not required here

**Snapshots/Videos:**
Not needed here

**If relevant, did you update the documentation?**
Not needed here

**Summary**
This makes sure code quality level is great

**Does this PR introduce a breaking change?**
No

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**

### CODE REVIEW

**Comment by CyberWake** [comment]
Can you please start from scratch code @sumitra19jha you me reuse the code currently on master but as most of the things are not done till now and adding these changes on GSoC branch would complicated the things leaving us with no pros of writing from scratch.
I would prefer to have these changes on the current codebase from GSoC not from master as the changes only include use of non hard coded strings.

**Comment by sumitra19jha** [comment]
@CyberWake @utkarshshendge Please review

**Review by palisadoes — APPROVED** [review]
Approved for the improvements in the GitHub actions. I'll defer to one of the other mentors for the code quality items.

**Comment by palisadoes** [comment]
@sumitra19jha . The flutter analysis is failing

**Comment by palisadoes** [comment]
@sumitra19jha  It's still failing the flutter analysis tool.

**Comment by DeltaHarbinger** [comment]
There seems to be an issue when the Pub Get command is run

I managed to find the segment which is throwing the error

**Comment by Sagar2366** [comment]
@sumitra19jha please add issue number to PR description.

**Comment by sumitra19jha** [comment]
@Sagar2366 Issue number added

**Comment by sumitra19jha** [comment]
@DeltaHarbinger @CyberWake @rutvik11062000 Can you help me here to find out and understand the error?

https://user-images.githubusercontent.com/35868598/120527169-a525fa00-c3f7-11eb-88ea-3de49535a154.mov

**Comment by rutvik11062000** [comment]
@sumitra19jha
In generated_plugin_registrant.dart file remove import , it is causing ambiguity in the below connection class.

` import 'package:connectivity_for_web/connectivity_for_web.dart';`

**Comment by DeltaHarbinger** [comment]
This could potentially be a problem with the version of flutter the github runner is using. Check the version you have installed, and the version the runner uses.

This may not be the issue, but it's worth checking

**Comment by palisadoes** [comment]
@sumitra19jha the flutter code analysis is failing.

**Comment by sumitra19jha** [comment]
Working on it

**Pull request closed without merging**
