### PR TITLE
after signup bug fixed

### PR DESCRIPTION
**Pull request by guptapriyanshu7**
This is regard to issue #184 

**What kind of change does this PR introduce?**
After signup and choosing  a organisation the user is redirected to  the profile page, and not the "HOME PAGE", so one cannot browse through all the categories.
As said in the issue, one has to close the app and the enter again to see the lower navigation bar.

**Did you add tests for your changes?**
No, i did not.

**If relevant, did you update the documentation?**
No.
**Summary**
The above said is happening due to lack of checking of the routes if the user is coming from profile section or signup section in to the join organization page.

**Does this PR introduce a breaking change?**
No.

**Other information**
Then:

before

Now:

after

### CODE REVIEW

**Comment by CyberWake** [comment]
This issue has an already existing PR please review #310

**Comment by Sagar2366** [comment]
@CyberWake let @guptapriyanshu7 work on this, as you are already working on many issues simultaneously.

**Comment by CyberWake** [comment]
> @CyberWake let @guptapriyanshu7 work on this, as you are already working on many issues simultaneously.

Sure😊

**Comment by CyberWake** [comment]
@Sagar2366 sir there is still has a issue pertaining to the navigation when a new user signs up and opts to create a new organization rather than joining. on doing so the bottom bar is still not available to the user after successful creation on organization.
Also after signup I can go back to create organization page using back button

**Demo**
[Watch the video](https://user-images.githubusercontent.com/44184786/111453633-c7ce3e00-8739-11eb-99a4-c90643a97c8b.mp4)

@Sagar2366 sir please look for this PR #310 it handles it fluently.

**Comment by CyberWake** [comment]
Encountered this one with the latest code pull from talawa/master.

**Pull request merged**
