### PR TITLE
[Fix] : Toast text RenderFlex overflowed

### LINKED ISSUE #594: [Bug] Toast text RenderFlex overflowed issue
- **Issue Description**
    At Create Organization page, Toast text RenderFlex overflowed issue

- **Issue Severity**
     Low

- **Observed Behaviour:**
     Toast text was overflowing by 303 pixels

- **Expected Behaviour:**
      Wrap text on overflow, like insert ellipsis or fade 

- **Steps to reproduce issue:**
      1. Open App
      2. Enter Url
      3. Try to Create organization

- **Snapshots/Videos:**

- **Does this issue need immediate attention?**
      Yes

- **Are you willing to work on this issue:**
     Yes

- **Other information:**
     Please assign this issue to me. @Sagar2366 @DeltaHarbinger sir

### PR DESCRIPTION
**Pull request by Udit-singh**
**What kind of change does this PR introduce?**
Fixes Toast text RenderFlex overflowed issue

**Summary**
Fixes #594 issue.

**Does this PR introduce a breaking change?**
No

**Other information**
Snapshot -

### CODE REVIEW

**Comment by Sagar2366** [comment]
@Udit-singh one of check is failing on your PR, have a look.

**Comment by Udit-singh** [comment]
@Sagar2366 I am unable to rectify the issue. can you help on it.

**Comment by Sagar2366** [comment]
> @Sagar2366 I am unable to rectify the issue. can you help on it.

@Udit-singh close this PR and create new one with same changes.

**Comment by Udit-singh** [comment]
@Sagar2366 Sure, I'll make another PR

**Pull request closed without merging**
