### PR TITLE
Updated social_share dependency

### LINKED ISSUE #1042: Fix Deprectated `social_share` Plugin
**Describe the bug**
The plugin `social_share` uses a deprecated version of the Android embedding. We get the error below when the `flutter pub get` command is run.

**To Reproduce**
```
$ flutter pub get
Running "flutter pub get" in talawa...                           2,340ms
The plugin `social_share` uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future release of Flutter will
remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.
```

**Expected behavior**
No error

**Actual behavior**
See message above

**Screenshots**
N/A

**Additional details**
N/A

### PR DESCRIPTION
**Pull request by AvneetSingh2001**
**What kind of change does this PR introduce?**
As the present version of the project's plugin social_share uses a deprecated version of the Android embedding so, updating it to its new version removes the respective error.

**Issue Number:**

Fixes #1042 

**Did you add tests for your changes?**
Yes

**Snapshots/Videos:**
N.A.

**If relevant, did you update the documentation?**
N.A.

**Does this PR introduce a breaking change?**
No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by palisadoes** [comment]
@AvneetSingh2001 Please fix the failure of the [Testing Build for iOS step](https://github.com/PalisadoesFoundation/talawa/actions/runs/1586188223) in the Pull Request GitHub action.

**Comment by AvneetSingh2001** [comment]
@palisadoes , I am facing the same error when running Talawa on the iOS simulator. I am trying to resolve it.

**Comment by palisadoes** [comment]
This PR claims to have fixed the issue, but it is failing there too.

- https://github.com/PalisadoesFoundation/talawa/pull/1046

**Comment by palisadoes** [comment]
Please consider working on this issue separately. When it is fixed, then your PR checks should complete without issue.

- https://github.com/PalisadoesFoundation/talawa/issues/1043

**Comment by CyberWake** [comment]
@AvneetSingh2001 can you please look into the number of unnecessary commits being made just to update just a dependency version in `pubspec.yaml`. If possible create a new PR after closing this one and making the desired changes against the issue linked.

**Review by CyberWake — CHANGES_REQUESTED** [review]
@AvneetSingh2001 can you please look into the number of unnecessary commits being made just to update just a dependency version in pubspec.yaml. If possible create a new PR after closing this one and making the desired changes against the issue linked.

**Comment by AvneetSingh2001** [comment]
@CyberWake sorry for it. Closing this PR and will open new PR for the issue.

**Comment by CyberWake** [comment]
great this would help all of us.

**Pull request closed without merging**
