### PR TITLE
[Bug Fix] Camera Access permission denied bug fix

### LINKED ISSUE #950: PlatformException (camera_access_denied)
**Describe the bug**
When user deny the  camera permission it will get permanently denied, after if user try to pick image then their is no response from the app side.

**To Reproduce**

1. Install App
2. Navigate To Profile Screen
3. Update profile pic 
4. Deny the runtime permission 
5. Once its get permanently denied retry to update profile pic
6. No response from the application

**Expected behavior**
Once the permission is permanently denied , alert dialog should raise with the message for permission and  
option to visit app setting to give permission .

**Actual behavior**
When the permission denied exception is thrown , no action is taken to alert the user

**Screenshots**
NO

**Additional details**
NO

### PR DESCRIPTION
**Pull request by tosif91**
**What kind of change does this PR introduce?**

bugfix

**Issue Number:**

Fixes   #950 

**Did you add tests for your changes?**

No

**Snapshots/Videos:**

https://user-images.githubusercontent.com/61594032/129401287-defec550-dd05-4c78-9419-4886485d8fe0.mp4

**If relevant, did you update the documentation?**

Not required.

**Summary**

When user deny the camera permission it will get permanently denied, after if user try to pick image then their is no response from the app side. 

**Does this PR introduce a breaking change?**

No, this PR does not bring breaking changes.

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by palisadoes** [comment]
@tosif91 Please fix your conflicting files

**Comment by tosif91** [comment]
ok

**Comment by palisadoes** [comment]
@tosif91 Please fix the error with [flutter code analysis](https://github.com/PalisadoesFoundation/talawa/pull/961/checks?check_run_id=3343262065)

**Comment by tosif91** [comment]
ok

**Comment by palisadoes** [comment]
@tosif91 You'll need to resolve the errors in the pull request see results.

**Comment by tosif91** [comment]
Due to some issues am closing this pull request and opening the new one with same changes

**Pull request closed without merging**
