### PR TITLE
Upgrading the Nav Bar to Animated Nav bar

### LINKED ISSUE #330: Ui/Ux Upgradation - On Hold
**Description:** The current Nav Bar uses `persistent_bottom_nav_bar` and from a UI/UX point of view is kind of outdated so had to rework and revamp this into `CurvedNavigationBar` with animation Support

**Problem:** The current nav bar looks like this,

image

### PR DESCRIPTION
**Pull request by adithyaakrishna**
**What kind of change does this PR introduce?**

Refactoring and Improving the UI as well as UX of the Nav Bar

**Did you add tests for your changes?**
Yes, the change was tested and works well in both iOS & Android systems without breaking anything.

**Solution Implemented:** Once this PR is merged, the nav bar will look like this
image

- This uses https://pub.dev/packages/curved_navigation_bar

This Commit Fixes #330

### CODE REVIEW

**Review by cyber-venom003 — COMMENTED** [review]
Perfectly implemented. 👍

**Comment by arteevraina** [comment]
Hi @adithyaakrishna! Just saw the thread on #330. I believe that this PR would have to wait for a while.

**Comment by adithyaakrishna** [comment]
> Hi @adithyaakrishna! Just saw the thread on #330. I believe that this PR would have to wait for a while.

Yes, I didn't want to close it but it can be merged in the future once we get it finalized

**Comment by Sagar2366** [comment]
@adithyaakrishna probably we don't need this UI change, with the GSOC UI/UX work Talawa will get new look.

**Pull request closed without merging**
