### PR TITLE
Fixed Keyboard Covering Login and SignUp Layout

### LINKED ISSUE #1371: In login screen , keyboard covering huge portion of UI
**Describe the bug**
For small mobile screens, the keyboard is covering the UI part for Login Screen. Which is not an user friendly.

**To Reproduce**
1. Go to Sign in Screen
2. Tap on any text edit box

**Expected behavior**
When the textedit box will be focused or keybaord is in open state, the top padding  of content need to be reduced, So that the textedit box and the button is visible to user , keyboard open state. When the focus removed or keyboard dismissed, it should rollback to old config.

**Actual behavior**
This time, if you tap on any textbox, it will open keyboard, and you can not go to next box or tap on the login button.

**Screenshots**

### PR DESCRIPTION
**Pull request by ALIRAZA17**
**What kind of change does this PR introduce?**

This PR added a resizeToAvoidBottomInset property under Scaffold which will solve the problem of keyboard covering the UI when user is typing something in the TextField. This issue as I perceived was because of the keyboard covering the UI when user is typing so I have added this property which will add focus on that text field so that user can see what he is typing.

**Issue Number:**

Fixes #1371 

**Did you add tests for your changes?**

Not required only UI changes

**UI before Change**

issue

**Summary**

As we can see that in the above image keypad cover text field but adding the above mentioned property of resizeToAvoidBottomInset solves this properly as it will focus on the field clearly and user can see what he/she is typing.

**Does this PR introduce a breaking change?**

No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by noman2002** [comment]
@ALIRAZA17 Please fix the failing formatting check. Run `flutter format  . ` and also attach a screenshot or video of the ui.

**Comment by noman2002** [comment]
@ALIRAZA17 pull the latest changes from develop.

**Comment by palisadoes** [comment]
Please add tests for the [lib/views/pre_auth_screens/signup_details.dart](https://app.codecov.io/gh/PalisadoesFoundation/talawa/blob/develop/lib/views/pre_auth_screens/signup_details.dart) up to 100%. We really need to get the cod base more reliable.

**Comment by noman2002** [comment]
@palisadoes another issue is there for test of signup detail which is assigned to someone else.

**Review by noman2002 — APPROVED** [review]

**Pull request merged**
