### PR TITLE
Unittests for organization_feed_view_model.dart

### LINKED ISSUE #1009: Unittests for organization_feed_view_model.dart
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

We will need unittests done for all methods, classes and functions found in this file.

Any widgets referenced in this file must also have unittests done

```
after_auth_view_models/feed_view_models/organization_feed_view_model.dart
```

This file can be found in the `lib/view_model` directory

- Parent Issue: https://github.com/PalisadoesFoundation/talawa/issues/1003

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base.
- [The current code coverage for the file can be found here](https://codecov.io/gh/PalisadoesFoundation/talawa/tree/develop/lib/view_model/after_auth_view_models)
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide

### PR DESCRIPTION
**Pull request by Yousef-Rabia**
**What kind of change does this PR introduce?**

Unittests for organization_feed_view_model.dart

**Issue Number:**

Fixes #1009 

**Did you add tests for your changes?**

Yes

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by Yousef-Rabia** [comment]
@noman2002 @palisadoes please review!!

**Comment by Cioppolo14** [comment]
@Yousef-Rabia Please fix the failing tests.

**Comment by Yousef-Rabia** [comment]
@Cioppolo14 I think i should fix it in another PR because it's a different issue

**Comment by Yousef-Rabia** [comment]
removePost function dosn't remove post from posts list and remove it only from DB

image


if I update removePost function all tests will pass 

image


Please explain to me if I have misunderstood

**Comment by Yousef-Rabia** [comment]
Review please
@noman2002
@Kevoniat
@Ayush0Chaudhary
@CyberWake
@literalEval
@DMills27

**Comment by Cioppolo14** [comment]
@Yousef-Rabia Please fix the issue in this PR.  In order for it to be ready for reviewers, the failing tests must be passing.

**Comment by Yousef-Rabia** [comment]
@Cioppolo14  Done

**Comment by Dante291** [comment]
image


Please try to get coverage to 100%

**Comment by Olatade** [comment]
@literalEval @DMills27 please can you review?

**Comment by palisadoes** [comment]
Your PR has unnecessary files that don’t relate to your issue. This is causing the tests to fail.

- `pubspec.lock`

You can from the PR by running the commands below from the root directory of the repository

git add -u
git reset HEAD path/to/file
git commit

**Comment by Yousef-Rabia** [comment]
Sorry for the trouble

**Comment by Yousef-Rabia** [comment]
Please review so I can work on other Issues
@noman2002
@Kevoniat
@Ayush0Chaudhary
@CyberWake
@literalEval
@DMills27

**Review by noman2002 — APPROVED** [review]
Looks fine to me.

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
