### PR TITLE
Fix: Proper State Management (Removal of Pull to Refresh Feature) #334

### PR DESCRIPTION
**Pull request by StrangeNoob**
**What kind of change does this PR introduce?**
Removes the Pull to Refresh Feature.
State Management of Posts and its like & comment.

**Did you add tests for your changes?**
Yes. Just a little tweak made it work in the NewsArticleTest.
**If relevant, did you update the documentation?**
No, It's not required.
**Summary**
- Add PostController to controll the post and its attributes.
- Adding New Post will add those have their createdAt is greater than last updated. 
- Made a small tweak to NewsArticleTest. 

**Does this PR introduce a breaking change?**
No.

**Issue No.** #334
**Snapshot/Videos**

https://user-images.githubusercontent.com/42904343/112716757-61ea6f00-8f0e-11eb-83c0-936396d5700b.mp4

**Other information**

### CODE REVIEW

**Comment by StrangeNoob** [comment]
@Sagar2366 As discussed in the previous PR #513, I have changed the only those files I worked on.  Sorry for the inconvenience again.

**Comment by StrangeNoob** [comment]
@Sagar2366 I have made change that are required for the PR. Thanks for the motivation last. Helped a lot.

**Comment by Sagar2366** [comment]
@StrangeNoob have you tested your PR properly ? I am getting this error on your PR.

Screenshot 2021-03-27 at 5 48 23 PM

**Comment by StrangeNoob** [comment]
> @StrangeNoob have you tested your PR properly ? I am getting this error on your PR.
> 
> 
> 
> Screenshot 2021-03-27 at 5 48 23 PM
> 
> 
Yes @Sagar2366. I have updated the the SnapVideo Also. Let me check again. Let me know the step that led to this.

**Comment by Sagar2366** [comment]
> > @StrangeNoob have you tested your PR properly ? I am getting this error on your PR.
> 
> Yes @Sagar2366. I have updated the the SnapVideo Also. Let me check again. Let me know the steps that led to this.

Steps to reproduce:
1. Signup with new account details
2. Joined Amazon Organisation
3. Click on Newsfeed

Also we have already removed pull to refresh feature in master. Can you please confirm if you still see this issue on Master ?

**Comment by StrangeNoob** [comment]
Sure I find a conflict in the NewsFeed.dart. Let me just check.

**Comment by StrangeNoob** [comment]
@Sagar2366 Can you review this again ?

**Comment by palisadoes** [comment]
Please fix merge conflicts. The code freeze has been lifted.

**Comment by StrangeNoob** [comment]
@palisadoes I have merged with current master, you can merge it now.

**Comment by StrangeNoob** [comment]
@Sagar2366 I have done the desire changes. Can you please review it ?

**Review by palisadoes — APPROVED** [review]

**Comment by StrangeNoob** [comment]
closes #334 via #518

**Pull request merged**
