### PR TITLE
Issue#1263

### LINKED ISSUE #1263: Add organization URL in documentation
**Is your feature request related to a problem? Please describe.**
At present, there is a lot of confusion about adding organization URL while setting up the development environment.

**Describe the solution you'd like**
Adding organization URL in the documentation will help the developer's to get rid of  confusion related to organization's URL

**Approach to be followed (optional)**
 Organization URL  example should be documented.

### PR DESCRIPTION
**Pull request by bhattabhi013**
**What kind of change does this PR introduce?**

Documentation updated.

**Issue Number:**

Fixes #1263 

**Did you add tests for your changes?**

No

**If relevant, did you update the documentation?**

Yes

**Summary**

**Does this PR introduce a breaking change?**

No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Review by palisadoes — APPROVED** [review]

**Comment by palisadoes** [comment]
Please fix the conflicting files. Thanks for making the update.

**Review by TheHazeEffect — DISMISSED** [review]
Nice, passes acceptance criteria

I'll approve

**Comment by palisadoes** [comment]
Please fix the conflicting files. We can't merge until that is done.

**Comment by bhattabhi013** [comment]
I've fixed the conflicting files. Please check and let me know for any improvements.

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
