### PR TITLE
ptch : fixed overflow

### PR DESCRIPTION
**Pull request by Omegaviv**
Fixed an overflow issue on Explore Event page

Before : 
before overflow

After : 
before overflow

### CODE REVIEW

**Comment by noman2002** [comment]
@Omegaviv Please follow the PR template and link the issue number.

**Comment by Omegaviv** [comment]
I just saw that there has been a PR raised for this already, but here I have not just changed the width or height value, I have made it scrollable so it will never break on any other screen

**Comment by Omegaviv** [comment]
Okay,

I just saw that there has been a PR raised for this already, but here I have not just changed the width or height value, I have made it scrollable so it will never break on any other screen

**Comment by noman2002** [comment]
This issue is not assigned to you. Please go through CONTRIBUTING.md before creating any PR.

**Comment by Omegaviv** [comment]
Alright

**Pull request closed without merging**
