### PR TITLE
Fixed Localization not working in Home Tour & Components across App

### LINKED ISSUE #2423: Localization (Language) not working in App Tour & Few Components across App
**Describe the bug**
- Localization feature has not been applied to few components in various screens and some of Snackbar messages.
- **For App Home Tour:** If we change language apart from English, the instructions (explaining Sections of App) and next button displayed during App Home Tour have constant strings and displayed in English only irrespective of whichever language preference is selected by user. 

**To Reproduce**

1. Open The app (Should not be logged in to get app home tour option)
2. Select any language apart from English 
3. When asked about App Tour click Start 
4. The instruction explaining app are always in English irrespective of language you choose
5. Some examples of localization not working on few screen are given below in screenshots

**Expected behavior**
The instructions displayed for App Home Tour Should also follow the language preference selected by user.

**Actual behavior**
The instructions displayed for App Home Tour Should doesn't follow the language preference selected by user and all instructions are always displayed in English only.

**Screenshots/Video**

https://github.com/PalisadoesFoundation/talawa/assets/109027247/595a123a-b4a4-4782-a8b8-dc9c150f1f61

| Profile | Donate | View Event |
|---------|--------|------------|
| Profile | Donate | View Event |

| Edit Profile | Profile Setting | Add Event | Add Member |
|--------------|-----------------|-----------|--------|
| Edit Profile | Profile Setting | Add Event | Add Member |

| Logout | Permission Dialog | Snackbar |
|--------------|-----------------|-----------|
 | Logout | Permission Dialog | Snackbar |

### PR DESCRIPTION
**Pull request by GlenDsza**
**What kind of change does this PR introduce?**

bugfix (Added missing Localization for strings)

**Issue Number:**

Fixes #2423 

**Did you add tests for your changes?**

Yes 

**Snapshots/Videos:**

App Home Tour:

https://github.com/PalisadoesFoundation/talawa/assets/109027247/494ca844-33e9-4f34-bf6f-85536812fdfd

Some example:
| Donate | Permission Dialog | Snackbar |
|--------------|-----------------|-----------|
 | donate | permission dialog | Snackbar |

**Summary**

The App Tour Section and some other components on various screens were missing localization as per user language preference. Relevant strings have been added for all languages. 

**Does this PR introduce a breaking change?**

No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by Cioppolo14** [comment]
@GlenDsza can you fix the codecov check?

**Comment by GlenDsza** [comment]
@palisadoes @Cioppolo14 need PR Reviewers

**Comment by GlenDsza** [comment]
@palisadoes @Cioppolo14 please assign reviewers

**Comment by dhanagopu** [comment]
@literalEval @Ayush0Chaudhary Can you review this PR?

**Comment by palisadoes** [comment]
This is an update on the PR merging freeze:

1. In the next few hours we will be merging the `develop-userTypeFix` branch into the `develop` branch. 
1. The `develop-userTypeFix` branch was created to fix a long standing design flaw where Admins were Admins of all organizations, not specific ones.
1. The `userType` field has been removed from the User collection and it has been replaced by an `appUserProfileId` field.
    1. This field is `null` if the user isn’t registered to use the apps. This will help people to add users manually during the event checkin process, or if an Admin wants to manually add someone in the Admin dashboard.
    1. When not `null` the `AppUserProfileID` will reference a `AppUserProfile` collection with App related information such as the organizations for which a user may be an Admin.
    1. The updated schema can be found here https://github.com/PalisadoesFoundation/talawa-api/blob/develop-userTypeFix/schema.graphql
    1. This is the parent issue that we have been using to track progress:
        1. https://github.com/PalisadoesFoundation/talawa-api/issues/1965
1. This merge will cause some conflicts in your PR.

We decided to do this at the beginning of the weekend to give us all time to adjust PR code and create bug fixes that may arise.

Update your code at or after midnight GMT on the morning of March 23, 2024. (5:30am IST). 

If your PRs have already been approved, request a re-review after fixing the conflicts and refactoring to the new `AppUserProfileID` methodology.

**Review by noman2002 — APPROVED** [review]
LGTM

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
