### PR TITLE
Write tests for access_request_screen_test.dart

### PR DESCRIPTION
**Pull request by SatwikMohan**
What kind of change does this PR introduce?

This change included the Unittest for access_request_screen.dart

Issue Number: https://github.com/PalisadoesFoundation/talawa/issues/2151

Fixes https://github.com/PalisadoesFoundation/talawa/issues/2151

Did you add tests for your changes?

Yes I have added tests for SendAccessRequest Widget in the access_request_screen.dart file

Snapshots/Videos: Test coverage
Screenshot (350)

Summary

Tests for access_request_screen are created for which files access_request_screen_test.dart, test_helper.dart and test_helper.mocks.dart are created and updated respectively.
The test_helper is updated for AccessRequestScreenViewModel class and correspondingly the test_helper.mocks.dart is updated on calling the build_runner command.

Does this PR introduce a breaking change?

No, this does not introduce any major changes to the codebase.

Have you read the contributing guide?

Yes, I have followed the guidelines.

### CODE REVIEW

**Review by noman2002 — CHANGES_REQUESTED** [review]
Fix formatting errors.

**Comment by SatwikMohan** [comment]
@noman2002 Sure sir

**Comment by SatwikMohan** [comment]
@noman2002 Sir can you please guide me by exactly what I have to do regarding "Fix Formatting errors".

**Comment by palisadoes** [comment]
1. There are too many files being changed for a simple PR
1. There should be no need to change the version of the SDK. 
1. Please watch this video for guidance. https://www.youtube.com/watch?v=dQuEKpsy1vM

I'm going to close this PR. Please resubmit when you are ready. It's  a learning process.

**Pull request closed without merging**
