### PR TITLE
Fixed Url not changing once set

### LINKED ISSUE #244: [Bug]Url doesnt change once set
once any wrong url (say by a typo) is saved (set url is pressed) , It just appears that you can edit and set another, while the app still uses the former
Steps to reproduce:
1. Run the app and set any url which does'nt exist.
Screenshot_20210315-154110
2. Sign in/Signup
Screenshot_20210315-154142
As expected, we get an error message, that we cannot connect to the url.
3. Change the url to an exisitng url(or any other)
Screenshot_20210315-154439
4. Try signing-in/signing-up again.
Screenshot_20210315-154229
We can see that despite changing the url, the app still tries to connect to the URL which was set first.
This is a bug because we can obviously expect a user to make a typing error while setting the url and if they do that, they wont be able to re-change the url.

### PR DESCRIPTION
**Pull request by Swayam221**
**What kind of change does this PR introduce?**
This PR fixes the problem that the url on the mainscreenpage was not updating once it was set for the first time.

bugfix
**Did you add tests for your changes?**
No
**If relevant, did you update the documentation?**
NA
**Summary**
Fixes #244 
This PR is necessary as it would have been impossible for a user to login/register if he/she had made a typo while setting the Urll.
**Does this PR introduce a breaking change?**
No

**Other information**

### CODE REVIEW

**Comment by Swayam221** [comment]
@Sagar2366 @DeltaHarbinger @jordanliu please review this PR.

**Comment by Sagar2366** [comment]
This PR has conflicts, please resolve them, test changes again and send it for review.

**Comment by Swayam221** [comment]
> This PR has conflicts, please resolve them, test changes again and send it for review.

Conflicts have been resolved.

**Comment by Sagar2366** [comment]
@Swayam221, can you please try to reproduce the issue on latest master ? I don't see this issue on master branch.

**Comment by Swayam221** [comment]
> @Swayam221, can you please try to reproduce the issue on latest master ? I don't see this issue on master branch.

@Sagar2366 Sure sir! Just tested on the latest master branch and the bug is still there for me.

**Comment by Sagar2366** [comment]
@Swayam221, as part of issue this https://github.com/PalisadoesFoundation/talawa/issues/104 fix has been added for if valid URL is not added then, it won't allow to proceed with next operations. Now, we will never come across Fixed Url not changing once set issue.

**Pull request closed without merging**
