### PR TITLE
Version update of Video Player to 2.8.1

### LINKED ISSUE #2091: Upgrade package video_player from 2.7.2 to 2.8.1
We need to bump [video_player](https://github.com/flutter/packages/tree/main/packages/video_player) from 2.7.2 to 2.8.1.

This was attempted as a  PR by dependabot
- https://github.com/PalisadoesFoundation/talawa/pull/2084

However, the checks failed:
- https://github.com/PalisadoesFoundation/talawa/actions/runs/6766167079/job/18386889120?pr=2084

Goals:
- You will need to update the package and make sure the tests pass, with the file in question getting to 100% test coverage.
- Functionality must remain unchanged as a result of completing this issue

### PR DESCRIPTION
**Pull request by vaidic-dodwani**
**What kind of change does this PR introduce?**

This change included the bumping of video_player package from 2.7.2 to 2.8.1.

**Issue Number:** 

Fixed #2091

**Did you add tests for your changes?**

No tests are required for this change as it only includes a package update.

**If relevant, did you update the documentation?**

updating the documentation isnt required for this.

**Summary**

It upgrades the video_player to 2.8.1 for enhanceability.

**Does this PR introduce a breaking change?**

No, this does not introduce any major changes to the codebase.

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**

Yes, i have followed the guidelines.

### CODE REVIEW

**Comment by palisadoes** [comment]
Please fix the first comment so that each issue listed automatically closes. The PR_GUIDELINES.md file has details.

Please also fill in the template for the pull request as completely as you can. It greatly helps others searching for code changes in future and helps others understand the summarized rationale for the work you have done

**Comment by vaidic-dodwani** [comment]
@palisadoes  hey, i have completed the pull request revision. The only remaining step is to grant permission for modifying unauthorized_files.

**Comment by palisadoes** [comment]
Do not modify any protected files or the checks for them. We have them for  the previously stated reason.

**Comment by vaidic-dodwani** [comment]
@palisadoes what do you suggest i should do next for this issue, as it only needs a version update and it wont be possible without changing the pubspec.yaml

**Comment by palisadoes** [comment]
Edit the file but not the GitHub action configuration file

**Comment by vaidic-dodwani** [comment]
@palisadoes I apologize for any misunderstandings I may have created. I just made changes to the pubspec.yaml file for the update and have not edited any GitHub Actions files.

**Comment by Dante291** [comment]
Hello @vaidic-dodwani you're only pushing yaml file however whenever you upgade any package in yaml, pubspec.lock file also make changes according to it so you need to push that file too. You can take refrence from the dependabot's PR.

**Comment by palisadoes** [comment]
@aashimawadhwa will be handling all issue queries and seeking reviewers for PRs. When necessary, this contributor will contact other contributors who will be able to assist. Please ask them for guidance on your future questions.

**Review by noman2002 — APPROVED** [review]

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
