### PR TITLE
Add join org after auth test

### LINKED ISSUE #1227: Views: Create tests for join_organisation_after_auth.dart
The Talawa code base needs to be 100% reliable. This means we need to have 100% test code coverage.

Tests need to be written for file `lib/views/after_auth_screens/join_organisation_after_auth.dart`

- When complete, all methods, classes and/or functions in the file will need to be tested. 
- These tests must be placed in a single file with the name `test/views/after_auth_screens_test/join_organisation_after_auth_test.dart`. You may need to create the appropriate directory structure to do this.

### IMPORTANT:
Please refer to the parent issue on how to implement these tests correctly:

- https://github.com/PalisadoesFoundation/talawa/issues/1217

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base. This will be clearly visible when you submit your PR.
- [The current code coverage for the file can be found here](https://codecov.io/gh/PalisadoesFoundation/talawa/tree/develop/lib/views/after_auth_screens/). If the file isn't found in this directory, or there is a 404 error, then tests have not been created.
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide.
- You can verify your own code coverage by creating an account at [Codecov.io](https://codecov.io)

### PR DESCRIPTION
**Pull request by literalEval**
**What kind of change does this PR introduce?**

Adds test for `lib/views/after_auth_screens/join_organization_after_auth.dart`

**Issue Number:**

Fixes #1227 

**Did you add tests for your changes?**

Yes, this is a test PR

**Snapshots/Videos:**

Screenshot_20230214_115951

**Summary**

Added tests for the code that is testable. The plugin used in this file can't be tested and thus coverage can't be 100%

**Does this PR introduce a breaking change?**

No

### CODE REVIEW

**Comment by literalEval** [comment]
@palisadoes I am getting the same error regarding `Object not found` in the github action. Either you can ignore this error and merge, and then I will delete my form of talawa and refork it. Or if you say, I will close this PR and then open a new PR after reforking.

**Comment by Ayush0Chaudhary** [comment]
> @palisadoes I am getting the same error regarding `Object not found` in the github action. Either you can ignore this error and merge, and then I will delete my form of talawa and refork it. Or if you say, I will close this PR and then open a new PR after reforking.

https://github.com/PalisadoesFoundation/talawa/pull/1484#issuecomment-1429148754

**Comment by literalEval** [comment]
Hmm. I thought my fork was somehow 'corrupted', but seems like this issue is hitting everyone.

**Comment by palisadoes** [comment]
1. We added the new documentationcheck.py script.
1. It works with pushes, however the variables presented in PRs seem different. 
1. I'll troubleshoot. It'll take a few hours.

**Comment by palisadoes** [comment]
Please make a minor commit update. I've commented out the failing section. It should pass now.

**Comment by literalEval** [comment]
Done

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
