### PR TITLE
[GSoC] Add functionality to register for event

### LINKED ISSUE #926: [Feature request] Event Grouping
**Problem**
All events in the organisation is currently displayed ungrouped : Ideally, the user should be able to toggle between their subscribed events or all events in the organization
**Goals**
Provide a more streamlined event display : This should allow modularity for feature development in event management
**Out of Scope**
The following are aspects of this feature which have been considered but are outside of the scope for the current project:

Tag events : This will eventually allow a user to subscribe to, toggle display of and get notifications for specific types of events
Toggle personal event view, co-ordinator, organization and all views on calendar : This will allow the user to switch between the different views based on their roles.

**Proposal/Solution (User Experience)**
From the home screen users should be presented with a button to view events.
This view defaults to display all events for which the user is subscribed.
The user should be presented with the option to toggle between viewing all events, only their subscribed events and only their coordinated events.

### LINKED ISSUE #959: [GSoC] Add functionality to Register for event
**Is your feature request related to a problem? Please describe.**
There needs to be a functionality to register users for events.

**Describe the solution you'd like**
Add a FAB that shows the user if the event is registerable, user can register to the event only if they are registerable.
The events are unregisterable by default, it's better to keep them registerable so the creator may toggle the event back to unregisterable. Once the user register for an event, the "Registered" Badge should appear on the event card.

### PR DESCRIPTION
**Pull request by utkarshshendge**
**What kind of change does this PR introduce?**
Added functionality to register for an event.

**Issue Number:**

Fixes #959 

**Did you add tests for your changes?**
No

**Snapshots/Videos:**

https://user-images.githubusercontent.com/57677520/129603875-426933f4-b260-4a34-a020-9d4e6868c39e.mp4

https://user-images.githubusercontent.com/57677520/129604001-e4269678-94c2-451c-afe6-1e68249b19fb.mp4

**If relevant, did you update the documentation?**
Not required

**Summary**

- Added functionality to register for the event
- Added badge for registered event
- Grouped created events and registered events - as per #926 

**Does this PR introduce a breaking change?**
No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by Sagar2366** [comment]
@utkarshshendge please resolve the conflicts on your PR.

**Comment by palisadoes** [comment]
@utkarshshendge There are still issues with your PR GitHub actions workflow. Please review

**Comment by utkarshshendge** [comment]
> @utkarshshendge There are still issues with your PR GitHub actions workflow. Please review

Thanks for bringing this to attention @palisadoes. The warnings will be fixed after #985 gets merged.

**Comment by utkarshshendge** [comment]
@CyberWake  @rutvik11062000  please review. The testing check is failing because the current code coverage is 32% and target is set to 35%.

**Comment by palisadoes** [comment]
@utkarshshendge I updated the code coverage to 32%. I think the easiest way to do this is to  raise it by 1% after each successful PR.

**Comment by palisadoes** [comment]
@utkarshshendge please resubmit, or add a commit. I've updated the coverage to 32% but the GitHub actions are not using it in this PR run.

**Review by CyberWake — DISMISSED** [review]

**Comment by utkarshshendge** [comment]
> @utkarshshendge please resubmit, or add a commit. I've updated the coverage to 32% but the GitHub actions are not using it in this PR run.

Thank you @palisadoes for updating the coverage %age.

**Comment by utkarshshendge** [comment]
No @palisadoes,  I didn't write tests as of now. I might take some time to write tests because 8+ files have significant changes. So I think it's ideal to write tests for the event section seperately.

**Comment by palisadoes** [comment]
@utkarshshendge, @CyberWake  Is this safe to merge now? It's been some time.

**Review by palisadoes — APPROVED** [review]

**Comment by palisadoes** [comment]
@utkarshshendge Please resolve this conflict so that we can merge.

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
