### PR TITLE
chore: Add request-screen-1 with optional message.

### PR DESCRIPTION
**Pull request by Ayush0Chaudhary**
fixes https://github.com/PalisadoesFoundation/talawa/issues/1895
**What kind of change does this PR introduce?**
It gives the option to User to write message alongside sending membership request. 

**Did you add tests for your changes?**
not yet

**Snapshots/Videos:**

WhatsApp Image 2023-06-06 at 03 13 21

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**
Yes

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**
yes

### CODE REVIEW

**Comment by Ayush0Chaudhary** [comment]
@noman2002 @AdityaBirangal @palisadoes  
I have made basic struct of the request screen. 
1. Is there changes in any component I should make? or I should go forward with it.
2. I wanted to know if you like the idea before completely implementing the screen?
3. Also wanted to know if talawa logo is ok?

**Comment by noman2002** [comment]
@Ayush0Chaudhary Fix the formatting

**Comment by palisadoes** [comment]
@noman2002 @AdityaBirangal please review

**Comment by Ayush0Chaudhary** [comment]
https://github.com/PalisadoesFoundation/talawa/pull/1891

closing as merged in above PR

**Pull request closed without merging**
