### PR TITLE
added tests for SignupProgressIndicator widget

### LINKED ISSUE #1140: Unittests for widget signup_progress_indicator.dart
We will need unittests done for all methods, classes and functions found in this file.

Any widgets referenced in this file must also have unittests done

```
signup_progress_indicator.dart
```

This file can be found in the `lib/widgets` directory

Parent Issue: 
- https://github.com/PalisadoesFoundation/talawa/issues/1125

### PR DESCRIPTION
**Pull request by guptapriyanshu7**
**What kind of change does this PR introduce?**
Added Tests for SignupProgressIndicator Widget

**Issue Number:**

Fixes #1140 

**Did you add tests for your changes?**
Yes

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by palisadoes** [comment]
Please fix your linting issues that are causing the PR to fail and update the commit

**Comment by guptapriyanshu7** [comment]
@palisadoes , please review.

**Comment by palisadoes** [comment]
The test code coverage declined with this PR? Why is that? There are 102 affected files. This cannot be reviewed effectively.

**Comment by palisadoes** [comment]
I'm going to close this PR until you can figure out why we must review 100 files.

**Comment by guptapriyanshu7** [comment]
Sir, there was this 'Missing a required trailing comma', linting issue which automated test in this PR were reporting, so , as indicated by you, I fixed those in a separate commit.
I don't know why the code coverage reduced due to that.

**Comment by guptapriyanshu7** [comment]
Shall I make a new PR?

**Comment by palisadoes** [comment]
This has already been created and is being reviewed.
- https://github.com/PalisadoesFoundation/talawa/pull/1154

**Pull request closed without merging**
