### PR TITLE
Add crypto package and implement Password Encryption

### PR DESCRIPTION
**Pull request by literalEval**
**What kind of change does this PR introduce?**

1. Created an Encryptor class, which will be responsible for handling all of the encryption tasks. For now, password encryption is implemented.
2. Created a global switch to turn encryption on/off. This is only for development purposes, and will be removed (encryption will be default and mandatory) in future version.

**Did you add tests for your changes?**

Not needed

**Does this PR introduce a breaking change?**

Not for now, as encryption is disabled by default.

### CODE REVIEW

**Review by noman2002 — CHANGES_REQUESTED** [review]
Please fix the failing tests.

**Comment by literalEval** [comment]
@noman2002 the documentation check is failing because a PR was merged even when it did not have documentation for some files.

**Comment by palisadoes** [comment]
@literalEval Can you resolve the oversight on the documentation as part of this PR?

**Comment by literalEval** [comment]
@palisadoes do you mean I need to add the missing documentation in this PR itself ?

**Comment by palisadoes** [comment]
Yes if possible.

**Comment by literalEval** [comment]
@palisadoes @noman2002 the fails are only for documentation and can be ignored, as the said files are important and should be documented in a separate PR. I can myself document it in another PR.

**Comment by palisadoes** [comment]
@noman2002 Please review and make a suggestion as to how to proceed.

**Comment by palisadoes** [comment]
@noman2002 Please respond

**Review by noman2002 — APPROVED** [review]

**Comment by noman2002** [comment]
@literalEval Fix the conflicting files.

**Comment by literalEval** [comment]
@noman2002 sure

**Comment by literalEval** [comment]
@noman2002 fixed the conflicting files. Please merge so that I can open new PRs

**Comment by palisadoes** [comment]
@literalEval Please fix the failing tests. It looks like it's related to documentation

**Comment by literalEval** [comment]
@palisadoes I have already addressed this issue to the mentors and it will be fixed by the respective author who introduced the documentation issue.

**Comment by palisadoes** [comment]
@noman2002 @sumitra19jha @ nishnatadebnath Do you approve these changes?

**Comment by palisadoes** [comment]
@noman2002 @sumitra19jha @nishnatadebnath Do you approve these changes?

**Comment by noman2002** [comment]
@palisadoes We need to make few changes in workflow as there are almost 90 files that needs documentation and it is not possible to document them all in one single PR.

**Comment by literalEval** [comment]
@noman2002 I have added ignore statements to the files in the new PR. That'll stop errors from being generated in new PRs, and the original author will get some time to document them. 
Modifying the workflow is not required.

**Comment by noman2002** [comment]
okay, Then we can merge this.

**Review by noman2002 — APPROVED** [review]

**Comment by literalEval** [comment]
@palisadoes please merge

**Pull request merged**
