### PR TITLE
feat:Deprecate the Event task/project feature

### LINKED ISSUE #2296: Mobile - Deprecate the Project / Task Feature
**Is your feature request related to a problem? Please describe.**

To simplify the UI/UX we have decided to deprecate the Project / Task feature for Events. This means that all support for this feature must be removed from:

1. Talawa Admin
1. Talawa API
1. Talawa Mobile

**Describe the solution you'd like**

This includes removing all of the following related `Talawa` (Mobile App)items:

1. Sections of screens that contain references this feature
1. Any screens completely dedicated to this feature
1. Underlying code related to the specific support of this feature
1. Any testing code specific to this feature

**Describe alternatives you've considered**
- N/A

**Approach to be followed (optional)**
- N/A

**Additional context**

1. This is a prerequisite for our menu of GSoC 2024 project ideas
1. All other features and testing methodologies must remain unchanged
1. Changes must be limited to this repository
1. You may have to coordinate with the assignees for these issues:
    1. https://github.com/PalisadoesFoundation/talawa-admin/issues/1346
    2. https://github.com/PalisadoesFoundation/talawa/issues/2296
    3. https://github.com/PalisadoesFoundation/talawa-api/issues/1617

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by AVtheking**
**What kind of change does this PR introduce?**

Removed all code related to Event Task/project feature

**Issue Number:**

Fixes #2296 

**Did you add tests for your changes?**
No

**Does this PR introduce a breaking change?**

No

### CODE REVIEW

**Review by noman2002 — DISMISSED** [review]
Looks fine.

**Review by palisadoes — DISMISSED** [review]

**Comment by palisadoes** [comment]
Please fix the conflicting file so we can merge

**Comment by AVtheking** [comment]
I have fixed conflicts

**Comment by AVtheking** [comment]
fixed failing test

**Comment by AVtheking** [comment]
fixed failing test

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
