### PR TITLE
[Bug] Organization creation without providing image

### PR DESCRIPTION
**Pull request by sumitra19jha**
Issue: #170
Removal of error for the creation of organization without image.

https://user-images.githubusercontent.com/35868598/111061096-87678980-84c7-11eb-92e5-5c298da41733.mp4

### CODE REVIEW

**Review by CyberWake — COMMENTED** [review]
:thumbsup: lgtm

**Comment by sumitra19jha** [comment]
> 👍 lgtm

Can you please merge it?

**Comment by Sagar2366** [comment]
@sumtra19jha, fix the conflicts on this pr and send it again for review.

**Comment by CyberWake** [comment]
@sumitra19jha  code base was updated before this PR so need to have the conflicts resolved first. :v:

**Comment by sumitra19jha** [comment]
> @sumitra19jha  code base was updated before this PR so need to have the conflicts resolved first. :v:

Yes I am sorry. Just didn't know. Will take care of this from next time.

**Pull request closed without merging**
