### PR TITLE
 Update firebase_messaging from 14.4.1 to 14.5.0

### LINKED ISSUE #1810: Bug Report: Update firebase_messaging from 14.4.1 to 14.5.0
**Describe the bug**
Update firebase_messaging from 14.4.1 to 14.5.0. See PR #1808 for more information. 

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by SiddheshKukade**
**What kind of change does this PR introduce?**
 Update firebase_messaging from 14.4.1 to 14.5.0

**Issue Number:**

Fixes #1810
 
**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by Cioppolo14** [comment]
@SiddheshKukade There is now as firebase_messaging 14.6.0, can you update to that version?

**Comment by SiddheshKukade** [comment]
@Cioppolo14 Sure.

**Comment by SiddheshKukade** [comment]
@Cioppolo14 done  👍🏻

**Comment by palisadoes** [comment]
This may have been resolved. Please verify.

**Pull request closed without merging**
