### PR TITLE
Fix routing on edit event flow completion.

### LINKED ISSUE #1614: Edit Event Page throws error after pressing "Done".
**Describe the bug**
In the current implementation of the "Edit Event Page" - `/lib/views/after_auth_screens/events/edit_event_page.dart`, after editing event details and pressing "Done", an error occurs, due to which the loader comes up momentarily and then shuts down, giving the user no indication as to whether the event was actually updated or not. 

**To Reproduce**

1. Install Talawa, Talawa-API and Talawa-Admin as per their installation guides
2. Login as a talawa user into the application and create an event.
3. Go to the Event Info Page and subsequently open the Edit Event Page.
4. Update some values of the event and press "Done".

**Expected behavior**
The loader should spin till the API request is successfully acknowledged, post which the user should be taken back to the Event Info Page.  

**Actual behavior**
The loader spins for a short while and the user stays on the same page with no indication of whether the event was updated or not.

**Screenshots**

https://user-images.githubusercontent.com/55295613/222953409-cf190261-e469-4c20-8f3a-c60dcc800e75.mp4

**Additional details**
This is the error that comes up:
image

Looking at the above, we see that the mainScreen route expects non null arguments(`router.dart` Line 130), which are actually null when the following occurs:
image
in `event_service.dart`.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by ikjot-2605**
**What kind of change does this PR introduce?**

This PR introduces the fix for the edit event flow. Currently, on pressing the "Done" button in the edit event page, we are shown a loader momentarily and are kept on the same page - with a `Null check operator used on a null value` in the background(due to the null arguments in the Main Screen route). After this PR, the users will be redirected to the events page.

**Issue Number:**

Fixes #1614 

**Did you add tests for your changes?**

Yes

**Snapshots/Videos:**

Before:

https://user-images.githubusercontent.com/55295613/223220112-7bdf5e0d-5e9d-4905-b407-ab9fe1d4aea2.mp4

After:

https://user-images.githubusercontent.com/55295613/223222224-55d18aca-5504-4c57-bbcd-186a13be7ec0.mp4

**If relevant, did you update the documentation?**

N/A

**Does this PR introduce a breaking change?**

No

**Other information**

N/A

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by palisadoes** [comment]
Please fix the failing tests. Our test code coverage system will fail if either of these two conditions occur:

1. The overall code coverage drops below the target threshold of the repository
1. Any file in the pull request has code coverage levels below the repository threshold

We do this to ensure the overall reliability of the code base is maintained.

**Comment by ikjot-2605** [comment]
@palisadoes I have added the test for my diff in the `event_service_test.dart` file.
Please check.

**Review by noman2002 — APPROVED** [review]

**Comment by palisadoes** [comment]
We have a new check in place. All Talawa mobile app methods, classes and functions need to have suitable comments. Please refer to this issue as  reference for what is now required. The aim is to help us improve the quality of our automated documentation on docs.talawa.io.
 
- https://github.com/PalisadoesFoundation/talawa/issues/1479

To fix this issue:

1. You will be required to remove a line containing `ignore_for_file`
1. After doing so you'll be requested to update the comments appropriately

We have also tried to make the documentation step automatically update your IDE with a custom Linter. If you have any comments, please contact @literalEval who worked on this code.

**Comment by palisadoes** [comment]
Please fix the conflicting file. There may also be failed tests after you do so.  

We have a new check in place. All Talawa mobile app methods, classes and functions need to have suitable comments. Please refer to this issue as  reference for what is now required. The aim is to help us improve the quality of our automated documentation on docs.talawa.io.
 
- https://github.com/PalisadoesFoundation/talawa/issues/1479

To fix this issue:

1. You will be required to remove a line containing `ignore_for_file`
1. After doing so you'll be requested to update the comments appropriately

We have also tried to make the documentation step automatically update your IDE with a custom Linter. If you have any comments, please contact @literalEval who worked on this code.

**Comment by literalEval** [comment]
@ikjot-2605 it should be `Future<void>` and not `Future`: void. Same with Future<dynamic> etc :wink:

**Pull request closed without merging**
