### PR TITLE
changed the location of the Issue template and pr template

### LINKED ISSUE #353: Move Issue and PR templates
Move templates to .github/ISSUE_TEMPLATE and .github/PR_TEMPLATE

### PR DESCRIPTION
**Pull request by yasharth291**
**What kind of change does this PR introduce?**

It is a bugfix 

**Summary**

Moved the file issue_template to .github/ISSUE_TEMPLATE and moved pr_template to .github/PR_TEMPLATE

**Other information**
Fixes #353

### CODE REVIEW

**Comment by Sagar2366** [comment]
@yasharth291 this will also require change in contribution guidelines file (update paths for templates)

**Comment by yasharth291** [comment]
ok sir i will change

**Comment by yasharth291** [comment]
@Sagar2366  sir it is changed please review

**Review by Sagar2366 — APPROVED** [review]

**Review by Sagar2366 — COMMENTED** [review]
why template files are empty ?

**Comment by yasharth291** [comment]
which files sir ?

**Comment by yasharth291** [comment]
the name is changed not emptied sir

**Comment by Sagar2366** [comment]
> the name is changed not emptied sir

.github/ISSUE_TEMPLATE/issue-template.md
.github/ISSUE_TEMPLATE/pr-template.md
Showing 0 lines

**Comment by yasharth291** [comment]
sir that shows zero line changed

**Pull request merged**
