### PR TITLE
displaying profile pic in comments

### PR DESCRIPTION
**Pull request by pr4nshul**
**What kind of change does this PR introduce?**
#362 Refer this issue. It displays profile picture for each individual user.

**Did you add tests for your changes?**

**If relevant, did you update the documentation?**

**Summary**
Previously, a constant image from assets was being used, now profile image of each user is used.

**Does this PR introduce a breaking change?**
I don't think so

**Other information**
I have also added a CircularLoader while the userDetails is being fetched so there is slight delay less than a second before the newsArticle is shown to the user.
Also, let me know  if profile picture for every user which commented needs to be shown as I have discussed on slack and on the issue #362 itself.

### CODE REVIEW

**Review by Sagar2366 — APPROVED** [review]

**Comment by Sagar2366** [comment]
@pr4nshul resolve conflicts on this PR,

**Comment by pr4nshul** [comment]
I didn't know there were any conflicts during i pushed the PR , could you tell me  what conflicts are there.

**Comment by pr4nshul** [comment]
@Sagar2366 I think it should not have anymore conflicts now, although this was my first time resolving conflicts so if any errors please let me know.

**Comment by pr4nshul** [comment]
I have also reformatted the code using shortcut because it was getting quite unorganized with adding of if else condition above scaffold, so some lines might have been reformatted.

**Comment by Sagar2366** [comment]
@pr4nshul resolve Travis ci issue, without Travis pass it won't allow to merge PR.

**Comment by pr4nshul** [comment]
Ok , what might be the reason it's not working I haven't changed anything outside this particular file. Can you give me some input on it. As I haven't deployed a full fledge app using Travis till now.

**Comment by pr4nshul** [comment]
@Sagar2366 yes , so I think why Travis is throwing an error. I am using a `circularProgressIndicator ` and Travis expects a `TextField` , which it would receive once `userDetails` are loaded. So we might need to make a change in the test file itself. What do you recommend we should do?

**Comment by pr4nshul** [comment]
So, either we can change the tests or I can put a dummy `textField` with `circularProgressIndicator` but that won't be good fix ,and considering that in future we would need to load profile imgs of every user who commented we should tweak the tests.

**Comment by pr4nshul** [comment]
it's still failing I am trying I will let you know if can't find a solution by tomorrow, so that someone can help me with it.

**Comment by pr4nshul** [comment]
Ok, @Sagar2366  I would need help with this one, I have tried `async.tester` and checking for `CircularProgressIndicator` . I don't know how can we add such a tests such that _it waits until the state has been changed from_ `ProgressIndicator` to `Scaffold`. Another issue there is test for `comment button` and _unless the app is on the other state it can't reach that_.

**Comment by Sagar2366** [comment]
> Ok, @Sagar2366 I would need help with this one, I have tried `async.tester` and checking for `CircularProgressIndicator` . I don't know how can we add such a tests such that _it waits until the state has been changed from_ `ProgressIndicator` to `Scaffold`. Another issue there is test for `comment button` and _unless the app is on the other state it can't reach that_.

@pr4nshul check if this helps you - https://api.flutter.dev/flutter/flutter_test/WidgetTester/runAsync.html

**Comment by pr4nshul** [comment]
@Sagar2366  Please review PR #468 . I am closing this one as per our discussion.

**Pull request closed without merging**
