### PR TITLE
feat: Added feature to crop picture, Fixes issue #779.

### PR DESCRIPTION
**Pull request by afaanshariff**
**What kind of change does this PR introduce?**
feat: Adds a feature to crop pictures either after clicking the picture using the camera or when a user selects desired image from the gallery.

**Did you add tests for your changes?**
No, but I've tested it on different devices and it works as expected.

**If relevant, did you update the documentation?**
No.
**Summary**
Currently, we have image_picker to pick the image, but we cannot crop it. We are picking up profile pictures at two places, the signup screen, and the update profile screen. There should be a feature to crop the profile picture similar to WhatsApp, Instagram. So that's the reason why I've added this feature where users can crop, rotate and scale images before uploading them. 

**Does this PR introduce a breaking change?**
No.

**Other information**

### CODE REVIEW

**Comment by afaanshariff** [comment]
I dont know why the formatting have failed here, but on my device the result exited without any error code.
flutter format results1
flutter format results2

**Comment by palisadoes** [comment]
@afaanshariff  You need to run the script multiple times to clear the messages. Your most recent run probably cleared it. Commit and your changes to update the pull request.

**Comment by TheHazeEffect** [comment]
Hi @afaanshariff 

Great PR!

I feel we can make it even better, I recommend :

1.  Pinning ImageCropper to a version, ^1.4.0 should work fine, that way it's explicit what version is being used during development
2. Moving the cropping logic into UpdateProfilePageViewModel from the page file so we can separate view from logic. (MVVM)
3. Delete old _imgFrom Function if it's no longer being used (Removing dead code)
4. For simplicity and readability, I think it's best to split picking from Gallery and Camera into two separate functions (KISS - Keep it Simple)
5. I see we have some Repetition of code for both cropping and taking a photo, It's probably best we create an "ImageService" class that has functions to cropImage and Take photos and return the files (DRY - Don't repeat yourself)

Happy coding 🚀 

PS: The viewModel should be the one calling the ServiceClass and not the page itself

**Comment by afaanshariff** [comment]
Thank you @TheHazeEffect for correcting me.
1. Ok I'll do it
2. Yeah I also thought the same thing that code is being repeated, I'll move it.
3, 4, and 5. Could you help me with that, I've few doubts.

**Comment by TheHazeEffect** [comment]
> Thank you @TheHazeEffect for correcting me.
> 
> 1. I'll do it and also look into semantic versioning.
> 2. Yeah I also thought the same thing that code is being repeated, I'll move it.
>    3, 4, and 5. Could you help me with that, I've few doubts.


For 3, I noticed that both UpdateProfilePageViewModel and updateProfilePage both have functions called imgfrom, I'd think we only need one, so replace the one inside the viewmodel with the one you made in the page.

For 4, I noticed from the imgFrom function, an enum is used determine if the user would be selecting from Gallery or Camera, I feel it's probably best to simplify this by having separate function for each, maybe a "fetchImageFromGallery" and a "fetchImageFromCamera". Doing this makes it easier for new contributors to both maintain and understand the code.

For 5, This would mean 
 - Creating a new class named "ImageService" inside the service directory 
 - Move image specific logic into the new class (Fetch from Gallery, Fetch from Camera, Crop Image - each returning A File Object)
 - Use this new class in your ViewModel and RegisterForm to handle ImageOperations

Hopefully that was much clearer, specify anywhere you have any uncertainties and I'll try to address them.

**Comment by afaanshariff** [comment]
@TheHazeEffect thank you for specifying the details, I'll implement those things and then I'll commit the changes.

**Comment by palisadoes** [comment]
@afaanshariff Please resolve the conflicting file

`lib/views/pages/login_signup/register_form.dart
`

**Comment by TheHazeEffect** [comment]
Hei @afaanshariff 

You seem to have a few build errors, could you clear these up.

you can also run "flutter analyze" in your terminal before pushing to check if there are any errors

**Comment by palisadoes** [comment]
@afaanshariff the error is because your `pubspec.yml` dependencies are conflicting. This was resolved in a recent pull request. Please merge your code again to fix the issue. 

You also need to run  `flutter format --set-exit-if-changed .`  from your home directory a few times until you get no errors before submitting again.

**Comment by afaanshariff** [comment]
@TheHazeEffect @palisadoes there were no errors on my laptop here when I run those commands, because of conflicting merges from previous PR's, it's causing the issue.

**Comment by afaanshariff** [comment]
And I have already resolved the things which are present in #820, again there will be a merge conflict.
@TheHazeEffect @palisadoes.

**Comment by TheHazeEffect** [comment]
> @TheHazeEffect @palisadoes there were no errors on my laptop here when I run those commands, because of conflicting merges from previous PR's, it's causing the issue.

@afaanshariff  Currently on the branch that this PR is based on and I'm getting the below Errors
Screen Shot 2021-05-22 at 12 42 51 AM

**Comment by afaanshariff** [comment]
IMG_20210522_111625
After running flutter analyze

**Comment by afaanshariff** [comment]
@TheHazeEffect, and I had removed enums, as you suggested me that day.

**Comment by TheHazeEffect** [comment]
Ok, type the comment "git branch' in your terminal and let's see the result

**Comment by afaanshariff** [comment]
IMG_20210522_112027

**Comment by afaanshariff** [comment]
IMG_20210522_112330
@TheHazeEffect after entering git branch

**Comment by TheHazeEffect** [comment]
> IMG_20210522_112330
> @TheHazeEffect after entering git branch

@afaanshariff alright thanks you're on the correct branch, now do a "git status"

**Comment by afaanshariff** [comment]
image

**Comment by afaanshariff** [comment]
@TheHazeEffect you're welcome Sir, also you can see that my local repo is up to date.
image

**Comment by afaanshariff** [comment]
I just tried to create a new PR, and this is what I got.
image

@palisadoes @TheHazeEffect, shall I close this PR and submit a new PR??

**Comment by palisadoes** [comment]
@afaanshariff [please resolve the conflicts introduced in your `pubspec.yml` it's causing Travis integration to fail.](https://travis-ci.org/github/PalisadoesFoundation/talawa/builds/771819245)

This may have been fixed with a more recent pull request. Merge your code with the latest and see if this gets fixed.

Here is the error:

image

**Comment by afaanshariff** [comment]
@palisadoes, I've figured out the problem, earlier there was a feature where users can add profile image while signing up. But now it has been removed.

**Comment by palisadoes** [comment]
@afaanshariff please resolve the conflicting files. 

`lib/views/pages/login_signup/register_form.dart`

**Comment by afaanshariff** [comment]
yeah, sir, there is a problem here. Am resolving it. Can you give me some time please

**Comment by TheHazeEffect** [comment]
Cleared up the conflicts with @afaanshariff 

I'll be merging now

**Review by TheHazeEffect — APPROVED** [review]
Reviewed and meets requirements

**Pull request merged**
