### PR TITLE
Fixed Navigation After Signup

### PR DESCRIPTION
**Pull request by shikharsaurav**
What kind of change does this PR introduce:
Now on clicking back button on join organisation page after signup it will not exit the app & go to home page

Issue Number:
#503 

Did you add tests for your code?
No

Snapshots/Videos:

https://user-images.githubusercontent.com/47968768/112425119-8b16ce00-8d5b-11eb-9c28-fe0c56462b3d.mp4

**What kind of change does this PR introduce?**

**Did you add tests for your changes?**

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

### CODE REVIEW

**Comment by Sagar2366** [comment]
@shikharsaurav think of better solution for this scenario from end user perspective.
If user is signed in and not joined to any organisation, first message he should get is "Please join organisation to proceed" or something similar.
By allowing user to scroll through newsfeed, events page when it is not part of any organisation and specially when there is no data available for user it doesn't look nice.
I am sure we can provide user better redirection in this scenario.

**Comment by shikharsaurav** [comment]
ok sir

**Comment by shikharsaurav** [comment]
sir for that i will use raised button in news feed just like member page which says "No organization " joined then below that a button to redirect to join organization page

**Comment by shikharsaurav** [comment]
@Sagar2366 sir for that i will use raised button in news feed just like member page which says "No organization " joined then below that a button to redirect to join organization page

**Comment by Sagar2366** [comment]
For now you can redirect it to profile page with options to update profile, join/create organization, leave organization, logout and about.
Disable switch organization option on profile page and also disable newsfeed, chats, events and members pages.

Feel free to share your idea to deal with this issue.

**Comment by shikharsaurav** [comment]
@Sagar2366  but sir what after some time the user leaves all the organization he/she is in then same condition will arise like signUp
so i think it will be better if i give that button on news feed just like member so that will also look alike 
Looking for ur suggestions

**Comment by Sagar2366** [comment]
> @Sagar2366 but sir what if ,after some time the user leaves all the organization he/she is in then same condition will arise like signUp
> so i think it will be better if i give that button on news feed just like member so that will also look alike
> Looking for ur suggestions


If user leaves all organisations,
1. They should see message - not joined any organisation(already done)
2. Option to update profile, join/create organisation, logout and about talawa (already done)

Screenshot 2021-03-27 at 1 09 55 AM

**Comment by shikharsaurav** [comment]
@Sagar2366  sir i have added the navigations 

here is the demo 
https://thepalisadoes-dyb6419.slack.com/files/U01RQUQE2TW/F01SM32B8F5/20210327_115937.mp4

**Comment by Sagar2366** [comment]
@shikharsaurav let's keep this PR on hold. We might be removing organisation create option completely from talawa app.
Also, you have not handled case properly for events, chats, members screen - when user is not part of any organisation, these screens still showing data.

**Comment by palisadoes** [comment]
Please fix merge conflicts. The code freeze has been lifted.

**Comment by palisadoes** [comment]
Please fix merge conflicts. 

1. We have completely re-linted the master branch. 
1. We now have automated linting testing added to pull requests
1. We also have added Google's pendantic package to pubspec.yaml

For best results, I'll close this PR and you'll need to reopen a new bug against the master branch. 

The code freeze has been lifted.

**Pull request closed without merging**
