### PR TITLE
refactor: replace icon with a permanent link

### PR DESCRIPTION
**Pull request by SiddheshKukade**
**What kind of change does this PR introduce?**
Refracted image path to make it visible on docs.talawa.io

**Issue Number:**

Fixes https://github.com/PalisadoesFoundation/talawa/issues/1731
https://github.com/PalisadoesFoundation/talawa-docs/issues/404
**Did you add tests for your changes?**
N/A

**Snapshots/Videos:**
N/A

**If relevant, did you update the documentation?**
N/A

**Summary**

**Does this PR introduce a breaking change?**
N/A

**Other information**
N/A

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by SiddheshKukade** [comment]
@anwersayeed does this seem okay to you to make the logo visible on docs.talawa.io ?

**Comment by palisadoes** [comment]
1. The image is located here https://github.com/PalisadoesFoundation/talawa/raw/develop/assets/images/talawa-logo-lite-200x200.png
2. Other images are located in that directory

**Comment by anwersayeed** [comment]
> @anwersayeed does this seem okay to you to make the logo visible on docs.talawa.io ?

Yes

**Comment by SiddheshKukade** [comment]
@palisadoes the code is ready to be merged. please assign reviewers.

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
