### PR TITLE
converted private orgs to userRegistrationRequired orgs

### LINKED ISSUE #2287: Mobile - Remove Support for Private Organizations
**Is your feature request related to a problem? Please describe.**
We need to reduce and simplify some of the Talawa features. 

The concept of private organizations is unlikely given that most organizations using Talawa will be non-profits where transparency will be important.

**Describe the solution you'd like**

Remove all support for private organizations in:
1. Screens, sections of screens and supporting code that reference the feature

Other:

1. All tests must be valid and pass
1. No other functionality must be affected.

**Describe alternatives you've considered**
- N/A

**Approach to be followed (optional)**
- See above

**Additional context**
Related issues include:
1. https://github.com/PalisadoesFoundation/talawa-api/issues/1604
2. https://github.com/PalisadoesFoundation/talawa-admin/issues/1327
3. https://github.com/PalisadoesFoundation/talawa/issues/2287

**Potential internship candidates**
- Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by Azad99-9**
**What kind of change does this PR introduce?**

This PR converts all the support & references of `private organizations` to `userRegistrationRequired organizations`.

**Issue Number:**

Fixes #2287 

**Did you add tests for your changes?**

Yes

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**

The motive of this PR is to transform all the references and code of `private` organizatioins to `userRegistrationRequired` organizations.
The above transformation is achieved by replacing the `isPublic` attribute of `Organisation` model with `userRegistrationRequired` attribute in entire code base and making respective change to the logic.

**Does this PR introduce a breaking change?**

No

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by Azad99-9** [comment]
@palisadoes

To ensure the correct functionality of these updates, it is necessary to replace the `documents` in `Organization` collection of sample database with the ones adhering to the new `Organization schema` (containing userRegistrationRequired field)."

Screenshot from 2024-01-13 22-47-36

Moreover, somehow the [previous](https://github.com/PalisadoesFoundation/talawa-api/pull/1643) PR didn't update the code responsible for generating sample database. 
More precisely the files: 
1. `src/utilities/createSampleOrganizationUtil.ts ` with callback `createSampleOrganization`. 
2. `sample_data/organizations.json`.
The above are the files that came to my notice and need to be addressed.

**Comment by palisadoes** [comment]
An issue has been created to fix the DB importation and add it to the GitHub action workflow
- https://github.com/PalisadoesFoundation/talawa-api/issues/1685

**Comment by AVtheking** [comment]
Please merge this pr as it isPublic field in the query is causing error

**Comment by Azad99-9** [comment]
@palisadoes @literalEval @Ayush0Chaudhary @DMills27 @sumitra19jha dear reviewers, kindly review and merge this PR as soon as possible because the new `schema` changes from this [PR](https://github.com/PalisadoesFoundation/talawa-api/pull/1686) are conflicting with the models in `Talawa `App and not allowing the users to `login/signup` in to the app.

**Review by Ayush0Chaudhary — APPROVED** [review]

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
