### PR TITLE
Fixes #1437 Utilize TalawaErrorWidget Throughout App

### LINKED ISSUE #1437: Utilize TalawaErrorWidget Throughout App
1. We do not have a standardized error reporting scheme
1. We recently created TalawaErrorWidget for handling errors. We need use it for all our error messages.

Ideally there should be ways to adjust the output depending on the error severity for example:

1. Warning
2. Info
3. Error

Additionally:

1. The error messaging must also adjust any text to match the user's selected language of choice
2. The methodology must output messages to the console for ease of troubleshooting

### PR DESCRIPTION
**Pull request by Ayush0Chaudhary**
**What kind of change does this PR introduce?**
[Fixes](https://github.com/PalisadoesFoundation/talawa/commit/2f8a25950606af9bafb670eee68c932f82c36ed9) https://github.com/PalisadoesFoundation/talawa/issues/1437 [Utilize TalawaErrorWidget Throughout App](https://github.com/PalisadoesFoundation/talawa/commit/2f8a25950606af9bafb670eee68c932f82c36ed9)

**Issue Number:**

Fixes #1437 

**Did you add tests for your changes?**
YES

**Snapshots/Videos:**
Screenshot from 2023-02-24 21-34-51
Screenshot from 2023-02-24 21-35-35
Screenshot from 2023-02-24 21-35-47
Screenshot from 2023-02-24 21-39-00
Screenshot from 2023-02-24 21-39-18
Screenshot from 2023-02-24 21-39-28

**If relevant, did you update the documentation?**
NO

**Summary**
It was made to in order to **formalise** the error showing widget of the **talawa-app** 
It also have multilingual basic support, but can be made better.

**Does this PR introduce a breaking change?**
YES, kind of

**Other information**
NO

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**
YES

### CODE REVIEW

**Comment by Ayush0Chaudhary** [comment]
@palisadoes @noman2002 @xoldyckk @SiddheshKukade @TheHazeEffect please review!! :sweat_smile:

**Comment by noman2002** [comment]
@Ayush0Chaudhary Please attach a screenshot of codecoverage

**Review by noman2002 — APPROVED** [review]
Looks good to me. Good work.

**Comment by noman2002** [comment]
Need to know the code coverage before merging.

**Review by palisadoes — APPROVED** [review]

**Comment by Kraken005** [comment]
Is the issue still open?

**Comment by Ayush0Chaudhary** [comment]
@Kraken005 the issue is fixed.

**Pull request merged**
