### PR TITLE
Remember me feature

### LINKED ISSUE #2488: "Remember Me" Feature for Authentication
Describe the bug
Currently, there is no functionality in the application to remember user credentials after logging out. This feature is essential for enhancing user experience, especially for users who frequently access the application and prefer not to re-enter their credentials each time.

To Reproduce
N/A

Expected behavior
When the user logs in and selects "Remember Me", their credentials should be securely stored locally on the device. Upon logging out and reopening the application, the login screen should display the option to log in with the previously saved credentials. The user can then choose to log in automatically without re-entering their credentials.

Actual behavior
Currently, the application does not offer the option to remember user credentials. After logging out, the login screen always appears blank, requiring the user to manually enter their credentials each time they reopen the application.

Screenshots
N/A

Additional details
Implementing the "Remember Me" feature would significantly improve user convenience and streamline the login process. It would contribute to a smoother user experience and encourage user engagement with the application.

### PR DESCRIPTION
**Pull request by MohitMaulekhi**
**What kind of change does this PR introduce?**

**Issue Number:**

Fixes #2488

**Did you add tests for your changes?**

Yes. Previous unit tests have been updated and widget tests are added.

**Snapshots/Videos:**

WhatsApp Image 2024-12-22 at 15 54 28_fec152d4
WhatsApp Image 2024-12-22 at 15 54 30_3f2213e9
WhatsApp Image 2024-12-22 at 15 54 30_662dc85a

**Summary**

This PR introduces the "Remember Me" feature for the login process. When a user selects the "Remember Me" option, their login credentials will be securely stored on the device. This allows the app to automatically fill in the user's credentials on subsequent launches, providing a smoother and more convenient login experience.

**Does this PR introduce a breaking change?**

No. This feature is additive and does not introduce any breaking changes to existing functionality.

**Other information**
- Implemented "Remember Me" checkbox on the login screen.
- Integrated FlutterSecureStorage to securely store and retrieve login credentials.
- Added and updated test cases.
- New UI components to dynamically switch languages based on user preferences.

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**

Yes

## Summary by CodeRabbit

- **New Features**
  - Added support for "Remember me" and "Login directly with" translations in multiple languages (German, English, Spanish, French, Hindi, Japanese, Portuguese, Chinese).
  - Introduced `DirectlyLogin` widget for easier access to previously used credentials.
  - Added `CustomAlertDialogWithCheckbox` for enhanced user interactions during logout.

- **Bug Fixes**
  - Adjusted existing translations for consistency and formatting across multiple languages.

- **Documentation**
  - Updated documentation comments to clarify return types and method functionality.

- **Refactor**
  - Transitioned `AppSettingsPage` to a `StatefulWidget` to manage internal state for user credential storage.

- **Tests**
  - Enhanced test coverage for `LoginViewModel`, `SignupDetailsViewModel`, and `DirectlyLogin` widget, including secure storage mock setups.

### CODE REVIEW

**Comment by Cioppolo14** [comment]
@MohitMaulekhi Please fix the failed tests and do not assign reviewers in the future.

**Comment by palisadoes** [comment]
@noman2002 PTAL

**Review by Dante291 — APPROVED** [review]
LGTM, This is really good @MohitMaulekhi, Thanks :)

**Comment by palisadoes** [comment]
> @palisadoes In this PR a new package is added to pubspec.yaml file, I think workflow for checking sensitive files changed is not working properly as it passed in this case.

I made the update to the workflow

**Pull request merged**
