### PR TITLE
Fix #2061 deprecated splash screen

### LINKED ISSUE #2061: Deprecated error for splash screen.
**Describe the bug**
A splash screen was provided to Flutter, but this is deprecated. See flutter.dev/go/android-splash-migration for migration steps.
**To Reproduce**

1. run the app
2.
3.
4.

**Expected behavior**
no warning

**Screenshots**
image

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by Aryashakya**
**What kind of change does this PR introduce?**

Deprecated Splash Screen API Migration

**Issue Number:**

Fixes #2061 

**Did you add tests for your changes?**

No

**Summary**

Remove deprecated code.

**Does this PR introduce a breaking change?**

No.

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**

Yes.

### CODE REVIEW

**Comment by Aryashakya** [comment]
Please review it.

**Comment by palisadoes** [comment]
@Ayush0Chaudhary Please take a look
@Aryashakya It looks like you completely removed the splash screen. We want a splash screen using non-deprecated code.

**Comment by Aryashakya** [comment]
I have followed the instructions on [Flutter documentation ](flutter.dev/go/android-splash-migration)

**Comment by palisadoes** [comment]
It doesn't look like you did the recommended step #4. Your solution deletes the splash screen. We need the splash screen with non-deprecated code.

image

**Comment by Aryashakya** [comment]
Could you try running it?

I have tried it and the splash is not removed.

I have only removed the deprecated code.

**Comment by Aryashakya** [comment]
image

**Comment by palisadoes** [comment]
Thanks. I just wanted to make sure we maintained the functionality.

**Pull request merged**
