### PR TITLE
Fixes #1559 Fixes the fetch post

### LINKED ISSUE #1559: Feature Request: Using proper graphql scalars for different data types shared between clients and server
**Is your feature request related to a problem? Please describe.**

Talawa-api currently uses default scalars provided by graphql to parse/validate queries and exchange data with the clients. We are migrating to making use of graphql-scalars package and custom scalar types in talawa-api. Check out these links for more info:- [link1](https://github.com/PalisadoesFoundation/talawa-api/pull/1081), [link2](https://github.com/PalisadoesFoundation/talawa-api/pull/1085).

You can work with [eshaan](https://github.com/EshaanAgg) who's working on this in talawa-api to figure stuff out.

**Describe the solution you'd like**

We'd like talawa mobile to migrate their graphql SDL documents to make use of the new scalars. This would provide better validation to fields and a certain standard to the data exchanged between talawa mobile and talawa api.

**Describe alternatives you've considered**

 -
 
**Approach to be followed**

1. Replace the old scalar values with the new ones in the main app. This would probably include the functionality of receiving the new scalar type values from the api and parsing/transforming them to whatever the data type requirements are in dart/flutter and the app.
2. Migrate your test code to make use of the new scalar values. In the tests make sure you're not using dummy data which doesn't conform to new scalars as later it could prove fatal if api is used in any way for E2E tests or something of the sort.

**Additional context**

 -

**Potential internship candidates**

 -

### PR DESCRIPTION
**Pull request by Ayush0Chaudhary**
**What kind of change does this PR introduce?**
The fetch post was not working due to change in backend, it fixes that

**Issue Number:**

Fixes #1559

**Did you add tests for your changes?**

**Snapshots/Videos:**
Screenshot from 2023-03-21 02-37-07

**Summary**
the created at type chnaged

**Does this PR introduce a breaking change?**
YEs, kind of

**Other information**
I asked the permission of @literalEval to work on it, so I helped him on the issue.
https://github.com/PalisadoesFoundation/talawa/issues/1559#issuecomment-1466714744

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**
yes

### CODE REVIEW

**Comment by Ayush0Chaudhary** [comment]
Now the fetch post is also working! @palisadoes @noman2002

**Comment by literalEval** [comment]
@Ayush0Chaudhary Thanks for the help. Please fix the documentation though.

**Comment by Ayush0Chaudhary** [comment]
@palisadoes @noman2002 I think we should also add CI/CD job to test whether this PR have latest changes of develop branch.
As of now their is nothing of this sort.

**Comment by Ayush0Chaudhary** [comment]
Also @palisadoes @noman2002 
The custom lint is asking me to write docs for main function of the test
I don't think that is necessary. 
@literalEval We should remove tests from the scope of documentation. They are already self explanatory as they have a description message. No-org in general document their tests.

**Comment by literalEval** [comment]
@Ayush0Chaudhary on it. Will fix that soon.

**Comment by literalEval** [comment]
The `custom_lint` package is itself evolving for now, and we are bound to use some workarounds for now.

**Review by noman2002 — CHANGES_REQUESTED** [review]
Please fix the failing test.

**Comment by palisadoes** [comment]
A 0.01% difference is a rounding error. This PR should be reviewed. @noman2002 @CyberWake @TheHazeEffect @tonythegr8

**Comment by literalEval** [comment]
@Ayush0Chaudhary variables don't need the `params:` block. Please remove that. You can have a look at our documentation for the lint system [here](https://docs.talawa.io/docs/developers/talawa/talawa-lint/#for-non-functionmethodgettersetter-classes-enums-variables-etc)

**Comment by literalEval** [comment]
@Ayush0Chaudhary thanks.

**Comment by Ayush0Chaudhary** [comment]
@literalEval 🫂
@palisadoes @noman2002 please review the PR.

**Review by palisadoes — APPROVED** [review]

**Review by noman2002 — APPROVED** [review]

**Pull request merged**
