### PR TITLE
Notification Related Implementation Removed

### LINKED ISSUE #2086: [Feature Request] Remove notification related implementation
**Is your feature request related to a problem? Please describe.**
Currently it doesn't hinder the app but comment out all the notification related logic and add `TODO:`

**Describe the solution you'd like**
comment it out

**Additional context**
this is to make app compatible for MVP

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by andoriyaprashant**
**What kind of change does this PR introduce?**

- Notification Related Implementation Removed

**Issue Number:**

Fixes #2086 

**Did you add tests for your changes?**

- Yes

**Summary**

This pull request addresses the removal of notification-related logic in the app to make it compatible with the MVP phase.

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**

- Yes

### CODE REVIEW

**Comment by Ayush0Chaudhary** [comment]
Please complete the checks @andoriyaprashant

**Comment by andoriyaprashant** [comment]
> Please complete the checks @andoriyaprashant

Done @Ayush0Chaudhary

**Review by noman2002 — COMMENTED** [review]
@Ayush0Chaudhary Is there anything else that needs to be commented?

**Comment by noman2002** [comment]
@Ayush0Chaudhary Please have a look.

**Review by noman2002 — APPROVED** [review]

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
