### PR TITLE
Test: Add test for post_widget.dart file

### LINKED ISSUE #1139: Unittests for widget post_widget.dart
We will need unittests done for all methods, classes and functions found in this file.

Any widgets referenced in this file must also have unittests done

```
post_widget.dart
```

This file can be found in the `lib/widgets` directory

Parent Issue: 
- https://github.com/PalisadoesFoundation/talawa/issues/1125

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base.
- [The current code coverage for the file can be found here](https://codecov.io/gh/PalisadoesFoundation/talawa/tree/develop/lib/widgets)
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide

### PR DESCRIPTION
**Pull request by RandyKdev**
**What kind of change does this PR introduce?**

Test

**Issue Number:**

Fixes #1139

**Did you add tests for your changes?**

Yes

**Snapshots/Videos:**

None

**If relevant, did you update the documentation?**

No

**Summary**

Add tests to the file post_widget.dart in the widgets folder. Fixes issue #1139 

**Does this PR introduce a breaking change?**

No

**Other information**

None

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by palisadoes** [comment]
Randy, please post the test coverage for the file in your comments. We cannot see the values.

**Comment by RandyKdev** [comment]
The post_widget.dart file has a test coverage of 100%

**Comment by RandyKdev** [comment]
[Here is the link to the codecov page](https://app.codecov.io/gh/PalisadoesFoundation/talawa/blob/237c55a5e5c635085b3d6ccf539ee1f8160f82e7/lib/widgets/post_widget.dart)

**Comment by palisadoes** [comment]
Thanks. This looks like a thorough approach.

**Review by DeltaHarbinger — APPROVED** [review]
Looks good to me

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
