### PR TITLE
Fixes the `step state output`, causing doc updation to be functional again.

### LINKED ISSUE #1750: Remove `docs` directory from codebase
Currently, we have a `docs` folder in the root of the codebase, which contains the documentation generated by `dart doc`. This issue proposes to remove this directory entirely.

The reasons can be explained as:

1. The directory is currently of about ~20mbs. That's a waste of bandwidth and space.
2. Everything that the doc mentions is already in the codebase and can be generated by `dart doc` on the go. Anyone can do this on their local machine.
3. We are already hosting our documentation on `Talawa-docs`

### PR DESCRIPTION
**Pull request by literalEval**
**What kind of change does this PR introduce?**

The doc updation to `Talawa Docs` was not working for some reason, for quite some time. Migrating to latest alternative of step-state causes things to work again.

**Issue Number:**

Fixes #1750

### CODE REVIEW

**Comment by literalEval** [comment]
@palisadoes please merge so that it's working can be confirmed. I'll be having a close look at the workflow run and let you know to revert if anything goes wrong. Thanks.

Once this is accepted to be working fine, I will remove the `docs` directory in the next PR.

**Review by palisadoes — APPROVED** [review]

**Comment by palisadoes** [comment]
If this doesn't work. Create an additional PR and have @anwersayeed review it too

**Comment by literalEval** [comment]
@palisadoes everything is working fine except the copying to `Talawa Docs` part. The environment variables need to be updated/properly referenced. To be precise, you will need to setup a secret named `API_TOKEN_GITHUB`, in this repo's secrets, and that will refer to the token of the account that is admin of all the talawa repos. Please setup that secret and make sure the TOKEN provided is correct. If the copying still doesn't work still, then we will revert and further analyze.

**Comment by palisadoes** [comment]
API_TOKEN_GITHUB was already created and was working before.

**Comment by palisadoes** [comment]
1. Please verify if something else was needed.
2. EMAIL is probably not needed as inter-repo copying was working before

**Comment by palisadoes** [comment]
This is the failure. It used to work before @anwersayeed  and I verified this about a month ago using the API_TOKEN_GITHUB credentials. 

- https://github.com/PalisadoesFoundation/talawa/actions/runs/4651664180/jobs/8231408545

What more should we be doing.

**Comment by literalEval** [comment]
@palisadoes maybe the token expired?
Because the name "palisadoes" seems to be correct, the email is not the problem (as you say), so the only variable in the authentication is the API token. Can you please confirm if its expired or not ?

**Comment by palisadoes** [comment]
It's not expired.

**Comment by literalEval** [comment]
@anwersayeed @palisadoes  the email it is using is mine (as I initiated the push workflow). Can you please once again confirm if that is not the problem?

Also, if possible, can you please link to a successful run of this workflow in the past? That will help me in debugging. I went back a lot, but didn't find a push workflow that actually ran this.

**Comment by palisadoes** [comment]
It should have been this one.

- https://github.com/PalisadoesFoundation/talawa/commit/3dfe1ff311ab597375bbf52ac510e9ff7f8e26f8
- https://github.com/PalisadoesFoundation/talawa/actions/runs/4396079495

**Comment by literalEval** [comment]
> It should have been this one.
> 
> * [3dfe1ff](https://github.com/PalisadoesFoundation/talawa/commit/3dfe1ff311ab597375bbf52ac510e9ff7f8e26f8)
> * https://github.com/PalisadoesFoundation/talawa/actions/runs/4396079495

@palisadoes Unfortunately this is not a 'successful' run, as the `Copy docs to Talawa Docs` step of the workflow says `No changes detected` :)

**Comment by literalEval** [comment]
> I created as secret called `TALAWA_DOCS_SYNC` that has been deployed as an environment variable for all the main Talawa repos. Please use this.
> 
> * [Add auto schema markdown generation to Talawa-API [Fixes part of #1240] talawa-api#1247](https://github.com/PalisadoesFoundation/talawa-api/pull/1247) as a reference. I'd prefer to use the same documentation update methodology across all the repos.
> 
> image

Let me try 🫡

**Comment by palisadoes** [comment]
You may want to discuss this with @eshaanagg
- https://github.com/PalisadoesFoundation/talawa-api/pull/1247#issuecomment-1502649860

**Comment by literalEval** [comment]
Will do. Thanks.

**Comment by literalEval** [comment]
@palisadoes you can revert this PR if you want. I'll try to open a new PR by today's EOD. Thanks.

**Comment by literalEval** [comment]
> I created as secret called `TALAWA_DOCS_SYNC` that has been deployed as an environment variable for all the main Talawa repos. Please use this.
> 
> * [Add auto schema markdown generation to Talawa-API [Fixes part of #1240] talawa-api#1247](https://github.com/PalisadoesFoundation/talawa-api/pull/1247) as a reference. I'd prefer to use the same documentation update methodology across all the repos.
> 
> image

@palisadoes what is the name of this environment? Please [read this section](https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment#using-an-environment)

**Comment by palisadoes** [comment]
We have a branch protection rules that require 2 approvals before merging. This is affecting the new push actions.
- https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/managing-a-branch-protection-rule

This is affecting the Talawa-API workflow.

The Talawa push workflow is now failing like this:

- https://github.com/PalisadoesFoundation/talawa/actions/runs/4669294915/jobs/8267543523

**Pull request merged**
