### PR TITLE
[Bug Fix] Camera Access permission denied bug fix

### LINKED ISSUE #950: PlatformException (camera_access_denied)
**Describe the bug**
When user deny the  camera permission it will get permanently denied, after if user try to pick image then their is no response from the app side.

**To Reproduce**

1. Install App
2. Navigate To Profile Screen
3. Update profile pic 
4. Deny the runtime permission 
5. Once its get permanently denied retry to update profile pic
6. No response from the application

**Expected behavior**
Once the permission is permanently denied , alert dialog should raise with the message for permission and  
option to visit app setting to give permission .

**Actual behavior**
When the permission denied exception is thrown , no action is taken to alert the user

**Screenshots**
NO

**Additional details**
NO

### PR DESCRIPTION
**Pull request by tosif91**
**What kind of change does this PR introduce?**

bugfix

**Issue Number:**

Fixes   #950   

**Did you add tests for your changes?**

No

**Snapshots/Videos:**

https://user-images.githubusercontent.com/61594032/129401287-defec550-dd05-4c78-9419-4886485d8fe0.mp4

**If relevant, did you update the documentation?**

Not required.

**Summary**

When user deny the camera permission it will get permanently denied, after if user try to pick image then their is no response from the app side. 

**Does this PR introduce a breaking change?**

No, this PR does not bring breaking changes.

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Review by Sagar2366 — DISMISSED** [review]

**Comment by Sagar2366** [comment]
@tosif91 please resolve the conflicts on your PR.

**Comment by tosif91** [comment]
> @tosif91 please resolve the conflicts on your PR.

Please help me in fixing this issue i have already fixed it before now again the issue occur

**Comment by palisadoes** [comment]
@tosif91 We have many contributors making simultaneous pull requests that often modify the same files. This can cause merge conflicts, especially if you don't do a `git merge` on your local repo immediately before making your PR submission. Please fetch the latest upstream `develop` branch, merge it successfully on your local machine, and then resubmit the PR. That should fix the issue.

**Comment by palisadoes** [comment]
@tosif91 there are some conflicts, please resolve and resubmit

**Comment by tosif91** [comment]
ok

**Comment by palisadoes** [comment]
@DeltaHarbinger @TheHazeEffect  please review.

**Review by palisadoes — CHANGES_REQUESTED** [review]
@tosif91 What issue does this resolve? You say it fixes the issue #969 that is this pull request. Please create an issue for this according to the guidelines in our [contributing.md](https://github.com/PalisadoesFoundation/talawa/blob/develop/CONTRIBUTING.md) documentation.

**Comment by palisadoes** [comment]
@tosif91 Your PR is failing as you have not included the required level of tests. We now require 35% code coverage. Please update your code to include the required level of testing. This may also require you to add tests for code you have not submitted. 

Improving our code coverage is a major goal for 2021 / 2022.

**Comment by palisadoes** [comment]
@tosif91 The code base has been updated with a more recent pull request that should have fixed the issue. Please merge your branch with the lastest `upstream/develop` and push to your repo. GitHub should detect the changes and re-run the tests on the updated code. This will fix the conflicting files.

**Comment by tosif91** [comment]
ok

**Comment by palisadoes** [comment]
@Sagar2366 @sumitra19jha @TheHazeEffect @CyberWake Please review.

**Comment by palisadoes** [comment]
@tosif91 Our code base has changed. Please merge you code with `upstream/develop` and resubmit. The changes made make most of our tests run on `pull_request` and not all on `pull_request_target` as you see in the image of the PR tests. This was causing us significant problems with successful testing sequencing and execution. The changes we just made should fix this. We are in effect, testing the test regime changes.

image

**Comment by palisadoes** [comment]
@tosif91 Please fix the conflicting file in your PR so we can review and merge.

**Comment by palisadoes** [comment]
@tosif91 Please fix the conflicting file in your PR so we can review and merge.

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
