### PR TITLE
enhancement for password strength bar

### LINKED ISSUE #210: Enhancement for the password strength bar
Currently, the **password strength bar** is visible to the user even when the **password text field** is empty.
Also, the **password strength bar** updates only after the `TextFormField` is saved.

**Enhancement:**
1. The **password strength bar** should only be visible if the **password text field** is not empty.

2. The **password strength bar** should update when the content in the `TextFormField` changes.

### PR DESCRIPTION
**Pull request by Raunakk02**
resolves #210

### CODE REVIEW

**Comment by DeltaHarbinger** [comment]
Hey @Raunakk02, it seems like this PR has conflicts with another that was recently merged. Can you pull the other changes and re-implement yours to avoid having to manually resolve merge conflicts?

**Comment by Raunakk02** [comment]
Ya sure. Working on it!

**Comment by Raunakk02** [comment]
@DeltaHarbinger I re-merged the changes on the upstream.  Please merge this PR if it's fine!

**Comment by Sagar2366** [comment]
This is cool addition to password field on signup page.

**Comment by Raunakk02** [comment]
> This is cool addition to password field on signup page.

Thanks, @Sagar2366!

**Comment by Raunakk02** [comment]
I submitted PR #385 which re-implements one of the features mentioned in this issue. Please review it!

**Pull request merged**
