### PR TITLE
Fixed FToast initialization bugs in all files.

### PR DESCRIPTION
**Pull request by AniketSindhu**
fixed issue #163

### CODE REVIEW

**Comment by DeltaHarbinger** [comment]
Hey @AniketSindhu, please check to see if your version of Flutter is up-to-date. Be sure to run ```flutter pub get``` to ensure your version of FToast is up to date as the ```.init``` is needed in newer versions. Please see https://pub.dev/packages/fluttertoast/changelog#710 for more info on that update to the package.

**Comment by AniketSindhu** [comment]
image
 in the pubspec.yaml(master branch) fluttertoast 7.0.1 is used which is older version which is causing the issue

**Comment by DeltaHarbinger** [comment]
That's a great idea. The minimum version listed in pubspec should be changed to be beyond the version with the breaking update. Feel free to make a PR with version 7.1 or over as the minimum version

**Comment by AniketSindhu** [comment]
@DeltaHarbinger created PR #166

**Pull request closed without merging**
