### PR TITLE
Add test for event_card.dart

### LINKED ISSUE #1131: Unittests for widget event_card.dart
We will need unittests done for all methods, classes and functions found in this file.

Any widgets referenced in this file must also have unittests done

```
event_card.dart
```

This file can be found in the `lib/widgets` directory

Parent Issue: 
- https://github.com/PalisadoesFoundation/talawa/issues/1125

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base.
- [The current code coverage for the file can be found here](https://codecov.io/gh/PalisadoesFoundation/talawa/tree/develop/lib/widgets)
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide

### PR DESCRIPTION
**Pull request by literalEval**
**What kind of change does this PR introduce?**

Adds test for widget EventCard (lib/widgets/event_card.dart)

**Issue Number:**

Fixes #1131

**Does this PR introduce a breaking change?**

No

### CODE REVIEW

**Comment by palisadoes** [comment]
The code coverage has declined from 71% to 68%. Please fix.

image

**Review by palisadoes — CHANGES_REQUESTED** [review]
The code coverage has declined. Please fix. image

**Comment by palisadoes** [comment]
Also, the code coverage for the file isn't 100%. Please refer to this link: https://app.codecov.io/gh/PalisadoesFoundation/talawa/blob/develop/lib/widgets/event_card.dart

**Review by palisadoes — CHANGES_REQUESTED** [review]
Also, the code coverage for the file isn't 100%. Please refer to this link: https://app.codecov.io/gh/PalisadoesFoundation/talawa/blob/develop/lib/widgets/event_card.dart

**Comment by literalEval** [comment]
But I didn't change any file except this new one. How can the code coverage decline then ? Can you please tell me anything about it so that I can fix that issue ?

**Comment by literalEval** [comment]
Also, please have a look at this [Event Card Coverage](https://app.codecov.io/gh/PalisadoesFoundation/talawa/blob/add_event_card_test/lib/widgets/event_card.dart)

**Review by palisadoes — APPROVED** [review]

**Comment by palisadoes** [comment]
I'm going to approve it and adjust the code coverage accordingly.

**Pull request merged**
