### PR TITLE
Testing: Edit profile page testing.

### LINKED ISSUE #1229: Views: Create tests for edit_profile_page.dart
The Talawa code base needs to be 100% reliable. This means we need to have 100% test code coverage.

Tests need to be written for file `lib/views/after_auth_screens/profile/edit_profile_page.dart`

- When complete, all methods, classes and/or functions in the file will need to be tested. 
- These tests must be placed in a single file with the name `test/views/after_auth_screens/profile_test/edit_profile_page_test.dart`. You may need to create the appropriate directory structure to do this.

### IMPORTANT:
Please refer to the parent issue on how to implement these tests correctly:

- https://github.com/PalisadoesFoundation/talawa/issues/1217

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base. This will be clearly visible when you submit your PR.
- [The current code coverage for the file can be found here](https://codecov.io/gh/PalisadoesFoundation/talawa/tree/develop/lib/views/after_auth_screens/profile/). If the file isn't found in this directory, or there is a 404 error, then tests have not been created.
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide.
- You can verify your own code coverage by creating an account at [Codecov.io](https://codecov.io)

### PR DESCRIPTION
**Pull request by CyberWake**
**What kind of change does this PR introduce?**

**Issue Number:**
#1229 
Fixes #1229 

**Did you add tests for your changes?**
Yes, I have added all the tests required for the corresponding issue.

**If relevant, did you update the documentation?**
Not, needed

**Summary**
This contains the tests for Edit profile page screen.

**Does this PR introduce a breaking change?**
No, this PR does not bring in breaking changes.

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**
Yes, I have read the contribution guide.

### CODE REVIEW

**Review by palisadoes — CHANGES_REQUESTED** [review]
1. Why did you explicitly create the `temporaryPath` directory? Is there a package that could be used to create temporary directories and clean them up after use, possibly outside of the code base tree? Some languages have that feature, for example the python `tmpfile` package.
1. Even so, shouldn't the `temporaryPath` directory be added to `.gitignore`?

**Comment by CyberWake** [comment]
> 1. Why did you explicitly create the `temporaryPath` directory? Is there a package that could be used to create temporary directories and clean them up after use, possibly outside of the code base tree? Some languages have that feature, for example the python `tmpfile` package.
> 2. Even so, shouldn't the `temporaryPath` directory be added to `.gitignore`?

1. @palisadoes these were auto generated files and they get generated when we test any hive model.
2. I don't feel that need of putting it to .gitignore since these will always we getting created on actions and every person adding test for there work if something breaks on adding it to .gitignore I don't have that sufficient input from the docs of the package Hive used for local storage in Talawa.

**Comment by palisadoes** [comment]
You have this hard coded in the test file. It implies that this is the name of the `temporaryPath` directory being used.

```
const String kTemporaryPath = 'temporaryPath';
```
We should not have temporary files checked in to the GitHub repository, even if the temporary files are generated on testing. We have used this strategy successfully for the `coverage/` directory used for generating our test code coverage. We need to do the same here. 

This PR is checking in several zero byte temporary files that should not be there.

**Comment by CyberWake** [comment]
> 

Thanks for correcting me out on `kTemporaryPath` this is just for testing purpose like when we mock some thing it has some hard coded things like on case of mocking local database we provide it with some mock system path. hence this is a constant and potentially be any string.
I am adding one more commit after seeing the possibilities that actions don't fail after putting these files in `.gitignore`.

**Comment by palisadoes** [comment]
@DeltaHarbinger @Sagar2366 @TheHazeEffect please review

**Review by TheHazeEffect — APPROVED** [review]
Looks good by me, Good Job!

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
