### PR TITLE
Intro slides to provide quick insights

### LINKED ISSUE #966: Introduction Slides
**Is your feature request related to a problem? Please describe.**
Introduction slides can be added at startup for first-time users to
provide a quick introduction of the app & its features.

**Describe the solution you'd like**
We can add 3-4 screens to introduce app &  it's feature. with some text & graphics 
also will provide skip option to directly jump to login page.

**Describe alternatives you've considered**
N/A

**Approach to be followed (optional)**
1. Design UI & graphics images 
2. Code UI in flutter 

**Additional context**
GitHub Externship

### PR DESCRIPTION
**Pull request by AdityaBirangal**
**What kind of change does this PR introduce?**
Introduction slides added at startup for first-time users to provide a quick insights of the app

**Issue Number:**
Fixes #966 

**Video/Screenshots**

ezgif com-resize

**If relevant, did you update the documentation?**
No required

**Summary**
3 sliding screens added to introduce app & it's feature. with some text & graphics
also skip option is provided to directly jump to login page.

**Does this PR introduce a breaking change?**
Nope

**Other information**
 Multi-lingual support also added

### CODE REVIEW

**Comment by CyberWake** [comment]
@AdityaBirangal can you please attach a demo clipping as well!

**Comment by AdityaBirangal** [comment]
@CyberWake comment Updated with gif. Thanks

**Comment by CyberWake** [comment]
@AdityaBirangal, please resolve the conflicts and also add this `.flutter-plugin-dependencies` in `.gitingnore`

**Comment by AdityaBirangal** [comment]
@CyberWake conflicts resolved  & .flutter-plugin-dependencies has been deleted from remote as well.

**Comment by AdityaBirangal** [comment]
@sumitra19jha , @CyberWake 
Is there any updates required in this PR ?

**Comment by CyberWake** [comment]
> @AdityaBirangal, please resolve the conflicts and also add this `.flutter-plugin-dependencies` in `.gitingnore`

Resolve the conflicts @AdityaBirangal so we can proceed with merge.

**Comment by CyberWake** [comment]
@palisadoes sir need inputs from you as well on this app intro slide feature about the aesthetics and flow.

**Comment by AdityaBirangal** [comment]
> > @AdityaBirangal, please resolve the conflicts and also add this `.flutter-plugin-dependencies` in `.gitingnore`
> 
> Resolve the conflicts @AdityaBirangal so we can proceed with merge.

@CyberWake Conflites resolved 👍🏻

Testing Workflow failing because of 'accentColor' is deprecated. & We need to use colorScheme.secondary everywhere .

**Comment by CyberWake** [comment]
no worries on this @AdityaBirangal we are working on it. Will let you know once it gets fixed.

**Comment by palisadoes** [comment]
@AdityaBirangal This is a good idea

1. These slides should come at the very end of registration, just before the user sees the newsfeed. The slides will be a distraction if presented before then.
1. There should be a "Congratulations" screen, to make the user know that they can proceed. The positive confirmation would be good.
1. Does this have multilingual support too?
1. The wording needs to be changed as it speaks to the needs of the Talawa administrator and not the user. We should be highlighting the newsfeed, the fact that you can group chat with anyone invited to your meetings or going to events that you have registered with, and that you can create your own chat groups.
1. Do you have a workflow in Figma that you can share?
1. The "congratulations" screen should offer a link to the tutorial screens, and skip.

**Review by palisadoes — CHANGES_REQUESTED** [review]
@AdityaBirangal This is a good idea

 1.   These slides should come at the very end of registration, just before the user sees the newsfeed. The slides will be a distraction if presented before then.
 1.   There should be a "Congratulations" screen, to make the user know that they can proceed. The positive confirmation would be good.
  1.  Does this have multilingual support too?
   1. The wording needs to be changed as it speaks to the needs of the Talawa administrator and not the user. We should be highlighting the newsfeed, the fact that you can group chat with anyone invited to your meetings or going to events that you have registered with, and that you can create your own chat groups.
  1.  Do you have a workflow in Figma that you can share?
   1. The "congratulations" screen should offer a link to the tutorial screens, and skip.

**Pull request closed without merging**
