### PR TITLE
Fixes Issue #1032

### LINKED ISSUE #1032: Bug report
**Describe the bug**
When uploaded an image in a post screen, the keyboard pop to write the caption produces the bottom overflow by 45 pixels.

**Screenshots**

*When keyboard is not triggered*

Screenshot 2021-12-09 at 2 13 59 AM

*When Keyboard is up*

Screenshot 2021-12-09 at 2 14 13 AM

I would like to work on this. Thanks

### PR DESCRIPTION
**Pull request by AvneetSingh2001**
**What kind of change does this PR introduce?**
The changes avoids every possibility of bottom overflow in the post screen. 
The bottom overflow was occurring when :-
- caption exceeds the length of the screen.
- Writing caption when keyboard was up.
- Writing caption after uploading image.

**Issue Number:**

Fixes #1032 

**Did you add tests for your changes?**
No

**Snapshots/Videos:**
Screenshot 2021-12-09 at 4 40 29 PM

**If relevant, did you update the documentation?**
No

**Does this PR introduce a breaking change?**
No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by palisadoes** [comment]
@AvneetSingh2001 Please investigate why your the PR tests are failing and modify your code to make sure all the tests pass.

**Comment by AvneetSingh2001** [comment]
@palisadoes @sumitra19jha, the greeting message(PR workflow) is fixed. Now, this error in checks is due to unnecessary imports present in the original codebase.

**Comment by palisadoes** [comment]
@AvneetSingh2001 Please lint the code with `flutter analyze --no-pub` and resubmit. It's an easy fix. We approved a PR when the greeting message first happened without realizing that other GitHub actions were failing.

**Comment by palisadoes** [comment]
The code base has been updated with a more recent pull request that should have fixed the issue. Please merge your branch with the lastest `upstream/develop` and push to your repo. GitHub should detect the changes and re-run the tests on the updated code.

This will fix the conflicting files message that has been found.

**Comment by AvneetSingh2001** [comment]
All checks have passed now. Thanks a lot, @palisadoes.

**Review by CyberWake — CHANGES_REQUESTED** [review]
Can you please look into the files for the ios build since there are a lot of ios platform-specific files getting changed which generally wouldn't be needed to resolve the issue linked.
Add-on please add .flutter-plugins-dependencies to .git folder

**Review by CyberWake — APPROVED** [review]

**Comment by CyberWake** [comment]
@palisadoes this PR is ready to be merged.

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
