### PR TITLE
language-selection-title-fix

### PR DESCRIPTION
**Pull request by Literal-Eval**
- Fixes title size change when selecting different languages. When selecting different language, due to difference in size of letters in different languages, size of title changes and causes the language list to shift a bit. This PR tends to fix that.
- Issue number - 1050
- Tests are not needed. It can easily been seen visually.

### CODE REVIEW

**Comment by palisadoes** [comment]
Please add the `.flutter.plugins.dependencies` file to `.gitignore`.

If you read the contents of the `.flutter.plugins.dependencies` file you'll see that it recommends that you do that.

**Comment by Literal-Eval** [comment]
Oh I'm really very sorry that I forgot that. I'll do it now.
Also, did you review the code regarding title size ? Does it need changes ?

**Comment by palisadoes** [comment]
@Literal-Eval Our code base has changed. Please merge you code with `upstream/develop` and resubmit. It should fix the failing `PR Workflow / Greeting Message to user (pull_request) ` error.

**Comment by Literal-Eval** [comment]
> @Literal-Eval Our code base has changed. Please merge you code with `upstream/develop` and resubmit. It should fix the failing `PR Workflow / Greeting Message to user (pull_request) ` error.

Sure. I'll close this pull request and add a new one.

**Pull request closed without merging**
