### PR TITLE
Feature-Request: Flutter SDK Migration to version 13.9.0

### LINKED ISSUE #2383: Update Talawa to the Latest Flutter and Dart SDK version
**Is your feature request related to a problem? Please describe.**
Our dependabot automated package updates are failing because we are using outdated versions of Flutter and Dart SDK

**Describe the solution you'd like**

1. Upgrade to the latest stable versions:
    1. Dart v3.3.0
    2. Flutter v3.19.0
1. Update packages to the latest supported versions for these versions of Dart and Flutter
1. Functionality must remain unchanged
2. All tests must pass and be valid

This will probably also require updating the YAML files in the `.github/workflows` directory where there are many references to software versions

**Describe alternatives you've considered**

- N/A

**Approach to be followed (optional)**

- N/A

**Additional context**
1. Dart SDK latest stable version information:
    1. https://dart.dev/get-dart
1. Flutter latest stable version information:
    1. https://docs.flutter.dev/release/release-notes
**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by ArinNigam**
**What kind of change does this PR introduce?**
It updates the flutter sdk to 13.9.0 and dart 3.3.0

**Issue Number:**

Fixes #2383 #2401 

**Did you add tests for your changes?**
Yes, updated flutter version for tests

**Snapshots/Videos:**
NA

**If relevant, did you update the documentation?**
No

**Summary**
https://github.com/PalisadoesFoundation/talawa/issues/2383
https://github.com/PalisadoesFoundation/talawa/issues/2401
The following issues are solved by the PR.
The sole motivation to make this change was to make the app compatible with the latest flutter version since packages have also been upgraded to make use of the latest flutter version which were causing errors because of lower version.

The app is migrated to the latest version by taking references from the following article:
https://medium.com/@iam.umairimran/flutter-app-migration-guide-updating-to-flutter-3-19-0-ab8b66008838

**Does this PR introduce a breaking change?**
Yes, It does make an impactful change since it updates the app to make use of the latest flutter sdk version that is 3.19.0. It changes android/build.gradle and app/build.gradle files and added changes in github workflows. 

**Other information**
However because of continuous failing of custom_lint in the github/workflows I am creating a new issue 
For reference One can go to .github/workflows/check_ignore and check for the following commented out code
image

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by ArinNigam** [comment]
@Cioppolo14 Requesting for review, I have updated .yaml files which is why I think 1 test didn't pass

**Comment by Cioppolo14** [comment]
@literalEval @CyberWake Can you review this PR?

**Review by Ayush0Chaudhary — COMMENTED** [review]
looks good to me, can you share screen recording of basic functions just to verify that nothing is breaking,

**Comment by ArinNigam** [comment]
https://github.com/PalisadoesFoundation/talawa/assets/99138286/b6d83fb6-4260-45fe-9a89-40735db9e102

@Ayush0Chaudhary Attaching the screen recording. Kindly review it. Nothing is breaking as of now.

**Review by Ayush0Chaudhary — APPROVED** [review]

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
