### PR TITLE
Fixes issue #1031

### LINKED ISSUE #1031: [Terminological error]  Misplaced description in `set_url_page_test.dart`
**Describe the bug**
While checking out the test files, I found a bug. Here it is "Testing if login button works" while it should be for the signup button.
**To Reproduce**

1. Open test/widget_tests/pre_auth_screens/set_url_page_test.dart
2. find the bug in lines 277 and 488

**Screenshots**
Screenshot (120)

**Additional details**
I would like to work on the issue @palisadoes pls assign me.

### PR DESCRIPTION
**Pull request by Simran1604**
**What kind of change does this PR introduce?**
bugfix

**Issue Number:**

Fixes #1031 

**Did you add tests for your changes?**
No

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**
No

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by palisadoes** [comment]
@Simran1604 Please take a look at your code and determine why the pull request checks are failing. We won't be able to review until all the tests pass.

**Comment by palisadoes** [comment]
Please lint your code and try again.

**Comment by Simran1604** [comment]
@palisadoes all checks have passed now.

**Comment by sumitra19jha** [comment]
@Simran1604 I checked a few merged PRs where workflow was working even in the absence of the Cupertino changes which you performed. Can you please share the workflow error which you were receiving previously?

**Comment by sumitra19jha** [comment]
> @Simran1604 I checked a few merged PRs where workflow was working even in the absence of the Cupertino changes which you performed. Can you please share the workflow error which you were receiving previously?

No need for this

**Review by sumitra19jha — DISMISSED** [review]

**Comment by palisadoes** [comment]
@Simran1604 The `flutter analyze --no-pub` linting test is failing. Please lint your code and update the PR with a new commit to your repo.

**Comment by Simran1604** [comment]
@palisadoes I don't know why it is failing the test. I have made all the changes already.

**Comment by palisadoes** [comment]
> @palisadoes I don't know why it is failing the test. I have made all the changes already.

The code base has been updated with a more recent pull request that should have fixed the issue. Please merge your branch with the lastest `upstream/develop` and push to your repo. GitHub should detect the changes and re-run the tests on the updated code.

**Comment by Simran1604** [comment]
@palisadoes all checks have passed now.

**Review by CyberWake — CHANGES_REQUESTED** [review]
Please try working with a fresh branch from the latest codebase. I see the PR getting over committed for the desired issue fix, correcting a typo can be a single commit PR.
Add-on the PR still doesn't some the issue linked with it the typo still persist in the codebase.

**Comment by CyberWake** [comment]
@Simran1604 I would recommend closing this PR and working on a fresh branch and trying not to over-commit for a typo fix.

**Comment by Simran1604** [comment]
Okay

**Pull request closed without merging**
