### PR TITLE
resolved bug in regEvent

### PR DESCRIPTION
**Pull request by pr4nshul**
**What kind of change does this PR introduce?**
There is an issue that if the event list has more than 0 items, when list view builder tries to print the text it shows data==null and data can't be null. I tried multiple things and found that there is a possibility that the event has been deleted hence the data has been changed to null. But the eventlist still has the id. So, I did a temporary fix that if the length isn't null but the data at first index is null . Reset the event list. 

**Did you add tests for your changes?**

**If relevant, did you update the documentation?**

**Summary**
Please review and tell me if any changes are needed. And if you can guide me to solve this issue totally, I am willing to work on that. Cause I think this might cause an issue in future. It's a good placeholder for now atleast the user won't get any errors.

Issue #258 
**Does this PR introduce a breaking change?**

**Other information**

### CODE REVIEW

**Review by CyberWake — CHANGES_REQUESTED** [review]
I guess having a appropriate message also to be displayed to user would be much intuitive. If the events registed list is null then we can simply show a desired message.
Implementing this would enhance user experience by letting him know why is nothing there to be displayed.

**Comment by pr4nshul** [comment]
Ok , going to do that

**Comment by pr4nshul** [comment]
Is this basic no registered events good ? Or should I edit the font and colors.

**Comment by pr4nshul** [comment]
Screenshot_20210316-134606

I have applied the same logic for Tasks , as their also nothing was being displayed if the tasks length was 0.

**Comment by CyberWake** [comment]
> Screenshot_20210316-133054
> 
> Is this basic no registered events good ? Or should I edit the font and colors. @CyberWake

UI upgradation I guess should be done after consulting the design team. BTW nice work✌

**Review by CyberWake — APPROVED** [review]
LGTM👍

**Comment by Sagar2366** [comment]
@pr4nshul fixing event registration bug will help to understand the problem. 
Few observations, Issue is only coming for "test Test" user. For all other users event registration is empty list, seems like this user only has event registration details in unsupported format format or data is not being read properly.

Fixing issue temporarily won't help us, we need to find permanent fix for this.

**Comment by pr4nshul** [comment]
Ok , so I would look into fixing registration bug if I can find a permanent fix after that I ll update this PR. Else , I ll close it.

**Comment by Sagar2366** [comment]
> Ok , so I would look into fixing registration bug if I can find a permanent fix after that I ll update this PR. Else , I ll close it.

@pr4nshul I have added fix for this issue. merging PR.

**Review by Sagar2366 — APPROVED** [review]

**Pull request merged**
