### PR TITLE
[Fix] login/signup buttons to take only gesture when not in wait of result

### PR DESCRIPTION
**Pull request by CyberWake**
**What kind of change does this PR introduce?**
This PR fixes the bug on login/signup pages the respective buttons made call to the server every time they were clicked which should only be made if it's not waiting to hear back a result from the server.

**Did you add tests for your changes?**
Yes, added test to the changes made.

**If relevant, did you update the documentation?**
Not, needed to update the document

**Summary**
The issue cased multiple API calls which was much severe when a user was signing up as in this case the user gets a toast saying email already taken when the the next API call was made on second click because by the time the account was already created with the following details. Same was in the login page page there as well the page caused the same problem.

**Does this PR introduce a breaking change?**
No, this PR doesn't bring in breaking changes.

**Other information**
#542

### CODE REVIEW

**Review by Sagar2366 — APPROVED** [review]

**Comment by Sagar2366** [comment]
@CyberWake resolve conflicts on this PR.

**Comment by Sagar2366** [comment]
@CyberWake there are still conflicts on your PR.

**Comment by Enigma04** [comment]
Hey there, is there any help needed?

**Review by Sagar2366 — APPROVED** [review]

**Comment by Sagar2366** [comment]
@CyberWake travic ci is failing, have a look.

**Comment by CyberWake** [comment]
Sure sir.

**Comment by CyberWake** [comment]
@Sagar2366 sir the test failing is because of the package used. logs here.
image
I marked the same on slack as well do we need to change the package or try something else. Added I guess the travis is also not working properly tried with the latest test available for the screen still the exception persist. And if this is not working then travis should fail for every PR but it isn't.

**Comment by Sagar2366** [comment]
@CyberWake fix test cases(travis CI issue) in this PR if possible asap.

**Comment by CyberWake** [comment]
@Sagar2366 sir please review this PR. Travis ci was failing in test due to a package used have raised the issue in the package meanwhile added the desired changes to the packages and extracted it for current use under Talawa till the package gets an update.

**Comment by CyberWake** [comment]
@Sagar2366 please review this pr

**Comment by Sagar2366** [comment]
@CyberWake I think you are adding changes other than fixing the issue.
Please remove unnecessary changes.

**Comment by CyberWake** [comment]
Aur the changes added are the once which were causing CI to fail due to the flutter_pw_validator plugin used.
To fix those I have changed the code of the plugin a bit and added it's code to the talawa codebase rather than importing it as a dependency. Have conveyed the owner of the plugin about the same. Once they update the plugin we may use it again if needed in future.

**Comment by CyberWake** [comment]
Should I create a new PR which solves the desired issues and passes all test?

**Pull request closed without merging**
