### PR TITLE
Event page's DraggableScrollableSheet's animation fixed & Minor Table Calendar fix

### PR DESCRIPTION
**Pull request by Enigma04**
What kind of change does this PR introduce?
Enhancement:

DraggableScrollableSheet is replaced by SlidingUpPanel for smoother animations and better UX in events.dart
Table Calendar's button that is on the top right corner shows exactly what it indicates.
i.e Calendar will show a full month while indicating a month, like in this photo.
WhatsApp Image 2021-04-22 at 6 15 38 PM

WhatsApp Image 2021-04-22 at 6 15 38 PM (1)

Summary

The DraggableScrollableSheet was making the app lag when dragging the sheet up and down. SlidingUpPanel package makes it not only smoother but also better looking due to the shadow effect it gives when the sheet is dragged up. To know about the issue in more detail, check #682

The calendar button on the top right shows the format which is not true to what it shows.
Eg: 2 weeks is showing Calander of a month and the Week shows the calendar content of 2 weeks, etc.
It had to be changed because a new user can get confused as the button doesn't do what it indicates it will. For more details, check #689

Does this PR introduce a breaking change?
No

### CODE REVIEW

**Comment by palisadoes** [comment]
@Enigma04 Please lint your code and fix the merge conflicts. An explanation can be found in CONTRIBTING.md

We will soon be enforcing a 300 line limit on Dart files. Please consider ways to reduce the sizes of the files you edit while maintaining functionality in future. PRs reviewed on or after May 15 will be rejected if this requirement is not met.

**Comment by Sagar2366** [comment]
@Enigma04 few of checks are failing on your PR, please have a look.

**Comment by Enigma04** [comment]
yes give me some time I will commit again

**Review by Sagar2366 — APPROVED** [review]

**Comment by dellyjm** [comment]
Looks good

**Pull request merged**
