### PR TITLE
resolved exception

### PR DESCRIPTION
**Pull request by pr4nshul**
**What kind of change does this PR introduce?**
Resolved error #515 

**Did you add tests for your changes?**
No
**If relevant, did you update the documentation?**
No
**Summary**
I guess the exception error has been changed since the app was created , I created another global variable and added another `if else` block under query just to verify and during the same login session before I was facing the error but after that if else block the issue was resolved.
So, rather than adding a new if else under each query I changed the` globalException ` which was already there.

**Does this PR introduce a breaking change?**
No

**Other information**
To reproduce the issue, you need to stay logged in for quite some time then maybe try to add a task or register for an event.

### CODE REVIEW

**Comment by CyberWake** [comment]
Do this solve the issue described. @pr4nshul

**Comment by pr4nshul** [comment]
Yes it does, you can try

**Comment by pr4nshul** [comment]
The token wasn't being refreshed as we were refreshing it based on whether the exception met the global access token exception. But now the string for that error has changed.

**Comment by pr4nshul** [comment]
Because I checked all the query calls , and we had everything in place in case the user was logged in but token expired. And then this caught my eye , when I changed it . It worked.

**Review by Sagar2366 — APPROVED** [review]

**Pull request merged**
