### PR TITLE
[Fix] Events, newsfeed, Groups etc. should be blank for newly created organizations

### LINKED ISSUE #537: Events, newsfeed, etc. should be blank for newly created organizations
- **Issue Description:** Events, newsfeed, etc. should be blank for newly created organizations
- **Issue Severity:** Low
- **Environment Details:** Almost in the whole app
- **Observed Behaviour:** Currently default data is getting loaded for newly created organizations.
- **Expected Behaviour:** It should be blank for newly created organizations
- **Steps to reproduce issue:** Create an organization and switch to members or events tab.
- **Does this issue need immediate attention?** Yes
- **Are you willing to work on this issue:** Yes, I am willing to work on this issue!

### PR DESCRIPTION
**Pull request by Raunakk02**
**What kind of change does this PR introduce?**
Resolves #537 

**Did you add tests for your changes?**
Yes

**If relevant, did you update the documentation?**
No

**Does this PR introduce a breaking change?**
No

**Here is the video before the issue was resolved:**
> 

https://user-images.githubusercontent.com/56073198/113135586-e820f100-923f-11eb-857f-8fdcb338086d.mp4

**Here is the video after the issue was resolved:**
> 

https://user-images.githubusercontent.com/56073198/113135713-10a8eb00-9240-11eb-8477-95fef8873b48.mp4

### CODE REVIEW

**Comment by Raunakk02** [comment]
@Sagar2366  I have created this new pull request for issue #537.
I closed the previous PR #553.
Please review this PR!

**Comment by Sagar2366** [comment]
@Raunakk02 resolve conflicts on this PR.

**Comment by Raunakk02** [comment]
> @Raunakk02 resolve conflicts on this PR.

@Sagar2366 I have resolved the conflicts now.
Awaiting review!

**Comment by Sagar2366** [comment]
@Raunakk02 seems like this PR is not tested properly.
If user switch to another organisation and back to newly created organisation, it will show posts from other organisations.

Break this PR into small issues - no events for newly created organisation, no events, etc.
Keep changes which are required to fix the issue.

**Comment by Raunakk02** [comment]
> @Raunakk02 seems like this PR is not tested properly.
> If user switch to another organisation and back to newly created organisation, it will show posts from other organisations.
> 
> Break this PR into small issues - no events for newly created organisation, no events, etc.
> Keep changes which are required to fix the issue.

@Sagar2366  that issue is something related to state management. If we use the pull-to-refresh feature to refresh the posts then the post from the currently selected organization will show up. (The same thing currently happens in the events, members, and groups pages.) 

Another possible workaround is to simply set the `stateManagement` parameter of the `PersistentTabView` widget in `home_page.dart` to **false**. This way all the **Tabs** will automatically refresh their data when switched. (I can add this change if it's permitted.)

Please let me know if I can use this approach!

**Pull request closed without merging**
