### PR TITLE
[FIX] Issue174 Update Profile Page Screen

### PR DESCRIPTION
**Pull request by sumitra19jha**
**What kind of change does this PR introduce?**
Issue #174. Bug Fix

**Did you add tests for your changes?**
Yes. Below is the test video:

https://user-images.githubusercontent.com/35868598/111901782-ff9df400-8a5f-11eb-9a86-a137145469fe.mp4

**If relevant, did you update the documentation?**
No

**Summary**
The motivation of the PR is to let user update there profile

**Does this PR introduce a breaking change?**
No

**Other information**
The PR is dependent on the backend API mutation, whose PR request is made but not yet merged

### CODE REVIEW

**Comment by sumitra19jha** [comment]
@Sagar2366 By Changing the Branch Name the previous PR has been deleted.

**Comment by sumitra19jha** [comment]
@Sagar2366 Only the following test existed in the test folder and PR passed the entire test.
Screenshot 2021-03-21 at 6 40 11 PM

**Comment by shikharsaurav** [comment]
@sumitra19jha  can i also help u ?
sry i was working on diff issue

**Comment by Sagar2366** [comment]
> @Sagar2366 Only the following test existed in the test folder and PR passed the entire test.
> Screenshot 2021-03-21 at 6 40 11 PM

You need to add unit test for your code.

**Comment by sumitra19jha** [comment]
@shikharsaurav I put the comment in issue

**Comment by sumitra19jha** [comment]
@shikharsaurav I put the comment in issue

**Comment by sumitra19jha** [comment]
> > @Sagar2366 Only the following test existed in the test folder and PR passed the entire test.
> > Screenshot 2021-03-21 at 6 40 11 PM
> 
> You need to add unit test for your PR/code adding by this PR.

Working on it

**Comment by sumitra19jha** [comment]
@Sagar2366 I added the Unit test for form update and basic widget test to make sure the layout is in a particular order.
Screenshot 2021-03-22 at 4 26 36 PM

**Comment by Sagar2366** [comment]
Screenshot 2021-03-22 at 9 23 15 PM

Getting overflow error, please check.
Also can you please improve UI little bit, not looking good.
Pull latest master changes to avoid travis CI failing.

**Comment by sumitra19jha** [comment]
> Screenshot 2021-03-22 at 9 23 15 PM
> 
> Getting overflow error, please check.
> Also can you please improve UI little bit, not looking good.
> Pull latest master changes to avoid travis CI failing.

Sure. working on it

**Comment by sumitra19jha** [comment]
@Sagar2366 All the updates have been done. Please check it

**Review by Sagar2366 — APPROVED** [review]

**Comment by Sagar2366** [comment]
@sumitra19jha resolve conflicts on this PR.

**Comment by sumitra19jha** [comment]
@Sagar2366 Done

**Pull request merged**
