### PR TITLE
Updating latest changed into talawa-docs-develop branch

### PR DESCRIPTION
**Pull request by itstasneem**
Updating `talawa-docs-develop` branch with the latest changes of `develop` branch.

### CODE REVIEW

**Review by DMills27 — CHANGES_REQUESTED** [review]
It's not clear what's causing the merge conflict in the profile_page.dart file. The best course of action is to remove it for the time being.

**Comment by palisadoes** [comment]
@itstasneem Do you mean remove it from this PR or from the code base completely? The file has an important function.

**Comment by palisadoes** [comment]
@itstasneem Please fix the conflicting files so that we can merge.

**Comment by palisadoes** [comment]
@itstasneem Please fix the conflicting files.

**Comment by palisadoes** [comment]
@itstasneem Should we close this?

**Comment by palisadoes** [comment]
@itstasneem @itstasneem Please fix the conflicting files so that we can merge

**Review by palisadoes — APPROVED** [review]

**Pull request closed without merging**
