### PR TITLE
Update Password Meter Height

### LINKED ISSUE #228: Fixing the Size of Password Strength Meter
Description: The height of the password strength meter was a bit large in my opinion as the height was ~20

image

This issue is Linked to PR #238

### PR DESCRIPTION
**Pull request by adithyaakrishna**
**What kind of change does this PR introduce?**

Refactoring and Improving the UI of the Create an Account Page

- The size of the password strength meter was also adjusted to make it more appealing to the user

**Did you add tests for your changes?**
Yes, the change was tested and works well in both iOS & Android systems without breaking anything.

This PR Fixes #228

### CODE REVIEW

**Comment by yasharth291** [comment]
hey @adithyaakrishna  can you please attach your issues with your pr so if they are merged the related issue will automatically closed

**Comment by adithyaakrishna** [comment]
@yasharth291 Thanks man, I've done it now 🚀

**Comment by Sagar2366** [comment]
@adithyaakrishna please fix conflicts on this pr.

**Review by DeltaHarbinger — CHANGES_REQUESTED** [review]
Hey @adithyaakrishna, it looks like a lot of people were working on this file in parallel, so conflicts have been invoked. Can you pull the most recent changes and apply your fix again?

**Comment by adithyaakrishna** [comment]
> Hey @adithyaakrishna, it looks like a lot of people were working on this file in parallel, so conflicts have been invoked. Can you pull the most recent changes and apply your fix again?

Yes Sure, I've used the latest file itself and done the changes to it :)

**Review by adithyaakrishna — COMMENTED** [review]
I've now fixed the conflicts using the recent version itself

**Pull request merged**
