### PR TITLE
Chat message screen

### PR DESCRIPTION
**Pull request by SriramPatibanda**
## Direct Chats

- Add Chat List Screen
- Add Chat Message Screen
- Fetching and displaying of chats
- We use graphql queries as of now. This will be shifted to graphql subscriptions as soon as backend support is available.

### CODE REVIEW

**Comment by palisadoes** [comment]
Please fix the failing tests

**Comment by nishnatadebnath** [comment]
@SriramPatibanda  I think the extra paramater in the databasemutation is causing the error just remove and I think we are good to go.

**Comment by palisadoes** [comment]
Sriram the tests continue to fail

**Comment by SriramPatibanda** [comment]
> Sriram the tests continue to fail

I and @nishnatadebnath are trying to resolve it since yesterday. We didn't write tests for the chat view model as I said and the current way the tests are written, it's trying to test the chat model dependency also and hence the tests are failing.

**Comment by palisadoes** [comment]
We should remove the tests to make them pass and then create another issue to create the correct tests.

**Comment by SriramPatibanda** [comment]
> We should remove the tests to make them pass and then create another issue to create the correct tests.

We were trying to do that, but the way the present testing is, it's trying to test the chat model also. Trying to figure out the solution. Will keep you updated on the progress by tonight.

**Comment by nishnatadebnath** [comment]
So the problem can be easily fixed with deletion of the `home_page_test.dart`.All the test cases will be passed!
@SriramPatibanda @palisadoes .I am making an new issue to recreate the tests.

**Comment by nishnatadebnath** [comment]
But this is working fine in my local .
Screenshot from 2022-03-08 15-40-45

**Comment by nishnatadebnath** [comment]
@palisadoes we should review the changes made in #1222 as many major files are being changed which shouldn't be the case for testing a viewmodel.Also the custom_drawer_test.dart need to be recreated.

**Comment by palisadoes** [comment]
> @palisadoes we should review the changes made in #1222 as many major files are being changed which shouldn't be the case for testing a viewmodel.Also the custom_drawer_test.dart need to be recreated.

Should we revert the other PR to get this one to work? We have other PRs since then, would we have to revert those too?

**Comment by nishnatadebnath** [comment]
Just merging this will do for now ,I will make another PR to revert back the changes done #1222 if anything is not required and made to change in the #1222 !

**Comment by palisadoes** [comment]
Merged. Please fix #1222

**Pull request merged**
