### PR TITLE
Fixed Overflow on `explore_events.dart`.

### LINKED ISSUE #1561: Overflow Issue on Events Page
**Describe the bug**
Overflow in the top bar of Events Screen

**To Reproduce**

**Screenshots**
photo_2023-02-24_15-28-27

### PR DESCRIPTION
**Pull request by mmjsmohit**
**What kind of change does this PR introduce?**

**Issue Number:**

Fixes #1561 

**Did you add tests for your changes?**
 Yes, added a widget test in `explore_events_test.dart` named `Testing if the top bar overflows`

**Snapshots/Videos:**
photo_2023-02-25_11-18-31

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**
No

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Review by palisadoes — CHANGES_REQUESTED** [review]
1. Why were the various Firebase and Gradle files updated for this?
1. Should we add these files to our `.gitignore` file? 
1. Should we also protect these files from being edited?

@noman2002 @TheHazeEffect please comment on this. This needs your action

**Comment by Ayush0Chaudhary** [comment]
@palisadoes @noman2002 @TheHazeEffect 
 I think we should protect these files specially **firebase_options** and **main.dart**
@mmjsmohit has forgotten to change the firebase options back to original, **it is a step in our setup** which i think he forgot :crying_cat_face: 
and main.dart is not required to be updated also.

**Comment by mmjsmohit** [comment]
What @Ayush0Chaudhary has mentioned is on point. I had some issues with my git installation so the revert back didn't work apparently. I'll change the files back to original.

**Comment by mmjsmohit** [comment]
What @Ayush0Chaudhary has mentioned is on point. I had some issues with my git installation so the revert back didn't work apparently. I'll change the files back to original.

**Comment by palisadoes** [comment]
@Ayush0Chaudhary 
1. should we just add firebase_options.dart in `.gitignore`? The firebase stuff is handled purely in the API to my knowledge.
1. Main.dart can be added to the authorized list.

**Comment by Ayush0Chaudhary** [comment]
@palisadoes 

1. Yes, you are right about application of firebase_options.dart, and we can add it in .gitignore but in the future if we have to implement any other Firebase feature, this will cause a problem. I suggest simply adding it in authorised list, so that we can get alert on its change.

2. yes, gradle files also can be added as changes in it can break the app.

3. yes, main.dart should be added authorised file list.

**Comment by Ayush0Chaudhary** [comment]
should I raise a PR for the same? @palisadoes @noman2002 @TheHazeEffect

**Comment by palisadoes** [comment]
Yes

**Pull request closed without merging**
