### PR TITLE
Reload App breaking and Image not loading fixed ⚙

### PR DESCRIPTION
**Pull request by rutvik11062000**
**What kind of change does this PR introduce?**

Bug Fixing and refactoring.

**Did you add tests for your changes?**
Yes

**If relevant, did you update the documentation?**
No

**Summary**
2 Major bugs were fixed:
   -  App doesn't show any data on reload. (Due to improper initialization).
   -  Url for fetching Organisation's Image is fixed.

**Does this PR introduce a breaking change?**
No

**Other information**
Changes in this merge need reinstallation / re-Login. 
A separate variable for storing Organisation Image Url is stored in "Preferences".
Proper initialization in GraphQLClient.

### CODE REVIEW

**Comment by Sagar2366** [comment]
@rutvik11062000 remove formatted code for now. Only add changes required to fix the issue.

**Comment by rutvik11062000** [comment]
SIr There is only appropriate code addition, I didn't changed anything which is not related with the issue.
I've added some functions to get the proper image URL and initailised the HTTP link in proper way.

**Comment by rutvik11062000** [comment]
You can check all 3 changed files.

**Comment by Sagar2366** [comment]
@rutvik11062000 I hope you get it now, what I was trying to pointing out.
Remove formatted code, everything is there in master. Only add functions to get the proper image URL and initialised the HTTP link in proper way.

**Comment by rutvik11062000** [comment]
Sorry for the Inconvenience I had prettier (auto format when save) was on. I'll make a separate PR

**Pull request closed without merging**
