### PR TITLE
Built User Interface for creating recurring events.

### LINKED ISSUE #2341: Mobile - Add support to recurring events.
**Is your feature request related to a problem? Please describe.**
Implement `recurring events` functionality into Talawa mobile. 

**Describe the solution you'd like**
- The event creation screen(s) should have functionality to create recurring events.
          1. weeks
          2. months 
          3. days 
          4. weekdays 
- The Calendar screen(s) should display all the created recurring events.
- The edit event screen(s) should have funcitonality to edit these recurring events.
          1. All instances in the series
          2. Just the instance in question
          3. The instance in question and all those in future
- Make use of updated `event mutations` to implement the described functionality.
- The screen(s) design must follow the guidelines of Talawa Design System found here:
          - https://docs.talawa.io/docs/design/ux/ux-design-system
- Other functionality must not be affected.
- Write tests and achieve 100% code coverage to all the new functionality added.

**Describe alternatives you've considered**
   N/A

**Approach to be followed (optional)**
   - see above.

**Additional context**
   1. related issues:
       - https://github.com/PalisadoesFoundation/talawa-api/issues/1583#issue-2057545112
   2. related PRs:
       - https://github.com/PalisadoesFoundation/talawa-api/pull/1658#issue-2069943639
       - https://github.com/PalisadoesFoundation/talawa-api/pull/1712#issue-2086753320

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by Azad99-9**
**What kind of change does this PR introduce?**

This PR introduces the essential User Interface for `Creating Recurring Events`.

**Issue Number:**

Fixes #2341

**Did you add tests for your changes?**

yes

**Snapshots/Videos:**

video [link](https://github.com/PalisadoesFoundation/talawa/issues/2341#issuecomment-1950268583).

**If relevant, did you update the documentation?**

**Summary**

- Added a `popupmenubutton` to switch views in EventCalendar. views [day, month, schedule].
- Added a Recurrence selection dialog box to `create event page.`
- Created a new page `CustomRecurrencePage` to define user desired recurrence configuration.
- Written tests to all the above mentioned new widgets.

Note: `Api` integration is not yet done. As significant number of lines of code were added, for manageable reviewing purpose the api integration part will be included in a subsequent PR.

**Does this PR introduce a breaking change?**

No.

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**

Yes.

### CODE REVIEW

**Comment by noman2002** [comment]
@Azad99-9 Please attach a video of it.

**Comment by Azad99-9** [comment]
Uploading ui-demo_lUUocDoR.mp4…

@noman2002 please find the attached video demo.

**Comment by Azad99-9** [comment]
@noman2002 please have a look I have attached the video.

https://github.com/PalisadoesFoundation/talawa/assets/120930148/389aeb12-18e4-4bde-8616-c79eebffbdcb

**Review by noman2002 — APPROVED** [review]
issu

Please make the selected circles filled to have a clear differentiation, rest looks good to me. Good work.

**Review by noman2002 — CHANGES_REQUESTED** [review]
issu

Please make the selected circles filled to have a clear differentiation, rest looks good to me. Good work.

**Comment by Azad99-9** [comment]
https://github.com/PalisadoesFoundation/talawa/assets/120930148/c6c2f647-9030-485d-9f83-2c88a814aab4

@noman2002 please suggest is it ok now.

**Comment by noman2002** [comment]
> 1000151545.mp4
> 
> @noman2002 please suggest is it ok now. If ok, I will push it's code.

Looks better now.

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
