### PR TITLE
Fix #514

### LINKED ISSUE #514: [Bug] - Tab bar pages not refreshed automatically on org switching and edge case not handled
- **Issue Description:**
State not handled properly in members page. And inappropriate message.
On suggestions as asked by @Sagar2366 sir [here](https://github.com/PalisadoesFoundation/talawa/pull/607#issuecomment-817335868)
Auto refreshing of event page, feeds page, and chats 

- **Issue Severity:**
High.

- **Environment Details:**
Home page-> Members tab
Visit it directly on app launch. Now go to the profile page switch the organization again visit members tab page is not refreshed.
Now leave/remove all the organizations than visit member page page doesn't get refreshed automatically as well as on pulling down to refresh refresh button is visible which should not be there as the user in not in any organization.
Switch the current org to new one still the tab bar pages show data relevant to previous organization. 
Not specific to members page all the pages on tab bar don't refresh automatically on change in current organization data

- **Observed Behaviour:**
Even if the user is not in organization he see a refresh button which is of no use to him. Comes handy only in case of internet connectivity that to for the user who has joined at least on organization. The all tab bar page doesn't update automatically on change in current organization.

- **Expected Behaviour:**
There should not me refresh button if the user is not joined any organization something more meaning full should be displayed.
tab bar page should automatically update on change with current organization.

- **Steps to reproduce issue:**
Follow the video and it has more ways as well you may direct visit without joining any organization or vice versa.

- **Snapshots/Videos:** 
Attaching a demo video.
<kbd></kbd>

- **Does this issue need immediate attention?**
Yes, this need to be resolved so that the user doesn't see inappropriate data.

- **Are you willing to work on this issue:**
Yes, I am will to work on this issue.

- **Other information:**
@Sagar2366 sir please assign this issue to me.

### PR DESCRIPTION
**Pull request by CyberWake**
**What kind of change does this PR introduce?**
This PR resolve the issue marked in #514 . On switch/join/creating/leaving organization the member page gets refreshed with the new list of members in all cases. And if the user is not a member of any organization he is shown a page asking him to join one. If there is any issue with internet or data not being fetched due to some issue. He is shown with the refresh button only if he is present in any organization.

**Did you add tests for your changes?**
Yes, test added. There could we some updates in them as well.

**If relevant, did you update the documentation?**
Not needed.

**Summary**

 | [**Earlier**](https://user-images.githubusercontent.com/44184786/112527539-2e51fc80-8dc9-11eb-82a4-1f2bfa7de748.gif)      | [**Now**](https://user-images.githubusercontent.com/44184786/112591659-ab618e00-8e2a-11eb-8f48-b0ff29444c4d.gif)     | 
|------------|-------------| 
|  <kbd></kbd> |  <kbd></kbd> |

This PR resolves the issues related to change in current organization on member screen. Plus the changes incorporated to resemble the changes on other tabs that show data depending on current organization.
This PR is made under the issue #514 

**Does this PR introduce a breaking change?**
No, it does not bring breaking changes.

**Other information**
Linked issue #514

### CODE REVIEW

**Comment by CyberWake** [comment]
@Sagar2366 please review this pr

**Comment by Sagar2366** [comment]
@CyberWake looks like this PR is not tested properly.
Few issues -
1. when user join existing organisation, it only changes member details, event list doesn't update
2. Once error come on newsfeed page, it does not show any option to reload page or auto reload it after particular time

Please test multiple different scenarios.

**Comment by CyberWake** [comment]
> @CyberWake looks like this PR is not tested properly.
> Few issues -
> 
> 1. when user join existing organisation, it only changes member details, event list doesn't update
> 2. Once error come on newsfeed page, it does not show any option to reload page or auto reload it after particular time
> 
> Please test multiple different scenarios.

Will add changes to these pages as well.

**Comment by CyberWake** [comment]
@Sagar2366 there is a issue with events the mutation is proper the function is evoked automatically on switching the organization. But the data received from the database is corrupt it does not return the events filtered by the organization id.
To verify the same use two different accounts join two different organizations and you'll notice the events list are same for both the accounts even if they are member of different organizations.

**Comment by Sagar2366** [comment]
> @Sagar2366 there is a issue with events the mutation is proper the function is evoked automatically on switching the organization. But the data received from the database is corrupt it does not return the events filtered by the organization id.
> To verify the same use two different accounts join two different organizations and you'll notice the events list are same for both the accounts even if they are member of different organizations.

@CyberWake can you fix above issue in another PR ? 
Please resolve conflicts on this PR to merge it.

**Comment by CyberWake** [comment]
Their needs to be a issue raised in the talawa-api for the same will raise one and fix it.
Sure resolving the merge conflicts.

**Comment by palisadoes** [comment]
Please fix merge conflicts. The code freeze has been lifted.

**Comment by palisadoes** [comment]
Please fix merge conflicts. 

1. We have completely re-linted the master branch. 
1. We now have automated linting testing added to pull requests
1. We also have added Google's pendantic package to pubspec.yaml

For best results, I'll close this PR and you'll need to reopen a new bug against the master branch. 

The code freeze has been lifted.

**Comment by CyberWake** [comment]
Sure creating a new one.

**Pull request closed without merging**
