### PR TITLE
Added Snackbar for leave organization

### LINKED ISSUE #176: Leave Organization button edge case error
If user is not a part of any organization then a `snackbar` should be created informing, `user is not a part of any organisation`. Currently, Alert Dialogue is displayed asking for the permission to leave even if user is added to no organisation at all.

WhatsApp Image 2021-03-14 at 8 41 21 AM

### PR DESCRIPTION
**Pull request by cyber-venom003**
## Added A Snackbar in place of alert dialogue in leave organization

Fixes #176 

Screenshot_1615697483

### CODE REVIEW

**Comment by cyber-venom003** [comment]
@DeltaHarbinger @heyjordn @Deandrew007 Please review this, and tell me if I need to make any more commits in this PR.

**Comment by Sagar2366** [comment]
@cyber-venom003 , can you please share video/snap what happens in case of selecting leave organization in both the cases - when part of any organization and when it is null ?
I pulled your code and tried both the scenarios, but it stuck/throws errors in second case.

**Comment by DeltaHarbinger** [comment]
Hey @cyber-venom003, there is an issue when trying to leave an organization. If the user just opens the app and attempts to leave the Org, the navigator pop is called, but there is no route to go back to

**Comment by DeltaHarbinger** [comment]
See the screenshot for an example of leaving an org directly after opening the app

**Comment by cyber-venom003** [comment]
> 
> 
> Hey @cyber-venom003, there is an issue when trying to leave an organization. If the user just opens the app and attempts to leave the Org, the navigator pop is called, but there is no route to go back to

I understood the bug, all I have to do is to replace it with some other route instead of popping it out from the whole navigation stack.

**Comment by cyber-venom003** [comment]
@sumitra19jha Please find your requested changes in latest commits. 
All I did is, used a conditional logic if orgName == null, and if user presses leave org, it will show snackbar.
Screenshot_1615763174

@Sagar2366 @DeltaHarbinger Please look into it and tell me if it resolves that Navigator.pop() issue also, that you mentioned in above comments.

**Comment by Sagar2366** [comment]
My suggestion is to remove leave organization option from list if user is not part of any organization.

**Comment by cyber-venom003** [comment]
> 
> 
> Remove leave organization option from list if user is not part of any organization to avoid further issues.
Ok cool. But a problem as stated in #307 is there, if we are joined in multiple organizations, after leaving one of them, it shows null. Hence for a time being, this snackbar option I've implemented.

**Comment by cyber-venom003** [comment]
> 
> 
> > Remove leave organization option from list if user is not part of any organization to avoid further issues.


Ok cool. But a problem as stated in #307 is there, if we are joined in multiple organizations, after leaving one of them, it shows null. Hence for a time being, this snackbar option I've implemented.

**Comment by sumitra19jha** [comment]
@Sagar2366 I am working on that

**Comment by cyber-venom003** [comment]
@sumitra19jha Till then, can we have this snackbar or what say @Sagar2366 ?

**Comment by sumitra19jha** [comment]
@cyber-venom003, I think I am not the right person to give this feedback.😅

@Sagar2366 Can provide you feedback on this

**Comment by Sagar2366** [comment]
@cyber-venom003 since PR https://github.com/PalisadoesFoundation/talawa/pull/212 is merged, can you add changes to this PR which were blocking your work ?

**Comment by Sagar2366** [comment]
@cyber-venom003 are you still working on this issue ? If not, we can open for someone else to work on.

**Comment by Sagar2366** [comment]
Closing this PR for now. As discussed with @cyber-venom003 he won't be continue working on this issue.

**Pull request closed without merging**
