### PR TITLE
Fixes #1464 Bug FIx[nav bar navigation]

### LINKED ISSUE #1464: Bug Report [Navbar]
**Describe the bug**
only home and profile are visible in nav bar.
**To Reproduce**

Navigate to home screen.

**Expected behavior**

Home,events,add,chat,profile all five tabs should be there.

**Actual behavior**
A clear and concise description of how the code performed w.r.t expectations.
only home and profile are visible in nav bar.

**Screenshots**

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by noman2002**
**What kind of change does this PR introduce?**
BugFix

**Issue Number:**

Fixes #1464 

**Did you add tests for your changes?**
NO

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**

### CODE REVIEW

**Comment by noman2002** [comment]
> 1. Do you know why this functionally was removed?
> 
>     2. Are you done with the changes?

Yes I'm done with the changes. 
I guess it is mistakenly removed by someone these are must have features it can't be removed intentionally.

**Comment by literalEval** [comment]
I think I have an idea why this was removed. The nav bar items were causing duplicate key error as I reported in #1476, so probably someone was writing tests for some widget and got that error and so instead of fixing the `KeyError`, they decided to remove the widgets themselves as this was the easiest 'fix'. 
I think we should be very rigorously checking the PRs, especially the test ones to make sure that they are covering all the corner cases and will surely fail if changes are made in the file.

**Comment by palisadoes** [comment]
@literalEval can you point to the PR that caused this to happen? I'm looking at the history of the file and it looks like it was done as [part of this PR](https://github.com/PalisadoesFoundation/talawa/commit/0b29763c2d6c48e13ed6d38f56399d39a9e0d536#diff-04a5e48a89ca3be023f160a40962fd410bd5d6974fc143aed0b9ef49adac3c01). Is that the case? This is really important to know. It is an opportunity for coaching.

**Comment by literalEval** [comment]
I apologize for my above comment. Maybe I understood the situation wrongly.

@palisadoes Yeah indeed it is. Author of that PR removed some buttons from `BottomNavigationBar` and created certain `plugin` data that would be inserted into `BottomNavigationBar` dynamically. The author included 2 features, namely `Organization Home` and `Profile Page` to be the core features and available to all the users, whereas `Events`, `Chats` etc would be shown only if their organization added those to the plugin list. Maybe this was the expected behavior back then and the author was right, or maybe they accidentally removed too much. But one thing is for sure that writing test data in the widget iteself, creating unnecessary classes and variables etc was certainly a bad idea.

**Comment by palisadoes** [comment]
@literalEval Do you have a proposed solution and is it in the form of an GitHub issue?

**Comment by literalEval** [comment]
@palisadoes I have already fixed much of this in #1482

**Pull request merged**
