### PR TITLE
Fixes MVP - Talawa #2108

### LINKED ISSUE #2108: MVP - Talawa
We need to have an Talawa MVP by the end of the year. The MVP will be the master branch. To do this we will need to remove features that either don’t work or have insufficient functionality. 

The features to remove include:

1. Links to chat
1. Notifications
    1. https://github.com/PalisadoesFoundation/talawa/issues/2086 Already removed in this issue
1. Dynamic linking

Other

1. You need to work on removing these functionalities from this repo and work with the contributors below to make sure the correct functionality occurs in the other repos.
1. Documentation related to configuring these features needs to be removed as they will be no longer valid.
1. Test code coverage needs to be maintained. Coverage for the PR patches needs to be 100%

The plan is to:

- remove these features from the develop branch by commenting out the code.
- merge the develop branch not containing these features into our master branch.
- make the master branch the default

Please work with @Ayush0Chaudhary (Talawa impacts), @EshaanAgg & @xoldyckk (Talawa-API impacts) @beingnoble03 (Talawa-Admin impacts). Ask to be assigned this task by them.

Issues related to this one include:

- https://github.com/PalisadoesFoundation/talawa-admin/issues/1069
- https://github.com/PalisadoesFoundation/talawa-api/issues/1427
- https://github.com/PalisadoesFoundation/talawa/issues/2108

### PR DESCRIPTION
**Pull request by AyushRaghuvanshi**
**What kind of change does this PR introduce?**

This PR removes all usage of dyanmic linking. Including Sharing Links and creating QR

**Issue Number:**

Fixes  #2108

**Did you add tests for your changes?**
No, It wasn't relevant.

**Summary**
 #2108 asks to remove three features to make app MVP ready. upon discussion with @Ayush0Chaudhary  it was come to conclusion that Chat and notification is already removed.
 
 Hence this PR removes dynamic Linking as well

**Does this PR introduce a breaking change?**
No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by AyushRaghuvanshi** [comment]
@Ayush0Chaudhary  How do i see which lines needs coverage? I am unable to identify for which function i am supposed to write test case. 

This PR do increase code coverage but I suppose one function is missing in the test? 

Can you help me out here?

**Comment by AyushRaghuvanshi** [comment]
@Ayush0Chaudhary  Can you once check if thats all I am required to comment out? 

Few Extra changes involves Writing documentations and tests

**Comment by Ayush0Chaudhary** [comment]
We can use QR to produce link that lead to our playstore app.

**Comment by noman2002** [comment]
@Ayush0Chaudhary Yes we can do that but currently we don't have it on playstore.
@palisadoes Your thoughts on this? Should we keep the QR or remove it.

**Comment by AyushRaghuvanshi** [comment]
Hey @noman2002 @Ayush0Chaudhary  , If my opinion is welcomed, I would like to also propose that , 

Provided we don't have Playstore link., for the time being we can use our github releases link. 

Also we enable invite feature to invite people through social media but rather than using dynamic linking , we craft a message like 
**Hey, I invite you to install this app and join \<Organization Name>** .

I think it would be a good alternative for the time being.

**Comment by palisadoes** [comment]
We won't have an App Store presence for the MVP. We don't have a strategy on how to handle incompatibilities between different versions of the mobile app, API and Admin. We'll need one by the middle of next year.

It's best to  have a link to the repo. @DMills27 is working on creating an issue that would help finalize where that location would be.

**Comment by AyushRaghuvanshi** [comment]
https://github.com/PalisadoesFoundation/talawa/releases/download/automated/app-release.apk 

@palisadoes 
Something like this?

if we create a QR for this link. It will automatically download the latest build to their mobile phones. 

For Example.
image

**Comment by palisadoes** [comment]
Thanks. I meant could we also embed it in a markdown file on GitHub to make it easier for the development community?

README.md for example, but do so in an automated way so that the QR code in the master branch and develop branches download the appropriate APK.

**Comment by AyushRaghuvanshi** [comment]
I think we can do that by creating two readme files for each branch. 

Creating a single Readme file and adding a placeholder is mentioned in [this](https://github.com/github/markup/issues/913) issue which is basically seems like not implemented as of now. 

I think best approach would be to create two readme.md for each branch...... 

Also what does this mean about this PR? Is it alright?

**Review by Ayush0Chaudhary — APPROVED** [review]

**Comment by palisadoes** [comment]
@AyushRaghuvanshi Keep the QR code. Link to the APK in a way that is independent of the branch. 
Let us know when that is complete so we can give it a final review before merging.

Is there anything in these files that need to be updated because of the disabled code?
1. README.md
2. CONTRIBUTING.md 
3. INSTALLATION.md 
4. Other markdown files?

**Comment by palisadoes** [comment]
@AyushRaghuvanshi have you commented out any unused packages in `pubspec.yaml` 
We don't want to be receiving unnecessary security alerts

**Review by noman2002 — APPROVED** [review]

**Comment by AyushRaghuvanshi** [comment]
@Ayush0Chaudhary @noman2002  Don't merge this yet. I am still working on the changes @palisadoes  recommended.

**Comment by noman2002** [comment]
@AyushRaghuvanshi What are the updates on this one? We need to merge this.

**Comment by AyushRaghuvanshi** [comment]
@noman2002  I have made the package version changes. I was researching a lot if i can automate a process where we get QR code according to the branch. 

I think we can set up a .env file as well? and in the installation.md we state that to access QR code you need to add the correct branch release link

@palisadoes How does that sound?

**Comment by noman2002** [comment]
@AyushRaghuvanshi I don't think it will work. It will make things more complex. I suggest we can just redirect the qr to master branch. There no need to redirect it to develop branch. 
@palisadoes Your thoughts on this ?

**Comment by palisadoes** [comment]
The QR code should be for the `main` branch.

**Review by noman2002 — APPROVED** [review]
Looks good to me.
@Ayush0Chaudhary Please have a look.

**Comment by palisadoes** [comment]
@AyushRaghuvanshi What version of the API were you using to test against? What commit were you working with? @Ayush0Chaudhary is working on the  `main` migration with another PR.

**Comment by AyushRaghuvanshi** [comment]
@palisadoes I have the latest pull of the talawa-api repo.

**Comment by AyushRaghuvanshi** [comment]
@palisadoes  I wasn't. But Now I am with my latest push.

**Comment by palisadoes** [comment]
Please fix the failing tests.

**Comment by palisadoes** [comment]
@noman2002 @Ayush0Chaudhary Please review and merge if OK.

**Review by noman2002 — APPROVED** [review]

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
