### PR TITLE
login/signup page fixed

### PR DESCRIPTION
**Pull request by priyanshu0405**
Issue #262 
This PR fixes the issue of user sliding to login/signup screen without entering org url.

### CODE REVIEW

**Comment by Sagar2366** [comment]
@priyanshu0405 , please follow guidelines while creating issues and pr's. Add proper description, expected and observed behaviour, snapshots/videos, fix added, environment details

**Comment by priyanshu0405** [comment]
@Sagar2366 Sure, will take care from next time.

**Comment by CoderMayhem** [comment]
@priyanshu0405 #262  is a duplicate of #261 and a PR has been opened for that so kindly close this PR. You must not open an issue which has already been opened and contributors are working in them.

**Comment by Sagar2366** [comment]
Closing this PR as this issue is fixed in https://github.com/PalisadoesFoundation/talawa/pull/265

**Pull request closed without merging**
