### PR TITLE
Adding Hashtag Feature

### LINKED ISSUE #1583: Implement the "Add Hashtag" Functionailty
**Is your feature request related to a problem? Please describe.**
Currently the "Add Hashtag" option does nothing; we would like for its required functionality to be implemented. See the video for a description of the issue 

[Steps outlined here till 2:41](https://www.youtube.com/watch?v=ix3eSReJj2k?t=124)

**Describe the solution you'd like**
When clicking the "Add Hashtag" option (pictured below), allow the user to add a hashtag . Currently, it does nothing.  

Screenshot at Feb 27 06-21-01

**Describe alternatives you've considered**
If possible, write some functionality to detect if a hashtag is present on a post rather than having the user select an "Add Hashtag" option. If this route is chosen then remove the "Add Hashtag" option altogether. 

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by andoriyaprashant**
**What kind of change does this PR introduce?**

This pull request introduces a hashtag feature to enhance the functionality of the app's post creation process. The feature allows users to easily add and manage hashtags within their posts, enhancing content discoverability and organization.

**Issue Number:**

## Fixes #1583 

**Did you add tests for your changes?**

- No

**Summary**

The AddPostViewModel class has been expanded with hashtag-related capabilities, facilitated by a custom PostTextController. This controller empowers users with hashtag highlighting and manipulation abilities. 

The dynamic handleTextChange function identifies hashtags in the text and provides suggestions based on prefixes. 
The _fetchTags function, which will eventually interface with the server, has been included for trending hashtags. User interaction is streamlined through the onTagClick function, allowing hashtags to be added or replaced by tapping suggestions and adjusting cursor position. An interactive hashtag suggestion list conveniently appears as users type hashtags, enabling swift integration into their posts.

A specialized PostTextController has been integrated to emphasize hashtags and provide real-time listener updates. Additionally, adjustments to the add_post_page.dart include a section that showcases the hashtag suggestions while typing, with tapping suggestions smoothly updating the text field.

**Does this PR introduce a breaking change?**

- No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**

- Yes

### CODE REVIEW

**Comment by palisadoes** [comment]
Please fix the failing tests.

**Comment by andoriyaprashant** [comment]
Sir @palisadoes Could you please provide a brief explanation about the tests that are currently failing
This will help me identify and address the issues correctly
Thank you.

**Comment by palisadoes** [comment]
Please click on the link of the failing test.

**Comment by andoriyaprashant** [comment]
Sir @palisadoes I made changes in my code to fix the workflows, such as ensuring the code is in the correct format, and I also fixed the ordering of directive sections. However, as soon as the video_player dependency changed in this project through pull request https://github.com/PalisadoesFoundation/talawa/pull/2006#issue-1874717384  , I started encountering this workflow error 
image

Please guide me on how to fix this error, or you can review my pull request. Thank you.

**Comment by literalEval** [comment]
@andoriyaprashant you might want to upgrade the package yourself in this PR.

**Comment by noman2002** [comment]
Hey @andoriyaprashant, @Ayush0Chaudhary is already working on this issue as a part of his GSoC project, it will be great if you can take another open issues. 
@palisadoes We need to close this PR.

**Pull request closed without merging**
