### PR TITLE
Built caching support

### LINKED ISSUE #2536: Build Caching Support to all the feeds in the mobile application. GSoC
**Is your feature request related to a problem? Please describe.**
Currently application lacks a feed caching mechanism, which makes the app barely usable in offline situations.

**Describe the solution you'd like**
Create a feed caching mechanism similar to Instagram in all the feeds of the application.

**Feed Caching mechanism.**
1. load cached data from cache.
2. fetch new data in background.
3. refresh cache with new data.
4. populate feed screens with new data.

**Describe alternatives you've considered**

**Approach to be followed (optional)**

**Additional context**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by Azad99-9**
**What kind of change does this PR introduce?**

This PR adds a caching mechanism to all the feeds in the mobile application.

**Issue Number:**

Fixes #2536 

**Did you add tests for your changes?**

Yes

**Snapshots/Videos:**

Screenshot from 2024-08-31 22-57-59

Screenshot from 2024-08-31 22-58-10

**If relevant, did you update the documentation?**

**Summary**

1. Created a hive manager class to handle hive functions.
2. Created a base feed manager to handle the caching of the feed.
3. All feed services will extend this base feed manager to employ the common caching mechanism.
4. Designed a feed caching flow as depicted in above images.

**Does this PR introduce a breaking change?**

No

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**

Yes

## Summary by CodeRabbit

- **New Features**
	- Enhanced documentation for constants related to languages and currencies.
	- Introduced `HiveKeys` class for centralized management of Hive box keys.
	- Added `HiveManager` class to encapsulate Hive initialization and teardown.
	- Integrated caching functionality into services for offline capabilities.
	- Improved data persistence for `Comment`, `Event`, and `Post` models with Hive integration.
	- Added new caching tests for the `Comment` and `Event` models.

- **Bug Fixes**
	- Improved error handling and logging in various services and view models.

- **Tests**
	- Expanded test coverage for caching functionality in models.
	- Streamlined test setup by removing unnecessary Hive initialization.
	- Added new tests for `EventService` and `PostService` to validate functionality under different scenarios. 

- **Documentation**
	- Updated comments and documentation for better clarity and maintainability across the codebase.

### CODE REVIEW

**Comment by palisadoes** [comment]
@coderabbitai review

**Comment by palisadoes** [comment]
Please make the suggested coderabbit.ai changes

**Comment by Azad99-9** [comment]
@palisadoes had a discussion with my mentor @noman2002 on the reviewal of this PR. He is currently a bit occupied with limited network connectivity. So he will review this PR as soon as he gets time.

Also right now I am working on the chatting UI right now. So everything is on track.

**Review by noman2002 — APPROVED** [review]
LGTM

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
