### PR TITLE
[Fix] Groups page should be blank for newly created organizations

### LINKED ISSUE #662: Groups page should be blank for newly created organizations
- **Issue Description:** Groups page should be blank for newly created organizations. Refer #537 
- **Issue Severity:** Medium
- **Environment Details:** Found in `talawa\lib\views\pages\chat\groups.dart`
- **Observed Behaviour:** Currently default data is getting loaded for newly created organizations.
- **Expected Behaviour:** It should be blank for newly created organizations
- **Steps to reproduce issue:** Create an organization and switch to the groups tab.
- **Does this issue need immediate attention?** Yes
- **Are you willing to work on this issue:** Yes, I am willing to work on this issue!

### PR DESCRIPTION
**Pull request by Raunakk02**
**What kind of change does this PR introduce?**
Fixes the issue of the groups page showing default static data.

**Did you add tests for your changes?**
Yes

**If relevant, did you update the documentation?**
No

**Summary**
Fixes #662 

**Does this PR introduce a breaking change?**
No

### CODE REVIEW

**Comment by palisadoes** [comment]
Please correct your code to pass our package analysis test. This needs to be resolved before we can review.

**Comment by Raunakk02** [comment]
> Please correct your code to pass our package analysis test. This needs to be resolved before we can review.

I have fixed the code now @palisadoes,

**Comment by Sagar2366** [comment]
@Raunakk02 can you attach before and after video visuals as well. 
Some problems I see, newly created event doesn't appear in event list and under group chat page too.

**Review by Sagar2366 — CHANGES_REQUESTED** [review]
@Raunakk02 can you attach before and after video visuals as well.
Some problems I see, newly created event doesn't appear in event list and under group chat page too.

**Comment by Raunakk02** [comment]
> @Raunakk02 can you attach before and after video visuals as well.
> Some problems I see, newly created event doesn't appear in event list and under group chat page too.

Sure @Sagar2366 sir.
Here are the before and after visuals.

> Before:
>

https://user-images.githubusercontent.com/56073198/115986181-a54b0280-a5cc-11eb-8c7f-cb1534d52b67.mp4

> After:
>

https://user-images.githubusercontent.com/56073198/115986190-ab40e380-a5cc-11eb-8f84-dfae4fff1fac.mp4

**Review by Sagar2366 — APPROVED** [review]

**Pull request merged**
