### PR TITLE
Fix Chat Screen

### PR DESCRIPTION
**Pull request by literalEval**
**What kind of change does this PR introduce?**

1. Fixes the error that popped up on selecting contacts for chats and tweaked the UI a bit.
2. The chat system on the other hand, will start working only after complete migration of the chat API to subscriptions.

**Did you add tests ?**

Nothing added/changed that requires new tests

**Does this PR introduce a breaking change?**

No

### CODE REVIEW

**Comment by palisadoes** [comment]
@noman2002 @nishnatadebnath Please review

**Review by noman2002 — CHANGES_REQUESTED** [review]
Please fix the failing test.

**Comment by literalEval** [comment]
Should I write documentation for the changed files ?

**Comment by noman2002** [comment]
@literalEval There is something else that is causing the tests to fail. check for it and get this merged.

**Comment by palisadoes** [comment]
Should this PR be closed?

**Comment by noman2002** [comment]
@literalEval Update ???

**Comment by literalEval** [comment]
@noman2002 We can discuss the UI once.

**Comment by palisadoes** [comment]
@noman2002 Please respond. It's been some time.

**Comment by noman2002** [comment]
@literalEval I think this PR should be closed.

**Pull request closed without merging**
