### PR TITLE
Fix : Not able to close pop up in Join Organization Screen #815

### LINKED ISSUE #815: Bug : Not able to close pop up in Join Organization Screen
**Describe the bug**
We are not able to close pop up in Join Organization Screen & we navigate to previous screen without closing popup.

**To Reproduce**

1. Switch to Profile Screen
2. Click on 'Join or Create New Organization'
3. Chose any organization & click on 'JOIN' button
4. Popup appears. Now Click on 'Close'

**Expected behavior**
Popup should disappear & we should stay on same page.

**Actual behavior**
Popup is not disappearing even after clicking on 'close' & we are navigate to previous screen without closing popup.

**Screenshots**
ezgif com-video-to-gif-2

**Additional details**
Github Externship Appication No. : ````20-05_Adi500_tfa_262````

### PR DESCRIPTION
**Pull request by AdityaBirangal**
**What kind of change does this PR introduce?**
fix #815 

**Did you add tests for your changes?**
No

**If relevant, did you update the documentation?**
Not required

**Summary**
The bug was caused due to Page context was used in the close button instated new context of a builder.
Fix:
Refactor : ctx -> dialogContext
Change : context -> dialogContext (line 142)

**Does this PR introduce a breaking change?**
No

**Other information**
Nope

### CODE REVIEW

**Review by sumitra19jha — APPROVED** [review]

**Comment by sumitra19jha** [comment]
The changes are good to go.
Please fix the Travis-ci error

**Review by palisadoes — APPROVED** [review]

**Comment by palisadoes** [comment]
@AdityaBirangal  `flutter test` is not working correctly on your code. This is causing Travis CI to fail. 

1. Follow the steps in the GitHub site's [Checking out pull requests locally](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/reviewing-changes-in-pull-requests/checking-out-pull-requests-locally) web page.
2. Resolve the conflicts, which appear related to `pubspec.yml`
3. Resubmit your pull request.

The error can be seen below

image

**Comment by palisadoes** [comment]
@AdityaBirangal Please run `flutter format --set-exit-if-changed .` a few more times from the root directory until you get no errors. The PR is failing because your code isn't autoformatted to our standard.

**Comment by AdityaBirangal** [comment]
> @AdityaBirangal Please run `flutter format --set-exit-if-changed .` a few more times from the root directory until you get no errors. The PR is failing because your code isn't autoformatted to our standard.

Done 👍🏻

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
