### PR TITLE
Custom drawer Unittests

### PR DESCRIPTION
**Pull request by architsangal**
**What kind of change does this PR introduce?**

Added Unit Test cases for custom_drawer.dart

**Issue Number:**
#1173

**Did you add tests for your changes?**
Yes

**Have you read the**  [**contributing guide**](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)? 
Yes

### CODE REVIEW

**Comment by palisadoes** [comment]
The code coverage for [custom_drawer_view_model.dart](https://app.codecov.io/gh/PalisadoesFoundation/talawa/compare/1219/diff?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr%20comments&utm_term=PalisadoesFoundation#diff-bGliL3ZpZXdfbW9kZWwvd2lkZ2V0c192aWV3X21vZGVscy9jdXN0b21fZHJhd2VyX3ZpZXdfbW9kZWwuZGFydA==) is not 100%. Please ensure we get to that goal. That is a prerequisite for merging the PR.

[You can see the sections that need to be covered here](https://app.codecov.io/gh/PalisadoesFoundation/talawa/blob/develop/lib/widgets/custom_drawer.dart).

**Review by palisadoes — CHANGES_REQUESTED** [review]
- The code coverage for [custom_drawer_view_model.dart](https://app.codecov.io/gh/PalisadoesFoundation/talawa/compare/1219/diff?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr%20comments&utm_term=PalisadoesFoundation#diff-bGliL3ZpZXdfbW9kZWwvd2lkZ2V0c192aWV3X21vZGVscy9jdXN0b21fZHJhd2VyX3ZpZXdfbW9kZWwuZGFydA==) is not 100%. Please ensure we get to that goal. That is a prerequisite for merging the PR.
- [You can see the sections that need to be covered here](https://app.codecov.io/gh/PalisadoesFoundation/talawa/blob/develop/lib/widgets/custom_drawer.dart).

**Comment by architsangal** [comment]
Sure! I will try to make it 100%.

**Comment by architsangal** [comment]
Submitting a new PR.

**Pull request closed without merging**
