### PR TITLE
Fixes#1407 Added the test for select_contact.

### LINKED ISSUE #1407: Views: Create tests for select_contact.dart
The Talawa code base needs to be 100% reliable. This means we need to have 100% test code coverage.

Tests need to be written for file `lib/views/after_auth_screens/chat/select_contact.dart`

- When complete, all methods, classes and/or functions in the file will need to be tested. 
- These tests must be placed in a single file with the name `test/views/after_auth_screens/chat/select_contact_test.dart`. You may need to create the appropriate directory structure to do this.

### IMPORTANT:
Please refer to the parent issue on how to implement these tests correctly:

- https://github.com/PalisadoesFoundation/talawa/issues/1217

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base. This will be clearly visible when you submit your PR.
- [The current code coverage for the file can be found here](https://codecov.io/gh/PalisadoesFoundation/talawa/tree/develop/lib/views/after_auth_screens/chat/). If the file isn't found in this directory, or there is a 404 error, then tests have not been created.
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide.
- You can verify your own code coverage by creating an account at [Codecov.io](https://codecov.io)

### LINKED ISSUE #1409: Views: Create tests for chat_list_screen.dart
The Talawa code base needs to be 100% reliable. This means we need to have 100% test code coverage.

Tests need to be written for file `lib/views/after_auth_screens/chat/chat_list_screen.dart`

- When complete, all methods, classes and/or functions in the file will need to be tested. 
- These tests must be placed in a single file with the name `test/views/after_auth_screens/chat/chat_list_screen_test.dart`. You may need to create the appropriate directory structure to do this.

### IMPORTANT:
Please refer to the parent issue on how to implement these tests correctly:

- https://github.com/PalisadoesFoundation/talawa/issues/1217

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base. This will be clearly visible when you submit your PR.
- [The current code coverage for the file can be found here](https://codecov.io/gh/PalisadoesFoundation/talawa/tree/develop/lib/views/after_auth_screens/chat/). If the file isn't found in this directory, or there is a 404 error, then tests have not been created.
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide.
- You can verify your own code coverage by creating an account at [Codecov.io](https://codecov.io)

### PR DESCRIPTION
**Pull request by Ayush0Chaudhary**
**What kind of change does this PR introduce?**
It contains test for Select Contacts

**Issue Number:**

Fixes #1407
also Fixes #1409 (was important to reach maximum coverage in my PR)

**Did you add tests for your changes?**
YES

**Summary**
I wrote test for select contacts

**Does this PR introduce a breaking change?**
no

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**
YES

### CODE REVIEW

**Comment by Ayush0Chaudhary** [comment]
**I achieved 70.4% coverage.**


Screenshot from 2023-01-31 01-53-22

**Comment by noman2002** [comment]
> **I achieved 70.4% coverage.**
> 
> Screenshot from 2023-01-31 01-53-22

try to get it to 100%. test for itembuilder is already implemented somewhere in the code.

**Comment by Ayush0Chaudhary** [comment]
More coverage cannot be achieved as the code this part of the app is not complete

the return statement is commented out.
https://github.com/PalisadoesFoundation/talawa/blob/13dd451e899ab8bec282b5cf860f742b0dd40faf/lib/view_model/after_auth_view_models/chat_view_models/select_contact_view_model.dart#L14-L20

And this return is required to test the **ListBuilder** part of the select_contact.dart
https://github.com/PalisadoesFoundation/talawa/blob/13dd451e899ab8bec282b5cf860f742b0dd40faf/lib/views/after_auth_screens/chat/select_contact.dart#L39-L58

**Comment by Ayush0Chaudhary** [comment]
Also in attempt to get maximum coverage the code coverage of chat_list_screen.dart reached 100%
Screenshot from 2023-01-31 02-00-16

It was assigned to someone else
the issue -> https://github.com/PalisadoesFoundation/talawa/issues/1409

**Comment by Ayush0Chaudhary** [comment]
@noman2002 @palisadoes what should we do??

**Comment by Ayush0Chaudhary** [comment]
@SiddheshKukade

**Comment by Ayush0Chaudhary** [comment]
Also added the Router of Select Contact.

https://github.com/Ayush0Chaudhary/talawa/blob/76ed5a2c8360a27671f48048f8185fa20a741fc6/lib/router.dart#L230-L232

**Comment by noman2002** [comment]
@Ayush0Chaudhary You have written test for select_contact only , right ? If yes, then its fine if the coverage of other file is going up.We close that issue too.

**Comment by Ayush0Chaudhary** [comment]
> @Ayush0Chaudhary You have written test for select_contact only , right ? If yes, then its fine if the coverage of other file is going up.We close that issue too.

yes I only added test for my file

**Review by noman2002 — APPROVED** [review]

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
