### PR TITLE
Fix Main Screen View Model doc

### PR DESCRIPTION
**Pull request by literalEval**
Some PRs were merged from fellow contributors which didn't address documentations properly. Since custom lint check was not working for some time due to flutter version upgrade, the checks started failing once the lint was re-enabled in #2335 . Though nearly all of the problems were fixed in that PR, one specific case of the `main_screen_view_model.dart` was missed. This PR fixes that.

### CODE REVIEW

**Comment by literalEval** [comment]
@palisadoes please merge.

**Comment by Dante291** [comment]
> @palisadoes please merge.

@literalEval I have taken the latest upstream fetch, and I am getting many custom linting errors in so many files. Sir should I create new issue for this and fix them all?

**Comment by literalEval** [comment]
@Dante291 you are supposed to get linting errors in the files you have changed. As of now, all of them are fixed, so only the ones changed in your PR need to be documented. Please merge latest develop now and write proper docs. No new issue needs to be opened as such.

**Comment by Dante291** [comment]
> @Dante291 you are supposed to get linting errors in the files you have changed. As of now, all of them are fixed, so only the ones changed in your PR need to be documented. Please merge latest develop now and write proper docs. No new issue needs to be opened as such.

@literalEval 

image

Getting wrong doc format in many files after taking latest pull only, I was talking about fixing these sir.

**Comment by Dante291** [comment]
maybe this is happening because now we are showing none for future<void> too

**Comment by literalEval** [comment]
`Future<void>` is `None` return type, as we discussed earlier. If you hover over the error, it would be telling you the same. Moreover, the linting errors are generated when you remove the `// ignore` directive on the top of the file (which you are supposed to do, and write proper docs).

**Comment by Dante291** [comment]
> `Future<void>` is `None` return type, as we discussed earlier. If you hover over the error, it would be telling you the same. Moreover, the linting errors are generated when you remove the `// ignore` directive on the top of the file (which you are supposed to do, and write proper docs).

So should I fix all these errors by making new issue for it or just fix these in my next PR?

**Comment by literalEval** [comment]
Since these are minor changes, please change in your PR itself, and mention this change specifically in the PR comment.

**Pull request merged**
