### PR TITLE
Ptch: fix overflow of keep registerable switch in create event page and edit event page

### LINKED ISSUE #1088: Fix : Switches of ``Keep Registerable`` overflow in Add Event and Edit Event pages
In the Add Event and Edit Event pages, `Keep Public` and `Keep Registerable` are aligned in a Row, because of that the switch for `Keep Registerable` is overflowing,  sometimes the switch is not sliding properly when tapped on it.

<table>
      <tr>
       <td></td>
       <td></td>
      </tr>
  </table>

I want to work on this issue, Please Assign it to me.

### PR DESCRIPTION
**Pull request by RandyKdev**
**What kind of change does this PR introduce?**

Patch: UI Fix and Tests

**Issue Number:**

Fixes #1088

**Did you add tests for your changes?**

Yes

**Snapshots/Videos:**

At Large screen sizes
Screenshot_1646694056

At small screen sizes
Screenshot_1646694091

**If relevant, did you update the documentation?**

No.

**Summary**

This PR resolves issue #1088. A wrap widget was introduced so that at small screen sizes the two switches will go to a column causing it not to overflow on small screen sizes. And at large screen sizes, it remains as a row.

**Does this PR introduce a breaking change?**

No, It doesn't.

**Other information**

No.

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**

Yes.

### CODE REVIEW

**Review by jadeharr — CHANGES_REQUESTED** [review]
Your code coverage is below the minimum level. Please add tests to the `create_event_page.dart` and or the `edit_event_page.dart` file to increase the code coverage.

**Comment by jadeharr** [comment]
Please not the changes requested.

**Comment by RandyKdev** [comment]
Ok, I will write some tests for them

**Comment by palisadoes** [comment]
@Sagar2366 @DeltaHarbinger please review.

**Review by Sagar2366 — APPROVED** [review]

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
