### PR TITLE
Refactor Talawa URL to Hamburger menu.

### LINKED ISSUE #2137: Refactor the Talawa connection URL string to the hamburger menu. Make the Talawa demo work without URL string.
**Is your feature request related to a problem? Please describe.**
Having to enter a connection URL string in order to use Talawa is counterproductive; it requires one to setup the API or have it available somewhere to see the frontend's features and functionalities. We would much rather have the user be able to enter the app to get a look and free for it without having the API available.

<p align="center">
Screenshot at Nov 24 06-44-01
</p>

**Describe the solution you'd like**
Have the user access the Talawa frontend and then give them an option to connect to an organisation via the hamburger menu, more specifically through the `Join new organization` option. The logic should allow the user to enter a connection string if they are not already connected to any org, as well as, allow them to sift through the different orgs they connected to on a separate page.

<p align="center">
Screenshot at Nov 24 06-46-02
</p>

### PR DESCRIPTION
**Pull request by Azad99-9**
**What kind of change does this PR introduce?**

This PR refactors Talawa connection URL string to the hamburger menu. Makes the Talawa demo work without URL string.

**Issue Number:**

Fixes #2137

**Did you add tests for your changes?**

Yes added tests for all the code that is modified/added in this PR.

**Snapshots/Videos:**

https://github.com/PalisadoesFoundation/talawa/assets/120930148/63956463-5c51-47b6-9b63-f7a993f9ee88

**If relevant, did you update the documentation?**

yes, added comments whereever needed.

**Summary**

The motive of this PR is to add a feature which allows users to use Talwa application without actually setting up the Talawa api in first place. Giving users a convenient way to switch between user mode and demo mode.

**Does this PR introduce a breaking change?**

No.

**Other information**

Created a files:  lib/views/demo_screens/explore_events_demo.dart
                          lib/views/demo_screens/organization_feed_demo.dart
                          lib/views/demo_screens/profile_page_demo.dart
                          test/service_tests/user_config_test.dart
                          test/views/demo_screens/explore_events_demo_test.dart
                          test/views/demo_screens/organization_feed_demo_test.dart
                          test/views/demo_screens/profile_page_demo_test.dart
                          
refactored code where ever possible.

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by Azad99-9** [comment]
@palisadoes `run_check_ignore` is giving me an error, asking for comments to be added to the code I modified. However, the comments in those specific files seem to be ignored due to `ignore_for_file` prior to this PR.

**Review by noman2002 — CHANGES_REQUESTED** [review]
Please fix the failing test and conflicting files.

**Comment by Azad99-9** [comment]
i have 4 files left to write tests, i am working on them.

**Comment by Dante291** [comment]
@Azad99-9 Could you wait for this [PR](https://github.com/PalisadoesFoundation/talawa/pull/2229) to get merged and then take the latest pull because I have edited test for whole profile_page_view_mode.dart file except the logout method that you've modified and added test for.

**Comment by Azad99-9** [comment]
Yeah that works @Dante291 you go on merging your PR, later i will resolve the conflicts in my PR.

**Comment by Dante291** [comment]
Thanks broski.

**Comment by palisadoes** [comment]
1. Please change the title of this PR so that it is more indicative of the aim of the original issue.
2. Please fix the failing tests

**Comment by Azad99-9** [comment]
@Ayush0Chaudhary  @DMills27 @noman2002 , i have added tests to almost all files I have modified in this pr.
 i am facing a bit difficulty in writing test to remaining 2 files in this pr. This code is related to animation that shows up when going through the apptour it's  a bit complicated because the animation goes on blinking infinitely. Which is quite hard to mock.

Apart from that I have added the tests and tested the UI entirely. Could you please suggest me what should I do next.

**Comment by Azad99-9** [comment]
@palisadoes i have written tests to all the files, and also made `main_screen_view_model.dart` (holds the animations part of apptour) coverage to 96%. please review this pr.

**Comment by noman2002** [comment]
> @palisadoes @DMills27 @Ayush0Chaudhary @noman2002 i have written tests to all the files, and also made `main_screen_view_model.dart` (holds the animations part of apptour) coverage to 96%. The unauthorized file `pubspec.lock` is also the same as the file in current repo. please review this pr.

Code looks fine but can you please attach a latest video and also if possible, send a apk build on slack.

**Comment by Azad99-9** [comment]
> > @palisadoes @DMills27 @Ayush0Chaudhary @noman2002 i have written tests to all the files, and also made `main_screen_view_model.dart` (holds the animations part of apptour) coverage to 96%. The unauthorized file `pubspec.lock` is also the same as the file in current repo. please review this pr.
> 
> Code looks fine but can you please attach a latest video and also if possible, send a apk build on slack.

I have shared the apk of the latest build over slack.

**Comment by Azad99-9** [comment]
hey @noman2002, any follow ups with yesterday's build.

**Comment by noman2002** [comment]
> hey @noman2002, any follow ups with yesterday's build.

Yes it looked good to me. waiting for others to review it. It will take some time as there are a lot of file changes.

**Review by Ayush0Chaudhary — APPROVED** [review]

**Review by palisadoes — APPROVED** [review]

**Comment by palisadoes** [comment]
@DMills27 Please take a look. This was your issue. We have two approvers already, but need your input.

**Review by DMills27 — APPROVED** [review]
Looks good to me

**Pull request merged**
