### PR TITLE
Fix Deprecated UniLinksPlugin API #1204

### LINKED ISSUE #1204: Fix Deprecated UniLinksPlugin API
**Describe the bug**
When building the `talawa` app we get an UniLinksPlugin API warning message. This needs to be fixed

- Our test code coverage percentage will need to be improved or maintained as part of this fix.
- **DO NOT ATTEMPT to solve the issue by ignoring the error message in `build.gradle`** That is not a viable solution to this issue.

**To Reproduce**

1. Build the Talawa app
2. Monitor the console
3. See message below

**Expected behavior**
There should be no deprecation warning

**Actual behavior**
```
Note: /home/xxx/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/uni_links-0.5.1/android/src/main/java/name/avioli/unilinks/UniLinksPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
```

**Screenshots**
N/A

**Additional details**
N/A

### PR DESCRIPTION
**Pull request by Tusharkhati**
**Issue Number: #1204 **

Fixes #1204

`close #1204 `

### CODE REVIEW

**Comment by palisadoes** [comment]
What issue does this fix and has it been assigned to you?

In our [CONTRIBUTING.md](https://github.com/PalisadoesFoundation/talawa/blob/develop/CONTRIBUTING.md) we also explain how you can link and automatically close the issue tied to your pull request by [using a supported keyword in either the pull request's description or in a commit message.](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) This is a very useful feature that helps to prevent zombie issues that never die.

Please update the comments in this PR to automatically close the issue that has been assigned to you.

**Review by palisadoes — CHANGES_REQUESTED** [review]
What issue does this fix and has it been assigned to you?

In our [CONTRIBUTING.md](https://github.com/PalisadoesFoundation/talawa/blob/develop/CONTRIBUTING.md) we also explain how you can link and automatically close the issue tied to your pull request by [using a supported keyword in either the pull request's description or in a commit message.](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) This is a very useful feature that helps to prevent zombie issues that never die.

Please update the comments in this PR to automatically close the issue that has been assigned to you.

**Comment by palisadoes** [comment]
Also, the subject of your PR does not explain what you are trying to achieve. `Enter` isn't sufficient. 

Please take more care in your work.

**Comment by palisadoes** [comment]
Are you fixing the issue by ignoring the error message in [build.gradle](https://github.com/PalisadoesFoundation/talawa/pull/1213/files#diff-197b190e4a3512994d2cebed8aff5479ff88e136b8cc7a4b148ec9c3945bd65a)? If so, this is not the solution. 

We need to update packages to non-deprecated version levels. Please fix.

**Review by palisadoes — CHANGES_REQUESTED** [review]
Are you attempting to solve the issue by ignoring the error message in [build.gradle](https://github.com/PalisadoesFoundation/talawa/pull/1213/files#diff-197b190e4a3512994d2cebed8aff5479ff88e136b8cc7a4b148ec9c3945bd65a)? If so, this is not the solution. 

We need to update packages to non-deprecated version levels. Please fix correctly.

**Comment by Tusharkhati** [comment]
I'm on it.

**Comment by palisadoes** [comment]
Are you still working on this?

**Comment by Tusharkhati** [comment]
yes! I'm on it. sorry due to exams I wasn't able to do. 
I'm also bit confuse bout the issue it will be great help if you help me.
Thanks.

**Comment by palisadoes** [comment]
> yes! I'm on it. sorry due to exams I wasn't able to do. I'm also bit confuse bout the issue it will be great help if you help me. Thanks.

- Please use our slack channel to ask for help. There are many persons there who will be able to provide assistance.
- [I'd suggest you try to contact persons who have already successfully closed PRs](https://github.com/PalisadoesFoundation/talawa/pulls?q=is%3Apr+is%3Aclosed).

**Comment by Tusharkhati** [comment]
Thank you sir. this will be helpful to me. for now you can close PR but I will find solution I promise.

**Pull request closed without merging**
