### PR TITLE
Adding Progress Indicator to Join Button

### LINKED ISSUE #172: Adding loading Spinner to join button
As the user press the `join` button, to make the app user interface responsive, the presence of a loading spinner at the `join` button after the dialogue box will make the page transition experience better for the user.

### PR DESCRIPTION
**Pull request by adithyaakrishna**
**What kind of change does this PR introduce?**

Improving the Experience of the Join an Organization Page

- The `CircularProgressIndicator` was added to the` join` button to improve the user experience 

**Did you add tests for your changes?**
Yes, the change was tested in Android systems and does not break anything.

**Summary**

The main motivation was to make the page transition better and improve the experience

This PR is related to Issue and Fixes #172

### CODE REVIEW

**Review by jordanliu — COMMENTED** [review]
Why the deletion of the in-line comments?

**Comment by adithyaakrishna** [comment]
> Why the deletion of the in-line comments?
@jordanliu I hadn't fetched from upstream before making changes and then had some conflicts but now I've fixed it altogether. Sorry for that :/

**Comment by DeltaHarbinger** [comment]
Hey @adithyaakrishna, there seems to be an issue with the 'color' parameter in CircularProgressIndicator. It seems like you should have used 'valueColor' instead

Please see the following:
https://api.flutter.dev/flutter/material/CircularProgressIndicator-class.html
https://api.flutter.dev/flutter/material/ProgressIndicator/valueColor.html

If there are no further issues after this change, I will merge it

**Comment by Sagar2366** [comment]
@adithyaakrishna have you added changes to 19 files for this change ? 
If not, can you please resend PR with files changed to fix this issue ?

**Comment by adithyaakrishna** [comment]
> @adithyaakrishna have you added changes to 19 files for this change ?
> If not, can you please resend PR with files changed to fix this issue ?

Yes sure, I will Close this and create the PR again :)

**Pull request closed without merging**
