### PR TITLE
Fixed Bug #477 backslash(\) and double quotes(") in a graphql query

### PR DESCRIPTION
**Pull request by TusharGupta05**
**What kind of change does this PR introduce:**
It fixes the bug #477 Currently it is not possible to pass backslash(\) and double quotes(") in a graphql query but after merging of this PR, it will become possible.

**Issue Number:**
#477 

**Did you add tests for your code?**
I have tested it and added the videos regarding the same.

**Snapshots/Videos:**

Create organization page:

https://user-images.githubusercontent.com/56271252/112399073-918d5180-8d2b-11eb-8a03-7673d06c9233.mp4

Add a post page:

https://user-images.githubusercontent.com/56271252/112399106-a0740400-8d2b-11eb-955b-6a6fffd13851.mp4

Create an account page:

https://user-images.githubusercontent.com/56271252/112399161-bda8d280-8d2b-11eb-94ff-202341993713.mp4

In rest of the pages also it is working.

**Does this PR introduce a breaking change?**
No

**Other information:**
I have edited the Queries.dart file and added a function 'replaceAll' that replaces all the backslash(\) and double quotes(") of its argument in such a way that it becomes possible to pass it in a graphql query. For future, if anyone writes some new query, s/he should make sure that a call should be made to this function before returning the query string.

**Have you read the contributing guide?**
Yes

### CODE REVIEW

**Comment by Sagar2366** [comment]
@TusharGupta05 instead of removing/replacing special characters, better solution is notify users to not use special characters except (hyphen, underscore).
Can you please add those changes if not placed already ?

**Comment by TusharGupta05** [comment]
> @TusharGupta05 instead of removing/replacing special characters, better solution is notify users to not use special characters except (hyphen, underscore).
> Can you please add those changes if not placed already ?

@Sagar2366  sir so are you saying that the user should not be able to use any of these special characters `~!@#$%^&*()+={}[]|\:";'<>,.?/ and only -_ should be valid special characters?
If I got it wrong, please correct me what all special characters should be valid?
And if it is like that the user can't use any special character in a person's name textfield, but can use some certain special characters in an organization name, can use some certain special characters in posts etc. then please tell me which special character should be valid and for which textfield.
Also, I think in case of chat page, each and every special character should be valid.
According to current code, each and every special character can be used. The problem was only with double quotes(") and backslash(\).

**Comment by Sagar2366** [comment]
> > @TusharGupta05 instead of removing/replacing special characters, better solution is notify users to not use special characters except (hyphen, underscore).
> > Can you please add those changes if not placed already ?
> 
> @Sagar2366 sir so are you saying that the user should not be able to use any of these special characters `~!@#$%^&*()+={}[]|:";'<>,.?/ and only -_ should be valid special characters?
> If I got it wrong, please correct me what all special characters should be valid?
> And if it is like that the user can't use any special character in a person's name textfield, but can use some certain special characters in an organization name, can use some certain special characters in posts etc. then please tell me which special character should be valid and for which textfield.
> Also, I think in case of chat page, each and every special character should be valid.
> According to current code, each and every special character can be used. The problem was only with double quotes(") and backslash().

Handle each page differently, for organisation name, event name, user names, etc we can restrict to use only -  and _ special characters.
For chat, all special characters can be used.
I won't list down all the rules for each field. We want you to understand/analyse issue properly and come up with best solutions.

**Comment by TusharGupta05** [comment]
> > > @TusharGupta05 instead of removing/replacing special characters, better solution is notify users to not use special characters except (hyphen, underscore).
> > > Can you please add those changes if not placed already ?
> > 
> > 
> > @Sagar2366 sir so are you saying that the user should not be able to use any of these special characters `~!@#$%^&*()+={}[]|:";'<>,.?/ and only -_ should be valid special characters?
> > If I got it wrong, please correct me what all special characters should be valid?
> > And if it is like that the user can't use any special character in a person's name textfield, but can use some certain special characters in an organization name, can use some certain special characters in posts etc. then please tell me which special character should be valid and for which textfield.
> > Also, I think in case of chat page, each and every special character should be valid.
> > According to current code, each and every special character can be used. The problem was only with double quotes(") and backslash().
> 
> Handle each page differently, for organisation name, event name, user names, etc we can restrict to use only - and _ special characters.
> For chat, all special characters can be used.
> I won't list down all the rules for each field. We want you to understand/analyse issue properly and come up with best solutions.

Ok sir, got it. 
Sir, I think the best way to do it is by editing some files related to front end of the app such as addEventPage.dart In that file, input fields are TextFields and not TextFormField which is not good. In the whole app every TextFormField (such as the register form input fields are TextFormFields) is being validated using the corresponding validator method of the Validator class but since in the addEventPage.dart file TextFields are not TextFormFields, we can not validate its content using a validator method as TextField's constructor does not accept any such parameter.
In short, I can make the changes in 2 ways :
1) By editing some files and converting the TextField into TextFormField (as it is the best way for validating) and writing the corresponding validator method in the validator class.
2) By changing the Queries.dart file and the files where the queries are used. Basically, I will validate a string in the corresponding query method of Queries class and if there is any error(i.e. any such character is found which should not be present in the string), I will throw that error and handle that error in the page where the query was called.(I don't think it's the best way to do it because validation should be at the user input level just like it is done in other files and classes too).
Please tell me sir which way should I choose and if there is any other good possible way too that you want me to implement then do let me know.

**Comment by Sagar2366** [comment]
@TusharGupta05 take one screen at a time. Start with login/signup pages, update validation queries to solve this issue first on these pages and then one by one tackle remaining pages.

**Comment by Sagar2366** [comment]
@TusharGupta05 any update on this PR ?

**Comment by TusharGupta05** [comment]
> @TusharGupta05 any update on this PR ?

Sir I have edited the validator function of user's first and last name entered on the registration page and update profile page.
Sir, according to [this](https://companieshouse.blog.gov.uk/2019/02/14/symbols-and-characters-in-a-company-name/) website, following are the valid special characters in a UK company's name :
A-Z (any standard letter)
0-9 (any standard numeric)
& (ampersand)
@ (at sign)
£ (pound sign)
$ (dollar sign)
€ (euro sign)
¥ (yen sign)
\# (hash tag)
. (full stop)
, (comma)
: (colon)
; (semi-colon)
\- (hyphen)
So, almost all the special characters are valid for an organization name. So, should I just add support for double quotes and backslash also? Because it may be possible that these characters are also valid for an organization name in some other country.

**Comment by Sagar2366** [comment]
> > @TusharGupta05 any update on this PR ?
> 
> Sir I have edited the validator function of user's first and last name entered on the registration page and update profile page.
> Sir, according to [this](https://companieshouse.blog.gov.uk/2019/02/14/symbols-and-characters-in-a-company-name/) website, following are the valid special characters in a UK company's name :
> A-Z (any standard letter)
> 0-9 (any standard numeric)
> & (ampersand)
> @ (at sign)
> £ (pound sign)
> $ (dollar sign)
> € (euro sign)
> ¥ (yen sign)
> # (hash tag)
> . (full stop)
> , (comma)
> : (colon)
> ; (semi-colon)
> - (hyphen)
> So, almost all the special characters are valid for an organization name. So, should I just add support for double quotes and backslash also? Because it may be possible that these characters are also valid for an organization name in some other country.

Explain with example. For now we will not be adding changes based on assumption. If required, we can add support for additional special characters in future.

**Comment by TusharGupta05** [comment]
> > > @TusharGupta05 any update on this PR ?
> > 
> > 
> > Sir I have edited the validator function of user's first and last name entered on the registration page and update profile page.
> > Sir, according to [this](https://companieshouse.blog.gov.uk/2019/02/14/symbols-and-characters-in-a-company-name/) website, following are the valid special characters in a UK company's name :
> > A-Z (any standard letter)
> > 0-9 (any standard numeric)
> > & (ampersand)
> > @ (at sign)
> > £ (pound sign)
> > $ (dollar sign)
> > € (euro sign)
> > ¥ (yen sign)
> > # (hash tag)
> > . (full stop)
> > , (comma)
> > : (colon)
> > ; (semi-colon)
> > 
> > * (hyphen)
> >   So, almost all the special characters are valid for an organization name. So, should I just add support for double quotes and backslash also? Because it may be possible that these characters are also valid for an organization name in some other country.
> 
> Explain with example. For now we will not be adding changes based on assumption. If required, we can add support for additional special characters in future.

Special characteres                                               Example
&                                                                           AT&T
!                                                                             Chips Ahoy!, YUM!, and Yahoo! 
?                                                                            ?What if! 
:°                                                                            su:m37° 
\-                                                                             Colgate-Palmolive
'                                                                             McDonald's
,.                                                                            Digg, Inc. 
5                                                                            F5 Networks 
\+                                                                           1+1 Research – Market Research
|                                                                             20|20 Research
()                                                                           NAIDU EN. CON. (I) PRIVATE LIMITED
"                                                                            Toys "R" Us
\                                                                            R\West
@                                                                          @Large Films
/                                                                            Tim/Kerr
\*                                                                            E*Trade Group, Inc.
Resources :
https://www.brandingmag.com/2016/09/29/what-the-exploring-the-use-of-symbols-in-brand-names/
https://theresearchclub.com/directory/a-z/
https://en.wikipedia.org/wiki/List_of_companies_of_the_United_States_by_state
https://en.wikipedia.org/wiki/@Large_Films
https://en.wikipedia.org/wiki/R%5CWest
https://www.sec.gov/rules/other/4-460list.htm

First of all, sorry sir for all the late replies from my end. I am currently sick in bed, so whenever I get a chance, I try to do the research and post the reply.

Sir I went through 2000+ companies names and I have added an example for most of the special characters. As you can see that some companies such Toys "R" Us and R\West have even used double quotes and backslash in its name.

There are some other companies also like Nestlé that has used é special character in its name. So, according to me the best solution is to just add support for double quotes(") and backslash(\) also, as nearly all the special characters are used in some company name.

@Sagar2366 what do you say?

**Comment by Sagar2366** [comment]
> > > > @TusharGupta05 any update on this PR ?
> > > 
> > > 
> > > Sir I have edited the validator function of user's first and last name entered on the registration page and update profile page.
> > > Sir, according to [this](https://companieshouse.blog.gov.uk/2019/02/14/symbols-and-characters-in-a-company-name/) website, following are the valid special characters in a UK company's name :
> > > A-Z (any standard letter)
> > > 0-9 (any standard numeric)
> > > & (ampersand)
> > > @ (at sign)
> > > £ (pound sign)
> > > $ (dollar sign)
> > > € (euro sign)
> > > ¥ (yen sign)
> > > # (hash tag)
> > > . (full stop)
> > > , (comma)
> > > : (colon)
> > > ; (semi-colon)
> > > 
> > > * (hyphen)
> > >   So, almost all the special characters are valid for an organization name. So, should I just add support for double quotes and backslash also? Because it may be possible that these characters are also valid for an organization name in some other country.
> > 
> > 
> > Explain with example. For now we will not be adding changes based on assumption. If required, we can add support for additional special characters in future.
> 
> Special characteres Example
> & AT&T
> ! Chips Ahoy!, YUM!, and Yahoo!
> ? ?What if!
> :° su:m37°
> - Colgate-Palmolive
> ' McDonald's
> ,. Digg, Inc.
> 5 F5 Networks
> + 1+1 Research – Market Research
> | 20|20 Research
> () NAIDU EN. CON. (I) PRIVATE LIMITED
> " Toys "R" Us
> \ R\West
> @ @large Films
> / Tim/Kerr
> * E*Trade Group, Inc.
> Resources :
> https://www.brandingmag.com/2016/09/29/what-the-exploring-the-use-of-symbols-in-brand-names/
> https://theresearchclub.com/directory/a-z/
> https://en.wikipedia.org/wiki/List_of_companies_of_the_United_States_by_state
> https://en.wikipedia.org/wiki/@Large_Films
> https://en.wikipedia.org/wiki/R%5CWest
> https://www.sec.gov/rules/other/4-460list.htm
> 
> First of all, sorry sir for all the late replies from my end. I am currently sick in bed, so whenever I get a chance, I try to do the research and post the reply.
> 
> Sir I went through 2000+ companies names and I have added an example for most of the special characters. As you can see that some companies such Toys "R" Us and R\West have even used double quotes and backslash in its name.
> 
> There are some other companies also like Nestlé that has used é special character in its name. So, according to me the best solution is to just add support for double quotes(") and backslash(\) also, as nearly all the special characters are used in some company name.
> 
> @Sagar2366 what do you say?

@TusharGupta05 thanks for putting efforts on research.
Let's keep this on hold for now, we can introduce support for more special characters when required.

and take care :)

**Comment by Sagar2366** [comment]
@TusharGupta05 for now we don't need this feature, closing PR. 
In case, any Organization comes with such names, we can add changes that time.

**Pull request closed without merging**
