### PR TITLE
[Fix] Events, newsfeed, etc. should be blank for newly created organizations

### LINKED ISSUE #537: Events, newsfeed, etc. should be blank for newly created organizations
- **Issue Description:** Events, newsfeed, etc. should be blank for newly created organizations
- **Issue Severity:** Low
- **Environment Details:** Almost in the whole app
- **Observed Behaviour:** Currently default data is getting loaded for newly created organizations.
- **Expected Behaviour:** It should be blank for newly created organizations
- **Steps to reproduce issue:** Create an organization and switch to members or events tab.
- **Does this issue need immediate attention?** Yes
- **Are you willing to work on this issue:** Yes, I am willing to work on this issue!

### PR DESCRIPTION
**Pull request by Raunakk02**
**What kind of change does this PR introduce?**
Resolves #537 

**Did you add tests for your changes?**
Yes

**If relevant, did you update the documentation?**
No

**Does this PR introduce a breaking change?**
No

### CODE REVIEW

**Comment by Sagar2366** [comment]
@Raunakk02 disable code auto-formatter and make sure you are sharing PR with changes added by you to fix this issue.

**Comment by Raunakk02** [comment]
@Sagar2366 I have disabled the code auto-formatter and resolved the conflicts. Please review the PR.

**Comment by Sagar2366** [comment]
@Raunakk02 clone latest master and add your changes to PR or revert previous commits from this PR.
This PR still have conflicts.

**Comment by Sagar2366** [comment]
@Raunakk02 few issue noticed in your PR -
1. Default list of events shown into chat page
2. Update message in newsfeed page to meaningful text.

Please send before and after visual videos for review.

**Comment by Raunakk02** [comment]
> @Raunakk02 few issue noticed in your PR -
> 
> 1. Default list of events shown into chat page
> 2. Update message in newsfeed page to meaningful text.
> 
> Please send before and after visual videos for review.

@Sagar2366 I have resolved both issues. 

**Here is the video before the issue was resolved:**
> 

https://user-images.githubusercontent.com/56073198/113135586-e820f100-923f-11eb-857f-8fdcb338086d.mp4


**Here is the video after the issue was resolved:**
> 

https://user-images.githubusercontent.com/56073198/113135713-10a8eb00-9240-11eb-8477-95fef8873b48.mp4

**Comment by Sagar2366** [comment]
@Raunakk02 add only changes to PR to fix the issue. Disable code auto-formatter.
File changes on this PR showing changes which are already present on Master.

**Comment by Raunakk02** [comment]
@Sagar2366  sorry for the changes due to code auto-formatter. I have disabled it now. Do you want me to close this PR and submit a new one with all the changes made again to it?
Awaiting reply!

**Comment by Sagar2366** [comment]
> @Sagar2366 sorry for the changes due to code auto-formatter. I have disabled it now. Do you want me to close this PR and submit a new one with all the changes made again to it?
> Awaiting reply!

Yes, please send only changes to fix this issue.

**Comment by Raunakk02** [comment]
> > @Sagar2366 sorry for the changes due to code auto-formatter. I have disabled it now. Do you want me to close this PR and submit a new one with all the changes made again to it?
> > Awaiting reply!
> 
> Yes, please send only changes to fix this issue.

Ok, let me fix it again and send submit a new PR afterwards!

**Pull request closed without merging**
