### PR TITLE
bfix: pause video when not inview

### LINKED ISSUE #997: Video on the feed is playing even when scrolled up or tab changed
**Describe the bug**
Videos embed on the feed is playing continuously even when page is scrolled up or even when the active tab on the bottom navigation bar is changed. 

**Expected behavior**
The video should stop when scrolled up or the tab is changed.

**Actual behavior**
The video is playing the background.

**Additional details**
N/A

### PR DESCRIPTION
**Pull request by aman-singh7**
**What kind of change does this PR introduce?**
-Bug Fixes in Video post.

**Issue Number:**
Fixes #997 

**Video/Screenshot:**

https://user-images.githubusercontent.com/77198905/142408219-2a9cb10e-d56b-4452-9505-a9e454a9cc47.mp4

https://user-images.githubusercontent.com/77198905/142407600-b1c95f9d-de57-47d3-b261-16cd1730476e.mp4

**Summary**
There is some bug in the existing `InView` implementation due to which only the first video is playing and does not pause when scrolled or the bottom navigation tab is changed.

**Does this PR introduce a breaking change?**
No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by aman-singh7** [comment]
Why Github action is faling??

**Review by CyberWake — DISMISSED** [review]
Ready for merge.

**Review by sumitra19jha — CHANGES_REQUESTED** [review]
Please remove pubspec.lock file from your PR

**Comment by CyberWake** [comment]
@palisadoes please mark the review on the PR I have tried and tested this.

**Review by rutvik11062000 — APPROVED** [review]

**Review by CyberWake — APPROVED** [review]
LGTM, ready for merge

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
