### PR TITLE
Provider addition for Newsfeed, Post, and Groups

### PR DESCRIPTION
**Pull request by sumitra19jha**
**What kind of change does this PR introduce?**
Refactoring for issue #721 

**Did you add tests for your changes?**
No

**If relevant, did you update the documentation?**
No

**Summary**
To separate business logic from Ui

**Does this PR introduce a breaking change?**
No

**Other information**

### CODE REVIEW

**Comment by palisadoes** [comment]
@dellyjm
@DeltaHarbinger
@Sagar2366
@TheHazeEffect

Please review this

**Comment by Sagar2366** [comment]
@sumitra19jha resolve conflicts on PR.

**Comment by sumitra19jha** [comment]
@Sagar2366 Please check. The conflict is resolved

**Comment by palisadoes** [comment]
@sumitra19jha Please resolve the conflicts

**Comment by sumitra19jha** [comment]
@palisadoes Conflict Resolved

**Comment by palisadoes** [comment]
@sumitra19jha Please resolve the conflicts in these files:
```
lib/main.dart
lib/views/pages/chat/groups.dart
test/widget_tests/home_page_test.dart
test/widget_tests/news_article_test.dart
test/widget_tests/newsfeed_test.dart
test/widget_tests/profile_page_test.dart
test/widget_tests/set_url_page_test.dart
```

**Comment by sumitra19jha** [comment]
@palisadoes Conflict Resolved

**Comment by palisadoes** [comment]
@sumitra19jha Please resolve the outstanding conflicts. 

```
lib/controllers/post_controller.dart
lib/services/post_provider.dart
lib/views/pages/events/events.dart
lib/views/pages/newsfeed/newsfeed.dart
```

**Comment by sumitra19jha** [comment]
@palisadoes Conflict resolved

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
