### PR TITLE
Increasing coverage to 35%

### PR DESCRIPTION
**Pull request by Literal-Eval**
### Tests for CustomListTile widget

### CODE REVIEW

**Comment by palisadoes** [comment]
@Literal-Eval 
- Your tests are failing. Please review.
- Please also open an issue for this PR. [Refer to or Pull Request guide.](https://github.com/PalisadoesFoundation/talawa/blob/develop/PR-guidelines.md)

**Comment by Literal-Eval** [comment]
- The tests failed because it has not reached the 33% threshold yet. But it will, soon, with more commits.
- Issue #986

**Comment by Literal-Eval** [comment]
Current coverage is approx 32.55
Can you please confirm whether it has increase with these commits or not ?

**Comment by palisadoes** [comment]
The current required coverage is 33%. Please consider some tests for
widgets.

**Comment by Literal-Eval** [comment]
Reached 32.9% :)
Hope I will pass 33 by tonight.

**Comment by Literal-Eval** [comment]
custom_alert_dialog_test.dart is not complete yet, but will be in the next commits.

**Comment by Literal-Eval** [comment]
@palisadoes please consider merging this PR :)

**Review by palisadoes — DISMISSED** [review]

**Comment by palisadoes** [comment]
- @Sagar2366 
- @CyberWake 
- @rutvik11062000 
- @TheHazeEffect 

Please review and merge if ready

**Review by CyberWake — COMMENTED** [review]
Can you please add why the title of the PR is Test of widgets/CustomListTile.dart if you are including test for more widgets.

**Comment by Literal-Eval** [comment]
Because it was supposed to be the test for only CustomListTile, but it didn't pass the checks (due to 33% threshold). And in fact NO single test could take the coverage to 33%, and so all the PRs would fail. So I decided to commit all the tests in this PR so that it ultimately passes.
I'll change it now.

**Review by CyberWake — CHANGES_REQUESTED** [review]
in custom_alert_dialog_test.dart there is a technical issue as well as a missing test. Since the name of the widget itself make it clear that it is a dialog and hence this makes it straightforward that it needs to be an overlay over a primary screen hence while testing you should not use it as the home parameter of the MaterialApp widget.
Instead, use any screen and then push the dialog.
Also the test missing is the one to find the original primary screen on which the dialog was pushed.

**Review by CyberWake — COMMENTED** [review]
Rest changes look's smooth and ready for merge.

**Comment by Literal-Eval** [comment]
Hmm. Sure.

**Comment by Literal-Eval** [comment]
Please review again.

**Review by palisadoes — APPROVED** [review]

**Comment by palisadoes** [comment]
- @CyberWake 
- @TheHazeEffect 
- @Sagar2366 
- @rutvik11062000 

Please review and merge if OK

**Comment by Literal-Eval** [comment]
Kindly consider merging so that the test threshold crosses 33 and I can work on other things too.

**Comment by palisadoes** [comment]
Merging as suggested by @CyberWake

**Pull request merged**
