### PR TITLE
Formatted the code by adding trailing commas

### LINKED ISSUE #735: Adding Trailing Comma in the Dart File.
**Issue Description**
As we are in refactor mode, Adding trailing commas will increase the readability of the code. It will help us auto-format the code and auto-comment the ending widget. 
| Before | After |
| --- | --- |
| Without Trailing Commas | With Trailing Commas |

**Pros:** 
1. Makes the code more readable 
1. With Bracket colorizer, figuring out the widget and all will be easy.
1. Helps to auto-format the code and auto-comment about the ending widget.

**Cons:** 
1. As we have line restriction, It may be a problem as it increase the line. We can do something about this @Sagar2366,  @palisadoes and @DeltaHarbinger.

**Other Information**   
Instead of using print() to debug and view the output, the use of debugPrint() will be better than it won't show in the production. 

**Please ask mentors/maintainers to assign if you are willing to work on this issue.**
I would to work on this but I have my exams starting tomorrow :grimacing:. Let new member work on this.

### PR DESCRIPTION
**Pull request by nayakastha**
**What kind of change does this PR introduce?** ->This Pull Request formats the codebase by adding trailing commas throughout the files.

**Did you add tests for your changes?** No, not needed.

**If relevant, did you update the documentation?** No, it wasn't relevant for this PR

**Summary** Fixes #735 (with the pull request #744 )

**Does this PR introduce a breaking change?** No, it is just minor code refactoring.

PS - This PR includes formatting of folders hence makes the code clean but a downside is that the files have become slightly lengthier which I think will be taken care by solving of other issues.

### CODE REVIEW

**Comment by palisadoes** [comment]
@nayakastha Is there any way that this could be automated as part of our pull request process. Did you do this manually or use a script?

**Comment by nayakastha** [comment]
> @nayakastha Is there any way that this could be automated as part of our pull request process. Did you do this manually or use a script?

I did it manually for now. I will find a way to automate it and get back to you. Usually, if one uses a code predictor for writing the code, it already has trailing commas but it is not very intuitive. I will search a way for automation.

**Review by palisadoes — APPROVED** [review]

**Comment by DeltaHarbinger** [comment]
Hey @nayakastha, there seem to be issues when I try to build your branch. lib/views/pages/events/events.dart seems to be the main file that causes errors

**Review by DeltaHarbinger — CHANGES_REQUESTED** [review]
lib/views/pages/events/events.dart seems to cause issues during build. Please take a look at this file @nayakastha

**Comment by dellyjm** [comment]
> 
> 
> lib/views/pages/events/events.dart seems to cause issues during build. Please take a look at this file @nayakastha

Will await these changes before reviewing.

**Comment by nayakastha** [comment]
> lib/views/pages/events/events.dart seems to cause issues during build. Please take a look at this file @nayakastha

I will look into it sir and make the required changes

**Comment by Sagar2366** [comment]
@nayakastha resolve conflicts on this PR.
Please avoid creating big PR's, break them into smaller ones so it gets easier for review.

**Comment by nayakastha** [comment]
> @nayakastha resolve conflicts on this PR.
> Please avoid creating big PR's, break them into smaller ones so it gets easier for review.

I am really sorry, but this PR demanded an indeed large change because it was an alteration in many files. I will merge the conflicts asap.

**Comment by nayakastha** [comment]
@Sagar2366 sir, I hope all the issues in this PR and clear and good to go for a merge.

**Comment by palisadoes** [comment]
@DeltaHarbinger are you OK with the changes you requested from @nayakastha?

**Comment by palisadoes** [comment]
@nayakastha  There is a final conflict. I'll merge it as soon as it's complete

**Comment by nayakastha** [comment]
> @nayakastha There is a final conflict. I'll merge it as soon as it's complete

Done sir.

**Comment by palisadoes** [comment]
> > @nayakastha There is a final conflict. I'll merge it as soon as it's complete
> 
> Done sir.

@nayakastha The `lib/views/pages/newsfeed/news_article.dart` file has a conflict

**Comment by nayakastha** [comment]
@palisadoes  I hope it good to go. Before merging any other or, do merge this, since it varies across various files, it will create conflicts every time

**Pull request merged**
