### PR TITLE
Refactor MainScreen

### LINKED ISSUE #1470: Fix documentation in `lib/views/main_screen.dart`
**Describe the bug**
1. Our push workflow [Add tests for UserTasksPage (#1468)](https://github.com/PalisadoesFoundation/talawa/actions/runs/4116213093) is failing.
2. This is most likely due to recent changes to `lib/views/main_screen.dart`
3. This has probably never been noticed before as we have not been adding new features to the app since we implemented the documentation workflow.

**To Reproduce**

1. Push code to repo

**Expected behavior**
1. No error
2. A way to detect these types of errors as part of the PR process. Possibly adapting the `documentationcheck.py` script

**Actual behavior**
Error:

```
Run git branch
* develop
Defaulting to user installation because normal site-packages is not writeable
Collecting GitPython
  Downloading GitPython-3.1.30-py3-none-any.whl (184 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 184.0/184.0 KB 4.9 MB/s eta 0:00:00
Collecting gitdb<5,>=4.0.1
  Downloading gitdb-4.0.10-py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.7/62.7 KB 11.8 MB/s eta 0:00:00
Collecting smmap<6,>=3.0.1
  Downloading smmap-5.0.0-py3-none-any.whl (24 kB)
Installing collected packages: smmap, gitdb, GitPython
Successfully installed GitPython-3.1.30 gitdb-4.0.10 smmap-5.0.0
🔍 DOCUMENTATION NOT UPDATED: Files with missing or not updated documentation found
>>> File name: lib/views/main_screen.dart
	DocumentationStatus.not_updated

Error: Process completed with exit code 1.
```

**Screenshots**
image

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by literalEval**
**What kind of change does this PR introduce?**

Fully refactor `MainScreen`

**Issue Number:**

Fixes #1470 

**Did you add tests for your changes?**

Was not needed for this file.

**If relevant, did you update the documentation?**

Yes I did.

**Summary**

The file was poorly written, had test data in the widget itself and didn't follow MVVM.
This PR refactors `main_screen.dart` by
- Moving all the data to corresponding view model
- Renaming variables properly
- Properly following MVVM
- Replacing unnecessary widgets with better alternatives
- Conditional rendering instead of re-render on each frame

**Does this PR introduce a breaking change?**

No

**Other information**

Since a lot of stuff is moved, please check the PR properly.

### CODE REVIEW

**Comment by noman2002** [comment]
@literalEval Please attach a screenshot or video after the changes.

**Comment by literalEval** [comment]
UI before

Screenshot_20230213-001528

UI after

Screenshot_20230213-001533

**Comment by noman2002** [comment]
@literalEval The push workflow is still failing .
https://github.com/literalEval/talawa/actions/runs/4157497029/jobs/7192029696

**Comment by literalEval** [comment]
@noman2002 I am getting `gitdb.exc.BadName: Ref 'edit_main_screen' did not resolve to an object`. What does this mean and how am I supposed to fix this ?

**Comment by literalEval** [comment]
@noman2002 @palisadoes please check now.

**Comment by literalEval** [comment]
@palisadoes because nothing changed for the user. This PR only introduces refactoring of the files, removal of unnecessary data, renaming of variables, change in architecture and `KeyError` bug fix.

**Review by palisadoes — APPROVED** [review]

**Review by noman2002 — APPROVED** [review]

**Review by SiddheshKukade — COMMENTED** [review]
the file deletions are not helping to  solve #1470.

**Comment by SiddheshKukade** [comment]
@palisadoes  @noman2002 This PR was supposed to fix the workflow build failure issue. But @literalEval has delete  all the dummy data which was required to make the plugin architecture work without the store data. Due to that deletions, he has removed an important part of the plugin architecture which was created by me. These deletions can also cause some irregular behavior in the application in the future because the plugin list is refreshed continuously.

I would suggest @noman2002  @palisadoes  to revert these changes.
> the file deletions are not helping to solve #1470.

**Comment by literalEval** [comment]
@SiddheshKukade can you please read this PR's description once ?

**Comment by literalEval** [comment]
@palisadoes This PR was not solely to solve #1470. There are many other things too. Also, the only thing that should change according to @SiddheshKukade would be the default plugins, which can be done simply by commenting some lines, which I will do in a new PR. This does not need to be reverted. Please understand and revert your commit.

**Review by palisadoes — CHANGES_REQUESTED** [review]
@SiddheshKukade , @literalEval 

1. We need an approach you can both agree on. Please work on that in this thread.
1. It is clear that the in code documentation is insufficient as it doesn't explain the rational for the plugin data placeholders. That will need to be addressed to the code as part of this PR.

Let me know when this is resolved

**Comment by literalEval** [comment]
@palisadoes sure. I have asked some questions to @SiddheshKukade in the corresponding issue of this PR. Once he responds, I'll open a new PR.

**Comment by palisadoes** [comment]
If this PR cannot be fixed by the weekend we'll need to close it. Any refactoring needs to maintain functionality.

**Pull request merged**
