### PR TITLE
Add ignore directive for corresponding custom lint rules

### PR DESCRIPTION
**Pull request by literalEval**
**What kind of change does this PR introduce?**

Adds `// ignore` directive to all the `dart` files to suppress custom lint rules. 

**Issue Number:**

Part of: #1584 

**Summary**

We are adding ignore directives to files so that the custom lint rules are suppressed for now. For new PRs, the authors will need to remove these ignore directives and add documentation for respective files in the correct format.

**Does this PR introduce a breaking change?**

No

### CODE REVIEW

**Comment by literalEval** [comment]
@noman2002 @palisadoes please review and merge.

**Comment by palisadoes** [comment]
What I should have asked was, does this need to be merged now?

**Comment by literalEval** [comment]
Yeah sure @palisadoes
The script to check for ignore directives is almost ready. So I believe custom lint integration will be finished by tonight.

**Comment by palisadoes** [comment]
I'll wait for final comments from Tasneem and Anwer.

**Comment by literalEval** [comment]
@palisadoes I believe that mentor approval can be taken on the final PR when we activate the checking of custom lint rules. For now, this PR doesn't really do anything to the workflow, so can be merged.
Reason for saying this is because this PR is stopping other's PRs from getting merged. Thanks.

**Review by palisadoes — APPROVED** [review]

**Comment by palisadoes** [comment]
Though Anwer was involved with this from the beginning, I want a final review just before. I doubt there will be any concerns, but I want to err on the side of caution.

**Comment by literalEval** [comment]
Sure.

**Pull request merged**
