### PR TITLE
Fixes #1203 Fixed Deprecated ImageCropper API

### LINKED ISSUE #1203: Fix Deprecated ImageCropper API
**Describe the bug**
When building the `talawa` app we get an ImageCropper API warning message. This needs to be fixed

- Our test code coverage percentage will need to be improved or maintained as part of this fix.
- **DO NOT ATTEMPT to solve the issue by ignoring the error message in `build.gradle`** That is not a viable solution to this issue.

**To Reproduce**

1. Build the Talawa app
2. Monitor the console
3. See message below

**Expected behavior**
There should be no deprecation warning

**Actual behavior**
```
Note: /home/xxx/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/image_cropper-1.4.1/android/src/main/java/vn/hunghd/flutter/plugins/imagecropper/ImageCropperPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
```

**Screenshots**
N/A

**Additional details**
N/A

### PR DESCRIPTION
**Pull request by noman2002**
**What kind of change does this PR introduce?**
bugfix

**Issue Number:**

Fixes #1203 

**Did you add tests for your changes?**
Not required for these changes

**Snapshots/Videos:**
talawa

**Summary**
It fixes #1203 , which improves the code coverage.

**Does this PR introduce a breaking change?**
No, it doesn't introduce any breaking change.

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**
YES

### CODE REVIEW

**Comment by palisadoes** [comment]
Please fix the failing test(s)

**Comment by noman2002** [comment]
In my local machine, it is showing all tests passed but why it is falling here?


Screenshot from 2022-02-26 00-11-13

**Review by palisadoes — APPROVED** [review]

**Comment by palisadoes** [comment]
I re-ran the GitHub actions and they passed.

**Comment by noman2002** [comment]
> I re-ran the GitHub actions and they passed.

Okk. Thank you.

**Pull request merged**
