### PR TITLE
Fixes ##1665 Mutation joinPublicOrganization not complatible with tal…

### PR DESCRIPTION
**Pull request by Ayush0Chaudhary**
**What kind of change does this PR introduce?**
The signup didn't used to work, the talawa-api schema changed, so the app was running on deprecated schema, I upgraded the flow of request the app make in order to signup

**Issue Number:**

Fixes https://github.com/PalisadoesFoundation/talawa/issues/1665 

**Did you add tests for your changes?**
No yet

**Snapshots/Videos:**

https://user-images.githubusercontent.com/95746190/226221375-d3e7640e-4663-4347-b7b7-ed51f1f67f5d.mp4

**If relevant, did you update the documentation?**
no

**Summary**
User caan sign up now

**Does this PR introduce a breaking change?**
yes, maybe

**Other information**
I also changed the name of function talawaerrorwidget and talawaerrordialog as it indicated that they were meant to show error only

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**
yes

### CODE REVIEW

**Comment by Ayush0Chaudhary** [comment]
@palisadoes @noman2002 @CyberWake

**Comment by Ayush0Chaudhary** [comment]
Please don't merge it before the API PR is merged
@palisadoes

**Comment by Ayush0Chaudhary** [comment]
This is the PR.
https://github.com/PalisadoesFoundation/talawa-api/pull/1205

**Review by noman2002 — CHANGES_REQUESTED** [review]
Please fix the failing test.

**Comment by Ayush0Chaudhary** [comment]
@palisadoes @noman2002 No need of this PR. 
I changed the talawa-api accordingly to return what mobile needs.

Closing this PR (First time using github's Close with Comment)

**Pull request closed without merging**
