### PR TITLE
new unittests added - validate empty text fields, loading greeting images and unfocus text fields.

### LINKED ISSUE #1007: Unittests for login_view_model.dart
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

We will need unittests done for all methods, classes and functions found in this file.

Any widgets referenced in this file must also have unittests done

```
pre_auth_view_models/login_view_model.dart
```

This file can be found in the `lib/view_model` directory

Parent Issue: 
- https://github.com/PalisadoesFoundation/talawa/issues/1002

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base.
- [The current code coverage for the file can be found here](https://codecov.io/gh/PalisadoesFoundation/talawa/tree/develop/lib/view_model/pre_auth_view_models)
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide

### PR DESCRIPTION
**Pull request by chiragtyagi2003**
**What kind of change does this PR introduce?**

Unittests for pre_auth_view_models/login_view_model.dart

**Issue Number:**  

Fixes #1007

**Did you add tests for your changes?**

No, I added unittests for existing code.

**Snapshots/Videos:**

Not relevant

**If relevant, did you update the documentation?**

Not Relevant

**Summary**

The new unit tests are for validation of empty email and password text fields, correct loading of greetings image and also unfocusing of the text fields after login.

**Does this PR introduce a breaking change?**

No

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by Huy1996** [comment]
@chiragtyagi2003 Please fix the failing test.

**Comment by Cioppolo14** [comment]
@chiragtyagi2003 Please fix the failing tests.

**Comment by chiragtyagi2003** [comment]
@Cioppolo14 I believe there are some changes required in the code, as the log suggests issues found in finding ancestors widgets, due to which tests are failing.

**Comment by palisadoes** [comment]
This is an update on the PR merging freeze:

1. In the next few hours we will be merging the `develop-userTypeFix` branch into the `develop` branch. 
1. The `develop-userTypeFix` branch was created to fix a long standing design flaw where Admins were Admins of all organizations, not specific ones.
1. The `userType` field has been removed from the User collection and it has been replaced by an `appUserProfileId` field.
    1. This field is `null` if the user isn’t registered to use the apps. This will help people to add users manually during the event checkin process, or if an Admin wants to manually add someone in the Admin dashboard.
    1. When not `null` the `AppUserProfileID` will reference a `AppUserProfile` collection with App related information such as the organizations for which a user may be an Admin.
    1. The updated schema can be found here https://github.com/PalisadoesFoundation/talawa-api/blob/develop-userTypeFix/schema.graphql
    1. This is the parent issue that we have been using to track progress:
        1. https://github.com/PalisadoesFoundation/talawa-api/issues/1965
1. This merge will cause some conflicts in your PR.

We decided to do this at the beginning of the weekend to give us all time to adjust PR code and create bug fixes that may arise.

Update your code at or after midnight GMT on the morning of March 23, 2024. (5:30am IST). 

If your PRs have already been approved, request a re-review after fixing the conflicts and refactoring to the new `AppUserProfileID` methodology.

**Comment by Cioppolo14** [comment]
@chiragtyagi2003 Please fix the failing tests.

**Comment by palisadoes** [comment]
Closing as stale. We can reopen it if you'd like

**Pull request closed without merging**
