### PR TITLE
Feat:Add logs

### PR DESCRIPTION
**Pull request by StrangeNoob**
**What kind of change does this PR introduce?**
 A feature that logs the exception and crashes in the App. 

**Did you add tests for your changes?**
No.
**If relevant, did you update the documentation?**
No. But in the near future, going to do this. As it will be required to implement in many more places.
**Summary** 
- Adds a helper class i.e. LogHelper in utilities folder.
- Adds a function to send the logs to backend using Multiparter. As the url is not defined, I have commented the block.

**Motivation**
In the past week, we found the app crashing and in order to debug it, we have to plug in our devices. If we have implement logs, It would be easy to know where the error is and is it fixable through backend. That made me think about this issue.

**Does this PR introduce a breaking change?**
Nope.
**Snapshots/video**
To view the video, click [here](https://drive.google.com/file/d/1DM7a7IMPE1mDm1Pk6IXQn21ZGJtxaDwK/view?usp=sharing)

**Other information**
It uses the flutter_log and path_provider plugin to do their respective jobs. Need to add background_fetch or cron to automate this process.

Issue Number : https://github.com/PalisadoesFoundation/talawa/issues/427 #675

### CODE REVIEW

**Comment by StrangeNoob** [comment]
@Sagar2366 can you have look on this?

**Comment by Sagar2366** [comment]
@StrangeNoob keeping this on hold because of code freeze.
But good addition to our project, really appreciate your work in this PR.

**Comment by Sagar2366** [comment]
@StrangeNoob resolve conflicts on your PR.

**Comment by StrangeNoob** [comment]
Sure @Sagar2366

**Comment by yasharth291** [comment]
@pr4nshul it would be great you can mention my issue in this pr to get it closed #675

**Comment by StrangeNoob** [comment]
Sure @yasharth291

**Comment by StrangeNoob** [comment]
@Sagar2366 I have pulled the changes and resolved the conflicts

**Comment by palisadoes** [comment]
Please fix merge conflicts. The code freeze has been lifted.

**Comment by StrangeNoob** [comment]
@palisadoes I have merged with current master, you can merge it now.

**Comment by palisadoes** [comment]
@StrangeNoob Please close the related issues: #427 #675

**Pull request merged**
