### PR TITLE
Implement scrolling functionality for the Event Details page #1601

### PR DESCRIPTION
**Pull request by aboutaditya**
- [x] - see all option removed.

- [x] - Members is scrollable

### CODE REVIEW

**Comment by palisadoes** [comment]
Please add tests for this functionality

**Comment by palisadoes** [comment]
Please fix the failing tests

**Comment by aboutaditya** [comment]
added the test for the functionality.

**Comment by CyberWake** [comment]
@aboutaditya please resolve the conflicts before hand so we could review the PR.

**Comment by TheHazeEffect** [comment]
hey @aboutaditya , Could you follow the [PR Template](https://github.com/PalisadoesFoundation/talawa/blob/master/.github/PR_TEMPLATE/pr-template.md), here's an example PR[this PR ](https://github.com/PalisadoesFoundation/talawa/pull/1616)

**Comment by aboutaditya** [comment]
Sorry, i do not understand what am i suppose to do?

**Comment by palisadoes** [comment]
Please fill in the PR template completely. Open another PR, copy and paste the template into the first comment and fill it in correctly. There is no reference issue for example.

We try to have complete documentation for both pull requests and PRs as they greatly help with our process. 

I'm going to close this PR

**Comment by palisadoes** [comment]
Please submit another PR when you have followed the procedure. It really helps everyone.

**Pull request closed without merging**
