### PR TITLE
Removed MyTasks button and navigated the userTasks page to Tasks tab.

### LINKED ISSUE #2198: Profile Settings: `My Tasks` option is duplicated should be removed
**Describe the bug**
- Please work with @Ayush0Chaudhary for comments, advice and review of your PR.

App Setting option doesn't work and should be removed

**To Reproduce**

1. Start app
2. Click on Profile
3. Click on the cog wheel icon
4. A drawer appears with a `My Tasks` option. 

**Expected behavior**
- No `My Tasks` option
- All tasks should be visible on the tasks tab of the profile without doing this extra step
- All modified files must be 100% covered by tests

**Actual behavior**
- `My Tasks` option appears.

**Screenshots**
- https://youtu.be/86AzK_Y_GCQ?t=585

**Additional details**
- You must get the test **_code coverage up to 100%_** for any edited files.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by ShubhamTiwari55**
**What kind of change does this PR introduce?**

Bug fix - Removed duplicated MyTasks button and implemented its feature in Tasks tab

**Issue Number:**

Fixes #2198 

**Did you add tests for your changes?**
No

**If relevant, did you update the documentation?**

No

**Summary**

Removed MyTasks button and implemented its feature in Tasks tab

**Does this PR introduce a breaking change?**

No

### CODE REVIEW

**Comment by noman2002** [comment]
@ShubhamTiwari55 Please attach a video/screenshot.

**Comment by ShubhamTiwari55** [comment]
> @ShubhamTiwari55 Please attach a video/screenshot.

These are the screenshots related to changes - 
WhatsApp Image 2023-12-05 at 00 07 05_f3e631e6
![WhatsApp Image 2023-12-05 at 00 10 32_0cdb9098
](https://github.com/PalisadoesFoundation/talawa/assets/125534462/c8e66d3c-306d-4cc4-b153-55c772c7872a)

**Review by Ayush0Chaudhary — COMMENTED** [review]
why changed files are 0?

**Comment by ShubhamTiwari55** [comment]
> why changed files are 0?



> why changed files are 0?

I think I have made a mistake while taking screenshot, probably in some git commands. I will fix them in an hour. Sorry for the inconvenience

**Pull request merged**
