### PR TITLE
Removed Unused RazorPay Support

### PR DESCRIPTION
**Pull request by ayushvrma**
Fixes issue #1206.

### CODE REVIEW

**Comment by ayushvrma** [comment]
I'm open to reviews and will act upon them asap. Just let me know!

**Comment by palisadoes** [comment]
Please fix the failing tests

**Comment by ayushvrma** [comment]
> Please fix the failing tests

@palisadoes okay, on it.

**Comment by palisadoes** [comment]
Are you still working on this?

**Comment by ayushvrma** [comment]
@palisadoes yes i am, sorry for taking so long, figuring out the tests

**Comment by palisadoes** [comment]
Please fix the failing linting tests. Run the following command to understand where the issues are:

`flutter format --set-exit-if-changed . `

**Pull request closed without merging**
