### PR TITLE
Fixes: #1145 Added password validation criteria in all languages supported

### LINKED ISSUE #1145: Password validator only shows invalid password on signup screen
**Describe the bug**
Password validator on signup detail page only show invalid password in every condition.
Example: when the password is too short, when the password doesn't have Capital letters, when the password doesn't have special character.

**To Reproduce**

1. Select Language
2. Verify org url
3. Click on signup
4. Select Organization and click next
5. Enter password and see the unexpected behavior.

**Expected behavior**
It should show "password is too short" when the length of password is short.
It should show "password doesn't contain special character" when a special character is not there.
It should show "password doesn't contain at least one capital/small letter" when it is not there is password.

**Actual behavior**
It only shows "invalid password" for every case.

**Screenshots**

**Additional details**
I am working on this issue please assign it to me.

### PR DESCRIPTION
**Pull request by noman2002**
**What kind of change does this PR introduce?**
Added password validation criteria for signup page in all supported languages.

**Issue Number:**

Fixes #1145 

**Did you add tests for your changes?**
No. I am waiting for one other PR to be merged then I will write the tests.

**Snapshots/Videos:**
   

**Summary**

Earlier it was just showing invalid password for all cases and doesn't state the desired password criteria. Now I have added the password criteria and added translation in all supported languages by the app.
Issues resolved by merging this PR is #1145 .

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by noman2002** [comment]
Do I have to fix this failing check or I have to wait for the reviewers to review the code.

**Review by sumitra19jha — APPROVED** [review]

**Comment by palisadoes** [comment]
@noman2002 Tests are failing. Please fix. It's not due to the code coverage percentage, there is something else.

**Comment by noman2002** [comment]
@palisadoes I have checked the tests they are not failing because of my changes there is something else. It is showing on set_url_page_test and waiting_page_test.

**Comment by guptapriyanshu7** [comment]
Those two test are failing, from the develop branch itself, a new issue could be opened to make them pass.

**Comment by palisadoes** [comment]
No new issue needs to be created. The failure is caused by this PR modifying code and the tests that tested the old version of the code are failing. New tests for this update need to be created as part of this PR.

**Comment by noman2002** [comment]
@palisadoes I am trying to fix it. Can you please guide me a little bit. It will be a great help.

**Comment by noman2002** [comment]
@palisadoes Now the test is failing due to code coverage. Can this be merged now?

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
