### PR TITLE
edited splash_screen_test

### PR DESCRIPTION
**Pull request by Sandesh-03**
What kind of change does this PR introduce?

Unit Test

Issue Number:

Fixes https://github.com/PalisadoesFoundation/talawa/issues/2145

Did you add tests for your changes?

Yes

Snapshots/Videos:

If relevant, did you update the documentation?

Summary

I have solved the issues that were mentioned.

Does this PR introduce a breaking change?

No

Other information

Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?

Yes

### CODE REVIEW

**Comment by Cioppolo14** [comment]
@Sandesh-03 Please fix the failing tests.

**Comment by Cioppolo14** [comment]
@Sandesh-03 Are you working on this?

**Comment by Sandesh-03** [comment]
@Cioppolo14 yes

**Comment by Cioppolo14** [comment]
@Sandesh-03 Please tell me when this PR will be ready.

**Comment by Azad99-9** [comment]
@Sandesh-03 are you facing any issue, need any help?

**Comment by Sandesh-03** [comment]
> @Sandesh-03 are you facing any issue, need any help?

Yeh. The test is running fine on my pc I have also tried the command which failed during review, can you help me with this?

**Comment by Azad99-9** [comment]
The reason for failing tests is, your code is not properly formatted.

use this procedure before raising any PR to talawa:
1. run` dart analyze`, fix all the issues that will be shown there.
2. run` dart format . `.
3. run `flutter test --coverage`, fix any failing tests.

**Comment by Sandesh-03** [comment]
@Azad99-9 
Thanks for your help.

**Pull request closed without merging**
