### PR TITLE
Pagination addition for organisation

### LINKED ISSUE #168: Adding Pagination in Join Organization Page
By adding the pagination we can reduce the screen loading time.

### PR DESCRIPTION
**Pull request by sumitra19jha**
**What kind of change does this PR introduce?**
Closes #168 

**Did you add tests for your changes?**
Not required

**If relevant, did you update the documentation?**
Not required

**Summary**
Pagination will help to fetch data fast even when database will scale to lots and lots of organisation data

**Does this PR introduce a breaking change?**
No

**Other information**

https://user-images.githubusercontent.com/35868598/116004580-03093a00-a621-11eb-8d92-ecfb55ae1546.mp4

### CODE REVIEW

**Comment by Sagar2366** [comment]
Looks like you are merging changes from all previous merged PR's, remove all other changes and keep only changes to fix this issue.

**Comment by sumitra19jha** [comment]
It's targeted to develop branch as its kind of new feature.
Develop branch is lagging behind master. @Sagar2366

**Comment by sumitra19jha** [comment]
Should I make PR to master branch ? @Sagar2366

**Comment by Sagar2366** [comment]
> Should I target PR to master branch ? @Sagar2366

@sumitra19jha take latest develop branch, it is stable now.

**Comment by sumitra19jha** [comment]
Sure

**Comment by sumitra19jha** [comment]
@Sagar2366 @palisadoes Please review this and give your feedback on the changes
Apart from Pagination, I also added filter capabilities.

Also I can work on fixing this Count line PR error, but the issue will come under code refactor which is already been worked on.

https://user-images.githubusercontent.com/35868598/116256047-767d8980-a790-11eb-96a5-d3ce803d9c08.mp4

**Comment by Sagar2366** [comment]
> @Sagar2366 @palisadoes Please review this and give your feedback on the changes
> Apart from Pagination, I also added filter capabilities.
> 
> Also I can work on fixing this Count line PR error, but the issue will come under code refactor which is already been worked on.
> 
>  whatsapp-video-2021-04-27-at-73056-pm_Nx1dZH1q.mp4

@sumitra19jha filter capability is good feature to add. Can you open new issue and PR for the same ?

**Comment by sumitra19jha** [comment]
> > @Sagar2366 @palisadoes Please review this and give your feedback on the changes
> > Apart from Pagination, I also added filter capabilities.
> > Also I can work on fixing this Count line PR error, but the issue will come under code refactor which is already been worked on.
> > whatsapp-video-2021-04-27-at-73056-pm_Nx1dZH1q.mp4
> 
> @sumitra19jha filter capability is good feature to add. Can you open new issue and PR for the same ?

Sure

**Review by DeltaHarbinger — COMMENTED** [review]
Hey @sumitra19jha, it seems like there are a few files in your PR with similar code such as lib/views/pages/organization/Join-Organization-Widgets/org_body.dart and lib/views/pages/organization/Join-Organization-Widgets/org_search.dart. Is it mandator that these be separate files, or can reusable components be created to reduce the code duplication?

**Comment by sumitra19jha** [comment]
@DeltaHarbinger I have broken down the reusable component by creating `lib/views/pages/organization/Join-Organization-Widgets/org_tile.dart` which will be used to display the individual organisation with there joining actions.

But I can create a separate pagination widget to avoid that code duplication.

**Comment by sumitra19jha** [comment]
@DeltaHarbinger I made the required changes by shifting org-search file code into body and creating separate pagination widget.

**Review by DeltaHarbinger — APPROVED** [review]
Hey @sumitra19jha, it seems like there are a few files in your PR with similar code such as lib/views/pages/organization/Join-Organization-Widgets/org_body.dart and lib/views/pages/organization/Join-Organization-Widgets/org_search.dart. Is it mandator that these be separate files, or can reusable components be created to reduce the code duplication?

**Comment by sumitra19jha** [comment]
@Sagar2366 @palisadoes @DeltaHarbinger @dellyjm 
I would love to hear your feedback on the changes, Should we add or remove something?
If the changes look good, then should we consider using this?

**Pull request merged**
