### PR TITLE
[Fix] Members page should show data specific to the newly created organization. 

### LINKED ISSUE #664: Members page should show data specific to the newly created organization.
- **Issue Description:** Members page should show data specific to the newly created organization. Refer #537 
- **Issue Severity:** Medium
- **Environment Details:** Found in `talawa\lib\views\pages\members\members.dart`
- **Observed Behaviour:** Currently previous organization's data is getting loaded even for newly created organizations.
- **Expected Behaviour:** It should show data specific to the newly created organization.
- **Steps to reproduce issue:** Create an organization and switch to the members tab.
- **Does this issue need immediate attention?** Yes
- **Are you willing to work on this issue:** Yes, I am willing to work on this issue!

### PR DESCRIPTION
**Pull request by Raunakk02**
**What kind of change does this PR introduce?**
Fixes members page to show data specific to the newly created organization.

**Did you add tests for your changes?**
Yes

**If relevant, did you update the documentation?**
No

**Summary**
Fixes #664 

**Does this PR introduce a breaking change?**
No

### CODE REVIEW

**Comment by palisadoes** [comment]
Please correct your code to pass our package analysis test. This needs to be resolved before we can review.

**Comment by Raunakk02** [comment]
> Please correct your code to pass our package analysis test. This needs to be resolved before we can review.

I have fixed the code now @palisadoes.

**Comment by Sagar2366** [comment]
@Raunakk02 try this scenario and add video visuals to verify :
1. Signup to app
2. Create new organisation
3. Go to members page, it should show one user (creator/admin)

**Comment by Raunakk02** [comment]
Here are the visuals for the scenario mentioned by you @Sagar2366 sir.

https://user-images.githubusercontent.com/56073198/115989970-90776a80-a5de-11eb-90cf-d82cf3f2e875.mp4

**Comment by Sagar2366** [comment]
@Raunakk02 resolve conflicts on this PR.

**Comment by Raunakk02** [comment]
@Sagar2366 sir, I have resolved the conflicts.

**Review by Sagar2366 — APPROVED** [review]

**Pull request merged**
