### PR TITLE
[Fix] Newsfeed should be blank for newly created organizations

### LINKED ISSUE #663: Newsfeed should be blank for newly created organizations
- **Issue Description:** Newsfeed should be blank for newly created organizations. Refer #537 
- **Issue Severity:** Medium
- **Environment Details:** Found in `talawa\lib\views\pages\newsfeed\newsfeed.dart`
- **Observed Behaviour:** Currently default data is getting loaded for newly created organizations.
- **Expected Behaviour:** It should be blank for newly created organizations
- **Steps to reproduce issue:** Create an organization and switch to the newsfeed tab.
- **Does this issue need immediate attention?** Yes
- **Are you willing to work on this issue:** Yes, I am willing to work on this issue!

### PR DESCRIPTION
**Pull request by Raunakk02**
**What kind of change does this PR introduce?**
Fixes newsfeed to be empty for newly created organization.

**Did you add tests for your changes?**
Yes

**If relevant, did you update the documentation?**
No

**Summary**
Fixes #663 

**Does this PR introduce a breaking change?**
No

### CODE REVIEW

**Comment by CyberWake** [comment]
@Raunakk02 can you please rebase your forked repo the loading widget is missing and this would remove other's work and will need to revert the changes back.

**Comment by Raunakk02** [comment]
> @Raunakk02 can you please rebase your forked repo the loading widget is missing and this would remove other's work and will need to revert the changes back.

Can you please specify where is it missing? If you are talking specifically about the newsfeed page then, it has been deliberately replaced on the newsfeed as a general user will need to know that the newsfeed is empty and also provide him/her the option to refresh the feed manually if it's empty, which was not possible with that loading widget.

**Comment by CyberWake** [comment]
It is possible with the widget itself just pass the refresh function to the widget and have modification in it similarly. That would be helpful in both the use case.

**Comment by Raunakk02** [comment]
> It is possible with the widget itself just pass the refresh function to the widget and have modification in it similarly. That would be helpful in both the use case.

The changes made by me are specifically for the newsfeed page like the text that will be shown in the newsfeed if it is empty. Also showing the loading widget does not specifically tells the user that the posts are empty and it's not any kind of error.

**Comment by palisadoes** [comment]
Please fix merge conflicts. The code freeze has been lifted.

**Comment by palisadoes** [comment]
Please fix merge conflicts. 

1. We have completely re-linted the master branch. 
1. We now have automated linting testing added to pull requests
1. We also have added Google's pendantic package to pubspec.yaml

For best results, I'll close this PR and you'll need to reopen a new bug against the master branch. 

1. The automated linting will be enabled for your work
1. We'll have better code consistency.

The code freeze has been lifted.

**Pull request closed without merging**
