### PR TITLE
custom_drawer_view_model_test is added

### LINKED ISSUE #1021: Unittests for custom_drawer_view_model.dart
The Talawa code base needs to be 100% reliable. This means we need to have 100% unittest code coverage.

We will need unittests done for all methods, classes and functions found in this file.

Any widgets referenced in this file must also have unittests done

```
widgets_view_models/custom_drawer_view_model.dart
```

This file can be found in the `lib/view_model` directory

Parent Issue: 
- https://github.com/PalisadoesFoundation/talawa/issues/1018
### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base.
- [The current code coverage for the file can be found here](https://codecov.io/gh/PalisadoesFoundation/talawa/tree/develop/lib/view_model/widgets_view_models)
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide

### PR DESCRIPTION
**Pull request by nishnatadebnath**
**What kind of change does this PR introduce?**

 Unit testing of custom_drawer_view_model 

**Issue Number:**

Fixes  #1021 

**Did you add tests for your changes?**

Yes
**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**

Updated the custom_drawer_view_model to change selectedorg to switchedOrg after switching of org takes place

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by nishnatadebnath** [comment]
@palisadoes  @sumitra19jha @CyberWake  please merge.

**Comment by palisadoes** [comment]
@nishnatadebnath  the code base has been updated since you created this PR. Please merge your code with `upstream/develop` and push to your repo. This PR will be automatically automated.

**Comment by palisadoes** [comment]
@nishnatadebnath  Please fix the conflicting file.

**Comment by nishnatadebnath** [comment]
There is some issue with the testing build for ios as all the PR are failing.

**Comment by nishnatadebnath** [comment]
Clossing this pull request because I made some error while merging conflicts.

**Pull request closed without merging**
