### PR TITLE
[Fix] Members page should show data specific to the newly created organization.

### LINKED ISSUE #664: Members page should show data specific to the newly created organization.
- **Issue Description:** Members page should show data specific to the newly created organization. Refer #537 
- **Issue Severity:** Medium
- **Environment Details:** Found in `talawa\lib\views\pages\members\members.dart`
- **Observed Behaviour:** Currently previous organization's data is getting loaded even for newly created organizations.
- **Expected Behaviour:** It should show data specific to the newly created organization.
- **Steps to reproduce issue:** Create an organization and switch to the members tab.
- **Does this issue need immediate attention?** Yes
- **Are you willing to work on this issue:** Yes, I am willing to work on this issue!

### PR DESCRIPTION
**Pull request by Raunakk02**
**What kind of change does this PR introduce?**
Fixes members page to show data specific to the newly created organization.

**Did you add tests for your changes?**
Yes

**If relevant, did you update the documentation?**
No

**Summary**
Fixes #664 

**Does this PR introduce a breaking change?**
No

### CODE REVIEW

**Comment by CyberWake** [comment]
@Raunakk02 changes made wont refresh the page automatically on creation of new organization and  please refer #514 for the same with PR #607  because this issue is already resolved no matter you create new organization or switch to another the member list will be shown of the current organization.

**Comment by Raunakk02** [comment]
> @Raunakk02 changes made wont refresh the page automatically on creation of new organization and please refer #514 for the same with PR #607 because this issue is already resolved no matter you create new organization or switch to another the member list will be shown of the current organization.

Hey, @CyberWake, I had a look at the PR you created and noticed that you have even fixed things that were not mentioned in the issue you stated. I previously solved these issues within PR #591, but Sagar sir told me to make separate small PRs for the same. So I guess the PR you submitted needs some reviews for the same reason. Secondly, my PR introduces fixes related to the creation of the new organization and it does refresh the members' list when we switch to the newly created organization.

**Comment by CyberWake** [comment]
Can you please state what will happen in member page when new organization is created.

**Comment by CyberWake** [comment]
Current feature implement and the use case marked over here.


https://user-images.githubusercontent.com/44184786/114996338-5c07fe00-9ebc-11eb-9c2e-95ea80b02621.MP4

Please update me on the changes made to same.

**Comment by Raunakk02** [comment]
This is the change introduced by my PR.

https://user-images.githubusercontent.com/56073198/115013771-19035600-9ecf-11eb-97e9-10cef8e48115.mp4

**Comment by CyberWake** [comment]
Clip shared by is the same as mine.

**Comment by CyberWake** [comment]
And I guess there is no point to to refresh the page this way as already there was a issue related to this update.
As well as I already had discussion on that thread.

**Comment by Raunakk02** [comment]
> Clip shared by is the same as mine.

@CyberWake, Please have a close look at the clip uploaded by me after 0:30 mins. In my case, I don't need to manually refresh the screen to fetch the new org members( which includes only me), the data is automatically being loaded for the new organization, whereas in your clip you are refreshing the screen to load new data. So the clips are not the same at all.

**Comment by Raunakk02** [comment]
> And I guess there is no point to to refresh the page this way as already there was a issue related to this update.
> As well as I already had discussion on that thread.

I would request you to please have a detailed look at the clip I shared and then arrive at the conclusions.

**Comment by CyberWake** [comment]
> > And I guess there is no point to to refresh the page this way as already there was a issue related to this update.
> > As well as I already had discussion on that thread.
> 
> I would request you to please have a detailed look at the clip I shared and then arrive at the conclusions.

My point is there was already a issue for the same #514 which was assigned to me and it already has a PR.
Creating another PR for the same is not needed I guess.

**Comment by CyberWake** [comment]
Issue #667 part of issue #537 was created after issue #514 and was already assigned to me. And it already had a PR for the same issue then there is no need to have this PR.

**Comment by Raunakk02** [comment]
> Issue #667 part of issue #537 was created after issue #514 and was already assigned to me. And it already had a PR for the same issue then there is no need to have this PR.

As I already mentioned I had worked on these changes previously in PR #537, which Sagar sir told me to break down into smaller PRs for each screen. This PR is just a breakdown of my previous work. So I guess let's wait for your PR to be merged and if it fixes the issue then surely I'll close this PR as it would not be needed after that. Is that fine?

**Comment by CyberWake** [comment]
Can you please look into the conversation thread of #537 I guess we already discussed the thing over there for the members page.

**Comment by CyberWake** [comment]
As well as the data was not auto updating which already had a issue opened for the same #514 so replicating the work is not required I guess.

**Comment by palisadoes** [comment]
Please fix merge conflicts. The code freeze has been lifted.

**Comment by palisadoes** [comment]
Please fix merge conflicts. 

1. We have completely re-linted the master branch. 
1. We now have automated linting testing added to pull requests
1. We also have added Google's pendantic package to pubspec.yaml

For best results, I'll close this PR and you'll need to reopen a new bug against the master branch. 

1. The automated linting will be enabled for your work
1. We'll have better code consistency.

The code freeze has been lifted.

**Pull request closed without merging**
