### PR TITLE
Resolved the deprecated Flatbutton and raised button issue.

### PR DESCRIPTION
**Pull request by i-anuragmishra**
**What kind of change does this PR introduce?**
Flat button and Raised button were Deprecated in new flutter version so they are migrated to Elevated button and Text button respectively.
Issue Number : https://github.com/PalisadoesFoundation/talawa/issues/219

Refactoring and Migration from Deprecated code
**Summary**
Flat button and Raised Button are Migrated to the Elevated and Text Buttons , Since they were deprecated by Flutter.
**Migration of code from Deprecated version** 
Flat button and Raised button were Deprecated in new flutter version so they are migrated to Elevated button and Text button respectively.

### CODE REVIEW

**Comment by yasharth291** [comment]
could you please attach the issue related to this pr .

So the issue can automatically closed.

**Comment by yasharth291** [comment]
could you please attach the issue related to this pr .

So the issue can automatically closed.

**Comment by i-anuragmishra** [comment]
> could you please attach the issue related to this pr .
> 
> So the issue can automatically closed.
> 
> @i-anuragmishra

i have already closed that.

**Comment by Sagar2366** [comment]
@i-anuragmishra please reopen the issue and provide details on this issue - observation, expected behaviour, environment details and fixed you added.

**Comment by jordanliu** [comment]
@i-anuragmishra resolve merge conflicts

**Comment by i-anuragmishra** [comment]
> @i-anuragmishra resolve merge conflicts

Okay @jordanliu will do.

**Comment by i-anuragmishra** [comment]
Hey @jordanliu  sorry for the delay. Merge conflict has been resolved. i request you to Please review and Merge.

**Comment by Sagar2366** [comment]
@i-anuragmishra have you created issue for this PR ? If no, please create he issue and add in PR description.

**Comment by i-anuragmishra** [comment]
> @i-anuragmishra have you created issue for this PR ? If no, please create he issue and add in PR description.

Yes I did create an issue  #219 for this PR. and i closed it when i created this PR. If u want i can reopen it.

**Pull request closed without merging**
