### PR TITLE
Tests: Added  Widget Test for addPost.dart

### PR DESCRIPTION
**Pull request by utkarshshendge**
**What kind of change does this PR introduce?**
I have added widget tests for `addPost.dart`

**Did you add tests for your changes?**
Yes.

**Does this PR introduce a breaking change?**
No

**Other information**
As per issue #326 this PR will help to enhance testing of the app.

### CODE REVIEW

**Comment by Sagar2366** [comment]
@utkarshshendge resolve merge conflicts on this PR.

**Comment by utkarshshendge** [comment]
@Sagar2366  Sir, Looks like someone recently added tests for the same file.
Closing this PR.

**Comment by utkarshshendge** [comment]
@CyberWake Please consider updating the thread on issue #326 if you are planning to add tests.

**Comment by CyberWake** [comment]
> @CyberWake Please consider updating the thread on issue #326 if you are planning to add tests.

Sure @utkarshshendge

**Pull request closed without merging**
