### PR TITLE
Bug/no validation and confirmation on comments 

### LINKED ISSUE #2277: No validation and confirmation on comments.
**Describe the bug**
Users are able to comment blank texts.

**To Reproduce**

1. Enter the comments view.
2. Without typing anything, hit 'send'.

**Expected behavior**
1. Should not allow sending the comment if the comment is empty.
2. Should provide confirmation once comment is successfully uploaded.

**Actual behavior**
Clicking 'send' is calling the API with empty comment message and adding the blank comment locally.
After an error is received from the backend, the comment disappears.
This leads to a poor user experience.

Can I work on this issue?

### PR DESCRIPTION
**Pull request by bhoomikshetty**
**What kind of change does this PR introduce?**
Bugfix

**Issue Number:**

Fixes #2277 

**Did you add tests for your changes?**
No

**Snapshots/Videos:**

https://github.com/PalisadoesFoundation/talawa/assets/76581406/7ee6ce8e-d82b-40fa-86b7-8e64955a83af

**Summary**

1. Disallowed empty comment message.
2. Confirmation after successful comment.

**Does this PR introduce a breaking change?**
No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by Ayush0Chaudhary** [comment]
fix the test

**Comment by SiddheshKukade** [comment]
Looks good

**Review by SiddheshKukade — DISMISSED** [review]

**Comment by SiddheshKukade** [comment]
Complete the failing tests

**Review by Kevoniat — APPROVED** [review]

**Comment by palisadoes** [comment]
Please fix the failing tests

**Comment by noman2002** [comment]
@bhoomikshetty Please fix the conflicting files.

**Comment by palisadoes** [comment]
@bhoomikshetty You need to write tests for this to fix the failing GitHub action workflow

**Comment by bhoomikshetty** [comment]
> @bhoomikshetty You need to write tests for this to fix the failing GitHub action workflow

Yes, I'm working on it.

**Comment by palisadoes** [comment]
@SiddheshKukade @Kevoniat @Ayush0Chaudhary @literalEval please review. It's been almost 2 weeks

**Comment by literalEval** [comment]
Codecov reports missing tests. @bhoomikshetty please add missing tests.

**Comment by noman2002** [comment]
@bhoomikshetty Any update on this PR ?

**Comment by noman2002** [comment]
@bhoomikshetty Closing due to inactivity.

**Pull request closed without merging**
