### PR TITLE
Deprecate Google Maps Integration

### LINKED ISSUE #2256: Remove references to Google Maps
**Is your feature request related to a problem? Please describe.**

We need to make Talawa independent of cloud service providers because:
1. many of their services are becoming paid
1. they require us to hard code access information in the app that would require the Palisadoes Foundation to pay for the usage of those services by all Talawa users
1. It makes setting up Talawa more difficult
1. the packages get frequently updated taxing our ability to integrate these modifications smoothly in the codebase 

We foresee that most organizations will be small and its members will know where the most commonly used venues are.

**Describe the solution you'd like**

We need to remove all references to Google Maps in the codebase while:
1. maintaining all non Maps functionality. (For example Google Maps is used in creating events. Events must still be created, the option to add location coordinates and any related map overlays must be removed) However there must be an alternative way for people to know where the venue is, such as a text field that may or may not be present in the API.
1. making all remaining features usable
1. removing all references to Google Maps in package management and configuration files

**Describe alternatives you've considered**

- N/A

**Approach to be followed (optional)**
- Also coordinate with @noman2002 and @Ayush0Chaudhary 

**Additional context**
- N/A

**Potential internship candidates**

1. Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359
2. **NOTE:** I’ve stopped assigning people to issues due to the workload, no exceptions. Please watch this video on how to proceed.

[Click me to start video](https://www.youtube.com/watch?v=GlqUm1UO-xM)

### PR DESCRIPTION
**Pull request by Dante291**
**What kind of change does this PR introduce?**

Removes Google Maps support in the App.

**Issue Number:**

Fixes #2256 

**Did you add tests for your changes?**

Yes

**Does this PR introduce a breaking change?**

No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by Dante291** [comment]
@palisadoes @Cioppolo14 this PR removes Google Maps support from the App, when this [PR](https://github.com/PalisadoesFoundation/talawa-api/pull/1763) from the backend side will be merged then I could work on adding support for venues for events in front side too.

**Comment by Dante291** [comment]
@palisadoes please assign reviewers for this

**Comment by Ayush0Chaudhary** [comment]
@Dante291 can you provide a screen rec of you creating an event.

**Comment by Dante291** [comment]
> @Dante291 can you provide a screen rec of you creating an event.

@Ayush0Chaudhary 


https://github.com/PalisadoesFoundation/talawa/assets/103507835/b0a57e82-8d92-476a-9776-1f78071a1abe

**Review by Ayush0Chaudhary — APPROVED** [review]

**Pull request merged**
