### PR TITLE
Fixes #1396 Test for lib/widgets/task_schedule.dart

### LINKED ISSUE #1396: Test: lib/widgets/task_schedule.dart
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

We will need unittests done for all methods, classes and functions found in this file.

Any widgets referenced in this file must also have unittests done

```
organization_list.dart 
```

This file can be found in the `lib/widgets` directory

Parent Issue: 
- https://github.com/PalisadoesFoundation/talawa/issues/1125

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base.
- [The current code coverage for the file can be found here](https://codecov.io/gh/PalisadoesFoundation/talawa/tree/develop/lib/widgets)
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide

### PR DESCRIPTION
**Pull request by Ayush0Chaudhary**
**What kind of change does this PR introduce?**
Contains Test for lib/widgets/task_schedule.dart

**Issue Number:**

Fixes #1396

**Did you add tests for your changes?**
YES

**Does this PR introduce a breaking change?**
NO

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**
YES

### CODE REVIEW

**Comment by Ayush0Chaudhary** [comment]
@noman2002 @palisadoes @TheHazeEffect please review the PR!

**Review by noman2002 — APPROVED** [review]

**Comment by palisadoes** [comment]
Merging will have to be delayed for an expected PR for upgrading Talawa to the latest Flutter version. This is expected over the weekend.

**Comment by Ayush0Chaudhary** [comment]
Ok @palisadoes, upgrading flutter will make dev exp for talawa smoother

**Review by palisadoes — APPROVED** [review]

**Comment by literalEval** [comment]
@Ayush0Chaudhary SDK bump introduces some new lint rules, one of them being `require_trailing_commas`. Files added in this and another one of your last merged PRs now have this lint warning after bump. Can you please add trailing commas and push again ? Because either someone else's PR will fail because of this or they will have to do this change themselves.

@palisadoes views ?

**Comment by palisadoes** [comment]
1. I noticed the push checks failed, which was expected. There is no need to revert.
1. The next submitted PR will fail and therefore that person will need to do the updates.

**Comment by literalEval** [comment]
Understood.

**Pull request merged**
