### PR TITLE
String refactoring

### LINKED ISSUE #800: Refactor Hard Coded strings
**Is your feature request related to a problem? Please describe.**
This is a child issue of #798

**Describe the solution you'd like**
1. Refactor all widgets in the Talawa app which have hardcoded strings.
2. Update the Talawa GitHub action workflow to automatically reject any hard coded strings outside of the language translation files.

### PR DESCRIPTION
**Pull request by sumitra19jha**
**What kind of change does this PR introduce?**
Closes #800 

**Did you add tests for your changes?**
No

**If relevant, did you update the documentation?**
No
**Summary**

**Does this PR introduce a breaking change?**
Yes. App is available in Multiple languages

**Other information**

### CODE REVIEW

**Comment by palisadoes** [comment]
1. @sumitra19jha please fix the crypto dependency error in Travis.
2. It looks like you are maintaining the existing English strings, and using them as a key for other languages in the translation table if these other languages are preferred by the user. Is this assumption correct?

**Comment by sumitra19jha** [comment]
@palisadoes yes 
It will help both app user and developers.

**Comment by sumitra19jha** [comment]
@palisadoes The error is due to the addition of language JSON files. I am working on updating the test cases based on the current changes.

**Comment by sumitra19jha** [comment]
### French

https://user-images.githubusercontent.com/35868598/119254162-737c8a00-bbd2-11eb-86f7-d1d0f81ad271.mp4

### English

https://user-images.githubusercontent.com/35868598/119254270-0b7a7380-bbd3-11eb-9c5f-663ebf17b99f.mp4

### Hindi

https://user-images.githubusercontent.com/35868598/119254364-7d52bd00-bbd3-11eb-8ba4-1b8873d30a4a.mp4

### Chinese

https://user-images.githubusercontent.com/35868598/119254409-c276ef00-bbd3-11eb-9a4a-4e99c4068609.mp4

### Spanish


https://user-images.githubusercontent.com/35868598/119254452-08cc4e00-bbd4-11eb-8c0a-36a1579beb96.mp4

**Comment by Sagar2366** [comment]
@sumitra19jha if the work on this issue is not finished, please add [WIP] to PR

**Comment by sumitra19jha** [comment]
@Sagar2366 The work is finished for the issue

**Review by palisadoes — CHANGES_REQUESTED** [review]
@sumitra19jha Merge this into the GSoC branch.

**Comment by sumitra19jha** [comment]
This is string refactoring for Master Branch.
Separate PR will come for String refactoring for GSoC Branch

**Comment by CyberWake** [comment]
@sumitra19jha please look into the test cases first so that we may review the changes as the PR is based for master.

**Comment by sumitra19jha** [comment]
@CyberWake Test cases are updated accordingly. Where are you facing test cases issue in this PR?

**Comment by sumitra19jha** [comment]
@palisadoes @rutvik11062000 @CyberWake Can you please review this

**Review by palisadoes — APPROVED** [review]

**Comment by palisadoes** [comment]
@rutvik11062000 @CyberWake @utkarshshendge Please review. We need at least 2 reviewers on the master branch for merging to occur.

**Comment by CyberWake** [comment]
Sure will review it by today.

**Review by utkarshshendge — APPROVED** [review]

**Pull request merged**
