### PR TITLE
Fixes #1615 Bug: Added pop-up which shows on clicking verify Button 

### LINKED ISSUE #1615: No message on Clicking verify organisation url
**Describe the bug**
1. In talawa app on startup page , No message is showing on clicking verify.
2. It should show a verify message or an error in case of invalid url.

**To Reproduce**

1. Install Talawa, Talawa-API and Talawa-Admin as per their installation guides
2. When you try to login and enter the url of organization it will show nothing.

**Expected behavior**
It should show a verify message or an error in case of invalid url.

**Actual behavior**
It is showing nothing

**Screenshots**

https://user-images.githubusercontent.com/76736055/222953485-1d9a002e-87fb-4d65-af42-2cb0cd0d001e.mp4

**Additional details**
See above

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by indresh149**
**What kind of change does this PR introduce?**

Bug Fix

**Issue Number:**

Fixes #1615 

**Did you add tests for your changes?**

No

**Snapshots/Videos:**

https://user-images.githubusercontent.com/76736055/223465813-490db634-c9c1-4d43-ad2f-f572d6451c40.mp4

**If relevant, did you update the documentation?**

No

**Summary**

1. There is no message showing on clicking the verify Button on the Home Page whether the URL is valid or not.
2. Issue [https://github.com/PalisadoesFoundation/talawa/issues/1615](url)

**Does this PR introduce a breaking change?**

No

**Other information**

See above

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Review by indresh149 — COMMENTED** [review]
formatting fixed

**Comment by Cioppolo14** [comment]
@indresh149 Please fix failing tests, and it would be good to show the code coverage report here.

**Comment by indresh149** [comment]
@Cioppolo14 @palisadoes I have fixed the failing test please review

**Comment by noman2002** [comment]
@indresh149 Please attach a screenshot for test coverage as it is not generated by codecov.

**Comment by indresh149** [comment]
@noman2002 now the test coverage report is generated , please review it. Thank you

**Review by noman2002 — CHANGES_REQUESTED** [review]
Write the test for the changes. Make sure the coverage don't drop.

**Comment by Ayush0Chaudhary** [comment]
@indresh149 you can try **MessageType.info** with **TalawaSnackbar.**
We made it so that messaging can be uniform in our app.

**Comment by palisadoes** [comment]
We have a new check in place. All Talawa mobile app methods, classes and functions need to have suitable comments. Please refer to this issue as  reference for what is now required. The aim is to help us improve the quality of our automated documentation on docs.talawa.io.
 
- https://github.com/PalisadoesFoundation/talawa/issues/1479

To fix this issue:

1. You will be required to remove a line containing `ignore_for_file`
1. After doing so you'll be requested to update the comments appropriately

We have also tried to make the documentation step automatically update your IDE with a custom Linter. If you have any comments, please contact @literalEval who worked on this code.

**Comment by literalEval** [comment]
@indresh149 `params:` should be like ```* `String`````

**Comment by literalEval** [comment]
@indresh149 please document things that help people in understanding codebase. Just naming the variable in the documentation is not good. Am I right @palisadoes  ?

**Comment by palisadoes** [comment]
Correct. Please adjust the linter if necessary

**Comment by palisadoes** [comment]
@indresh149 the train for this is to make out documentation better for others. Please take this more seriously.

**Comment by indresh149** [comment]
@palisadoes @literalEval sir , sorry for that I will improve the documentation part

**Comment by CyberWake** [comment]
@indresh149 please fix the merge conflicts so we could proceed ahead on this.

**Comment by indresh149** [comment]
@CyberWake merge conflicts are resolved sir but getting failing test can you please help me to fix this.

**Review by noman2002 — CHANGES_REQUESTED** [review]
Fix the failing test

**Comment by indresh149** [comment]
@noman2002 @CyberWake @Cioppolo14 @palisadoes sir failing test issue is resolved please review it.

**Comment by noman2002** [comment]
@indresh149 Don't remove any reviewer they are assigned for a purpose. Please refrain from these type of practice.

**Comment by indresh149** [comment]
@noman2002 sorry but I didn't do anything, I just click on review from you, and GitHub automatically removed review requests from others.

**Review by CyberWake — APPROVED** [review]
Looks good to me. We can merge this.

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
