### PR TITLE
Added test for direct_chat_view_model.dart

### LINKED ISSUE #1411: View Models: Create tests for direct_chat_view_model.dart
We will need unittests done for all methods, classes and functions found in this file.

Any widgets referenced in this file must also have unittests done

```
after_auth_view_models/chat_view_models/direct_chat_view_model.dart
```

This file can be found in the `lib/view_model` directory

- Parent Issue: https://github.com/PalisadoesFoundation/talawa/issues/1003

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base.
- [The current code coverage for the file can be found here](https://codecov.io/gh/PalisadoesFoundation/talawa/tree/develop/lib/view_model/after_auth_view_models/chat_view_models)
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide

### PR DESCRIPTION
**Pull request by droy312**
**What kind of change does this PR introduce?**

Added test for `direct_chat_view_model.dart`

**Issue Number:**

Fixes #1411 

**Did you add tests for your changes?**

Yes

**Does this PR introduce a breaking change?**

No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by noman2002** [comment]
pull the recent changes @droy312

**Comment by palisadoes** [comment]
- This file path needs to be corrected `test/view_model_tests/after_auth_view_model_tests/chat_view_model_tests.dart/direct_chat_view_model_test.dart`
- Please try to get the coverage up to 100% on the test file
- Please make sure that all the files are in locations that match our existing test directory structure

**Comment by noman2002** [comment]
@droy312 Any progress on this ?

**Comment by droy312** [comment]
Unit testing for this file is completed but for 100% test coverage of this file I believe we need integration testing.

**Comment by palisadoes** [comment]
> Unit testing for this file is completed but for 100% test coverage of this file I believe we need integration testing.

Could mocking fix the coverage issue? There is a [helpers](https://github.com/PalisadoesFoundation/talawa/tree/develop/test/helpers) folder where previous PR submissions have mimicked integrations. Is this pertinent in this situation?

**Review by palisadoes — DISMISSED** [review]
The Code coverage has fallen significantly with some files going from 100% coverage to 0%. Please fix this situation. We need the coverage restored in those files and the coverage for `direct_chat_view_model.dart` to be 100%. See attached report as of Feb 7, 2023

image

**Comment by droy312** [comment]
Yes checking

**Comment by droy312** [comment]
@palisadoes The three files which is showing decreased code coverage has 100% code coverage. I believe the decreased code coverage was showing in earlier commit.

add_post_page
individual_post
event_info_body

**Review by TheHazeEffect — APPROVED** [review]

**Comment by palisadoes** [comment]
1. Please fix the conflicting files
1. Please try to get the coverage for `direct_chat_view_model.dart` to 100%

**Comment by palisadoes** [comment]
Please fix the failing tests

**Review by noman2002 — CHANGES_REQUESTED** [review]
@droy312 Fix the failing tests.

**Comment by droy312** [comment]
Yes checking

**Comment by droy312** [comment]
The streams inside functions `initialise`, `getChatMessages` and `sendMessageToDirectChat` were being listened after the streams were added which I believe is undesirable. Made the changes mane in the latest commit allows the streams to listen first then add.

**Comment by droy312** [comment]
@noman2002 The maximum code coverage for this file is achieved. The remaining coverage is showing for print statements in the code.

Capture

**Comment by noman2002** [comment]
> @noman2002 The maximum code coverage for this file is achieved. The remaining coverage is showing for print statements in the code.
> 
> Capture

Remove the print function it was used for checking the functionality.

**Comment by droy312** [comment]
@noman2002 This file has now 100% code coverage
Capture

**Review by palisadoes — APPROVED** [review]

**Review by palisadoes — APPROVED** [review]

**Review by noman2002 — APPROVED** [review]

**Pull request merged**
