### PR TITLE
Tests for encryptor.dart written

### PR DESCRIPTION
**Pull request by Manik2708**
**What kind of change does this PR introduce?** 
This change is about:
1) Making the coverage of `lib/utils/encryptor.dart` from 2.94% to 100%
2) Covering all the test cases related to this file
3) Correcting the `generateRSAKeyPair()` function which previously was not generating keys but currently is!
4) Created AsymetricKeys Model to save Key Pairs in Hive which previously was not created, registered the respective Adapters in the `main.dart` file.  
5) Created a Mock/Testing environment for Hive Data Base, so that Future Developers are able to write tests including Hive easily.   

**Issue Number:** 2149

Fixes #

**Did you add tests for your changes?** Yes

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?** Yes, the Testing Environment for Hive is going to make life of Talawa Developers easy! 

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?** Yes

### CODE REVIEW

**Comment by Manik2708** [comment]
> Run `dart format` to correct the failed test

`Missing paths to code to format` This is the reply from Terminal
I am not able to understand the need of it as the Workflow suggests I have edited the Unauthorised files which can only be reviewed by the maintainers.

**Comment by noman2002** [comment]
> > Run `dart format` to correct the failed test
> 
> `Missing paths to code to format` This is the reply from Terminal I am not able to understand the need of it as the Workflow suggests I have edited the Unauthorised files which can only be reviewed by the maintainers.

Apart from unauthorized file, you PR is also failing the tests for linting. That is why you need to format your code.

**Comment by Manik2708** [comment]
@noman2002 
What this Failed Test for Checking Codebase is about? I checked the analysis and couldn't understand the reason. Can you help?

**Comment by noman2002** [comment]
> @noman2002 What this Failed Test for Checking Codebase is about? I checked the analysis and couldn't understand the reason. Can you help?

Take a latest pull from develop.

**Comment by Manik2708** [comment]
> @Manik2708 Write the tests for missing lines.

1) The line changed in `main.dart` is registration of Adapter of Hive. The tests for these are not written and code coverage also show that even older Adapters are also uncovered.
2) The new created file `lib/models/asymetric_keys/asymetric_keys.g.dart` is generated by code generator which don't require tests but this file is very significant, as without it Hive will become insignificant!

**Comment by noman2002** [comment]
@Manik2708 Write the tests for main.dart

**Comment by Manik2708** [comment]
> @Manik2708 Write the tests for main.dart, even if they were not written before.

`main.dart` contains UI part and business logic in the same file and it needs to be separated for writing tests. Should I proceed with modifying the `main.dart` file?

**Comment by noman2002** [comment]
> > @Manik2708 Write the tests for main.dart, even if they were not written before.
> 
> `main.dart` contains UI part and business logic in the same file and it needs to be separated for writing tests. Should I proceed with modifying the `main.dart` file?

No, let it be for now.

**Comment by noman2002** [comment]
@literalEval @Ayush0Chaudhary Please review.

**Comment by Manik2708** [comment]
> > > @Manik2708 Write the tests for main.dart, even if they were not written before.
> > 
> > 
> > `main.dart` contains UI part and business logic in the same file and it needs to be separated for writing tests. Should I proceed with modifying the `main.dart` file?
> 
> No, let it be for now.

I have tried my best and written tests for all functions outside the main() function but I am not able to write tests for the main() function as I can't send Parameters to this function but without it I can't use Mock Environments for testing. I have been scrolling through Google for the last few hours but got nothing. Can you guide me or if you know how to prepare the mock environments for the main() function?

**Comment by Manik2708** [comment]
> @nishnatadebnath @CyberWake I think you worked on encryption before. This PR tests that it's working. It could provide insights into getting chats working again. Please review

Please note that I edited the main `encryptor.dart` file. The `generateRSAKeyPair()` method was not generating the RSA Keys before but now it is able to do that! Please verify the changes if it is compatible with the requirements of Talawa.

**Comment by Manik2708** [comment]
> > > > @Manik2708 Write the tests for main.dart, even if they were not written before.
> > > 
> > > 
> > > `main.dart` contains UI part and business logic in the same file and it needs to be separated for writing tests. Should I proceed with modifying the `main.dart` file?
> > 
> > 
> > No, let it be for now.
> 
> I have tried my best and written tests for all functions outside the `main()` function but I am not able to write tests for the `main()` function as I can't send Parameters to this function but without it I can't use Mock Environments for testing. I have been scrolling through Google for the last few hours but got nothing. Can you guide me or if you know how to prepare the mock environments for the `main()` function?

Also see that most of the code in `main.dart` file is not testable, it has to be converted to the testable form which requires heavy changes and can't be completed without the assistance of Maintainers as wrong implementation might pass the tests but could break other services. So an issue can be raised for making `main.dart` file testable. I have written tests for it and made the best possible changes in the main file making it coverage to 4.8% which was 0 earlier, but I don't think that I should commit the changes in this PR. So should I raise a new PR @noman2002 ?

**Comment by Manik2708** [comment]
@literalEval @Ayush0Chaudhary @CyberWake @TheHazeEffect A humble reminder to review this PR!

**Comment by noman2002** [comment]
> @literalEval @Ayush0Chaudhary @CyberWake @TheHazeEffect A humble reminder to review this PR!

Please pull the latest code into this branch.

**Comment by noman2002** [comment]
I think we can merge this. 
@literalEval @Ayush0Chaudhary Please review it once.

**Review by palisadoes — APPROVED** [review]

**Review by noman2002 — APPROVED** [review]

**Pull request merged**
