### PR TITLE
Enhance custom avatar test.dart

### PR DESCRIPTION
**Pull request by literalEval**
**What kind of change does this PR introduce?**

Increases coverage for lib/widgets/custom_avatar.dart

**Issue Number:**

#1127 

**Did you add tests for your changes?**

Yes

**Does this PR introduce a breaking change?**

No

### CODE REVIEW

**Comment by literalEval** [comment]
@noman2002 @palisadoes please have a look and suggest changes.

**Comment by noman2002** [comment]
Looks good to me. Waiting for the codecov, so I can see the code coverage.

**Review by noman2002 — CHANGES_REQUESTED** [review]
The code coverage is at 86.36% currently, please try to get it up to 100%.

**Comment by literalEval** [comment]
@noman2002 I have already mentioned the problems I am facing in getting it to 100% in the corresponding issue of this PR. Please have a look there and then suggest me what to do. Thanks.

**Comment by palisadoes** [comment]
@noman2002 please provide feedback

**Comment by noman2002** [comment]
> @noman2002 please provide feedback

I think we should merge this PR but let the issue open so we can get the coverage to 100% later.

**Review by noman2002 — APPROVED** [review]

**Review by noman2002 — APPROVED** [review]
Merge this but let the issue be open. @literalEval Please unassign the issue.

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
