### PR TITLE
event_card sharp corners fixes

### PR DESCRIPTION
**Pull request by Pavel401**
**What kind of change does this PR introduce?**

=> ptch ( Added rounded corners on the event_cards)

**Summary**
The event_card's rectangle with sharp edges are not looking good with the UI. These cards take high cognitive effort to visually process the UI by the user. Users can appreciate the aesthetic beauty of rounded corners on the UI.Rounded corners are not only easier for our eyes to process, but they also make information easier to process for the user. There’s no doubt that rounded corners are appealing.In the present UI, the rectangle with sharp edges cards is not looking good with the rounded buttons and rounded bottom sheets UI.

**Snapshots/Videos:**
Sharp corners |  Rounded Corners
:-------------------------:|:-------------------------:
WhatsApp Image 2021-12-23 at 9 45 48 PM | WhatsApp Image 2021-12-23 at 9 45 47 PM

**Issue Number:**#1077

Note: I've not done any changes in .flutter-plugins-dependencies, so I don't know why it's in the commit. So if it's not in the main branch, kindly ignore that file and merge only event-card fix.

### CODE REVIEW

**Comment by palisadoes** [comment]
Closing. Fixed in:
- https://github.com/PalisadoesFoundation/talawa/pull/1076

**Comment by Pavel401** [comment]
Is it reviewed ?

**Comment by palisadoes** [comment]
Isn't this the same feature that was handled in this pull request?
- https://github.com/PalisadoesFoundation/talawa/pull/1076

**Comment by Pavel401** [comment]
> Isn't this the same feature that was handled in this pull request that was merged into the codebase?
> 
> * [event_card ui changes  #1076](https://github.com/PalisadoesFoundation/talawa/pull/1076)

yes,but its not merged with the source .

**Pull request closed without merging**
