### PR TITLE
The Join organisation button has stick to the bottom

### LINKED ISSUE #2392: Bug Report: The "Join Organisation button" should stick to the bottom.
**Describe the bug**
The Join organization button should stick to bottom. 

**To Reproduce**

1. Open drawer

**Expected behavior**
The Join organization button should stick to bottom. 

**Actual behavior**
Currently, Its not stick to the bottom. 

**Screenshots**
Screenshot_1708871819

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by SumitPareek2401**
**What kind of change does this PR introduce?**
Bugfix

**Issue Number:**
Fixes #2392 

Fixes #

**Did you add tests for your changes?**
Yes

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**
This pull request solves the bug report of sticking the "join organization button" to the bottom.

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by Cioppolo14** [comment]
@noman2002 @DMills27 Can you review this PR?

**Comment by Ayush0Chaudhary** [comment]
Add screen shot

**Comment by SumitPareek2401** [comment]
drawer1

**Comment by Olatade** [comment]
@SumitPareek2401 Please update your branch with the latest changes.

**Review by noman2002 — APPROVED** [review]
LGTM

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
