### PR TITLE
Adds test for org_info.dart

### LINKED ISSUE #1419: Models: Tests for org_info.dart
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

We will need unittests done for all methods, classes and functions found in this file.

Any widgets referenced in this file must also have unittests done

```
lib/models/organization/org_info.dart
```

- Parent Issue: https://github.com/PalisadoesFoundation/talawa/issues/1414

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base.
- [The current code coverage for the file can be found here](https://codecov.io/gh/PalisadoesFoundation/talawa/tree/develop/lib/models/organization)
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide

### PR DESCRIPTION
**Pull request by droy312**
**What kind of change does this PR introduce?**

Adds test for org_info.dart

**Issue Number:**

Fixes #1419 

**Did you add tests for your changes?**

Yes

**Does this PR introduce a breaking change?**

No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by palisadoes** [comment]
Please also attach the code coverage report as it was not generated automatically.

**Review by noman2002 — CHANGES_REQUESTED** [review]
Attach code coverage screenshot.

**Comment by droy312** [comment]
@noman2002 I deleted these debugPrint messages because I wanted the test coverage to be 100% but after I deleted the debugPrint messages 1 of the checks are not working. Could you give some insight about why it is failing.
Capture

**Comment by palisadoes** [comment]
Please click on the details of the failing test. The answer is there.

**Comment by palisadoes** [comment]
1. Please fix the conflicting files, and failing tests.
1. We upgraded to Flutter 3.7.0. Try to refactor your code accordingly

**Comment by droy312** [comment]
@palisadoes The code coverage for this file is 100%
Capture

**Comment by droy312** [comment]
The **testing codebase test** is failing since I added trailing commas in `database_mutation_functions.dart` file since flutter analysis was asking to put commas in it but there is no test present for this file.

The **build for android test** is failing since I believe we upgraded to Dart 2.18.2 but in github it is still 2.17.

**Comment by palisadoes** [comment]
The tests all passed for pushes after the upgrade's merge. They all passed for other subsequent PRs too.

**Comment by literalEval** [comment]
@droy312 can you please check the flutter version in you local `.github/pull_request.yml` and `.github/push.yml` ?

**Comment by literalEval** [comment]
@palisadoes please look at `pull-request.yml` line no - 102 :)
It need to be updated to `flutter 3.7.3`

image

**Comment by palisadoes** [comment]
I did a search and replace on this. I'll fix it now.

**Comment by palisadoes** [comment]
> @palisadoes please look at `pull-request.yml` line no - 102 :) It needs to be updated to `flutter 3.7.3`
> 
> image

It was missed here: https://github.com/PalisadoesFoundation/talawa/pull/1510

**Comment by palisadoes** [comment]
@droy312 Please make a minor commit and it should trigger the correct workflow.

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
