### PR TITLE
Unit test event service

### LINKED ISSUE #2616: Write Unittests for `lib/services/event_service.dart`
We will need unittests done for all methods, classes and functions found in this file.

Any widgets referenced in this file must also have unittests done

### PR Acceptance Criteria

1. When complete this file must show **100%** coverage when merged into the code base.
1. [The current code coverage for the file can be found here](https://app.codecov.io/gh/PalisadoesFoundation/talawa/tree/develop/?displayType=list)
1. CodeRabbit must approve all your changes to the test file(s) and the file(s) under test
1. The PR will show a report for the code coverage for the file you have added. You can use that as a guide
1. No functionality must be removed to achieve this goal
1. All tests must be valid and truly test the code base

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by MohitMaulekhi**
**What kind of change does this PR introduce?**

Unit test for Event service

**Issue Number:**

Fixes #2616

**Did you add tests for your changes?**

Yes

**Snapshots/Videos:**

image

**Summary**

This PR aims to increase the code coverage of the specified file by adding comprehensive unit tests. It ensures that all methods, functions, and widgets are thoroughly tested, improving the overall reliability and maintainability of the codebase. The Pr will resolve issue https://github.com/PalisadoesFoundation/talawa/issues/2616.

**Does this PR introduce a breaking change?**

No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**

Yes

## Summary by CodeRabbit

- **New Features**
	- Introduced a new getter for accessing current organization information in the Event Service.
  
- **Bug Fixes**
	- Enhanced error handling and functionality verification through additional tests for various methods in the Event Service.

- **Tests**
	- Expanded test suite to cover success and failure scenarios for fetching volunteer groups and organization updates, as well as data retrieval handling.

### CODE REVIEW

**Review by Cioppolo14 — COMMENTED** [review]
@coderabbitai review

**Comment by Cioppolo14** [comment]
@MohitMaulekhi  Please make sure coderabbit reviews your PR and any comments it has are addressed.  Please do not assign reviewers.

**Comment by palisadoes** [comment]
Please make coderabbit.ai approve your changes

**Comment by MohitMaulekhi** [comment]
@coderabbitai review

**Comment by palisadoes** [comment]
@noman2002 PTAL

**Review by noman2002 — APPROVED** [review]

**Pull request merged**
