### PR TITLE
Bug fix : Unresponsive UI of App drawer (UI Improvement) #1669

### LINKED ISSUE #1669: Bug Report :Unresponsive UI of App drawer (UI Improvement)
**Describe the bug**
The UI of the App Drawer is unresponsive and shows irregular padding behavior on the bottom side in different screen sizes.

**To Reproduce**

1. Install Talawa, Talawa-API, and Talawa-Admin as per their installation guides.
2. log in to Talawa and open the App Drawer.
3. See the bottom of the App drawer, it has different padding on different devices, in some devices, it is showing zero padding.

**Expected behavior**
The Bottom name should have some padding according to the screen size.

**Actual behavior**
It is showing zero padding on some devices.

**Screenshots**
image

image

**Additional details**
See above

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by indresh149**
**What kind of change does this PR introduce?**

BugFix

**Issue Number:**

Fixes #1669 

**Did you add tests for your changes?**

No

**Snapshots/Videos:**

image

**If relevant, did you update the documentation?**

No

**Summary**

Talawa App is already using Media Query for responsive Ui. I have just added a sized box and decreased some heights to make it consistent.

**Does this PR introduce a breaking change?**

No

**Other information**

See above

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Review by palisadoes — DISMISSED** [review]

**Review by palisadoes — CHANGES_REQUESTED** [review]
Please fix the failing tests

**Comment by indresh149** [comment]
@palisadoes sir getting test fail due to except error in documentation custom lint. I am trying to fix it asap. Thank you

**Review by noman2002 — CHANGES_REQUESTED** [review]
Please fix the failing test by adding documentation.

**Comment by indresh149** [comment]
@palisadoes @noman2002 sir failing tests fix please review the PR. Thank you

**Review by palisadoes — CHANGES_REQUESTED** [review]
Please fix the failing tests. Code coverage has declined. Try increasing the code coverage for the files edited to 100%

**Comment by palisadoes** [comment]
Please fix the failing tests

**Comment by indresh149** [comment]
> Please fix the failing tests

sir custom drawer test file is completely commented and has errors, I am trying to fix the tests of that file.  sorry for the delay.

**Comment by palisadoes** [comment]
Closing this PR. It's been over 2 weeks without an update. Files are conflicting too. Please resubmit.

**Comment by indresh149** [comment]
@palisadoes Sorry for the inconvenience sir, I was busy making proposal will resubmit soon .

**Pull request closed without merging**
