### PR TITLE
Comprehensive Language Translation Enhancement for App Globalization

### PR DESCRIPTION
**Pull request by Dante291**
**What kind of change does this PR introduce?**

Adding proper translation to all the translation files and making sure that translation works in other languages throughout the app.

**Issue Number:**

Fixes https://github.com/PalisadoesFoundation/talawa/issues/2283

**Did you add tests for your changes?**

Yes

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

No

**Does this PR introduce a breaking change?**

No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by Dante291** [comment]
image

Script is working fine.

**Comment by Dante291** [comment]
@palisadoes @noman2002 @Ayush0Chaudhary @literalEval I've carefully reviewed my local changes, I haven't made any direct changes to main_screen_view_model.dart and main_screen_view_model. I think there's a glitch in this PR where these files are showing changes although no modifications are made. 

Should I close it, or it would be accepted?

**Comment by Dante291** [comment]
> @palisadoes @noman2002 @Ayush0Chaudhary @literalEval I've carefully reviewed my local changes, I haven't made any direct changes to main_screen_view_model.dart and main_screen_view_model. I think there's a glitch in this PR where these files are showing changes although no modifications are made.
> 
> Should I close it, or it would be accepted?

@palisadoes please clarify

**Comment by palisadoes** [comment]
Sometimes the code coverage report doesn't get updated with every commit, especially if they are rapid updates.

**Comment by palisadoes** [comment]
@noman2002 @Ayush0Chaudhary @literalEval Please review

**Comment by SiddheshKukade** [comment]
@Dante291 can you attach screenshot of different dashboards in different ui so that we can see if all lang variables are working fine or not.

**Comment by Dante291** [comment]
> @Dante291 can you attach screenshot of different dashboards in different ui so that we can see if all lang variables are working fine or not.

@SiddheshKukade Sure sir

**Comment by Dante291** [comment]
@SiddheshKukade Take a look sir

Screenshot_1704191958
Screenshot_1704191964
Screenshot_1704191981
Screenshot_1704191984
Screenshot_1704191996
Screenshot_1704192005
Screenshot_1704192014

**Comment by Dante291** [comment]
Screenshot_1704192197

**Review by literalEval — APPROVED** [review]
LGTM

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
