### PR TITLE
Issue #584 fixed along with other problems due to the new url

### PR DESCRIPTION
**Pull request by Hrishikesh-Bhagwat**
**What kind of change does this PR introduce?**
The PR fixes the bug that the user is able to go back to the set url page even after logging in by back pressing. This must not happen ideally

**Did you add tests for your changes?**
No
**If relevant, did you update the documentation?**
No
**Summary**
The user must not be able to go back to the set url page after logging in as this does normally not happen in apps.

**Does this PR introduce a breaking change?**
A moderate change as the flow was tweaked.

**Other information**
Along with this there were some typos and recent updates in pub packages that again showed deprecation warnings. Those have been fixed.

### CODE REVIEW

**Comment by CyberWake** [comment]
@Hrishikesh-Bhagwat we already have a pending discussion on url over slack. Would we better to not have a temporary solution.😊

**Comment by CyberWake** [comment]
@Hrishikesh-Bhagwat we already have a pending discussion on URL over slack. Would we better to not have a temporary solutio😊. Plus this needs to be a separate issue not marked till now by any of the mentors.

**Comment by Hrishikesh-Bhagwat** [comment]
Bro, I came to know that. I just forgot to close it.

**Comment by Hrishikesh-Bhagwat** [comment]
You would understand better if you saw the commits I made there were some typos in it that caused org url to be same as image url. Check the preferences class. There you can see it. This was a intended that way. Half knowledge is dangerous☺

**Comment by Hrishikesh-Bhagwat** [comment]
You would understand better if you saw the commits I made there were some typos in it that caused org url to be same as image url. Check the preferences class. There you can see it. This was a intended in that way. Thanks for your concern☺

**Comment by Hrishikesh-Bhagwat** [comment]
Did you see the word 'other' in the heading?
Btw there was one typo barely had to change a few letters. I did it in good faith so that nobody faces that typo issue. Life is much beyond gsoc. Contribute for fun not for gsoc!

**Comment by CyberWake** [comment]
I just wanted the issue to be kept separate not floating with others because url won't be constant they may be kept changing and a temporary fix won't work too long. BTW you correctly said life is much beyond gsoc. please don't keep merging issues in one.

**Pull request closed without merging**
