### PR TITLE
Update image_cropper 5.0.1 to 8.0.2

### PR DESCRIPTION
**Pull request by MayankJha014**
**Upgrading `image_cropper` 5.0.1 to 8.0.2**

It involve  changes involve reorganizing the `aspectRatioPresets `configuration within the `ImageService` class, moving it from the `cropImage` method to the `AndroidUiSettings` and `IOSUiSettings` . The pubspec.yaml file has been updated to upgrade the `image_cropper`. Additionally, test files have been modified to  removing the `aspectRatioPresets` parameter in the `mockImageCropper.cropImage` method calls, simplifying the tests.

## Summary by CodeRabbit

- **New Features**
	- Updated the image cropping functionality to enhance organization and clarity in the code.
	- Upgraded the `image_cropper` package for potential new features and improvements.
  
- **Bug Fixes**
	- Addressed compatibility issues with the `intl` package through dependency overrides.

- **Documentation**
	- Streamlined documentation for the `cropImage` method for improved clarity. 

- **Tests**
	- Simplified test cases by removing unnecessary parameters related to aspect ratio presets.

### CODE REVIEW

**Comment by palisadoes** [comment]
Please fix the failing tests

**Comment by palisadoes** [comment]
The tests are still failing

**Comment by MayankJha014** [comment]
> The tests are still failing
@palisadoes   Sir can help me why  Checking for unauthorized file changes is failing.

**Comment by palisadoes** [comment]
1. The unauthorized file check failure is expected as you are editing the `package.json` file. That can be ignored.
2. Oops! I just realized that you made your change against the `main` branch. This needs to be against `develop`. That's why the `Base Branch Check` failed. If that fails, then the testing part fails too.
3. We have to close this. Please apply your changes to the `lastest` develop branch.

**Pull request closed without merging**
