### PR TITLE
Changed built-in widget constructors to corresponding const constructors wherever necessary

### LINKED ISSUE #419: [Enhancement] Changing built-in widget constructors to corresponding const constructors wherever necessary
- **Issue Description:** In most part of the code, currently we don't use const constructor for widgets having static data in their constructor like:

> `Text("create an account")`
> `SizedBox(height:5)`
> `AlignmentDirectional(0.0,0.0)`
> `Icon(Icons.arrow_downward,...)` and more widgets like this.....

Thus whenever a build method is called all these non-constant constructors rebuild their objects thereby consuming some processing time.

- **Issue Severity:** Low
- **Environment Details:** Issue found mostly in the `talawa\lib\views`
- **Observed Behaviour:** Currently we don't use const constructor for widgets having static data in their constructor like:

> `Text("create an account")`
> `SizedBox(height:5)`
> `AlignmentDirectional(0.0,0.0)`
> `Icon(Icons.arrow_downward,...)` and more widgets like this.....

- **Expected Behaviour:** To use const constructor for widgets having static data in their constructor
> `const Text("create an account")`
> `const SizedBox(height:5)`
> `const AlignmentDirectional(0.0,0.0)`
> `const Icon(Icons.arrow_downward,...)`

Then we can prevent their unnecessary rebuilds incase the build method re-runs. Thereby saving some processing time.

- **Does this issue need immediate attention?** No.
- **Are you willing to work on this issue:** Yes, I am willing to work on this issue. Please assign this to me!

### PR DESCRIPTION
**Pull request by Raunakk02**
**What kind of change does this PR introduce?**
Switched to const constructor for widgets having static data in their constructor
const Text("create an account")
const SizedBox(height:5)
const AlignmentDirectional(0.0,0.0)
const Icon(Icons.arrow_downward,...)

Then we can prevent their unnecessary rebuilds in case the build method re-runs. Thereby saving some processing time.

**Did you add tests for your changes?**
No.

**If relevant, did you update the documentation?**
No, a  documentation update is not needed.

**Summary**
Resolves #419 

**Does this PR introduce a breaking change?**
No

### CODE REVIEW

**Comment by Sagar2366** [comment]
@Raunakk02 remove changes which are not required to fix this issue.
Also resolve the conflicts.

**Comment by Raunakk02** [comment]
Sure, will do.

**Comment by Raunakk02** [comment]
@Sagar2366, I resolved the conflicts.

**Comment by Sagar2366** [comment]
@Raunakk02 have you added changes to 30 files and code addition of 1183 lines ?
If no, please remove everything else other than fix for this issue.

**Comment by Raunakk02** [comment]
Yes, @Sagar2366 what I did is added const keywords to the constructors of widgets which had static data in them and since these type of widgets (like Text(), SizedBox,Padding, TextStyles, etc.) are present in almost every file of `talawa\lib\views\pages` folder. So, I made changes in all of them.
Therefore, all the changes that I have done is related this issue only.

**Comment by Sagar2366** [comment]
Ok great. Please add unit test for this PR.

**Comment by Raunakk02** [comment]
@Sagar2366 can you please guide me on what kind of test I should add?
Because I only added a **const** keyword to the already present constructors. Sorry for bothering you with this!

**Comment by Raunakk02** [comment]
@Sagar2366 I have added the test now.

**Comment by palisadoes** [comment]
Please fix merge conflicts. The code freeze is lifted.

**Comment by Raunakk02** [comment]
sure!

**Comment by palisadoes** [comment]
Please fix the `Lint Code Base` error 

[CONTRIBUTING.md](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md) has been updated with what you need to do to lint your code before submission.

**Comment by palisadoes** [comment]
Please fix the `Lint Code Base` error. 

[CONTRIBUTING.md](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md) has been updated with what you need to do to lint your code before submission.

**Comment by Raunakk02** [comment]
> Please fix the `Lint Code Base` error.
> 
> [CONTRIBUTING.md](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md) has been updated with what you need to do to lint your code before submission.

I have fixed the error now @palisadoes.

**Comment by palisadoes** [comment]
@Raunakk02 please fix the conflicting files in the PR

**Comment by Raunakk02** [comment]
@palisadoes I have fixed the conflicting files.

**Comment by palisadoes** [comment]
@Sagar2366 @jordanliu @DeltaHarbinger  Please review as there are lots of files to consider.

**Comment by Sagar2366** [comment]
@Raunakk02 can you break out this PR in small PR's for different files/screens ? It's difficult to review large PR's.

**Comment by palisadoes** [comment]
@Raunakk02 Please lint your code. An explanation can be found in CONTRIBTING.md

We will soon be enforcing a 300 line limit on Dart files. Please consider ways to reduce the sizes of the files you edit while maintaining functionality in future. PRs reviewed on or after May 15 will be rejected if this requirement is not met.

**Comment by palisadoes** [comment]
@Raunakk02 Please lint your code and fix the merge conflicts. An explanation can be found in CONTRIBTING.md

We will soon be enforcing a 300 line limit on Dart files. Please consider ways to reduce the sizes of the files you edit while maintaining functionality in future. PRs reviewed on or after May 15 will be rejected if this requirement is not met.

**Comment by Raunakk02** [comment]
> @Raunakk02 Please lint your code and fix the merge conflicts. An explanation can be found in CONTRIBTING.md
> 
> We will soon be enforcing a 300 line limit on Dart files. Please consider ways to reduce the sizes of the files you edit while maintaining functionality in future. PRs reviewed on or after May 15 will be rejected if this requirement is not met.

Sure @palisadoes !

**Comment by palisadoes** [comment]
@Raunakk02 Please resolve the merge conflicts

**Comment by palisadoes** [comment]
@Raunakk02 Please resolve the merge conflicts

**Comment by DeltaHarbinger** [comment]
Hey @Raunakk02, the changes you made to fix the issue are fine, but I see that a lot of files are added in this PR such as lib/views/pages/organization/remove_member.dart and lib/views/pages/newsfeed/newsArticle.dart. These have nothing to do with the issue that was assigned. Could you either tell us what the files are for or remove them if they're not necessary. You can see all new files in the "Files Changed" section of this PR

**Comment by Raunakk02** [comment]
> Hey @Raunakk02, the changes you made to fix the issue are fine, but I see that a lot of files are added in this PR such as lib/views/pages/organization/remove_member.dart and lib/views/pages/newsfeed/newsArticle.dart. These have nothing to do with the issue that was assigned. Could you either tell us what the files are for (e.g. Added to resolve merge conflict) or remove them if they're not necessary. You can see all new files in the "Files Changed" section of this PR

Hey @DeltaHarbinger, ya those files were added due to changes added by me for resolving merge conflicts, also when I was updating the PR with the latest changes from master then some of the tests ( which I had nothing to do with ) which were previously passing, failed somehow. So, In order to make those test cases pass, I added some of the necessary changes.

**Comment by Raunakk02** [comment]
@DeltaHarbinger I have now removed those files from this PR.

**Review by DeltaHarbinger — APPROVED** [review]

**Comment by DeltaHarbinger** [comment]
I resolved a merge conflict that arose. This will now be merged

**Pull request merged**
