### PR TITLE
[BUG] Added functionality of like button and added comment button opens the comment

### LINKED ISSUE #235: [BUG] Issue with the post
1.  Tapping like button twice do not remove the like.
2.  Comment icon doesn't work 
3.  Color doesn't changes on clicking the like button
4.  there is no dislike button 
5.  there is not a share button as well
6.  post structure is not good
7.  can't put video or image in the post 

would you please assign me this to do 
@Sagar2366  @DeltaHarbinger @heyjordn @jordanliu 

https://user-images.githubusercontent.com/55004621/111064890-b63c2a80-84dc-11eb-9ecd-b7e605f29c9a.mp4

### LINKED ISSUE #301: [bug] Comment Screen
hint text: "leave a comment..." is not center aligned and text field should be wrapped in intrinsicHeight widget.

Can someone assign this to me?

WhatsApp Image 2021-03-15 at 8 33 19 AM

### LINKED ISSUE #303: [bug] comment text field does not has multi-line support.
All text comes in one line that will create bad user experience.

Can someone assign this to me?
https://user-images.githubusercontent.com/43651504/111098985-93585780-856a-11eb-8ce6-9c212b930628.mp4

### PR DESCRIPTION
**Pull request by yasharth291**
**What kind of change does this PR introduce?**

it is a bugfix and modified version of my previous pr.

**Did you add tests for your changes?**
no

**If relevant, did you update the documentation?**
no

**Summary**
The motivation behind this bugfix was non functionality of the like button. In this pr i have introduced 4 changes.

1. Like decrease when clicked twice.
2. Color of like button changes when clicked.
3. Comment icon sends to comment page.
4. comment section has a limit.

**Does this PR introduce a breaking change?**
no

**Other information**
Fixes #303 
Fixes #301 

https://user-images.githubusercontent.com/55004621/111461094-ca816100-8742-11eb-8083-c22744ede371.mp4

https://user-images.githubusercontent.com/55004621/111461159-dff68b00-8742-11eb-9390-227a08c8c0f7.mp4

### CODE REVIEW

**Comment by Sagar2366** [comment]
@yasharth291 multiline comment is not working. Please make sure you are testing PR properly before sending it for review.

**Comment by yasharth291** [comment]
> > > @yasharth291 multiline comment is not working. Please make sure you are testing PR properly before sending it for review.
> > 
> > 
> > i will apply that in other pull request as now it is taking time because it is not the problem of the textfield but rather a problem of graphql query
> 
> Update pr and issue description - keep changes in this PR only for like button. And in another PR fix comment related bugs.

done sir i have changed the title and made the pr description new

**Comment by yasharth291** [comment]
> > > @yasharth291 multiline comment is not working. Please make sure you are testing PR properly before sending it for review.
> > 
> > 
> > i will apply that in other pull request as now it is taking time because it is not the problem of the textfield but rather a problem of graphql query
> 
> Update pr and issue description - keep changes in this PR only for like button. And in another PR fix comment related bugs.

all the mentioned bug in the above pr are working all together

**Review by Sagar2366 — APPROVED** [review]

**Comment by yasharth291** [comment]
can it be merged now sir ?

**Pull request merged**
