### PR TITLE
feat: add tests for direct_chat_view_model

### LINKED ISSUE #1016: Unittests for direct_chat_view_model.dart
The Talawa code base needs to be 100% reliable. This means we need to have 100% unittest code coverage.

We will need unittests done for all methods, classes and functions found in this file.

Any widgets referenced in this file must also have unittests done

```
after_auth_view_models/chat_view_models/direct_chat_view_model.dart
```

This file can be found in the `lib/view_model` directory

Parent Issue: https://github.com/PalisadoesFoundation/talawa/issues/1003

### PR DESCRIPTION
**Pull request by SriramPatibanda**
**What kind of change does this PR introduce?**

Tests

**Issue Number:**

Fixes #1016 

**Did you add tests for your changes?**

Yes

**Snapshots/Videos:**

N.A.

**If relevant, did you update the documentation?**

N.A.

**Summary**

Add unit tests for DirectChatViewModel.

**Does this PR introduce a breaking change?**

No

**Other information**
N.A

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Review by rutvik11062000 — APPROVED** [review]
Hi @SriramPatibanda, thank you for your contribution.

1. Don't alter/manipulate the existing viewModel without a solid reason, it will lead to failures of other tests.
2. Kindly look into the video on slack I just shared, you've to create a MockClass of the particular class you're going to test, so that it can have stubbing functionality.

**Review by rutvik11062000 — CHANGES_REQUESTED** [review]
Please do the above changes.

**Comment by SriramPatibanda** [comment]
> Hi @SriramPatibanda, thank you for your contribution.
> 
> 1. Don't alter/manipulate the existing viewModel without a solid reason, it will lead to failures of other tests.
> 2. Kindly look into the video on slack I just shared, you've to create a MockClass of the particular class you're going to test, so that it can have stubbing functionality.

@rutvik11062000 
1. I had removed the late keyword before LRUChatListCache (_chats) because it is already a nullable field and I initialising it late didn't really make any sense when it already had a default value. LRUCache (_chats) was set as a nullable field but at the same time its getter was set to non-nullable. I don't think that's possible. I think it should either be initialised late without being null or be null throughout the view model. Please correct me or give suggestions if I made a mistake.

2. I'll surely watch the video and make the necessary changes and will ask my queries here. Thank you!

**Comment by rutvik11062000** [comment]
@SriramPatibanda can you make necessary changes to this?

**Comment by SriramPatibanda** [comment]
> @SriramPatibanda can you make necessary changes to this? 

Yeah, was busy over the week days. Will do them tomorrow.

**Comment by palisadoes** [comment]
Rutvik, the changes have been made. Please review.

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
