### PR TITLE
Remove shadow from buttons

### LINKED ISSUE #2393: Remove shadow from buttons
**Describe the bug**
Remove shadow from buttons.

**Expected behavior**
No shadow on buttons

**Screenshots**
Screenshot_1708872180
Screenshot_1708872226

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by Yousef-Rabia**
**What kind of change does this PR introduce?**

Remove shadow from buttons

**Issue Number:**

Fixes #2393

**Did you add tests for your changes?**

No

**Snapshots/Videos:**

Screenshot_1708893501
Screenshot_1708893435

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by Cioppolo14** [comment]
@Yousef-Rabia Please fix the failing tests.  We will assign reviewers once the tests are passed.

**Comment by Cioppolo14** [comment]
@Yousef-Rabia Are you working on this?

**Comment by Yousef-Rabia** [comment]
@Cioppolo14 
yes, but i think i need a help with this error

**Comment by Olatade** [comment]
@noman2002 @Ayush0Chaudhary please can you review ?

**Review by noman2002 — APPROVED** [review]

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
