### PR TITLE
Feature Request: Make pinned post for important post by admin.

### LINKED ISSUE #1954: [GSoC] Feature Request: Make pinned post for important post  by admin
**Is your feature request related to a problem? Please describe.**
Yes current pinned post are not properly visible/accessible

**Describe the solution you'd like**
image

**Describe alternatives you've considered**
the original

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by Ayush0Chaudhary**
**What kind of change does this PR introduce?**
This PR add the pinned post

**Issue Number:**

Fixes #1954

**Did you add tests for your changes?**

**Snapshots/Videos:**
[device-2023-07-12-140858.webm](https://github.com/PalisadoesFoundation/talawa/assets/95746190/1595e14f-b026-435e-80dd-4e3838e8c98c)

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**

### CODE REVIEW

**Comment by Ayush0Chaudhary** [comment]
[device-2023-07-12-140858.webm](https://github.com/PalisadoesFoundation/talawa/assets/95746190/22ee3db9-9ff3-44d8-80cb-aeaa691acd65)

**Comment by Ayush0Chaudhary** [comment]
Do I need to change the UI? @noman2002

**Comment by palisadoes** [comment]
@noman2002 @AdityaBirangal Please review

**Review by noman2002 — COMMENTED** [review]
Get the coverage of router.dart and organization_feed.dart to 100%. Then we can merge it.

**Comment by noman2002** [comment]
@Ayush0Chaudhary Any update on this.

**Comment by Ayush0Chaudhary** [comment]
Can we merge this?
@noman2002 @palisadoes

**Comment by palisadoes** [comment]
@Ayush0Chaudhary We need to get the code coverage up the patch coverage test is failing

**Review by noman2002 — APPROVED** [review]
Looks good to me.

**Comment by palisadoes** [comment]
@Ayush0Chaudhary Please write tests for the code you have submitted. There are large gaps. Our GitHub actions are failing as a result.

**Comment by palisadoes** [comment]
@Ayush0Chaudhary Please write the appropriate tests

**Comment by palisadoes** [comment]
@Ayush0Chaudhary Please fix the failing tests. It looks like a formatting issue.

**Comment by palisadoes** [comment]
@Ayush0Chaudhary Any update on this? It's causing real hardship with our GitHub actions and any future development work

**Comment by Ayush0Chaudhary** [comment]
> @Ayush0Chaudhary Any update on this? It's causing real hardship with our GitHub actions and any future development work

https://github.com/PalisadoesFoundation/talawa/pull/1971
fixed in this PR

**Comment by Ayush0Chaudhary** [comment]
> @Ayush0Chaudhary Please write tests for the code you have submitted. There are large gaps. Our GitHub actions are failing as a result.

it down to .2%

image

**Comment by palisadoes** [comment]
@Ayush0Chaudhary Please fix the conflicting files so that we can merge this. Thanks for the work on the other PR

**Comment by noman2002** [comment]
@Ayush0Chaudhary Please fix the conflicting file, we can merge this.

**Comment by palisadoes** [comment]
@Ayush0Chaudhary Please fix the conflicting files

**Review by noman2002 — DISMISSED** [review]

**Comment by palisadoes** [comment]
@Ayush0Chaudhary Tests are failing. Please fix.

**Pull request merged**
