### PR TITLE
Create Organization Page Form Filling UX enhancement

### PR DESCRIPTION
**Pull request by CyberWake**
**What kind of change does this PR introduce?**
Enhances the form filling experience on the create organization screen

**Did you add tests for your changes?**
Yes, I have tested it successfully for all use cases.
**If relevant, did you update the documentation?**
No, documentation was needed to be updated.
**Summary**

To enhance the user experience with form filling I had this PR raised. The pull safely improves the UX.
#203 

**Does this PR introduce a breaking change?**
No, as it includes all the latest commits on master

**Other information**
Please review and merge.

### CODE REVIEW

**Comment by Sagar2366** [comment]
LGTM. Please fix the conflicts and send PR again for review.

**Comment by Sagar2366** [comment]
@CyberWake, consider one more case here - if blank newline is added to Organization description and/or member description, create organization doesn't work/throws error.

**Comment by CyberWake** [comment]
added the null checks for all the input field and giving proper toast to user regarding the @Sagar2366 

> @CyberWake, consider one more case here - if blank newline is added to Organization description and/or member description, create organization doesn't work/throws error.
> Also, change PR and issue titles.

So be need to remove all the white spaces after the last word, am I getting it right if so please review the updates I have trimmed the text values for all fields before posting the data.

**Comment by CyberWake** [comment]
I have fixed it, now new organizations are being made successfully.

**Comment by Sagar2366** [comment]
@CyberWake, can you please share video/snaps for the test you are running ? 
I still see error on executing this feature from your PR.
Please test PR's fully before sending out for review and focus on one issue at a time to avoid such errors.

Screenshot 1942-12-25 at 4 33 54 PM

**Comment by CyberWake** [comment]
Please have a review on the screen recording and changes made.
https://user-images.githubusercontent.com/44184786/111309627-20da9b00-8682-11eb-8dac-b0e49d9ffbbc.mp4

**Review by Sagar2366 — APPROVED** [review]

**Pull request merged**
