### PR TITLE
Switch org

### PR DESCRIPTION
**Pull request by Deandrew007**
finished switch org  implementation and added new auth changes using refresh and access tokens

### CODE REVIEW

**Comment by MrSambo** [comment]
What's supposed to happen when you change organizations apart from the profile page changing your "current organization"? I'm not seeing any difference with any of the other tabs (unless I'm missing it?)

The switch organization page has a few bugs
- The first radio button is selected by default regardless of the organization you're currently in. 

- You cannot switch to the first organization even if the first radio button is selected

An (important) aside. There really shouldn't be 84 different commits from back in April in this PR.. That increases the potential for merge conflicts.. Please try to limit commits in PRs relevant to the PR

**Comment by Deandrew007** [comment]
Yes, I noticed those bugs when I moved on to the next milestones, so I fixed it there. 
The data in the app is supposed to change relevant to the organization. Awaiting Dimitri's update, as the existing queries he had weren't filtered by organization ID, hence you didn't see any change

As it relates to the commits in a PR... how do I limit it to just that PR? From my understanding, if those commits are merged, then only new commits made will be shown...

**Comment by MrSambo** [comment]
> As it relates to the commits in a PR... how do I limit it to just that PR? From my understanding, if those commits are merged, then only new commits made will be shown...

I believe the issue is that your local repository is based on talawa's master branch not this month's talawa branch which has your previous changes merged

**Comment by Deandrew007** [comment]
Oh I see, thanks

**Pull request closed without merging**
