### PR TITLE
Color on click

### LINKED ISSUE #1048: Language picker colors
When a language is selected, the name remains greyed out and that doesn't convey
the selection very well, especially against the selection box that appears around it, which is also grey.

### PR DESCRIPTION
**Pull request by ayush-mahawar26**
Issue Fixed #1048 
Now we can see the color change on taping on any of the selected language 
If theme is Dark Mode then Selected language will display in color white , and if theme is Light the the selected text is in black Color.

https://user-images.githubusercontent.com/65828946/147253528-c0267f57-12bf-4083-950c-5bb68772b264.mp4

### CODE REVIEW

**Comment by nishnatadebnath** [comment]
@ayush-mahawar26  why is the font size changing for different  language ,I guess #1067 solved this problem or is it a old screen recording before upstreaming.Also run `flutter analyze --no-pub` to check and remove unused imports.

**Comment by ayush-mahawar26** [comment]
@nishnatadebnath 
I have make some Changes again , to fix that font size issue 
I don't think so that font is changing now , if you also feel the same please guide me how I can recreate the PR , as Im a beginner

https://user-images.githubusercontent.com/65828946/147278363-36de478b-4cc8-4fe9-a984-e1c029dff310.mp4

**Comment by palisadoes** [comment]
Please fix your conflicting files

**Comment by ayush-mahawar26** [comment]
Im recreating PR after fix workflow error

**Pull request closed without merging**
