### PR TITLE
Finalize custom lint integration

### PR DESCRIPTION
**Pull request by literalEval**
**What kind of change does this PR introduce?**

- Adds a Python script to the workflow that checks if any of the changed files contains ignore directive(s) corresponding to any of custom lint rules.
- Adds the command that checks for presence of `DartDoc` compatible documentation for each field.

**Issue Number:**

Fixes: #1479 
Fixes: #1584 

**Does this PR introduce a breaking change?**

No

### CODE REVIEW

**Comment by literalEval** [comment]
@palisadoes @anwersayeed @noman2002 please review

**Comment by literalEval** [comment]
To test if everything works, without merging:

1. Fork my fork of `Talawa` and checkout to `finalize_custom_lint_integration` branch.
2. Edit any file without removing the `// ignore:...` directives and run the `check_ignore.py` script. It should assert an error.
3. Remove the `// ignore:...` directives from the changed file and run the script again. It should run without issues now.
4. Now run `flutter pub run custom_lint`. It should report error for that specific file (if documentation is not found.
5. Write documentation for each field and run the above command again. It should report `No errors found` this time.

Please confirm if each step works and report any issues otherwise. Thanks.

**Comment by literalEval** [comment]
I am having trouble getting the files that are changed during `pull_request.yaml` and it is a known issue. Work fine during `pull.yml` though.

**Comment by palisadoes** [comment]
You may want to add a delay. We've had that issue with GitHub actions in the past.

**Comment by literalEval** [comment]
@palisadoes I was able to solve the problem by giving the commits a name (by checking out to a new branch). Please analyze if you see any problem with this approach.

**Comment by palisadoes** [comment]
1. Echo the GitHub context. It's commented out in the yaml file.
2. The context variables are sometimes different for pushes and PRs. 
3. That's maybe why it's failing in one and not the other.

**Comment by literalEval** [comment]
Let me try @palisadoes , but the thing is that all the commits are `head detached` till `pull_request` and given a name only during `push` workflow. That is why we get the branch name during `push.yml` but not during `pull_request.yml`, as it doesn't exist till then.
Correct me if I am wrong.

**Comment by palisadoes** [comment]
Let me know when it's finally ready

**Comment by palisadoes** [comment]
> Let me try @palisadoes , but the thing is that all the commits are `head detached` till `pull_request` and given a name only during `push` workflow. That is why we get the branch name during `push.yml` but not during `pull_request.yml`, as it doesn't exist till then. Correct me if I am wrong.

That explains it. Thanks.

**Comment by literalEval** [comment]
@palisadoes I settled for the `creating a new branch` trick and it works fine. If you or any mentor has a better suggestion for this issue, I will be more than happy to use that one instead. 
For now, everything works and can be tested. If this looks merge-able to you after review, I will update `Contributing.md` in this PR itself too.

**Comment by literalEval** [comment]
@palisadoes the current implementation of `countline.py` only recognizes (excludes from line count) Python comments, if I understand its code correctly. 

image

I think it should be modified to recognize and exclude Dart comments too, as you might see that file's line count will grow in large amount after we enforce Doc compliance.

**Comment by palisadoes** [comment]
1. OK, please add that to the PR.

**Comment by literalEval** [comment]
@palisadoes changed `countline.py` and modified `CONTRIBUTIN.md` and `INSTALLATION.md`.

**Comment by literalEval** [comment]
@palisadoes please ask some volunteers to test before merging. Thanks.

**Comment by palisadoes** [comment]
1. Can you ask on the #talawa channel? 
1. I'm swamped

**Comment by literalEval** [comment]
@palisadoes please merge. I have slack message ready.

**Pull request merged**
