### PR TITLE
Auto gen doc

### LINKED ISSUE #1216: CI/CD pipeline for generating JSDoc artifacts used for automating documentation
Following https://github.com/PalisadoesFoundation/talawa/issues/1215, create a pipeline to run the `dart doc` command for any files that get approved in a pull request. After the command has been run, the artifact HTML files generated from this should then be added via a pull request to the path `docs/talawa/` in the Talawa Docs repo (https://github.com/PalisadoesFoundation/talawa-docs).

**Parent Issue**
- https://github.com/PalisadoesFoundation/talawa-docs/issues/189

**Sister Issue**
- https://github.com/PalisadoesFoundation/talawa/issues/1215

### PR DESCRIPTION
**Pull request by CyberWake**
**What kind of change does this PR introduce?**
This PR adds in the automatic generation of documentation via help of a Github Action using `dart doc`(older version `dartdoc`) command and uses artifact action to collect the artifacts generated to store them as reference plus add them to the codebase inside `docs/talawa/` directory.

**Issue Number:**
Fixes #1216 

**Did you add tests for your changes?**
Not required

**If relevant, did you update the documentation?**
Not required for now.

**Summary**
This action adds the documentation whenever a push is being made to Github for branches other than `main` and `develop`

**Does this PR introduce a breaking change?**
No, this PR does not bring in breaking changes.

**Other information**
This PR is not alone a stand alone success as there is a need for script to check if the modified file has updated documentations or not. Which is going to be handled in the issue #1215 
Plus I will be creating a separate PR to enable the `Checking workflow files` workflow. 
!--Add extra information about this PR here-->

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**
Yes, I have read the contribution guidelines.

### CODE REVIEW

**Comment by CyberWake** [comment]
@palisadoes can you please help me out why is the code coverage percent not passing even though I haven't changed any dart file still it is getting shrink by 0.002% and as a result the action is failing let me know what should I do in this case.

**Review by palisadoes — CHANGES_REQUESTED** [review]
@CyberWake Why are there 2,282 files in this PR when there are only 202 files under the `lib/` folder? Did you include the `Talawa-API` and and `Talawa-Admin` repos?

Is it because we now have one html file per class, method and function?

**Comment by CyberWake** [comment]
> @CyberWake Why are there 2,282 files in this PR when there are only 202 files under the `lib/` folder?

This basically happens due to the fact it link the documentation for all the dependencies as well.

**Comment by palisadoes** [comment]
> > @CyberWake Why are there 2,282 files in this PR when there are only 202 files under the `lib/` folder?
> 
> This basically happens due to the fact it link the documentation for all the dependencies as well.

Should we be including the dependencies as part of our documentation? It would be better for the dependencies to document their code themselves. We should only be documenting what we can control. What do you think?

Is there a way to exclude the dependencies?

**Comment by CyberWake** [comment]
> > > @CyberWake Why are there 2,282 files in this PR when there are only 202 files under the `lib/` folder?
> > 
> > 
> > This basically happens due to the fact it link the documentation for all the dependencies as well.
> 
> Should we be including the dependencies as part of our documentation? It would be better for the dependencies to document their code themselves. We should only be documenting what we can control. What do you think?
> 
> Is there a way to exclude the dependencies?

There should be a way I am researching on the point by the time we could have this PR merged since this satisfies the points mentioned in the issue.

**Comment by CyberWake** [comment]
@palisadoes have looked into the generated doc. Basically the addition of so many files would get clear once you run the following command `dart pub global activate dhttpd` then `dhttpd --path docs/talawa` on the feature branch.
The number of files is so large due to the first time doc generation in addition to this what happens is that the class have properties and properties of classes themselves have doc page so this goes on with a combinatorial problem. 

I feel this could be avoided with the dart documentation annotations which are needed to be placed in the individual files to mark that the documentation of relative entity is not needed to be generated.

**Comment by palisadoes** [comment]
Though your solution meets the requirements of the issue, the spirit of what we need has not been achieved. It is implicit that we only want to document code that our contributors directly add to the repo. The dependencies do not meet this requirement. Please update this PR with code that makes our project better.

@DMills27 Please note.

**Comment by palisadoes** [comment]
> @palisadoes have looked into the generated doc. Basically the addition of so many files would get clear once you run the following command `dart pub global activate dhttpd` then `dhttpd --path docs/talawa` on the feature branch. The number of files is so large due to the first time doc generation in addition to this what happens is that the class have properties and properties of classes themselves have doc page so this goes on with a combinatorial problem.
> 
> I feel this could be avoided with the dart documentation annotations which are needed to be placed in the individual files to mark that the documentation of relative entity is not needed to be generated.

I realize that it is a one time addition of 2000 files, but the issue is that Google is going to index the documents and we could be asked by totally unrelated developers to fix dependencies. This has two disadvantages:

1. Our documentation could be viewed as a click-bait site
1. People will think we don't know what we are doing

We have to consider our reputation external to the code we produce.

**Comment by palisadoes** [comment]
Can these commands that clean up the doc tree be included in the GitHub Action?

**Comment by CyberWake** [comment]
> Can these commands that clean up the doc tree be included in the GitHub Action?

So basically the docs generated every time would be same until we enforce the contributor to add the doc for the relative changes which is a separate issue. Until then each time the action runs the same files are generated and commited in the branch.

**Comment by palisadoes** [comment]
@Dev-Dominic @xsh2047 Please review. Ritik and I spoke on slack. This is OK.

**Review by palisadoes — APPROVED** [review]

**Review by DMills27 — APPROVED** [review]
This PR meets the requirements set out in the ticket

**Pull request merged**
