### PR TITLE
Added Spinner to Join Button

### LINKED ISSUE #172: Adding loading Spinner to join button
As the user press the `join` button, to make the app user interface responsive, the presence of a loading spinner at the `join` button after the dialogue box will make the page transition experience better for the user.

### PR DESCRIPTION
**Pull request by adithyaakrishna**
**What kind of change does this PR introduce?**

Improving the Experience of the Join an Organization Page

- The `CircularProgressIndicator` was added to the` join` button to improve the user experience 

**Did you add tests for your changes?**
Yes, the change was tested in Android systems and does not break anything.

**Summary**

The main motivation was to make the page transition better and improve the experience

This PR is related to Issue and Fixes #172

### CODE REVIEW

**Comment by Sagar2366** [comment]
@adithyaakrishna seems like you pulled master changes and pushed all updated files from local system.
Can you please send only files which are required to fix this issue ?

**Comment by adithyaakrishna** [comment]
@Sagar2366 I've sent those files only right now, and also there were some conflicts which I have resolved :)

**Comment by Sagar2366** [comment]
@adithyaakrishna Travis ci is failing, have a look.

**Comment by adithyaakrishna** [comment]
Hey @Sagar2366 ,  I Have Fixed it and resolved the conflict too

**Review by Sagar2366 — APPROVED** [review]

**Pull request merged**
