### PR TITLE
Adding admins is no longer an option in create new event

### LINKED ISSUE #1600: Disable a user being added to an event if they have already been added
**Is your feature request related to a problem? Please describe.**
In the 'Add Event' page fix the bug that allows the user to add a user that is already added.Also, remove the distinction of them being an admin or not as it is irrelevant.

**Describe the solution you'd like**

Follow the steps outlined here till 9:42
[Follow the steps outlined here](https://www.youtube.com/watch?v=ix3eSReJj2k?t=538)

As shown in the screenshot below form a single list instead of separating it into "members" and "admin" and prevent a user that has already been added from being added again.

Screenshot at Mar 01 22-02-06

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by Kushalrock**
**What kind of change does this PR introduce?**
Bug Fixes and unnecessary code removal

**Did you add tests for your changes?**
Tests updated to reflect the changes

**Issue Number:**
Closes #1600 

**Have you read the [contributing guide]**
Yes

**Summary**
As administrative functions will not be handled by the app the section Select Admins was no longer valid in creating events and several lists associated with it.

### CODE REVIEW

**Comment by palisadoes** [comment]
1. Please update the title of the PR so that it easier to understand what your intention is. It will help with searches in future.
1. Please fix any failing tests

**Comment by Kushalrock** [comment]
@palisadoes Can you please check again and let me know I have done the required change and also looked into workflow failing and made changes.

**Comment by palisadoes** [comment]
- It is not that we don't want admins added to events.
- We want them to be able to be added, we just don't want all three invited to be grouped together in the interface.

Is this what you have done?

**Comment by Kushalrock** [comment]
> * It is not that we don't want admins added to events.
> * We want them to be able to be added, we just don't want all three invited to be grouped together in the interface.
> 
> Is this what you have done?

Yeah I mean you can add any member from the organization to the event as members

**Comment by palisadoes** [comment]
That is not what you have stated in the comment and heading off the PR. You specifically said that admins cannot create events.

We don't want administrative functions in the mobile app. That doesn't mean that a person who happens to be an admin using the mobile app cannot do anything. They just have to use Talawa Admin to manage things.

Please be very precise in your PR and issue descriptions. This is the second time I have mentioned this to you.

You have also removed large sections of our testing code. 

We pride our community in being professional in their contributions.

I'm going to close this PR. Please create a new one that does what is stated we need in the video and maintains the levels of code coverage we need with valid testing.

We will also require a screen shot of the code coverage report if it is not automatically generated.

Please be more careful. It's a learning process we all have experienced in the industry.

**Pull request closed without merging**
