### PR TITLE
Fixes #1133 Unittests for widget event_search_delegate.dart

### LINKED ISSUE #1133: Unittests for widget event_search_delegate.dart
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

We will need unittests done for all methods, classes and functions found in this file.

Any widgets referenced in this file must also have unittests done

```
event_search_delegate.dart
```

This file can be found in the `lib/widgets` directory

Parent Issue: 
- https://github.com/PalisadoesFoundation/talawa/issues/1125

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base.
- [The current code coverage for the file can be found here](https://codecov.io/gh/PalisadoesFoundation/talawa/tree/develop/lib/widgets)
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide

### PR DESCRIPTION
**Pull request by Ayush0Chaudhary**
**What kind of change does this PR introduce?**
Unittests for widget event_search_delegate.dart

**Issue Number:**

Fixes #1333

**Did you add tests for your changes?**
YES

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**
NO

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**
YES

### CODE REVIEW

**Comment by Ayush0Chaudhary** [comment]
@palisadoes @noman2002 please review the PR

**Comment by noman2002** [comment]
@Ayush0Chaudhary Please attach code coverage screenshot.

**Comment by palisadoes** [comment]
We'll need to merge https://github.com/PalisadoesFoundation/talawa/pull/1474 before merging this PR.

**Comment by Ayush0Chaudhary** [comment]
Screenshot from 2023-02-09 03-12-23
@noman2002 @palisadoes

**Comment by palisadoes** [comment]
1. We are going to have delay any potential merge until this PR is complete https://github.com/PalisadoesFoundation/talawa/pull/1474
1. It may cause minor merge conflicts, so be prepared

**Review by noman2002 — APPROVED** [review]

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
