### PR TITLE
UI improvements on Login and Registration page

### PR DESCRIPTION
**Pull request by AniketSindhu**
For issue #118 
1. Textfield's border was not visible when out of focus due to the background image. Changed TextField's border and icon color to grey when out of focus.
2. "Sign in!" and "Sign up!" text's visibility was very less. Changed font-weight to bold and underlined the texts.

# Before
Login Page                  |          Registration page
:-------------------------:|:-------------------------:
|| 

# Now
Login Page                  |          Registration page
:-------------------------:|:-------------------------:
||

### CODE REVIEW

**Comment by jordanliu** [comment]
Please link an issue before creating a PR

**Comment by AniketSindhu** [comment]
I created an issue but someone told me to discuss it on slack so I closed that

**Comment by DeltaHarbinger** [comment]
Hey @AniketSindhu. I reviewed the issue that you previously created and closed. I believe it's fine for you to re-open and link it here. This pull request can be accepted and merged as an incremental change while we review the design of the entire application.

Please link your issue so that I can merge this

**Comment by AniketSindhu** [comment]
#118 reopened the issue. @DeltaHarbinger

**Review by DeltaHarbinger — CHANGES_REQUESTED** [review]
Hey @AniketSindhu , thanks for reopening the issue. As a quick change before I merge, can you revert all changes you made to '.flutter-plugins-dependencies' as it is a file that should be ignored by version control? Once that is reverted, we can merge this branch

**Comment by AniketSindhu** [comment]
@DeltaHarbinger is it fine now?

**Review by DeltaHarbinger — APPROVED** [review]
It seems to be fine now. This will be merged

**Pull request merged**
