### PR TITLE
Feat: Important additions to CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by CoderMayhem**
**What kind of change does this PR introduce?**
This PR aims to add important guidelines for new contributors by laying out some ground rules for maintaining their project structure and efficiently naming their commits to the repo. This will prevent any unnecessary structure disruptions and will save time and efforts of both the contributors as well as the reviewers. 

**If relevant, did you update the documentation?**
Yes

### CODE REVIEW

**Comment by Sagar2366** [comment]
I would like to see commands for each instructions to raise PR for issue/feature. Can you add those in this pr and send it again for review ?

**Comment by CoderMayhem** [comment]
Can you please elaborate on this? I did not understand what you exactly want. @Sagar2366

**Comment by Sagar2366** [comment]
Sure. In contributing code section, please add commands to clone the repo, adding new/updated files, commit and push files, etc.

**Comment by CoderMayhem** [comment]
Ohh okay. Got it. Thanks for clarification.

**Comment by CoderMayhem** [comment]
@Sagar2366 kindly have a look. Let me know if anything else is needed.

**Comment by Sagar2366** [comment]
Perfect 👍

**Pull request merged**
