### PR TITLE
[Fix] - Navigation fix after signup on creating new organization

### PR DESCRIPTION
**Pull request by CyberWake**
**What kind of change does this PR introduce?**
Perfect navigation on new user successful signup and create or join organization

**Did you add tests for your changes?**
Yes, have tested it on both android and iOS simulator

**If relevant, did you update the documentation?**
No, need to update the documentation
**Summary**
Major functionality of app came to live because without bottom navbar app was almost dead or void.

After successful signup and on creation on new account creation there was a bug in navigation. For more see #377 

#377 bug was introduced after the merge of #327 

**Does this PR introduce a breaking change?**
No, this does not bring breaking changes

**Other information**
This is the against the issue #377

### CODE REVIEW

**Comment by Sagar2366** [comment]
@CyberWake tried to reproduce the issue on master.
Seems like issue is still not fixed in this PR. 
Can you please share Video/snapshots visuals to confirm it is fixed ?

**Comment by CyberWake** [comment]
> @CyberWake tried to reproduce the issue on master.
> Seems like issue is still not fixed in this PR. 
> Can you please share Video/snapshots visuals to confirm it is fixed ?

Sure sir sharing here.

**Comment by CyberWake** [comment]
**On organization joining flow:**
[Watch the video](https://user-images.githubusercontent.com/44184786/111857330-b9a93900-8956-11eb-9a2d-1bf424d63c91.mp4)
**On organization creation flow:**
[Watch the video](https://user-images.githubusercontent.com/44184786/111857321-a8f8c300-8956-11eb-99e4-77a06c874b36.mp4)

**Comment by Sagar2366** [comment]
@CyberWake have you noticed now application is throwing error in organization creation flow and taking time to load organizations in both the flows -

Screenshot 1942-12-29 at 9 17 27 AM

**Comment by CyberWake** [comment]
@Sagar2366 sir can you try again like I have tested it navigator has a history image in both the organization join flow on login and in joining from profile. attaching a demo.
**Demo:**
[Watch the video](https://user-images.githubusercontent.com/44184786/111858946-f713c380-8962-11eb-8965-b7b3275e34d4.mp4)

**Comment by Sagar2366** [comment]
> @Sagar2366 sir can you try again like I have tested it navigator has a history image in both the organization join flow on login and in joining from profile. attaching a demo.
> **Demo:**
> [Watch the video](https://user-images.githubusercontent.com/44184786/111858946-f713c380-8962-11eb-8965-b7b3275e34d4.mp4)

Can you share demo video for organization creation flow as well ? Because I observed this behaviour in organization creation flow.

**Comment by CyberWake** [comment]
sure @Sagar2366 sir

**Comment by CyberWake** [comment]
**Demo of the create organization flow from the profile page:**
https://user-images.githubusercontent.com/44184786/111861622-d2751700-8975-11eb-8eef-92c3cfae5069.mp4

**On organization creation flow from signup:**
[Watch the video](https://user-images.githubusercontent.com/44184786/111857321-a8f8c300-8956-11eb-99e4-77a06c874b36.mp4)

**Review by Sagar2366 — APPROVED** [review]

**Pull request merged**
