### PR TITLE
App localization and language controller addition

### LINKED ISSUE #799: Develop a Language Localization File
**Is your feature request related to a problem? Please describe.**
This is a child of issue #798

**Describe the solution you'd like**
Develop language notifier and localization delegate file to enable language modifications within the app.

### PR DESCRIPTION
**Pull request by sumitra19jha**
**What kind of change does this PR introduce?**
feature closes #799 

**Did you add tests for your changes?**
Not needed here

**If relevant, did you update the documentation?**
Not needed here

**Summary**
App Localization file to load user preferred language file and controller to make sure user can switch language as per their convenience. 

**Does this PR introduce a breaking change?**
No

**Other information**

### CODE REVIEW

**Comment by palisadoes** [comment]
@dellyjm
@DeltaHarbinger 
@TheHazeEffect 

Could one of your please take a look at this? It's a GSoC PR

**Comment by palisadoes** [comment]
@sumitra19jha please resolve the conflict with: `lib/views/pages/newsfeed/newsfeed.dart`

**Review by DeltaHarbinger — APPROVED** [review]
This seems like a good initial commit for the feature. We may need to remove hard coded values such as the supported languages array, but that may be done at a later date.

**Comment by sumitra19jha** [comment]
@DeltaHarbinger The hard-coded string is part of issue #800 
That is the reason why I have not included it in this PR.
It will be done, once this PR is merged.

**Comment by palisadoes** [comment]
@sumitra19jha `flutter test` is not working correctly on your code. This is causing Travis CI to fail. 

1. Follow the steps in the GitHub site's [Checking out pull requests locally](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/reviewing-changes-in-pull-requests/checking-out-pull-requests-locally) web page.
2. Resolve the conflicts, which appear related to `pubspec.yml`
3. Resubmit your pull request.

The error can be seen below

image

**Comment by palisadoes** [comment]
@sumitra19jha [It's a slightly different issue now.](https://travis-ci.org/github/PalisadoesFoundation/talawa/builds/771841407) Please resolve. We should be close to getting this fixed.

```
12.01s$ travis_apt_get_update
0.00s
git.checkout
1.35s$ git clone --depth=50 https://github.com/PalisadoesFoundation/talawa.git PalisadoesFoundation/talawa
0.01sDart for Travis-CI is not officially supported, but is community maintained.
Please file any issues using the following link
  https://travis-ci.community/c/languages/dart
and mention `@athomas` and `@a14n` in the issue
$ export PUB_ENVIRONMENT=travis
dart_install
Installing Dart on linux
cache.1
Setting up build cache
$ dart --version
Dart SDK version: 2.13.0 (stable) (Wed May 12 12:45:49 2021 +0200) on "linux_x64"
install.1
15.21s$ git clone https://github.com/flutter/flutter.git -b stable
install.2
34.18s$ ./flutter/bin/flutter doctor
3.85s$ ./flutter/bin/flutter test
Running "flutter pub get" in talawa...                                 ⡿       ⣽       ⣯Because every version of flutter_driver from sdk depends on crypto 3.0.1 and graphql >=3.1.0-beta.4 <4.0.0-alpha.0 depends on crypto ^2.1.3, flutter_driver from sdk is incompatible with graphql >=3.1.0-beta.4 <4.0.0-alpha.0.
And because graphql_flutter >=3.1.0 <4.0.0-alpha.0 depends on graphql ^3.1.0, flutter_driver from sdk is incompatible with graphql_flutter >=3.1.0 <4.0.0-alpha.0.
So, because talawa depends on both graphql_flutter ^3.1.0 and flutter_driver any from sdk, version solving failed.
                                       ---- Log transcript ----
FINE: Pub 2.13.0
MSG : Resolving dependencies...
SLVR: fact: talawa is 1.0.0+1
```

image

**Comment by sumitra19jha** [comment]
Yes @palisadoes 
I am trying to figure this out

**Comment by sumitra19jha** [comment]
@palisadoes Done

**Pull request merged**
