### PR TITLE
Fixes issue #1031

### LINKED ISSUE #1031: [Terminological error]  Misplaced description in `set_url_page_test.dart`
**Describe the bug**
While checking out the test files, I found a bug. Here it is "Testing if login button works" while it should be for the signup button.
**To Reproduce**

1. Open test/widget_tests/pre_auth_screens/set_url_page_test.dart
2. find the bug in lines 277 and 488

**Screenshots**
Screenshot (120)

**Additional details**
I would like to work on the issue @palisadoes pls assign me.

### PR DESCRIPTION
**Pull request by Simran1604**
**What kind of change does this PR introduce?**
bugfix

**Issue Number:**

Fixes #1031 

**Does this PR introduce a breaking change?**
No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by palisadoes** [comment]
@Simran1604, @sumitra19jha, @Sagar2366 should `.flutter-plugins-dependencies` be removed from the repo and a `.flutter-plugins-dependencies` entry added to `.gitignore`

**Comment by Simran1604** [comment]
> @Simran1604, @sumitra19jha, @Sagar2366 should `.flutter-plugins-dependencies` be removed from the repo and a `.flutter-plugins-dependencies` entry added to `.gitignore`

Yes, Sir I think that would be better.

**Comment by palisadoes** [comment]
Thanks @Simran1604 I've added the entry to `.gitignore`. Please:
- Resync your repo / branch with our `upstream/develop`
- Merge with the code for this PR
- Push the code you your repo
- The PR will be automatically updated.

This should get rid of the conflicting files error.

image

**Comment by Simran1604** [comment]
@palisadoes I can't fetch upstream and merge as there are conflicts so shall I create another branch and then open a pull request?

**Comment by palisadoes** [comment]
> @palisadoes I can't fetch upstream and merge as there are conflicts so shall I create another branch and then open a pull request?

Yes, that is another option.

**Review by CyberWake — APPROVED** [review]
Terminology correction as stated in the issue against the PR is resolved.

**Review by palisadoes — CHANGES_REQUESTED** [review]
@Simran1604 Please add the `.flutter-plugins-dependencies` file  to `.gitignore` and resubmit.

The very first line of the file states:

```
This is a generated file; do not edit or check into version control
```

We should therefore not include it.

**Comment by palisadoes** [comment]
@Simran1604 Our code base has changed. Please merge you code with `upstream/develop` and resubmit. The changes made make most of our tests run on `pull_request` and not all on `pull_request_target` as you see in the image of the PR tests. This was causing us significant problems with successful testing sequencing and execution. The changes we just made should fix this. We are in effect, testing the test regime changes.

image

**Comment by Simran1604** [comment]
I'm making another PR for this as the conflicts can't be resolved in this PR.

**Pull request closed without merging**
