### PR TITLE
Use new env secrets in push workflow to make docs work again.

### LINKED ISSUE #1768: Updating Talawa-Docs with DartDoc markdown files fails
**Describe the bug**
We recognized that Talawa-Docs was not getting updated as expected in this issue:

- https://github.com/PalisadoesFoundation/talawa/issues/1750

However, documentation is not getting updated as expected. The push workflow created is not working and needs to be rectified:

- [push.yaml](https://github.com/PalisadoesFoundation/talawa/blob/develop/.github/workflows/push.yaml)

**To Reproduce**

All our pushes are failing. This needs to be fixed.

- https://github.com/PalisadoesFoundation/talawa/actions

**Expected behavior**

See Above

**Actual behavior**

See Above

**Screenshots**

N/A

**Additional details**

N/A

### PR DESCRIPTION
**Pull request by literalEval**
**What kind of change does this PR introduce?**

Uses newly generated env secrets in order to make automatic docs updation in `Talawa Docs` work again.

**Issue Number:**

Fixes #1768

### CODE REVIEW

**Comment by literalEval** [comment]
@palisadoes please merge to test if this works.

**Review by palisadoes — APPROVED** [review]

**Comment by palisadoes** [comment]
The push seems to have failed.

https://github.com/PalisadoesFoundation/talawa-docs/actions/runs/4680880922

**Comment by literalEval** [comment]
I too was looking into it. The changes from here are uploaded fine, so I think this repo's part is good. And about the push fail in `Talawa Docs`, my initial view says that the errors are due to a large number of file changes in a single PR. I will look at the error in depth and try to resolve that in `Talawa Docs` itself.

**Comment by palisadoes** [comment]
Can you create one with a minor change?

**Comment by literalEval** [comment]
Okay. Will do real quick :)

**Comment by literalEval** [comment]
Meanwhile I also found an issue which existed previously. There are 2 doc locations in the `Talawa Docs` repo (the second one probably came to existence when the docs workflow was implemented and the folder was assigned to it). One of it is in `static/talawa` and the other is in `static/talawa/talawa` (an extra talawa). Fixing that too.

**Pull request merged**
