### PR TITLE
Keyboard closing on direct clicking on set URL button

### PR DESCRIPTION
**Pull request by CyberWake**
**What kind of change does this PR introduce?**
Closes the keyboard if the user directly clicks on the set URL button **[Bug-Fix]**
Also this one auto fills the fields correctly previously name and last name field took the same autofill value. **[Bug-Fix]**
Auto focusing next field on submission of previous one in registration form. **[Enhancement]**

**Did you add tests for your changes?**
Yes, tested it.
**If relevant, did you update the documentation?**
No need to update documentation
**Summary**
The merge helps in enhancing the UX and releasing un used resources

**Does this PR introduce a breaking change?**
No, this PR merge won't cause breaking changes

**Other information**
#269

### CODE REVIEW

**Comment by Sagar2366** [comment]
LGTM. Please resolve the conflicts and send PR again for review.

**Comment by CyberWake** [comment]
@Sagar2366 Resolved the conflicts please review and merge.😊

**Comment by Sagar2366** [comment]
Screenshot 1942-12-24 at 3 08 05 PM

Please make sure your PR is not breaking previous changes before sending it for review.
Check attached snap, getting this error on your PR after you resolved the conflicts.
Can you please recheck it once and send PR again for review ?

**Comment by CyberWake** [comment]
@Sagar2366 sir can you give it a last try. I have fixed all these breaking points.

**Comment by Sagar2366** [comment]
Throwing same error. Please test the changes on your end before sending it for review.

**Comment by CyberWake** [comment]
Are the build errors arising again for the same issues.

> Screenshot 1942-12-24 at 3 08 05 PM
> 
> Please make sure your PR is not breaking previous changes before sending it for review.
> Check attached snap, getting this error on your PR after you resolved the conflicts.
> Can you please recheck it once and send PR again for review ?

@Sagar2366 sir are these still there? or is there something new because I have checked it twice. Everything is working fine.

**Review by Sagar2366 — APPROVED** [review]

**Pull request merged**
