### PR TITLE
Implement custom lint

### PR DESCRIPTION
**Pull request by literalEval**
Regenerated pub dependency hashes.

### CODE REVIEW

**Comment by literalEval** [comment]
@palisadoes @noman2002 please merge again. I should pass this time as I have regenerated the pub hashes.

**Review by palisadoes — APPROVED** [review]

**Comment by palisadoes** [comment]
It failed again. It's this a one time thing or will something else need to be done after reverting?

**Comment by literalEval** [comment]
@palisadoes the error says that the analysis server crashed, but no such thing happens for me locally. `flutter pub get` runs perfectly according to the error log and the error happens when the analyzer starts running. For one last time, I am commenting out the line that tells flutter about our custom lint rules. If this time it works, I'll fix this issue in the followup tasks, otherwise I'll need to pair up with someone so that we can see if they can reproduce the issue on their laptop or not.

Most probably what is happening is that `flutter pub get` is not running inside our small `talawa_lint` package and that's why it fails. For it to run in there, we'll need to `cd` in that and run `flutter pub get` there. But for now, I am just commenting a few lines and see if that works.

**Comment by literalEval** [comment]
But surprisingly no such error occurs when the same commands run during `pull-request.yaml`

**Comment by literalEval** [comment]
@palisadoes maybe the dart sdk used in `push.yaml` is a bit older ? Because the latest one is `2.19.2` but the actions uses `2.18.0`.

Can we please verify one other's machine before reverting it ?

**Comment by literalEval** [comment]
@palisadoes but still, I have opened a PR [here](https://github.com/PalisadoesFoundation/talawa/pull/1579/) in which I have commented some things. Please take the decision of reverting it based on your understanding. Since that specific version of dart is not used in `pull-request.yaml`, there is no way for me to actually test whether it will fail during `push.yaml` or not.

**Pull request merged**
