### PR TITLE
[Fix] - Member page gets automatically refreshed on create/join/switch/leave(ing) organization #514

### PR DESCRIPTION
**Pull request by CyberWake**
**What kind of change does this PR introduce?**
This PR resolve the issue marked in #514 . On switch/join/creating/leaving organization the member page gets refreshed with the new list of members in all cases. And if the user is not a member of any organization he is shown a page asking him to join one. If there is any issue with internet or data not being fetched due to some issue. He is shown with the refresh button only if he is present in any organization.

**Did you add tests for your changes?**
Yes, test added. There could we some updates in them as well.

**If relevant, did you update the documentation?**
Not needed.

**Summary**

 | [**Earlier**](https://user-images.githubusercontent.com/44184786/112527539-2e51fc80-8dc9-11eb-82a4-1f2bfa7de748.gif)      | [**Now**](https://user-images.githubusercontent.com/44184786/112591659-ab618e00-8e2a-11eb-8f48-b0ff29444c4d.gif)     | 
|------------|-------------| 
|  <kbd></kbd> |  <kbd></kbd> |

This PR resolves the issues related to change in current organization on member screen. Plus the changes incorporated to resemble the changes on other tabs that show data depending on current organization.
This PR is made under the issue #514 

**Does this PR introduce a breaking change?**
No, it does not bring breaking changes.

**Other information**
Linked issue #514

### CODE REVIEW

**Comment by CyberWake** [comment]
Linked issue #514

**Comment by Sagar2366** [comment]
@CyberWake have you added tests for these changes in your PR ?
Can you please send changes required to fix this issue only ? disable auto-formatter before sending PR for review.

**Comment by CyberWake** [comment]
> @CyberWake have you added tests for these changes in your PR ?
> Can you please send changes required to fix this issue only ? disable auto-formatter before sending PR for review.

Test have been added for the current minor changes. There would a patch of updates after some of the other PR out there because they also tend to have changes in the same file.
Will turn off the auto formatter next time.

**Comment by CyberWake** [comment]
@Sagar2366 sir please review the PR 😊

**Comment by Sagar2366** [comment]
@CyberWake there are some conflicts on this PR, resolve them.
Did you add changes to 10 files, turn off auto-formatter and send PR with only changes required to fix the issue.

**Comment by Sagar2366** [comment]
@CyberWake any update on this PR ?

**Comment by CyberWake** [comment]
@Sagar2366 sir resolved the conflicts please review it. 😊

**Comment by CyberWake** [comment]
Any updates on this @Sagar2366 sir

**Comment by Sagar2366** [comment]
Looks like you pulled master changes and send every new change added with your PR.
Send only changes which required to fix this issue you currently working on.
Make sure to disable code auto-formatter, do not remove any existing test cases, code if not required.

**Comment by CyberWake** [comment]
> Looks like you pulled master changes and send every new change added with your PR.
> Send only changes which required to fix this issue you currently working on.
> Make sure to disable code auto-formatter, do not remove any existing test cases, code if not required.

sir I have disabled the auto formatting. Changes visible are not available on master. Branch master was pulled to resolve the merge conflicts arising after too many PR getting merged.

**Comment by Sagar2366** [comment]
@CyberWake please open new PR with only your changes to fix this issue (no code auto formatting, no changes from other PR's should come under this PR).
Update test cases wherever required.

**Comment by CyberWake** [comment]
> @CyberWake please open new PR with only your changes to fix this issue (no code auto formatting, no changes from other PR's should come under this PR).
> Update test cases wherever required.

Ok sir.

**Comment by CyberWake** [comment]
Closing this one opened a new PR #607. @Sagar2366 sir please review.

**Pull request closed without merging**
