### PR TITLE
Added Hero Animation Transition in NewsFeed

### PR DESCRIPTION
**Pull request by rutvik11062000**
Against Issue:  #316

Description:
Added Hero Animation in the news feed thumbnail.
Dynamic hero tags if the post model contains pictures in the future.

Does this PR introduce a breaking change?
No, this does not bring breaking changes to the existing code base

### CODE REVIEW

**Comment by CyberWake** [comment]
Can you please provide at least some description about the work done. That would help everyone to look into the feature added.😊

**Comment by rutvik11062000** [comment]
I've removed the conflicts caused due to recently merged PR.

**Comment by jordanliu** [comment]
Hey @rutvik11062000, seeing how that we are in the process of redesigning how Talwa looks - I don't think it's currently necessary to animate things that will be refactored.

**Comment by rutvik11062000** [comment]
Okay @jordanliu , So should I close this PR for now?

**Pull request closed without merging**
