### PR TITLE
Fix userType (Fixed SignUp and LogIn)

### LINKED ISSUE #2373: Mobile: Fix the usage of userType
### NOTE

1. This issue will require close coordination with persons assigned issues in the reference section.
2. You may find it easier to split responsibilities in a different way than proposed here to be more efficient is creating the goal

**Describe the bug**

1. The schema doesn't apply a person's `userType` by organization. 
1. The `userType` is currently a part of the `User` definition not part of a `userOrganization` definition or something similar. 
    1. This means that an `Admin` is an `Admin` for all organizations which grants the same rights as a `SuperAdmin`. This is not the intention.
    2. This has created historical confusion in the `Admin` and `SuperAdmin` roles.

This needs to be resolved as it is a showstopper bug.

**Expected behavior**

These conditions must apply:

1. The `userType` must be applied per person per organization.
2. Each `SuperAdmin` must be a `SuperAdmin` for all organizations
3. All other `userType`s would be on a per organization basis

This means that all code logic referencing the `userType` will need to be updated accordingly.

_TALAWA API_

Additional considerations include:

1. New user registrations will need to default to the `userType` `USER` if not done so already
1. The Schema will need to be updated to reflect this requirement
1. Mutations and queries will need to be updated and in some cases new ones added.
1. Changes must be made against the `develop-userTypeFix` branch

_TALAWA ADMIN_

Additional considerations include:

1. The current screen that edits a person's userType will need to be updated. A design is being created for this and will be reflected in the Figma file on our Design Guide page:
    1. https://docs.talawa.io/docs/design/ux/ux-design-system
1. Changes must be made against the `develop-userTypeFix` branch

_TALAWA MOBILE_

1. Update the app to work correctly with the modified queries and mutations of the API's `develop-userTypeFix` branch.
1. Changes must be made against the `develop-userTypeFix` branch

**Actual behavior**

- The schema doesn't apply a person's `userType` by organization. 

**Screenshots**

The previouse API schema:

image

**Additional details**

Related issues and PRs:

1. _Primary_
    1. https://github.com/PalisadoesFoundation/talawa-api/issues/1711
    1. https://github.com/PalisadoesFoundation/talawa-admin/issues/1445
    1. https://github.com/PalisadoesFoundation/talawa-api/pull/1830
    1. https://github.com/PalisadoesFoundation/talawa-api/issues/1904
1. _Secondary_
    1. https://github.com/PalisadoesFoundation/talawa-admin/issues/1451
    1. https://github.com/PalisadoesFoundation/talawa-admin/issues/1452
    1. https://github.com/PalisadoesFoundation/talawa-api/issues/1862

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by Dante291**
**What kind of change does this PR introduce?**

Fixes userType in the app by adding isSuperAdmin filed in user schema.

**Issue Number:**

Fixes 2373 (not tagging issue as that will close it)

**Did you add tests for your changes?**

No

**Does this PR introduce a breaking change?**

Somewhat yeah

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by Dante291** [comment]
@palisadoes @noman2002 @AVtheking 

Instead of adding userAppProfile schema in the App I have added `isSuperAdmin ` field and have updated the fetching and storing user Info (createdOrganisation, adminFor and isSuperAdmin) have updated queries such that logIn and SignUp work properly.

Please let me know if this approach is fine or do I need to add more field from appUserProfile document?

**Comment by palisadoes** [comment]
We want no admin features in the mobile app, so you'll need to assume a user login.

**Comment by Dante291** [comment]
@palisadoes sorry but I didn't get you sir, what you meant by I will need to assume user login.

**Comment by palisadoes** [comment]
1. I was mixing up Admin where there are separate routes for Admin and User screens.
2. No admin features in the mobile app at this time. We want to keep it simple

**Comment by Dante291** [comment]
@palisadoes This is ready for review

**Comment by AVtheking** [comment]
> 1. I was mixing up Admin where there are separate routes for Admin and User screens.
> 
>     2. No admin features in the mobile app at this time. We want to keep it simple

This means we do not require adminFor field in app ?

**Comment by Dante291** [comment]
> > 1. I was mixing up Admin where there are separate routes for Admin and User screens.
> >    
> >    2. No admin features in the mobile app at this time. We want to keep it simple
> 
> This means we do not require adminFor field in app ? @Dante291 if it was previously not being used then remove it

I am gonna let this be in the userInfo schema as we might have some support for admin user type in future, this field will be helpful that time.

**Comment by palisadoes** [comment]
@noman2002 @literalEval @Ayush0Chaudhary 

Please review

**Review by Ayush0Chaudhary — APPROVED** [review]

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
