### PR TITLE
[FIX] #174/Update Profile Page

### PR DESCRIPTION
**Pull request by sumitra19jha**
**What kind of change does this PR introduce?**
Issue #174. Bug Fix

**Did you add tests for your changes?**
Yes. Below is the test video:

https://user-images.githubusercontent.com/35868598/111901782-ff9df400-8a5f-11eb-9a86-a137145469fe.mp4

**If relevant, did you update the documentation?**
No

**Summary**
The motivation of the PR is to let user update there profile

**Does this PR introduce a breaking change?**
No

**Other information**
The PR is dependent on the backend API mutation, whose PR request is made but not yet merged

### CODE REVIEW

**Comment by sumitra19jha** [comment]
Dear Mentors, 
The working of the Update Profile Page is directly dependent on PR [#172](https://github.com/PalisadoesFoundation/talawa-api/pull/172) made in talawa-api repo.

**Comment by Sagar2366** [comment]
@sumitra19jha really appreciate your work in this PR.
1. Can you change branch name, may be because it is starting with # i am not able to clone it.
2. I need this entire PR unit tested before merging it, just to make sure nothing breaks.

**Comment by sumitra19jha** [comment]
> @sumitra19jha really appreciate your work in this PR.
> 
> 1. Can you change branch name, may be because it is starting with # i am not able to clone it.
> 2. I need this entire PR unit tested before merging it, just to make sure nothing breaks.

Sure

**Comment by sumitra19jha** [comment]
@Sagar2366 By changing the name the branch was deleted and PR closed. The new PR created is #446

**Pull request closed without merging**
