### PR TITLE
Develop - coderabbit yaml

### LINKED ISSUE #2513: YAML Config for CodeRabbit AI
**Is your feature request related to a problem? Please describe.**
We recently added CodeRabbit AI for reviewing PRs, it requires us to have a YAML config file for all the settings to be followed.

**Describe the solution you'd like**
Configure using CodeRabbit YAML File

**Describe alternatives you've considered**
Configure using CodeRabbit UI

**Approach to be followed (optional)**
A clear and concise description of approach to be followed.

**Additional context**
Using the docs - https://docs.coderabbit.ai/guides/configure-coderabbit/

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by pranshugupta54**
**What kind of change does this PR introduce?**

Feature

**Issue Number:**

Fixes #2513 

**Did you add tests for your changes?**

NA

**Snapshots/Videos:**

NA

**If relevant, did you update the documentation?**

NA

**Summary**

Added YAML Config file for CodeRabbit AI using docs- https://docs.coderabbit.ai/guides/configure-coderabbit

**Does this PR introduce a breaking change?**

NA

**Other information**

NA

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by dhanagopu** [comment]
@pranshugupta54 Can you fix the failing checks ?

**Comment by pranshugupta54** [comment]
We're adding the YAML file for coderabbit to our workflows so it's going to fail.

**Comment by Cioppolo14** [comment]
@noman2002 @DMills27 Can you review thisPR ?

**Comment by pranshugupta54** [comment]
Reference: https://github.com/PalisadoesFoundation/talawa-admin/pull/1991

**Pull request merged**
