### PR TITLE
Create a new documentation website #2678

### PR DESCRIPTION
**Pull request by Mamatha1718**
## Summary by CodeRabbit

- **New Features**
  - Introduced custom CSS theming with light and dark mode support
  - Added color variables for consistent design across the application

- **Style**
  - Implemented navbar styling with hover effects
  - Created responsive color scheme for improved user experience

### CODE REVIEW

**Comment by palisadoes** [comment]
Please fix the first comment so that each issue listed automatically closes. The PR_GUIDELINES.md file has details.

Please also fill in the template for the pull request as completely as you can. It greatly helps others searching for code changes in future and helps others understand the summarized rationale for the work you have done

Also make sure the title is easily searchable for terms related to what the PR is about.

Closing

**Comment by palisadoes** [comment]
Please submit your PRs against our `develop-postgres` branch. This is a temporary requirement as we prepare to migrate our API backend to Postgres.

Also if applicable, make sure your branch name is different from `develop-postgres` when resubmitting.

Closing.

**Comment by palisadoes** [comment]
Please coordinate your CSS with @Abhi-MS. The talawa-docs site must lead the others in the design aesthetic

**Comment by Abhi-MS** [comment]
@Mamatha1718 

Please refer to the website, https://docs.talawa.io/ and repo https://github.com/PalisadoesFoundation/talawa-docs for styling. Lets collaborate more to make sure the styling looks similar and navbar looks the same for the websites we are working on.

**Pull request closed without merging**
