### PR TITLE
Issue #528 and Issue #598 fixed together

### PR DESCRIPTION
**Pull request by Hrishikesh-Bhagwat**
**What kind of change does this PR introduce?**
This PR fixes the bugs in Issue #528 and Issue #598 . This was because both were connected and the previous issue had suddenly stopped getting reproduced. But I found that that happens only in a certain case.
**Did you add tests for your changes?**
No
**If relevant, did you update the documentation?**
No
**Summary**
This PR fixes the bugs in organization search. There was an out-of-index exception and when no results were found, still the search result list was not empty.
**Does this PR introduce a breaking change?**
No

**Other information**
I fixed both issues together as they were interrelated.

### CODE REVIEW

**Comment by Sagar2366** [comment]
@Hrishikesh-Bhagwat please provide update on this PR.

**Comment by palisadoes** [comment]
Please fix merge conflicts. The code freeze has been lifted.

**Comment by palisadoes** [comment]
Please fix merge conflicts. The code freeze has been lifted.

**Comment by palisadoes** [comment]
Please fix merge conflicts. 

1. We have completely re-linted the master branch. 
1. We now have automated linting testing added to pull requests
1. We also have added Google's pendantic package to pubspec.yaml

For best results, I'll close this PR and you'll need to reopen a new bug against the master branch. 

1. The automated linting will be enabled for your work
1. We'll have better code consistency.

The code freeze has been lifted.

**Pull request closed without merging**
