### PR TITLE
enabled avoid_dynamic_calls check for post related functionalities

### LINKED ISSUE #1761: Enabling `avoid_dynamic_calls` for post related functionalities
**Describe the bug**
We need to re-enable the `avoid_dynamic_calls` check and fix the resulting bugs. However since the bugs are highly sensitive, we are creating multiple issues for different functionalities so that it becomes easier to spot any unforeseen problems.

**To Reproduce**
Run the current suite of tests, and they all pass. This is because the avoid_dynamic_calls check has been disabled

**Expected behavior**
`avoid_dynamic_calls` must be re-enabled, and all the resulting errors must be fixed.

**Actual behavior**
`avoid_dynamic_calls` is currently disabled.

**Additional details**
This is a sub-part of issue #1721 for all the post-related bugs.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by Amogh35**
**What kind of change does this PR introduce?**

bugfix

**Issue Number:**

Fixes #1761 

**Did you add tests for your changes?**

NA

**Snapshots/Videos:**

NA

**If relevant, did you update the documentation?**

Yes

**Summary**

Type casted the resulting bugs In post_nodel.dart and post_service.dart. Had to make necessary changes in chat_service.dart to accommodate the previously made changes

**Does this PR introduce a breaking change?**

No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by palisadoes** [comment]
I raised the limit to 400 lines to accommodate comments. Please sync your PR with the latest upstream. We need to make sure the tests pass before merging.

**Comment by literalEval** [comment]
@palisadoes 

1. The `countline.py` script was modified to only consider 'non-comment' lines.
2. The specific file causing the issue in this PR already had `304` lines even before this PR.

**Comment by palisadoes** [comment]
@Amogh35 the file needs to be refactored to get it below 300 lines

**Comment by Amogh35** [comment]
Yeah, once the countline.py has been correctly configured, we can see that the lines of code in this file are well below the set limit of 300.
Should I make the relevant changes in this PR itself?

**Comment by palisadoes** [comment]
@Amogh35 Please do a minor commit to trigger the GitHub actions with the new script

**Comment by Amogh35** [comment]
The error shown is because `avoid_dynamic_calls` was enabled, and the resulting bugs were fixed only in the post-related files.
Is there any way this check can be overlooked temporarily? or should I fix all the bugs through the codebase in the same PR?
However, if all the bugs are fixed together, it will be difficult to accurately find the problem in any unforeseen circumstances, as some of the code to be changed is very sensitive in nature.

**Comment by literalEval** [comment]
@Amogh35 you can suppress the warnings in other files by adding `// ignore_for_file: ...` statement in the corresponding files (if you press Ctrl + . over the fields having this issue, an option will popup to add this for you. So I think the best way will be to suppress the warning for the files you are not working on and then remove the lines and fix the issues with each respective PR.

@palisadoes thoughts ?

**Comment by palisadoes** [comment]
> @Amogh35 you can suppress the warnings in other files by adding `// ignore_for_file: ...` statement in the corresponding files (if you press Ctrl + . over the fields having this issue, an option will popup to add this for you). So I think the best way will be to suppress the warning for the files you are not working on and then remove the lines and fix the issues with each respective PR.
> 
> @palisadoes thoughts ?

OK. Create the issue to clean up the files now so that we don't forget.

**Review by noman2002 — CHANGES_REQUESTED** [review]
Please fix the failing test and conflicting files.

**Comment by Amogh35** [comment]
Sorry for the delay, i have fixed the issues, but I am facing complications in pushing the changes and some merge conflicts. I will make sure to resolve it at the earliest.

**Comment by Amogh35** [comment]
Since this PR was too messy and outdated, there were many conflicts that were difficult to resolve. I have created another PR #1780 for this issue. Could you please review that instead.

**Comment by palisadoes** [comment]
Close this PR

**Pull request closed without merging**
