### PR TITLE
Testing of chat input field and improving coverage upto 100%

### LINKED ISSUE #1406: Views: Create tests for chat_input_field.dart
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

The Talawa code base needs to be 100% reliable. This means we need to have 100% test code coverage.

Tests need to be written for file `lib/views/after_auth_screens/chat/widgets/chat_input_field.dart`

- When complete, all methods, classes and/or functions in the file will need to be tested. 
- These tests must be placed in a single file with the name `test/views/after_auth_screens/chat/widgets/chat_input_field_test.dart`. You may need to create the appropriate directory structure to do this.

### IMPORTANT:
Please refer to the parent issue on how to implement these tests correctly:

- https://github.com/PalisadoesFoundation/talawa/issues/1217

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base. This will be clearly visible when you submit your PR.
- [The current code coverage for the file can be found here](https://codecov.io/gh/PalisadoesFoundation/talawa/tree/develop/lib/views/after_auth_screens/chat/widgets/). If the file isn't found in this directory, or there is a 404 error, then tests have not been created.
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide.
- You can verify your own code coverage by creating an account at [Codecov.io](https://codecov.io)

### PR DESCRIPTION
**Pull request by Kushalrock**
**What kind of change does this PR introduce?**
Chat Input Field Test for checking the main input field

**Issue Number:**
Closes #1406 

**Have you read the [contributing guide]**
Yes

**Summary**
As mentioned in #1217 talawa mobile app needs to be very reliable and is slowly inching toward complete test coverage. This issue solves chat input field test coverage and improves it to 100%.

**Screenshots Supporting my PR:**
image

### CODE REVIEW

**Comment by Kushalrock** [comment]
@palisadoes I have completed this issue and PR but again test helpers is a long file and commenting it for documentation will be a huge task so yeah the test will fail there. Please, if possible exclude the test folders especially test helpers from documentation rules or yes a separate task or issue for test helper documentation will be a good thing.

Thank You...

**Comment by palisadoes** [comment]
@literalEval This is a showstopper bug. How's progress on this?: 

- https://github.com/PalisadoesFoundation/talawa/issues/1646

**Comment by literalEval** [comment]
@palisadoes working on priority basis. Expect to get all the sub issues of #1646 to be fixed by today EOD

**Review by noman2002 — CHANGES_REQUESTED** [review]
add documentation in test_helper.dart

**Comment by Kushalrock** [comment]
@palisadoes Can you check now?

**Review by palisadoes — APPROVED** [review]

**Review by CyberWake — APPROVED** [review]
Ready for merge.✌🏻

**Comment by Kushalrock** [comment]
@noman2002 @palisadoes I guess the thing is ready to be merged. Any comments?

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
