### PR TITLE
Refactor: Decouple ViewModel by Moving UI Logic to View

### LINKED ISSUE #2303: Bug Report:  ViewModel should not have code for View.
**Describe the bug**
The logout dialog has not called as before. The profile page view model contains the code for profile view (the logout one). It needs to be moved to the respective widget's page. View model should not have code for view.

**To Reproduce**

1. Go to profile_page_view_model.dart file 
2. You would see logout function on line no. 90

**Expected behavior**
Move the logout code to somewhere in the profile page

**Actual behavior**
The profile page view model contains the code for logout.

**Screenshots**

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by Dante291**
**What kind of change does this PR introduce?**

Refactoring the UI logic from Profile_page_view_model to profile_page.

**Issue Number:**

Fixes #2303 

**Did you add tests for your changes?**

Yes

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

No

**Does this PR introduce a breaking change?**

No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by Dante291** [comment]
@palisadoes @noman2002 @Cioppolo14 please assign reviewers.

**Comment by Dante291** [comment]
@palisadoes [this](https://github.com/PalisadoesFoundation/talawa/pull/2299) PR which recently got merged moved the Logout user logic from profile_page_view_model to app_setting_view_model but issue still persists i.e. app_setting_view_model still has UI logic which should be in app_setting_page so im gonna fix that in this PR only.

**Comment by Dante291** [comment]
@noman2002 review please

**Review by noman2002 — APPROVED** [review]
Looks fine to me.

**Comment by Dante291** [comment]
@palisadoes please review and if fine please merge so that i could work on other issues. Thanks

**Review by Ayush0Chaudhary — APPROVED** [review]

**Pull request merged**
