### PR TITLE
Post list widget test

### LINKED ISSUE #1138: Unittests for widget post_list_widget.dart
We will need unittests done for all methods, classes and functions found in this file.

Any widgets referenced in this file must also have unittests done

```
post_list_widget.dart
```

This file can be found in the `lib/widgets` directory

Parent Issue: 
- https://github.com/PalisadoesFoundation/talawa/issues/1125

### PR DESCRIPTION
**Pull request by patrickwitter**
What kind of change does this PR introduce?

Added Tests for Post list Widget
Added Post Model Mock in test helpers as a mock was necessary to complete tests

Issue Number:
Fixes #1138

Did you add tests for your changes?
Yes

Have you read the contributing guide?
Yes

### CODE REVIEW

**Review by palisadoes — DISMISSED** [review]

**Comment by palisadoes** [comment]
You'll need to fix the merge conflicts with `test/helpers/test_helpers.mocks.dart`. You may need to autogenerate it again and add it to your commit.

**Comment by patrickwitter** [comment]
@palisadoes  In order to add a model as a mock the test/helpers/test_helpers.mocks.dart will have to be auto-generated again so that may be causing the merge conflict (The addition of the mock post class while the other programmers were working on the file without the additional mock). If the merge conflict continues please note that I did not change anything except the addition of the mock class. Thus most of the changes you will see are because the entire file is autogenerated again not due to the code being modified.

**Comment by palisadoes** [comment]
> @palisadoes In order to add a model as a mock the test/helpers/test_helpers.mocks.dart will have to be auto-generated again so that may be causing the merge conflict (The addition of the mock post class while the other programmers were working on the file without the additional mock). If the merge conflict continues please note that I did not change anything except the addition of the mock class. Thus most of the changes you will see are because the entire file is autogenerated again not due to the code being modified.

The easiest way to fix the merge conflicts on an autogenerated file is to:
- checkout the branch in your local repo that you used for the PR 
- delete the file with the merge conficts
- regenerate the file
- add the updated file to a new commit
- push the commit to your repo

The PR should auto-update

**Comment by patrickwitter** [comment]
@palisadoes Good day sir I believe I  have resolved the merge conflict with the current develop branch. Please try and see if it can be merged.

**Comment by palisadoes** [comment]
The conflict checking cannot be reached as the  PR is failing with flutter formatting.
1. Please run `flutter format --set-exit-if-changed .` on your code. 
2. Make the appropriate edits until there are no more errors.
2. Update your commit.

**Comment by patrickwitter** [comment]
@palisadoes Those linting errors were introduced after I made a pull from the develop branch and are from files that I did not modify. Furthermore, those warnings were introduced due to previous commits that were merged into the codebase. Please See the GitHub checks on commit 81a1e1f312496eb248bbb704958b823b97d4195d. I tried to use the flutter format command but it did not fix those warnings. There are over 700 instances of the error so fixing them manually is not something I can do alone. So if it is possible could you make it an issue if you see fit.

**Comment by palisadoes** [comment]
The failing is due to the regeneration of the `test/helpers/test_helpers.mocks.dart` file not deleting the `pubspec.lock` file.
I'll restore the file in the meantime.

**Pull request closed without merging**
