### PR TITLE
Fixing bug to join or switch to any joined org

### LINKED ISSUE #2199: Switching organizations fails when organization exists
**Describe the bug**
- Please work with @Ayush0Chaudhary for comments, advice and review of your PR.
- Switching organizations fails even when the organization exists
- A `No organization found! Please contact your admin` message is seen

**To Reproduce**

1.  Log into the app
2. Access the left drawer to switch organizations
3. Click Join new organization
4. Select organization
5. Error occurs

**Expected behavior**
- No error should occur
- If the user is already a member of the organization, then the transition must be seamless
- If the user is not a member, then a registration screen or something similar must be viewed

**Actual behavior**
- Error occurs

**Screenshots**
- https://www.youtube.com/watch?v=86AzK_Y_GCQ&t=711s
- https://youtu.be/86AzK_Y_GCQ?t=764 This could be related to the Firebase implementation. Ideally we don't want Firebase integration. You may have to work with an API and Admin person on this.

**Additional details**
- You must get the test **_code coverage up to 100%_** for any edited files.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by Dante291**
**What kind of change does this PR introduce?**

Fix the bug to switch or join new org.

**Issue Number:**

Fixes #2199 

**Did you add tests for your changes?**

No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by Dante291** [comment]
Before: 

[before.webm](https://github.com/PalisadoesFoundation/talawa/assets/103507835/78d2758c-9f97-493c-b997-aba58c663726)



After:

[after.webm](https://github.com/PalisadoesFoundation/talawa/assets/103507835/e4d47199-50c8-448e-929f-c8a1d76b7af3)

**Comment by Dante291** [comment]
@noman2002 @Ayush0Chaudhary Should I fix the overflow error in the TalawaDialogBox in this PR or make new issue for that?

**Review by noman2002 — CHANGES_REQUESTED** [review]

**Comment by Dante291** [comment]
image

**Comment by noman2002** [comment]
> @noman2002 @Ayush0Chaudhary Should I fix the overflow error in the TalawaDialogBox in this PR or make new issue for that?

Yes, please do.

**Comment by Dante291** [comment]
@noman2002 Ok so I increased the height of talawaerrordialogbox to fit 3 lines by manually testing for different size of error message. Please review and get this merged.

**Review by noman2002 — APPROVED** [review]
Looks good to me

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
