### PR TITLE
 test added for comments_view_model.dart

### LINKED ISSUE #1022: Unittests for comments_view_model.dart
The Talawa code base needs to be 100% reliable. This means we need to have 100% unittest code coverage.

We will need unittests done for all methods, classes and functions found in this file.

Any widgets referenced in this file must also have unittests done

```
widgets_view_models/comments_view_model.dart
```

This file can be found in the `lib/view_model` directory

Parent Issue: 
- https://github.com/PalisadoesFoundation/talawa/issues/1018
### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base.
- [The current code coverage for the file can be found here](https://codecov.io/gh/PalisadoesFoundation/talawa/tree/develop/lib/view_model/widgets_view_models)
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide

### PR DESCRIPTION
**Pull request by Simran1604**
**What kind of change does this PR introduce?**
Test code

**Issue Number:**

Fixes #1022 

**Did you add tests for your changes?**
Yes

**Snapshots/Videos:**
No

**If relevant, did you update the documentation?**
No

**Summary**

**Does this PR introduce a breaking change?**
No

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by palisadoes** [comment]
@Simran1604 Your PR checks are failing during the codebase check running this command:

`flutter format --set-exit-if-changed .`

Please review

**Comment by Simran1604** [comment]
> @Simran1604 Your PR checks are failing during the codebase check running this command:
> 
> `flutter format --set-exit-if-changed .`
> 
> Please review

Yes, sir I had formatted the code. I don.t know why it is failing.

**Comment by rutvik11062000** [comment]
@Simran1604 Did you use auto generation for making mock class of view_model? If not please make it using auto generation.
Watch this: https://www.youtube.com/watch?v=5BFlo9k3KNU , we have already set up, you just have to follow this video for generating mock.

**Comment by palisadoes** [comment]
@Simran1604 are you still working on this?

**Comment by palisadoes** [comment]
Some tests are failing. Please fix

**Comment by palisadoes** [comment]
Please review and merge.

- @rutvik11062000 
- @CyberWake 
- @Sagar2366

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
