### PR TITLE
Pagination Improvement for Join/Create Organisation

### PR DESCRIPTION
**Pull request by sumitra19jha**
**What kind of change does this PR introduce?**
feature #168

**Did you add tests for your changes?**
Not required

**If relevant, did you update the documentation?**
Not required

**Summary**
Pagination Improvement for a better experience

**Does this PR introduce a breaking change?**
No

**Other information**

https://user-images.githubusercontent.com/35868598/118017325-1a139000-b374-11eb-8343-11bc502a239b.mp4

### CODE REVIEW

**Comment by sumitra19jha** [comment]
@palisadoes Please check this pagination. As we talked about in issue #168, I have removed the button and pagination will happen automatically as the user reaches the bottom of the list just like in instagram.

**Review by Sagar2366 — APPROVED** [review]

**Comment by Sagar2366** [comment]
@sumitra19jha resolve conflicts on this PR.

**Comment by sumitra19jha** [comment]
@Sagar2366 Please check sir. Conflict is resolved

**Comment by palisadoes** [comment]
@sumitra19jha please resolve the conflicts

**Comment by sumitra19jha** [comment]
@palisadoes Conflict resolved.
The PR is target to the master branch. Is it ok? or should I target it to develop

**Pull request merged**
