### PR TITLE
Reorganizing files/folders in test folder

### LINKED ISSUE #1112: Reorganizing the test files and folder for cleaner codebase
**Describe the bug**
Reconstructing the `test` folder for cleaner look and documentation.

### PR DESCRIPTION
**Pull request by nishnatadebnath**
**Issue Number:**

Fixes #1112

### CODE REVIEW

**Comment by nishnatadebnath** [comment]
The code changes are above 300 lines so will require manual merging @palisadoes

**Comment by palisadoes** [comment]
One of the test files has too many lines of code. Please fix.

**Comment by nishnatadebnath** [comment]
@palisadoes Actually I didn't make any changes just put them in respective folder,so these are previously approved codes only.

**Comment by palisadoes** [comment]
[Please edit the GitHub action for line counting](https://github.com/PalisadoesFoundation/talawa/blob/develop/.github/workflows/pull-request.yml), it's failing because of the new file location

**Comment by nishnatadebnath** [comment]
So should I increase the line count limit or remove the line counting system?

**Comment by palisadoes** [comment]
The filename is in the GitHub action file. Please modify the path.

**Comment by nishnatadebnath** [comment]
Oh sorry I didn't check they were excluded! Will do the changes

**Comment by palisadoes** [comment]
Remember the change

**Comment by palisadoes** [comment]
Are you still working on this? There are some merge conflicts and the test file needs to be excluded

**Comment by nishnatadebnath** [comment]
I will make  a new pull request with the latest upstream and closing this.Sorry for the delay .

**Pull request closed without merging**
