### PR TITLE
resolved article description clarity issue

### PR DESCRIPTION
**Pull request by pr4nshul**
**What kind of change does this PR introduce?**
Refer issue #544 . The article description was being overlaped and the text was cut into single line.

**Did you add tests for your changes?**
No
**If relevant, did you update the documentation?**

**Summary**
Now the description is clear and the widgets take space accordingly due to `flexible `widget instead of `expanded`.

**Does this PR introduce a breaking change?**

**Other information**
Screenshot_20210328-180723

### CODE REVIEW

**Comment by pr4nshul** [comment]
When I was trying the changes , I might have imported `intl` pkg automatically which is of no use now , should I push the commit for it ? or let it be

**Comment by pr4nshul** [comment]
Hey @Sagar2366 can you review this?

**Comment by Sagar2366** [comment]
> When I was trying the changes , I might have imported `intl` pkg automatically which is of no use now , should I push the commit for it ? or let it be

remove unused package.

**Comment by pr4nshul** [comment]
Done!

**Comment by pr4nshul** [comment]
Hey , @Sagar2366  If you will check the build log of Travis  CI , I am sure it isn't due to my changes as my previous commit passed the build and I have only removed the unused pkg in this one.

**Comment by pr4nshul** [comment]
Hey @Sagar2366  what can I do to update this PR , so that travis again tries to build.

**Comment by Sagar2366** [comment]
@pr4nshul Travis will run for each commit in PR.If you fix the issue and add commits to this PR, it will auto start building.

**Comment by pr4nshul** [comment]
Screenshot (8)

So , I pushed the same commit again to trigger the build. As you can see the build is passing in request in this screenshot. But why isn't it updating here on github or when you click details. I don't know. What do you think I should do?

**Comment by pr4nshul** [comment]
Screenshot (9)

Hey , @Sagar2366  The build i failing due to `updateProfilePage` . Should I close this PR, and try with the latest master?

**Comment by Sagar2366** [comment]
@pr4nshul keeping this PR on hold, once tests are updated to resolve CI issue you can pull latest changes to fix CI fail issue on this PR.

**Comment by pr4nshul** [comment]
Hey , @Sagar2366 The build passed. You can review it now 👍

**Review by Sagar2366 — APPROVED** [review]

**Pull request merged**
