### PR TITLE
updating registration of an event

### PR DESCRIPTION
**Pull request by pr4nshul**
**What kind of change does this PR introduce?**
Refer issue #188 , The register button was working fine . It was registering the user at the back end. But on the front end it seems like it wasn't.

**Did you add tests for your changes?**
No
**If relevant, did you update the documentation?**

**Summary**
I added `getEvents` once user clicks register it updates the frontend , user needed to pull to refresh before.

**Does this PR introduce a breaking change?**
No

**Other information**

### CODE REVIEW

**Comment by pr4nshul** [comment]
https://user-images.githubusercontent.com/51524156/112461981-8adff800-8d86-11eb-86d7-9f707b006f37.mp4

Updating the page once user clicks register for an event

https://user-images.githubusercontent.com/51524156/112461985-8c112500-8d86-11eb-8293-72d9cac5e600.mp4
Checking whether I was registered for the event or not.

**Comment by pr4nshul** [comment]
https://user-images.githubusercontent.com/51524156/112462152-bd89f080-8d86-11eb-8e6d-a5f4d29913c7.mp4


Checking whether I was registered for the event or not.

**Comment by Sagar2366** [comment]
@pr4nshul I am not able to reproduce this issue on master, can you please confirm with latest master you are seeing this issue ?

**Comment by pr4nshul** [comment]
Well as I have mentioned it is not an issue as such when I looked it up. When this was opened then it was definitely a issue and I saw that this was still open so I picked it up. But when I looked at the code everything was working fine. But , **yes you still need to pull to refresh. I have only changed that.** And I am calling `getEvents()` once the user click on register and the event is registered.

**Comment by pr4nshul** [comment]
and I have checked on the current master. You still need to refresh. The user should be shown registered as soon as he clicks the button otherwise he will think the button is not working until he refreshes . But actually it would be working.

**Comment by pr4nshul** [comment]
Though I would like to bring another issue to your attention, it throws `user is not verified exception on console`. If you logged in last time when you were working on the app and rebuild it and not login again. So , if you logout and login again then it would work just fine. So, if someone is working on login and logout  state of the app then, this issue would be resolved in it.

**Comment by Sagar2366** [comment]
Closing this issue as it is already fixed in recent master changes.

**Comment by pr4nshul** [comment]
Screenshot (228)

Also, while I  was working on this I received this console exception when I tried to register for the event. And what I have concluded is that if I logout and login it would work fine. So, there is some issue with login and logout state due to which after some time the user becomes unauthenticated.

**Comment by Sagar2366** [comment]
> Screenshot (228)
> 
> Also, while I was working on this I received this console exception when I tried to register for the event. And what I have concluded is that if I logout and login it would work fine. So, there is some issue with login and logout state due to which after some time the user becomes unauthenticated. @Sagar2366


@pr4nshul let's not discuss that issue here. You can open new issue for this. Continuing discussion on this thread will mix up with the original issue discussion and difficult to track progress.

**Comment by pr4nshul** [comment]
Ok.

**Pull request closed without merging**
