### PR TITLE
Implement custom lint

### LINKED ISSUE #1479: Create a documentation comment linter that is compatible with DartDoc
We recently implemented automatic updating of the [docs.talawa.io](https://docs.talawa.io) with descriptions extracted from the comments in the Talawa code base.  This creates a wide range of HTML pages that explain the [methods, functions and classes present in each file](https://docs.talawa.io/talawa/index.html).

There are limitations with this approach.
1. It relies on the code contributors to be diligent in their comments so that they can be extracted
2. The formatting of the comments needs to be consistent.

There are many ways to approach this, but there are some general standards that are being accepted. For example there is the simple python pydocstyle linter that ensures basic compliance and the presence of comments immediately below each class, method and function declaration. This is insufficient.

Google has taken this one step further. In their python guide they explain that every method, class and function should have a [description, definitions of the arguments and definitions of the results](https://docs.talawa.io/talawa/index.html).

image

The [TSDoc project](https://tsdoc.org/) attempts to do the same with `Typescript`, and have created a linter to help enforce compliance.

image

We want to maintain the quality of our documentation by identifying a linter which has a way of creating HTML documentation.

Research a method to enforce documentation compliance for dart comments.
- Every class, method, and function must have documentation about it

Documentation should include:

- A brief description of the code
- Argument variables that are used to initialize the code with a description of what each argument does
- Variables that the code returns and a description of each variable

### Note 
1. We are currently using [DartDoc](https://pub.dev/packages/dartdoc) for generating HTML and would **GREATLY PREFER** to see whether there is any way to use it to enforce these or very similar standards
1.  For example linting to make sure that the comments comply with the [Dart Documentation Comments](https://dart.dev/guides/language/language-tour#documentation-comments) standard would be acceptable.
1. You can refer to this pull request for work that is being done by the dart team https://github.com/dart-lang/linter/pull/3820, but others may be doing something through GitHub actions or some other means

**Describe the solution you'd like**
1. Finding a linting package that can be used as part of our GitHub actions
2. Finding a way for it to be run on all files or on just one file at a time.

**Describe alternatives you've considered**
1. Writing script files. We feel that there must be an existing solution to this.

### PR DESCRIPTION
**Pull request by literalEval**
**What kind of change does this PR introduce?**

Adds Custom Lint capabilities to Talawa. Now we can write and enforce our own custom lint rules which can be useful from the IDE itself, as well as can be run from our workflow.

### How it works ?

We are accessing the `Dart Analysis Server` (say DAS) directly and sending it the custom rules set by us. DAS exposes the Abstract Syntax Tree (AST) it builds while linting and we can access the tree as a client. Then, we can iterate over all the AST nodes, accessing the nodes which are of our interest. From there, it becomes a simple game of string parsing.

### Custom Rules Enforced

1. `TalawaAPIDoc` - Every declared field must have its own documentation comment.
2. `TalawaGoodDoc`: Every field must have a documentation comment that respects DartDoc guidelines.

**Issue Number:**

Fixes #1479 

**Did you add tests for your changes?**

Not needed / Can be discussed.

**Snapshots/Videos:**

Provided in comments of #1479 

**If relevant, did you update the documentation?**

Not yet.

**Summary**

**Does this PR introduce a breaking change?**

No

### Followup steps

1. Add `// ignore:` directive to all existing files.
3. Add the `// ignore:` directive checking script to workflow.
4. Add analyzer command to workflow actions.
5. Add more documentation for the Custom Rules written in this PR so that future contributors can also understand and enhance it.
6. Write tests for custom rules.

### CODE REVIEW

**Comment by literalEval** [comment]
@palisadoes unauthorized files is failing because `analysis_options.yaml` is modified.

**Comment by literalEval** [comment]
@palisadoes @noman2002 please review and merge if looks good to you. So that I can work on the followup tasks.

**Review by noman2002 — APPROVED** [review]
Looks good to me.

**Comment by literalEval** [comment]
@noman2002 sorry a debug check was still there. Removed it now. Please approve again. Sorry for the inconvenience.

**Review by noman2002 — APPROVED** [review]

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
