### PR TITLE
Unittest for custom_view_modal.dart

### PR DESCRIPTION
**Pull request by nidhin29**
This change included the Unittest for custom_view_modal.dart

Issue Number: https://github.com/PalisadoesFoundation/talawa/issues/1021

Fixed https://github.com/PalisadoesFoundation/talawa/issues/1021

Did you add tests for your changes?

Yes

Summary

It is unittest for custom_view_modal.dart

Does this PR introduce a breaking change?

No, this does not introduce any major changes to the codebase.

Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?

Yes, i have followed the guidelines.

### CODE REVIEW

**Comment by nidhin29** [comment]
can i close this pull request?

**Comment by nidhin29** [comment]
Can I close this pr?

**Comment by palisadoes** [comment]
Why?

**Comment by nidhin29** [comment]
Ok sir

**Comment by nidhin29** [comment]
Ok sir

**Comment by nidhin29** [comment]
Sir, can I give a latest pull request for this. I had accidentally written an extra line which was not needed but its showing that that is not covered also i had removed that and gave a commit but still the previous response can i give a new pull request

**Comment by nidhin29** [comment]
Sir, can I give a latest pull request for this. I had accidentally written an extra line which was not needed but its showing that that is not covered also i had removed that and gave a commit but still the previous response can i give a new pull request
My latest commit [1c2c643] is having 100% coverage but still not showing when I click that link to codecov its showing 100%

**Comment by nidhin29** [comment]
Sir, my work is ready

**Comment by palisadoes** [comment]
@literalEval @Ayush0Chaudhary @Kevoniat Please review

**Review by noman2002 — APPROVED** [review]
Looks good.

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
