### PR TITLE
Add Map Screen test #1511

### PR DESCRIPTION
**Pull request by Skdahale**
What kind of change does this PR introduce?

Adds tests for map_screen class and fixes a bug in the same

Issue Number:

Fixes https://github.com/PalisadoesFoundation/talawa/issues/1403

Did you add tests for your changes?

Yes, this is a test PR

Summary

Added tests for test/views/after_auth_screens/venue/map_screen_test.dart, fixed KeyError bug and formatted the file a little bit.

Does this PR introduce a breaking change?

No

Have you read the contributing guide?

Yes

### CODE REVIEW

**Review by noman2002 — CHANGES_REQUESTED** [review]
Please fix the failing tests. And also why there is `sha256` added in pubspec.lock

**Comment by palisadoes** [comment]
The new dependabot checker is causing the pubspec.lock changes. It uses a slightly different version of Dart, and we are working on fixing it.

**Comment by noman2002** [comment]
@Skdahale Please resolve the conflicts and fix the tests.

**Comment by noman2002** [comment]
closing due to inactivity on this PR. Please submit a new PR once this is fixed.

**Pull request closed without merging**
