### PR TITLE
Ayush0 chaudhary/workflow

### LINKED ISSUE #1622: Fix deprecated `get-changed-files` Pull Request GitHub Action
**Describe the bug**
We are getting these errors when PRs are submitted:

```
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: jitterbit/get-changed-files@v1. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
```

The `get-changed-files` GitHub **_pull request_** action has not been updated since 2020 and will soon be unsupported by GitHub. We need to fix this deficiency.

**To Reproduce**

1. [See this action run](https://github.com/PalisadoesFoundation/talawa/actions/runs/4107719370)
2. It is happening in all repositories

**Expected behavior**
No errors

**Actual behavior**
See above

**Screenshots**
image

**Additional details**
N/A

### PR DESCRIPTION
**Pull request by Ayush0Chaudhary**
**What kind of change does this PR introduce?**
Brought Back the `files changed` feature of Github Actions

**Issue Number:**

Fixes #1622

**Did you add tests for your changes?**

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**
no

**Other information**
no

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**
yes

### CODE REVIEW

**Comment by Ayush0Chaudhary** [comment]
@palisadoes @noman2002 @CyberWake @TheHazeEffect please have a look!

**Comment by literalEval** [comment]
@Ayush0Chaudhary does it list the file-name diff between develop and the branch on which the PR is opened? Also, can the result be used in another workflow?

**Comment by literalEval** [comment]
That's cool. I have a great use case of this in `custom_lint` workflow. Thanks for the info.

**Comment by Ayush0Chaudhary** [comment]
Ig, You can use the `id`

**Comment by palisadoes** [comment]
This is no longer required as it was used in this earlier version of the workflow. However I'll merge it as it could be useful in future.

- https://github.com/PalisadoesFoundation/talawa/blob/60256923446d9978d0df4df4f73e7785b0176f22/.github/workflows/pull-request.yml

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
