### PR TITLE
[Fix] : Mapping of Registered Events and Tasks in the Member Pages

### PR DESCRIPTION
**Pull request by StrangeNoob**
**What kind of change does this PR introduce?**

- Mapping of Tasks and Members
- Decreased the Time Complexity (n2) to n in member Page.
- Add Loader for the user to know the data is loading/fetch otherwise it gives a wrong impression

**Issue :** #575 

**Did you add tests for your changes?**
Yes. 

**If relevant, did you update the documentation?**
No.

**Does this PR introduce a breaking change?**
No.

**Snapshot/Video**

https://user-images.githubusercontent.com/42904343/113352515-fe22d480-9359-11eb-9dd9-f48289eb9cf2.mp4

**Other information**

### CODE REVIEW

**Comment by StrangeNoob** [comment]
@Sagar2366 Can you review this ?

**Comment by Sagar2366** [comment]
@StrangeNoob we need below feature -
1. Mapping of event to task in members tab - You can add extra field in every task list item to show event it belongs to.
For Example:
Task Name : A Task
Event Name: A Event
Task Description : A Task Description
Due Date : 04-04-2021

2. Another way to map tasks to events list item is with click button, something similar which is happening in events tab.

3. Please add tests for this change.

**Comment by StrangeNoob** [comment]
Sure @Sagar2366. I will notify you when its done

**Comment by StrangeNoob** [comment]
I made change as per requirement. Below attached is a snap video.

https://user-images.githubusercontent.com/42904343/114751207-79c94c00-9d72-11eb-81df-93b9159cd171.mp4

**Review by Sagar2366 — APPROVED** [review]

**Pull request merged**
