### PR TITLE
Post list widget test(#1138)

### LINKED ISSUE #1138: Unittests for widget post_list_widget.dart
We will need unittests done for all methods, classes and functions found in this file.

Any widgets referenced in this file must also have unittests done

```
post_list_widget.dart
```

This file can be found in the `lib/widgets` directory

Parent Issue: 
- https://github.com/PalisadoesFoundation/talawa/issues/1125

### PR DESCRIPTION
**Pull request by patrickwitter**
**What kind of change does this PR introduce?**

Added Tests for Post list Widget
Added Post Model Mock in test helpers as a mock was necessary to complete tests

**Issue Number:**
Fixes #1138

**Did you add tests for your changes?**
Yes

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Review by palisadoes — APPROVED** [review]

**Comment by palisadoes** [comment]
@patrickwitter  I'm going to have to revert this PR. You changed the `test/helpers/test_helpers.mocks.dart` file which is causing all the other PRs to fail due to merge conflicts. Why did you make the changes? In some cases it looks like you downgraded the versions of the mockito tests being applied.

**Comment by patrickwitter** [comment]
@palisadoes  Good day sir. The post List widget needed posts in order to test the behaviours within the test. Unfortunately, this meant I had to create a post mock in order to stub some values as the post list widget asserts that there are no null properties by the usage of the null assertion(!) see lines 31 and 29.  Thus this caused the test to fail. Also, several of the post model functions had to be mocked for the same reason. For the changes I made to the test_helpers.dart. I only generated a new mockPost class to use to get the tests running.

**Comment by palisadoes** [comment]
@patrickwitter I just realized that ` test/helpers/test_helpers.mocks.dart` is autogenerated. Please resubmit so we can merge your work into the codebase.

**Comment by patrickwitter** [comment]
@palisadoes Ok sir no problem

**Comment by palisadoes** [comment]
> @palisadoes Good day sir. The post List widget needed posts in order to test the behaviours within the test. Unfortunately, this meant I had to create a post mock in order to stub some values as the post list widget asserts that there are no null properties by the usage of the null assertion(!) (see lines 31 and 29 of post_widget.dart). Thus this caused the test to fail. Also, several of the post model functions had to be mocked for the same reason. For the changes I made to the test_helpers.dart. I only generated a new mockPost class to use to get the tests running.

Please resubmit, I was hasty in the reversion of your changes. I was more concerned with the conflicts in `test/helpers/test_helpers.mocks.dart` before I realized the file was autogenerated. The testing regime you selected is sound. We need to get our test code coverage increased. Your efforts are very helpful. Thanks for taking the initiative to submit this work.

**Pull request merged**
