### PR TITLE
Filepicker replaced with imagepicker for registration

### LINKED ISSUE #264: Filepicker plugin causing lot of issues
Issues like this
image

And sometimes it is causing the issue like file called on null.

# Will you be working on it?
Yes creating a PR fixing this

### PR DESCRIPTION
**Pull request by AniketSindhu**
fixed #264 

# Changes I did
1. Replace filepicker with image picker on the registration page
2. Replace deprecated .pickImage methods

### CODE REVIEW

**Review by CyberWake — APPROVED** [review]
LGTM👍

**Comment by Sagar2366** [comment]
@AniketSindhu keep changes only required to fix the issue.
Revert changes in all other files.

**Comment by AniketSindhu** [comment]
@Sagar2366 done

**Comment by Sagar2366** [comment]
@AniketSindhu you are deleting two files from iOS folder. Keep them as it is.

**Comment by AniketSindhu** [comment]
@Sagar2366 files added

**Review by Sagar2366 — APPROVED** [review]

**Pull request merged**
