### PR TITLE
[Refactoring] Better state-management, testable refactoring of joinOrganization Page 

### PR DESCRIPTION
**Pull request by rutvik11062000**
**What kind of change does this PR introduce?**
Refractoring , separation of UI from business logic , statemanagement using MVVM.

**Did you add tests for your changes?**
No
**If relevant, did you update the documentation?**

**Summary**
The motivation is to write separated testable code with better state-management solution.

Issue: #478 
**Does this PR introduce a breaking change?**
Yes
JoinOrganization class name is changed to JoinOrganizationView
locator is set up.
GraphQLConfiguration is now to and should be injected using locator only.

**Other information**
Implemented statemanagement to joinOrganization Page.

### CODE REVIEW

**Comment by rutvik11062000** [comment]
@Sagar2366 I'm sorry to tag you but please merge it now I've fixed the errors.

**Comment by rutvik11062000** [comment]
Sure sir I'll work on testing and will include the recent changes.

**Comment by palisadoes** [comment]
Please fix merge conflicts. The code freeze has been lifted.

**Comment by palisadoes** [comment]
I'm closing this issue. Please reopen it based on the suggestions below:

1. We now have automated linting enabled. 
1. The entire code base has also been linted for consistency. 
1. [CONTRIBUTING.md](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md) has been updated with what you need to do to lint your code before submission.

Please follow the following steps.

1. Merge your code with the recently updated master branch. 
1. Follow the linting guidelines
1. Resubmit your pull request
1. Please correct your code if it the PR process fails the package analysis test. This needs to be resolved before we can review.

The code freeze has been lifted.

**Comment by palisadoes** [comment]
1. Please fix the conflicting files. 
2. Merge with the latest master branch
1. The new full repo linter will be applied with the update. [CONTRIBUTING.md](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md) has been updated with what you need to do to lint your code before submission.

**Pull request closed without merging**
