### PR TITLE
Fixes #1242 Create tests for create_event_page.dart

### LINKED ISSUE #1242: Views: Create tests for create_event_page.dart
The Talawa code base needs to be 100% reliable. This means we need to have 100% test code coverage.

Tests need to be written for file `lib/views/after_auth_screens/events/create_event_page.dart`

- When complete, all methods, classes and/or functions in the file will need to be tested. 
- These tests must be placed in a single file with the name `test/views/after_auth_screens/events_test/create_event_page_test.dart`. You may need to create the appropriate directory structure to do this.

### IMPORTANT:
Please refer to the parent issue on how to implement these tests correctly:

- https://github.com/PalisadoesFoundation/talawa/issues/1217

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base. This will be clearly visible when you submit your PR.
- [The current code coverage for the file can be found here](https://codecov.io/gh/PalisadoesFoundation/talawa/tree/develop/lib/views/after_auth_screens/events/). If the file isn't found in this directory, or there is a 404 error, then tests have not been created.
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide.
- You can verify your own code coverage by creating an account at [Codecov.io](https://codecov.io)
- No functionality must be removed to achieve this goal

### PR DESCRIPTION
**Pull request by Ayush0Chaudhary**
**What kind of change does this PR introduce?**
Fixes #1242 Create tests for create_event_page.dart

**Issue Number:**

Fixes #1242

**Did you add tests for your changes?**
YES

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**
Fixes #1242 Create tests for create_event_page.dart

**Does this PR introduce a breaking change?**
NO

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**
YES

### CODE REVIEW

**Comment by Ayush0Chaudhary** [comment]
I got **93.2%** in these test

Screenshot from 2023-02-08 20-18-12

**Comment by Ayush0Chaudhary** [comment]
The part which was not tested is in below ss
Screenshot from 2023-02-08 20-18-27





the below loop return false for every value
https://github.com/PalisadoesFoundation/talawa/blob/311b205a8371eee891e5bef1a794f904295cd6cb/lib/view_model/after_auth_view_models/event_view_models/create_event_view_model.dart#L143-L152

Thus the frontend can never be tested, as the list is always null

**Comment by Ayush0Chaudhary** [comment]
@palisadoes @noman2002 @TheHazeEffect please review.

**Comment by Ayush0Chaudhary** [comment]
@noman2002

**Review by noman2002 — APPROVED** [review]
Looks good but we should keep the issue open to get it to 100%

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
