### PR TITLE
Invalid Password hint fixes

### PR DESCRIPTION
**Pull request by Literal-Eval**
### Fixes - #1030 
- This PR fixes the issue with invalid password hint text. Earlier, it always said "Invalid Password" without telling what's wrong with the entered password, making it very hard to figure out what's needed. 
Now, the hints are modified and added in all languages to tell the user what is actually expected.

### Screenshots
- 

- 

- 

- 

- 

- 

### Extra
- Also fixed some Hindi translations, as I am a native Hindi speaker :)

### Note
- The indentations in the language json files don't match with my VSCode settings, so even after trying all my best, Hindi json file got indented as my settings. But there are merely 10 - 12 changes in that file.

### CODE REVIEW

**Comment by palisadoes** [comment]
@Literal-Eval 
1. Tests are failing in the PR. Please review.
1. We need a single message when the person finally enters their password. 
    1. Messages during the typing will be distracting
    1. It makes it easier for someone to guess the type and position of a character in the password
 1. The messages will need to support the multilingualism of the app.

**Comment by Literal-Eval** [comment]
1. Yes, I'll check.
2. Yes it only shows these errors when user finally presses submit. Not from starting. The screenshots I took were taken only after submitting once.
3. Done.
4. Can you please clarify the password criteria once ? 
  - At least one lowercase
  - At least one uppercase
  - At least one digit
  - At least one special character
  Is it not correct ?

**Comment by palisadoes** [comment]
- Please only use one message to state the password criteria. The code will get bloated otherwise.
- The criteria should be listed in the issue:
   - https://github.com/PalisadoesFoundation/talawa/issues/1030

We have increased the code coverage to 33%, so I'd also suggest you add tests for any widgets you find in the code files you are editing.

**Comment by Literal-Eval** [comment]
1. About single message: Yeah at first I did think about this, but the problem I saw was with short screens. I think a sentence like "Uppercase & lowercase letters, number & symbol & must be 8 letters long" (and this is the shortest message I can think of) might overflow on short screens.
2. About criteria, the issue says:
issue 1080
That's what I took, please clarify where I'm wrong.

- So kindly clarify these two things. It it's insisted for a single message, I'll do.

**Comment by palisadoes** [comment]
For the message can you use an error or question icon that displays a
temporary pop-up when pressed?

My mistake, use the regex system you found for validity verification.

**Comment by Literal-Eval** [comment]
So this is final

- The previous regex system was all good, and the only change that's needed is that the error messages should be descriptive. (meaning I should remove the extra regex checks that I introduced).
- For error message, a temporary popup can be used.

Should I go with it ?

**Comment by palisadoes** [comment]
> So this is final
> 
>     * The previous regex system was all good, and the only change that's needed is that the error messages should be descriptive. (meaning I should remove the extra regex checks that I introduced).
> 
>     * For error message, a temporary popup can be used.
> 
> 
> Should I go with it ?

Yes

**Review by palisadoes — CHANGES_REQUESTED** [review]
@Literal-Eval your pull request is failing as the minimum code coverage for testing has not been met. Please refer to our [CONTRIBUTING.md](https://github.com/PalisadoesFoundation/talawa/blob/develop/CONTRIBUTING.md) for details. We need to get to 33% coverage. 
Please write tests for the code you just modified and include it in the PR.

**Comment by Literal-Eval** [comment]
Okay.

**Pull request closed without merging**
