### PR TITLE
Refactor of the toast widget and deletion of `snackbar.dart`

### PR DESCRIPTION
**Pull request by nayakastha**
**What kind of change does this PR introduce?** 
This is a Pull Request that introduces a few changes as suggested in Issue #780   
- deleted `toast_container.dart` and replaced it's uses with `customToast`
- removed the flutter toast imports from the files and replaced them with 'customToast'
- deleted `snackbar.dart` since it had no implementation

**Did you add tests for your changes?**  The tests already existed using `customToast` hence required no alterations.

**If relevant, did you update the documentation?** No

**Does this PR introduce a breaking change?** Not a breaking change, but it removed a few redundant files.

### CODE REVIEW

**Comment by palisadoes** [comment]
@nayakastha  `flutter test` is not working correctly on your code. This is causing Travis CI to fail. 

1. Follow the steps in the GitHub site's [Checking out pull requests locally](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/reviewing-changes-in-pull-requests/checking-out-pull-requests-locally) web page.
2. Resolve the conflicts, which appear related to `pubspec.yml`
3. Resubmit your pull request.

The error can be seen below

image

**Comment by palisadoes** [comment]
@nayakastha please also resolve the conflicting files

```
lib/controllers/post_controller.dart
lib/views/pages/login_signup/login_form.dart
```

**Comment by palisadoes** [comment]
@DeltaHarbinger 
@Sagar2366 
@TheHazeEffect 
This looks ready for your review.

**Comment by TheHazeEffect** [comment]
Hi @nayakastha ,could you resolve the conflict

**Comment by palisadoes** [comment]
@TheHazeEffect the merge conflict is now resolved.

**Comment by Sagar2366** [comment]
@nayakastha reminder again, please resolve the conflicts.

**Comment by nayakastha** [comment]
> @nayakastha reminder again, please resolve the conflicts.

Sir, I have resolved the conflicts. Please do check and merge. Else merge conflicts will rise again.

**Review by palisadoes — APPROVED** [review]

**Comment by palisadoes** [comment]
@Sagar2366 @TheHazeEffect @DeltaHarbinger Please review. I'll merge when done.

**Review by TheHazeEffect — APPROVED** [review]
Looks good

**Pull request merged**
