### PR TITLE
[Bug] - Profile Page Fix for currentOrgName null for any reason will so user …

### PR DESCRIPTION
**Pull request by CyberWake**
Fix for the present PR #257 

**What kind of change does this PR introduce?**
Assigns the new organization as current Organization on leaving the current one. Also if the user leaves all the organization then current Organization shows user to join a organization, It fixes all type of null current organization issues.

**Did you add tests for your changes?**
Yes, I have tested it on android device.

**If relevant, did you update the documentation?**
Documentation doesn't need to be updated
**Summary**
Fixes all kind of current organization name or id null still user sees proper message regarding that.

**Does this PR introduce a breaking change?**
No, it does not.

**Other information**

### CODE REVIEW

**Comment by CyberWake** [comment]
This one updates the current org name, id in the preferences on leaving and notify the listeners if its null the org name is set to No Organization joined. Please have a review on this one @sumitra19jha @Sagar2366

**Comment by sumitra19jha** [comment]
PR already created in #257

**Comment by sumitra19jha** [comment]
This looks gud. Instead of null you are showing no organization joined. Great

**Review by cyber-venom003 — COMMENTED** [review]
Perfectly implemented @CyberWake

**Comment by CyberWake** [comment]
> This looks gud. Instead of null you are showing no organization joined. Great

Thanks

**Comment by CyberWake** [comment]
> Perfectly implemented @CyberWake 

Thanks

**Comment by Sagar2366** [comment]
Though it sets meaningful tag now instead of null, it throws error in the console. 
Please handle this scenario in this PR. Get latest code from master, check if https://github.com/PalisadoesFoundation/talawa/pull/257 already solve this problem.

I/flutter (11090): GraphQL Errors:
I/flutter (11090): Cast to ObjectId failed for value "null" at path "_id" for model "Organization": Undefined location

**Comment by CyberWake** [comment]
@Sagar2366 sir successfully merged from master please have a review.

**Review by Sagar2366 — APPROVED** [review]

**Pull request merged**
