### PR TITLE
Fixes #1483 showSnackBar error: showing snackbar before screen is built2

### LINKED ISSUE #1483: showSnackBar error: showing snackbar before screen is built
**Describe the bug**

**To Reproduce**

1. Use this org url https://talawaapi.azurewebsites.net/graphql
2. click o sign up button
3. screen will appear

**Expected behavior**
Should provide with poper error

**Actual behavior**
giving this error screen 

**Screenshots**
Screenshot from 2023-02-14 01-13-23

**Additional details**
I checked the error stack and it showed the this line showed this error
https://github.com/PalisadoesFoundation/talawa/blob/ac0571bcf6c7fc0a3bd930989a9848348024d094/lib/services/database_mutation_functions.dart#L126-L128

we have to make the changes in these line too so we don't get same error in the future
https://github.com/PalisadoesFoundation/talawa/blob/ac0571bcf6c7fc0a3bd930989a9848348024d094/lib/services/database_mutation_functions.dart#L89-L124

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by Ayush0Chaudhary**
**What kind of change does this PR introduce?**
I removed the error which was shown when there was a problem with URL, the snackbar was shown before the widget completed its build.

**Issue Number:**

Fixes #1483

**Snapshots/Videos:**
Screenshot from 2023-02-14 01-32-20

**Does this PR introduce a breaking change?**
NO

**Have you read the [contributing guide]
YES
(https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**

### CODE REVIEW

**Review by noman2002 — CHANGES_REQUESTED** [review]
Adding delay is not a viable solution for this. There is a method to check if the widget is built or not, use that to achieve the desired outcome. And also update the test files for the same if needed.

**Comment by Ayush0Chaudhary** [comment]
@noman2002 @palisadoes @TheHazeEffect I have solved the issue, but a action are failing.

**Comment by palisadoes** [comment]
We made an adjustment to the actions yesterday. Please make a minor commit to update the PR.
It may take about 2 more tries to make sure it works OK

**Comment by palisadoes** [comment]
Please try again. I've removed the part that was failing completely

**Comment by Ayush0Chaudhary** [comment]
Actions passed 😀

**Comment by Ayush0Chaudhary** [comment]
@noman2002 @palisadoes @TheHazeEffect please review the PR!

**Review by noman2002 — APPROVED** [review]

**Comment by palisadoes** [comment]
Merging will have to be delayed for an expected PR for upgrading Talawa to the latest Flutter version. This is expected over the weekend.

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
