### PR TITLE
Tests for edit_event_page.dart

### LINKED ISSUE #1517: Tests for edit_event_page.dart
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

The Talawa code base needs to be 100% reliable. This means we need to have 100% test code coverage.

Tests need to be written for file `lib/views/after_auth_screens/events/edit_event_page.dart`

- When complete, all methods, classes and/or functions in the file will need to be tested. 
- Our `test/` folder has the same structure as the `lib` folder. Place your test file in the equivalent folder under `test/`. You may need to create the appropriate directory structure to do this.
- [Current test code coverage for this file can be found here](https://app.codecov.io/gh/PalisadoesFoundation/talawa?search=&displayType=list)

### IMPORTANT:
Please refer to the parent issue on how to implement these tests correctly:

- https://github.com/PalisadoesFoundation/talawa/issues/1217

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base. This will be clearly visible when you submit your PR.
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide.
- You can verify your own code coverage by creating an account at [Codecov.io](https://codecov.io)

### PR DESCRIPTION
**Pull request by Azad99-9**
**What kind of change does this PR introduce?**

This PR adds tests for edit_event_page.dart.

**Issue Number:**

Fixes #1517

**Did you add tests for your changes?**

yes

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

No

**Summary**

[https://github.com/PalisadoesFoundation/talawa/issues/1517](url)

**Does this PR introduce a breaking change?**

No

**Other information**

Added tests to the edit_event_page.dart and increased its code coverage from 0% to 100%.

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**

yes

### CODE REVIEW

**Comment by palisadoes** [comment]
Please fix the first comment so that each issue listed automatically closes. The PR_GUIDELINES.md file has details.

Please also fill in the template for the pull request as completely as you can. It greatly helps others searching for code changes in future and helps others understand the summarized rationale for the work you have done

**Comment by Azad99-9** [comment]
> Please work with @aashimawadhwa on this PR. This week this contributor is working on assigning issues, assigning reviewers to PRs and answering general questions.

Sure @palisadoes , got it.

**Comment by Azad99-9** [comment]
@aashimawadhwa please assign reviewers to this PR.

**Comment by aashimawadhwa** [comment]
@noman2002 @Ayush0Chaudhary  please review this pr.

**Comment by Ayush0Chaudhary** [comment]
> ## [Codecov](https://app.codecov.io/gh/PalisadoesFoundation/talawa/pull/2130?src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=PalisadoesFoundation) Report
> All modified and coverable lines are covered by tests :white_check_mark:
> > Comparison is base [(`4385f71`)](https://app.codecov.io/gh/PalisadoesFoundation/talawa/commit/4385f71700da127382bc4457ada1f96c2e01b0c0?el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=PalisadoesFoundation) 77.29% compared to head [(`36ac99f`)](https://app.codecov.io/gh/PalisadoesFoundation/talawa/pull/2130?src=pr&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=PalisadoesFoundation) 78.78%.
> > Report is 1 commits behind head on develop.
> 
> 
> <details><summary>Additional details and impacted files</summary>
> 
> 
> ```diff
> @@             Coverage Diff             @@
> ##           develop    #2130      +/-   ##
> ===========================================
> + Coverage    77.29%   78.78%   +1.48%     
> ===========================================
>   Files          152      152              
>   Lines         7456     7456              
> ===========================================
> + Hits          5763     5874     +111     
> + Misses        1693     1582     -111     
> ```
> 
> 
> 
> </details>
> 
> [:umbrella: View full report in Codecov by Sentry](https://app.codecov.io/gh/PalisadoesFoundation/talawa/pull/2130?src=pr&el=continue&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=PalisadoesFoundation).   
> :loudspeaker: Have feedback on the report? [Share it here](https://about.codecov.io/codecov-pr-comment-feedback/?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=PalisadoesFoundation).
> 

Please share the code coverage of the file.

**Review by Ayush0Chaudhary — APPROVED** [review]

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
