### PR TITLE
Feature Request : Plugin Architecture (Features as Plugins) 

### LINKED ISSUE #1339: Feature Request : Plugin Architecture (Features as Plugins)
**Is your feature request related to a problem? Please describe.**
Problem statement taken from Project Ideas Page :  

[ Latent features in the mobile app should be enabled by installing plugins via the Admin web portal. The API would need to detect the existence of a plugin, and automatically query the plugin for authorization to do some action. When authorized, the mobile app will display new capabilities. ](https://palisadoesfoundation.github.io/talawa-docs/docs/internships/internship-ideas/#admin-web-portal-plugin-architecture)

**Describe the solution you'd like**
Plugin are features which can toggled to enable or disable by the talawa-admin application with proper authorization
This  project has two parts:

-   The design and development of the plugin architecture

- [x] Create `TalwaPluginProvider` widget in flutter which can control visibility of the UI according to the visibility property set by the admin. It can look like this 

```dart
class TalawaPluginProvider extends StatelessWidget {
  const TalawaPluginProvider(
      {Key? key,
      @required this.child,
      required this.visible,
      required this.pluginName})
      : super(key: key);

  ///child contains the widget for the plugin UI.
  final Widget? child;

  ///visible is the property that decides visibility of the UI.
  final bool visible;

  ///name of plugin preferred with underscores(_) insted of spaces
  final String pluginName;

  ///return `bool` decides the final visibility of the verifying from database and current OrgId
  bool checkFromPluginList() {
    final UserConfig _userConfig = locator<UserConfig>();
    final Box box;
    bool res = false;
    box = Hive.box('pluginBox');
    final pluginList = box.get('plugins');

    ///mapping over the list from the server
    pluginList
        .map((plugin) => {
              if (plugin["pluginName"] == pluginName)
                {
                  if (plugin["pluginInstallStatus"] as bool)
                    {
                      res = plugin["pluginInstallStatus"] as bool ||
                          plugin["installedOrgs"]
                              .contains(_userConfig.currentOrg.id) as bool
                    }
                }
            })
        .toList();
    return res;
  }

  ///build the Plugin combining local `visibility` property and `serverVisible` property
  @override
  Widget build(BuildContext context) {
    var serverVisible = false;
    serverVisible = checkFromPluginList();
    return Visibility(visible: serverVisible || visible, child: child!);
  }
```   
 

- [x] `fetch_plugin_list ` function which will load the new list of plugin after the app is restarted
- [x] Store the plugin data is Hive Box
- [x] Add the query for 'fetchPlugins' . It can look like this:
```dart

  ///`getPluginList` queries all properties of  pluginList from the server
  String getPluginsList() {
    return '''
query  {
  getPlugins {
    _id
    pluginName
    pluginCreatedBy
    pluginDesc 
    pluginInstallStatus
    installedOrgs
  }
}
  ''';
```
**Describe alternatives you've considered**
No. but alternatives can be suggested by the mentors

**Approach to be followed (optional)**
Above tasks will be carried out one by one.

**Additional context**
Not required.

### PR DESCRIPTION
**Pull request by SiddheshKukade**
**What kind of change does this PR introduce?**

Feature Request #1339

**Issue Number:**

Fixes #1339

**Did you add tests for your changes?**
Yes

**Snapshots/Videos:**
Not Needed

**If relevant, did you update the documentation?**

Not required

**Summary**
Plugin are features which can toggled to enable or disable by the talawa-admin application with proper authorization
This  project has two parts:

-   The design and development of the plugin architecture

- [x] Create `TalwaPluginProvider` widget in flutter which can control visibility of the UI according to the visibility property set by the admin. It can look like this 

```dart
class TalawaPluginProvider extends StatelessWidget {
  const TalawaPluginProvider(
      {Key? key,
      @required this.child,
      required this.visible,
      required this.pluginName})
      : super(key: key);

  ///child contains the widget for the plugin UI.
  final Widget? child;

  ///visible is the property that decides visibility of the UI.
  final bool visible;

  ///name of plugin preferred with underscores(_) insted of spaces
  final String pluginName;

  ///return `bool` decides the final visibility of the verifying from database and current OrgId
  bool checkFromPluginList() {
    final UserConfig _userConfig = locator<UserConfig>();
    final Box box;
    bool res = false;
    box = Hive.box('pluginBox');
    final pluginList = box.get('plugins');

    ///mapping over the list from the server
    pluginList
        .map((plugin) => {
              if (plugin["pluginName"] == pluginName)
                {
                  if (plugin["pluginInstallStatus"] as bool)
                    {
                      res = plugin["pluginInstallStatus"] as bool ||
                          plugin["installedOrgs"]
                              .contains(_userConfig.currentOrg.id) as bool
                    }
                }
            })
        .toList();
    return res;
  }

  ///build the Plugin combining local `visibility` property and `serverVisible` property
  @override
  Widget build(BuildContext context) {
    var serverVisible = false;
    serverVisible = checkFromPluginList();
    return Visibility(visible: serverVisible || visible, child: child!);
  }
```   
 

- [x] `fetch_plugin_list ` function which will load the new list of plugin after the app is restarted
- [x] Store the plugin data is Hive Box
- [x] Add the query for 'fetchPlugins' . It can look like this:
```dart

  ///`getPluginList` queries all properties of  pluginList from the server
  String getPluginsList() {
    return '''
query  {
  getPlugins {
    _id
    pluginName
    pluginCreatedBy
    pluginDesc 
    pluginInstallStatus
    installedOrgs
  }
}
  ''';
```
 

**Does this PR introduce a breaking change?**

No

**Other information**
Not Required.

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by SiddheshKukade** [comment]
@JamaicanFriedChicken  
@DMills27
would like to have your thoughts on current changes.

**Review by DMills27 — CHANGES_REQUESTED** [review]
Add a couple more tests to get the code coverage higher such that it will pass all the criteria to be merged. Other than that it looks good! Good job!

**Comment by SiddheshKukade** [comment]
> Add a couple more tests to get the code coverage higher such that it will pass all the criteria to be merged. Other than that it looks good! Good job!

Sir I have added some tests now 👍🏻

**Comment by SiddheshKukade** [comment]
@palisadoes  Please provide the workflow approval for this PR 
image

**Review by DMills27 — APPROVED** [review]
Looks good to me

**Review by JamaicanFriedChicken — APPROVED** [review]

**Pull request merged**
