### PR TITLE
Fixed Buttons Visibility before entering Org URL and added test for b…

### LINKED ISSUE #611: Confusing Buttons before Setting Organisation URL
- **Issue Description:** 
  The Main Goal of User should be to set Organisation URL.
 But "Create an Account" button and Login Button, confuses the user. 
**Both buttons donot have any value before setting URL**.
- **Issue Severity:** 
  Low
- **Environment Details:** 
  Visual Studio Code
- **Observed Behaviour:** 
  Create an Account button visible before entering Organisation URL. And It doesn't have any action at that time.
- **Expected Behaviour:**
  Both Buttons should be visible after the user enter's Organisation URL.
- **Steps to reproduce issue:** 
  1. Open talawa app (User must be logged out.)
  2. Observe the first Screen(i.e Set Org URL Page)
- **Snapshots/Videos:**
WhatsApp Image 2021-04-05 at 12 52 21 AM
  Both buttons confuses the user before submitting url. So it must be visible after entering Organisation URL.
- **Does this issue need immediate attention?**
  No, But very important as per User Experience.
- **Are you willing to work on this issue:** 
  Yes, I am willing to work on this issue.
- **Other information:** <Add extra information about this PR here>
  Please let me know, if I am wrong. Or there could be any better option.

### PR DESCRIPTION
**Pull request by theRoushan**
**What kind of change does this PR introduce?**
Change in User Experience by adjusting "Create an Account" and "Login" button after User enters the Organisation url.
>Before this Pull Request
  - Let's Understand it with Images and Videos.
Screenshot_2021-04-05-05-14-14-841_com example talawa
 *Here* all buttons are visible which confuses user to click on Create an Account and Login Also, which are not functional before Entering Organisation URL

>After thisPull Request
WhatsApp Image 2021-04-05 at 1 14 35 AM
In this screenshot, User goal is clear,
then, after entering Org URL, button will appear as shown below.
WhatsApp Image 2021-04-05 at 1 14 38 AM

It introduces enhancement and ease to take proper action for user.
**Did you add tests for your changes?**
No, it donot requires.
**If relevant, did you update the documentation?**
No, It doesn't requires document updation.
**Summary**
```dart
 (saveMsg == "URL SAVED!")?Column(children: [ //This checks if Org Url is called and correct and then renders the button if org url is correct
                  FadeTransition(
                  //changed opacity animation to match login button animation
                  opacity: loginAnimation,
                  child: Container(
                    //padding: EdgeInsets.all(100.0),
                    child: new Container(
                      width: _media != null
                          ? _media.size.width
                          : MediaQuery.of(context).size.width,
                      margin: const EdgeInsets.only(
                          left: 50.0, right: 50.0, top: 10.0),
                      alignment: Alignment.center,
                      child: new Row(
                        children: <Widget>[
                          new Expanded(
                            child: ElevatedButton(
                              style: ElevatedButton.styleFrom(
                                padding: EdgeInsets.zero,
                                shape: RoundedRectangleBorder(
                                  borderRadius: BorderRadius.circular(30.0),
                                ),
                              ),
                              onPressed: saveMsg != "URL SAVED!"
                                  ? null
                                  : () async {
                                      if (_formKey.currentState.validate()) {
                                        _formKey.currentState.save();
                                        Navigator.push(
                                          context,
                                          MaterialPageRoute(
                                              builder: (context) =>
                                                  RegisterPage()),
                                        );
                                      }
                                    },
                              child: new Container(
                                padding: const EdgeInsets.symmetric(
                                  vertical: 20.0,
                                  horizontal: 20.0,
                                ),
                                decoration: BoxDecoration(
                                    border: Border.all(color: Colors.orange),
                                    borderRadius:
                                        new BorderRadius.circular(50.0)),
                                child: new Row(
                                  mainAxisAlignment: MainAxisAlignment.center,
                                  children: <Widget>[
                                    new Expanded(
                                      child: Text(
                                        "Create an Account",
                                        textAlign: TextAlign.center,
                                        style: TextStyle(
                                          //color: UIData.quitoThemeColor,
                                          color: Colors.white,
                                          fontSize: 18,
                                          //fontWeight: FontWeight.bold
                                        ),
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                          ),
                        ],
                      ),
                    ),
                  ),
                ),
                SizedBox(height: 5),
                FadeTransition(
                  opacity: loginAnimation,
                  child: Container(
                    child: new Container(
                      width: _media != null
                          ? _media.size.width
                          : MediaQuery.of(context).size.width,
                      margin: const EdgeInsets.only(
                          left: 50.0, right: 50.0, top: 10.0),
                      alignment: Alignment.center,
                      child: new Row(
                        children: <Widget>[
                          new Expanded(
                            child: new ElevatedButton(
                              style: ElevatedButton.styleFrom(
                                padding: EdgeInsets.zero,
                                shape: RoundedRectangleBorder(
                                  borderRadius: BorderRadius.circular(30.0),
                                ),
                              ),
                              onPressed: saveMsg != "URL SAVED!"
                                  ? null
                                  : () async {
                                      if (_formKey.currentState.validate()) {
                                        _formKey.currentState.save();
                                        Navigator.push(
                                            context,
                                            MaterialPageRoute(
                                                builder: (context) =>
                                                    LoginPage()));
                                      }
                                    },
                              child: new Container(
                                padding: const EdgeInsets.symmetric(
                                  vertical: 20.0,
                                  horizontal: 20.0,
                                ),
                                decoration: BoxDecoration(
                                    border: Border.all(color: Colors.orange),
                                    borderRadius:
                                        new BorderRadius.circular(50.0)),
                                child: new Row(
                                  mainAxisAlignment: MainAxisAlignment.center,
                                  children: <Widget>[
                                    new Expanded(
                                      child: Text(
                                        "Login",
                                        textAlign: TextAlign.center,
                                        style: TextStyle(
                                          //color: UIData.quitoThemeColor,
                                          color: Colors.white,
                                          fontSize: 18,
                                          //fontWeight: FontWeight.bold
                                        ),
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                          ),
                        ],
                      ),
                    ),
                  ),
                ),
                ],):SizedBox(height: 0,), 
```
Just wrapped the both buttons with column and added an ternary operation on  condition (saveMsg == "URL SAVED!").
Hope it explains the code change well.

Merging this PR will close this issue #611 
**Does this PR introduce a breaking change?**
No, it does not includes a breaking change.

**Other information**
resolve #611 . Please review this PR @Sagar2366 .

### CODE REVIEW

**Comment by Sagar2366** [comment]
@theRoushan one of check is failing on your PR, please have a look.

**Comment by Sagar2366** [comment]
> @theRoushan one of check is failing on your PR, please have a look.

@theRoushan let us know if you still want to continue working on this issue.

**Comment by theRoushan** [comment]
I had worked on it and raised a PR to close this issue. You can review PR and merge that to close this issue

**Comment by Sagar2366** [comment]
> I had worked on it and raised a PR to close this issue. You can review PR and merge that to close this issue

Right, can you please have a look into why CI check is failing ?

**Comment by Sagar2366** [comment]
@theRoushan closing this PR, open new PR with same changes to avoid CI issue.

**Pull request closed without merging**
