### PR TITLE
Fixing logic error in talawa_plugin_provider.dart for visibility of plugins

### LINKED ISSUE #2141: Logic error in talawa_plugin_provider.dart file for the visibility of a plugin.
**Describe the bug**
There is a logic error in this [file](https://github.com/PalisadoesFoundation/talawa/blob/develop/lib/plugins/talawa_plugin_provider.dart).

Screenshot 2023-11-26 234224

In this code, condition `plugin["installedOrgs"].contains(userConfig.currentOrg.id)` as bool` is never getting checked. 

This could be fixed with this logic:

Screenshot 2023-11-26 235223

This will check both conditions i.e. whether Plugin is installed or plugin is already installed in the specific organization and determine the visibility of the Plugin.

### PR DESCRIPTION
**Pull request by Dante291**
**What kind of change does this PR introduce?**

Fixing logic error in [this](https://github.com/PalisadoesFoundation/talawa/blob/develop/lib/plugins/talawa_plugin_provider.dart) file.

**Issue Number:**

Fixes #2141 

**Did you add tests for your changes?**

No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by palisadoes** [comment]
Please update the corresponding test file for your PR to get its test coverage up to 100%

**Comment by Dante291** [comment]
@palisadoes @noman2002 The reason why PR target workflow is getting failed is because of [this](https://github.com/actions/first-interaction/issues/286) issue in first-interaction.

**Comment by palisadoes** [comment]
> @palisadoes @noman2002 The reason why PR target workflow is getting failed is because of [this](https://github.com/actions/first-interaction/issues/286) issue in first-interaction.

Thanks. I've assigned reviewers. Please work with them to get this merged.

**Review by noman2002 — APPROVED** [review]

**Comment by palisadoes** [comment]
@SiddheshKukade please take a look

**Comment by Dante291** [comment]
@Ayush0Chaudhary Could you review this and get this merge.

**Pull request merged**
