### PR TITLE
Bugfix/fix comment icon

### PR DESCRIPTION
**Pull request by OnyemaAnthony**
**What kind of change does this PR introduce?**
bug fix and added widget test

**Did you add tests for your changes?**
  yes

**If relevant, did you update the documentation?**
no

**Summary**

i make the leave a comment button responsive so that when the text in the comment textfield becomes bigger it remains in the center of the textfield also make some ui changes in the leave comment textfield,finally i wrote a widget test to test the code

**Does this PR introduce a breaking change?**

no

**Other information**
issue:#495

### CODE REVIEW

**Comment by OnyemaAnthony** [comment]
Screenshot_20210327-200610

**Comment by OnyemaAnthony** [comment]
Screenshot_20210327-200249

**Comment by OnyemaAnthony** [comment]
Here are the screenshots to the changes I made

**Review by Sagar2366 — APPROVED** [review]

**Pull request merged**
