### PR TITLE
Version and packages upgraded 

### LINKED ISSUE #1886: Update packages
## Describe the bug
This Project is outdated, it is crucial to keep the project dependencies and version up to date to leverage the latest features, bug fixes, and improvements offered by the Flutter ecosystem and its associated packages.

To resolve this issue, the dependencies listed in the project's "pubspec.yaml" file need to be updated to their latest versions.
And we also have to update build.gradle file for this

## To Reproduce

1. Go to pubspec.yaml file and build.gradle android\app file for check the version
2. Click on terminal and type "flutter pub get" to know the updates before this we have to change the version of environment: sdk in
pubspec.yaml file
3. Scroll down to see the updates

## Expected behavior
 Version up to date 

## Screenshots
Screenshot 2023-06-06 200401

**build.gradle android\app file**
Screenshot 2023-06-06 200501

### PR DESCRIPTION
**Pull request by andoriyaprashant**
## What kind of change does this PR introduce?

There are many updates are available and I upgrade dependencies with the help of "flutter pub upgrade --major -version" command
And I change the version of intl
Screenshot 2023-06-06 201657

## Fixes #1886 

**Did you add tests for your changes?**

 - Yes 

## Snapshots

Screenshot 2023-06-06 201629

Screenshot 2023-06-06 201636

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**

- Yes

### CODE REVIEW

**Comment by literalEval** [comment]
@andoriyaprashant 

1. Don't do any changes inside `talawa_lint` directory.
2. Don't upgrade compile SDK version. If such a major update is absolutely required, please open a respective issue for Major Version upgrade and discuss with everyone before opening a Pull Request.

**Comment by literalEval** [comment]
Was was the value of `flutter.compileSdkVersion` ?

**Comment by andoriyaprashant** [comment]
@literalEval 
The compileSdkVersion is 33 according to the latest version bcz Using the Flutter constant 'compileSdkVersion flutter.compileSdkVersion' is generally advised to ensure compilation with the most up-to-date version of the SDK supported by Flutter.

**Comment by literalEval** [comment]
That's what I am saying. Leave the variables as they are until unless absolutely required to change.

**Comment by andoriyaprashant** [comment]
@literalEval If you want, I can open a new pull request and make this change because I felt the need for this change. If you don't want this change, it's fine

**Comment by palisadoes** [comment]
Closing for the reasons previously provided

**Pull request closed without merging**
