### PR TITLE
Fixes #1483 showSnackBar error: showing snackbar before screen is built

### LINKED ISSUE #1483: showSnackBar error: showing snackbar before screen is built
**Describe the bug**

**To Reproduce**

1. Use this org url https://talawaapi.azurewebsites.net/graphql
2. click o sign up button
3. screen will appear

**Expected behavior**
Should provide with poper error

**Actual behavior**
giving this error screen 

**Screenshots**
Screenshot from 2023-02-14 01-13-23

**Additional details**
I checked the error stack and it showed the this line showed this error
https://github.com/PalisadoesFoundation/talawa/blob/ac0571bcf6c7fc0a3bd930989a9848348024d094/lib/services/database_mutation_functions.dart#L126-L128

we have to make the changes in these line too so we don't get same error in the future
https://github.com/PalisadoesFoundation/talawa/blob/ac0571bcf6c7fc0a3bd930989a9848348024d094/lib/services/database_mutation_functions.dart#L89-L124

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by Ayush0Chaudhary**
**What kind of change does this PR introduce?**
I removed the error which was shown when there was a problem with URL, the snackbar was shown before the widget completed its build.

**Issue Number:**

Fixes #1483

**Snapshots/Videos:**
Screenshot from 2023-02-14 01-32-20

**Does this PR introduce a breaking change?**
NO

**Have you read the [contributing guide]
YES
(https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**

### CODE REVIEW

**Comment by palisadoes** [comment]
Please ask someone in the pinned issue to either assign or review the PR. I need to step back.

**Comment by Ayush0Chaudhary** [comment]
@palisadoes @noman2002 please help with problem? ig actions are using flutter new version to show linting warnings.

**Comment by palisadoes** [comment]
1. Should we be using the latest version of flutter?
1. Would the upgrade be hard to do?

**Comment by Ayush0Chaudhary** [comment]
looking into it, will get back to you

**Comment by palisadoes** [comment]
Some of these messages would be really good to resolve
- `'returnNullOnMissingStub' is deprecated and shouldn't be used. Specify "missing stub" behavior with the [onMissingStub] parameter`
- `Avoid method calls or property accesses on a "dynamic" target`
- `Avoid leading underscores for local identifiers`
- `no_leading_underscores_for_local_identifiers`
- `noop_primitive_operations`
- `Missing a required trailing comma`

**Comment by noman2002** [comment]
> 1. Should we be using the latest version of flutter?
> 
>     2. Would the upgrade be hard to do?

we are using 3.0.0 in the workflows. It is kind of old now but in the latest version i.e 3.7.0 there are lot of changes and various things are deprecated and it might break the current app.

**Comment by palisadoes** [comment]
> > 1. Should we be using the latest version of flutter?
> >    
> >    2. Would the upgrade be hard to do?
> 
> we are using 3.0.0 in the workflows. It is kind of old now but in the latest version i.e 3.7.0 there are lot of changes and various things are deprecated and it might break the current app.

Should we create an issue to do the upgrade? These problems are going to continue unless we do it. We could do a brief code freeze and have a few volunteers work on doing the migration.

**Comment by palisadoes** [comment]
We could also make it part of a GSoC idea. What do you think?

**Comment by Ayush0Chaudhary** [comment]
@palisadoes @noman2002  should I create separate PR for my actual issue??, It was blocking the work of our contributors.

**Comment by palisadoes** [comment]
> @palisadoes @noman2002 should I create separate PR for my actual issue??, It was blocking the work of our contributors.

Yes

**Comment by noman2002** [comment]
> We could also make it part of a GSoC idea. What do you think?

Yes we can add it.

**Comment by noman2002** [comment]
Another PR is open for the same issue

**Pull request closed without merging**
