### PR TITLE
Fixes #1574 Add Back button to go to select org screen

### LINKED ISSUE #1574: Add Back button to go to select org screen
**Describe the bug**
No back button to remove the current screen, user is stuck!

**To Reproduce**

1. Do sign up
2. select org
3. signup screen will be prompted

**Expected behavior**
Should have a back button so the user can choose other organization
**Actual behavior**
NO back button
**Screenshots**
Screenshot from 2023-02-27 05-22-13

**I suggest**  doing the following
Screenshot from 2023-02-27 05-33-31

**Additional details**
it is a small issue **but very important to increase app's UX**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by Ayush0Chaudhary**
**What kind of change does this PR introduce?**
add back arrow

**Issue Number:**

Fixes #1574

**Did you add tests for your changes?**
YES

**Snapshots/Videos:**
Screenshot from 2023-02-27 05-33-31

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**
no

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**
yes

### CODE REVIEW

**Comment by Ayush0Chaudhary** [comment]
@palisadoes @noman2002 please review

**Comment by Ayush0Chaudhary** [comment]
@noman2002 @palisadoes please have a look at failing test

**Comment by palisadoes** [comment]
Is there a way to refactor the code in a way that makes sense to avoid this?

We have the test to prevent bloated code

**Comment by Ayush0Chaudhary** [comment]
@palisadoes @noman2002

**Review by noman2002 — APPROVED** [review]

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
