### PR TITLE
[Feature Request #1346 ]: Enabling Plugins , Donation as a Plugin, Refractor for TalawaPluginProvider Widget

### LINKED ISSUE #1346: Feature Request : Enabling Plugins , Donation as a Plugin, Refractor for TalawaPluginProvider Widget
### Work in Progress : Details to be added soon
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

**Describe the solution you'd like**
 
1. Currently I am planning to implement these features as plugins by using the `TalawaPluginProvider` Class 
image
2, Making the scope of the Plugins organization wide
**Describe alternatives you've considered**
Alternatives can be suggested by mentors and reviewers

**Approach to be followed (optional)**
#### Problem :
Currently the donation feature in the talawa app is not functional and also not implemented as a plugin so that the admins can't control it's visibility
#### Solution :
Donation UI must be implemented as a plugin in order control it's visibility across the organization in the talwa app by the talawa-admin panel. Donations feature should be implemented by using payment pacakges like `flutter braintree` etc.
#### Approach :
1. Wrap the Donation with `TalawaPluginProvider` Widget (to enable as plugin)
2. Implement the payment button by using the
`flutter_braintree` package (https://pub.dev/packages/flutter_braintree)
3. After successful payment the donation transaction must be stored in the database and can be accessed by talawa-admin
 
More on braintree : https://www.braintreepayments.com/about-braintree

---
#### Problem : The main features of the talawa app are Events, Posts , etc. These features are not implemented as plugins which means that admin can't control whether to enable these features in the org or not.
We need some solution to implement it as a plugin
#### Solution :
Implement a mechanism to control visibility of those main features
#### Approach :
The main feature of the talawa app are only accessible from the navbar of the app So, to implement them as plugin we have to :
1. Create a separate widget `TalwaPluginProviderNav` that will be used for wrapping around theses navbar items.
2. `TalwaPluginProvider` will make sure to only show those components that are installed for that org only
3. If a `Plugin` has installed in the Organization by the admin then some of it's property should be like
```js
{
Visible : true,
installedOrgs : […,<YOUR_ORG_ID>]
}
```
a. The `TalawaPluginProviderNav` will make sure that these properties are valid and then and only then it will insert that items in the flutter UI tree for that navbar
b. Specific Icons for specific features are need to be specified already in a Object called as `insert-here` and then the Icons would also be dynamically rendered according to visibility of those features as plugins
c. The `visible` property of the navbar items can be set to `true` for development purposes . If true the features will be visible and  accessible in the organization even if they are not installed for that organization (use this for development only)

4. Working of the TalwaPluginProvider class :
---
#### Problem :
`TalawaPluginProvider` widget is used for implementing features as plugins.  It uses `Visiblity` widget to control  the visibility of the UI that It is wrapped over. `Visiblity` widget have some a issue that it does not remove that component from the Flutter UI tree . This can create some bugs in the future and  needs to be resolved
#### Solution :
We should directly return the componet instead of wrapping it in `Visiblity` Component
#### Approach :
Replace the `Visibility ` widget by an empty Container() widget.
---

**Additional context**
Will be added soon.

### PR DESCRIPTION
**Pull request by SiddheshKukade**
### Details will be added soon

**What kind of change does this PR introduce?**
Feature Request : for Enabling Plugins in Navbar, Implementing Donation as a Plugin, Refractor for TalawaPluginProvider Widget
**Issue Number:**

Fixes #1346 

**Did you add tests for your changes?**
Will be added soon.

**Snapshots/Videos:**
Will be added soon

**If relevant, did you update the documentation?**
Not needed for now but will be added later if required

**Summary**
Problems and their solutions are described below

#### Problem :
Currently the donation feature in the talawa app is not functional and also not implemented as a plugin so that the admins can't control it's visibility
#### Solution :
Donation UI must be implemented as a plugin in order control it's visibility across the organization in the talwa app by the talawa-admin panel. Donations feature should be implemented by using payment pacakges like [`flutter_braintree`](https://pub.dev/packages/flutter_braintree) etc.
#### Approach :
1. Wrap the Donation with `TalawaPluginProvider` Widget (to enable as plugin)
2. Implement the payment button by using the
`flutter_braintree` package (https://pub.dev/packages/flutter_braintree)
3. After successful payment the donation transaction must be stored in the database and can be accessed by talawa-admin
 
More on braintree : https://www.braintreepayments.com/about-braintree

---
#### Video : 

https://user-images.githubusercontent.com/65951872/189489729-ba913de7-8376-438f-a29d-bfcabecaddd2.mp4

#### Problem : The main features of the talawa app are Events, Posts , etc. These features are not implemented as plugins which means that admin can't control whether to enable these features in the org or not.
We need some solution to implement it as a plugin
#### Solution :
Implement a mechanism to control visibility of those main features
#### Approach :
The main feature of the talawa app are only accessible from the navbar of the app So, to implement them as plugin we have to :
1. Create a separate widget `TalwaPluginProviderNav` that will be used for wrapping around theses navbar items.
2. `TalwaPluginProvider` will make sure to only show those components that are installed for that org only
3. If a `Plugin` has installed in the Organization by the admin then some of it's property should be like
```js
{
Visible : true,
installedOrgs : […,<YOUR_ORG_ID>]
}
```
a. The `TalawaPluginProviderNav` will make sure that these properties are valid and then and only then it will insert that items in the flutter UI tree for that navbar
b. Specific Icons for specific features are need to be specified already in a Object called as `insert-here` and then the Icons would also be dynamically rendered according to visibility of those features as plugins
c. The `visible` property of the navbar items can be set to `true` for development purposes . If true the features will be visible and  accessible in the organization even if they are not installed for that organization (use this for development only)

4. Working of the TalwaPluginProvider class :
---
#### Problem :
`TalawaPluginProvider` widget is used for implementing features as plugins.  It uses `Visiblity` widget to control  the visibility of the UI that It is wrapped over. `Visiblity` widget have some a issue that it does not remove that component from the Flutter UI tree . This can create some bugs in the future and  needs to be resolved
#### Solution :
We should directly return the componet instead of wrapping it in `Visiblity` Component
#### Approach :
Replace the `Visibility` widget by an empty Container() widget.

---

**Does this PR introduce a breaking change?**
 No
**Other information**
Not needed.

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by SiddheshKukade** [comment]
@palisadoes actually sir, the tests cases are failing for the following file
`/talawa/test/widget_tests/widgets/custom_drawer_test.dart` and I've not changed anything in that file. I am not sure how the tests are failing for that. Can you give any advice ? 
image

**Review by DMills27 — DISMISSED** [review]
LGTM

**Comment by palisadoes** [comment]
@SiddheshKukade Please fix the failing tests.

**Comment by SiddheshKukade** [comment]
> @SiddheshKukade Please fix the failing tests.

@palisadoes Sir the now  current CI/CD is failing due to the code coverage. But I've added tests for the entire `utils` folder under 
you can check them [Test for `utils` folder](https://github.com/PalisadoesFoundation/talawa/pull/1355/files#diff-dde648740005822ab8cbf1f3951be139660d4188b1397693501b725f85926334).
But it looks like the codecov.io is not recognizing tests from `utils` folder. is that folder ignored from the code coverage ? 
image

**Comment by palisadoes** [comment]
I'm wondering if this could be caused by the extra comments we have been adding in the code

**Comment by palisadoes** [comment]
[You can see the files that are not covered here](https://github.com/PalisadoesFoundation/talawa/actions/runs/3255029955).

**Comment by SiddheshKukade** [comment]
> [You can see the files that are not covered here](https://github.com/PalisadoesFoundation/talawa/actions/runs/3255029955). Click on the `show more` link under the `Annotations` heading

Actaully Sir I just checked out that the Current code coverage of  `talawa` for the `develop` branch is around `68%`
From Codecov.io : [talawa ](app.codecov.io/gh/PalisadoesFoundation/talawa)
image

And in the workflow file `pull-request.yml`  it is set as` 71%  ( 3% more than current coverage )`
image
 
Should the expected coverage (workflow file) should be less than current coverage (codecov) ?

**Comment by palisadoes** [comment]
OK. I'll adjust it.

**Pull request merged**
