### PR TITLE
Add trailing commas wherever missing and format code (fixes #1153)

### LINKED ISSUE #1153: Receiving a bunch of 'Missing a required trailing comma' warnings
**Describe the bug**
Not exactly a bug but the entire codebase has missing trailing commas in most of the function calls and declarations. This is not a good linting practice as specified by the [Dart Linter Rules](https://dart.dev/tools/linter-rules#require_trailing_commas)

**To Reproduce**

1. If you have the Flutter and Dart plugin for VS Code installed, you should receive a bunch of warnings with the message "Missing a required trailing comma."

**Screenshots**
image

### PR DESCRIPTION
**Pull request by umang-sinha**
**What kind of change does this PR introduce?**

Adds trailing commas wherever they are missing and then formats the code accordingly

**Issue Number:** 

Fixes #1153 

**Did you add tests for your changes?**

  No. The change was only related to adding missing trailing commas

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

Documentation change is irrelevant in this case

**Summary**

To fix the hundreds of warnings mentioning 'missing trailing commas'

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by palisadoes** [comment]
- Please fix your conflicting files.
- The `/home/runner/work/talawa/talawa/lib/custom_painters/language_icon.dart` is now too long. Please add it to the exception list in [pull-request.yml](https://github.com/PalisadoesFoundation/talawa/blob/develop/.github/workflows/pull-request.yml) for `countline.py` to use. We will need to open a follow up issue to see how we can reduce the sizes of the currently excluded files.

**Comment by umang-sinha** [comment]
@palisadoes made the requested changes. Please take a look at this

**Comment by palisadoes** [comment]
Please fix the conflict in `test/helpers/test_helpers.dart` and update your commit

**Comment by umang-sinha** [comment]
> Please fix the conflict in `test/helpers/test_helpers.dart` and update your commit

hopefully this fixes the merge conflict

**Comment by umang-sinha** [comment]
the error that was being caused because of `flutter format --set-exit-ef-changed` is now fixed. However I am not sure how to fix the other one which states 'unauthorized file modification in PR'. How do I fix that?

**Comment by palisadoes** [comment]
The unauthorized file change failure is caused by editing the `pull-request.yml` file. I'll override it.

**Comment by palisadoes** [comment]
Please fix the linting error

**Pull request merged**
