### PR TITLE
[Fix] - Organization setting related issues #355

### PR DESCRIPTION
**Pull request by CyberWake**
**What kind of change does this PR introduce?**
- [x] Refactoring of code on the following screens: Profile, Organization setting, Organization member remove/admin, Update Organization.
- [x] Creation on reusable widgets for decreasing code redundancy enhancing readability of codebase.
- [x] User if not present in any organization now can only join/create new or either can logout.

- [x] **User(member)** in a organization can only **leave an organization**.

- [x] **User(Creator/admin)** of organization will only be able to see **organization settings** instead of leave organization tile.

- [x] In organization settings if **organization is private** then only **membership request tile** is shown else not.
 **Private Organization**     |    **Public Organization**   
  

- [x] **User(Creator)** only has the rights to **remove an organization** for organization settings.
     **User(Creator)**        |       **User(Admin)**   
  
- [x] **User(Admins/Creator)** can make **new admin or remove current members**.

- [x] **Intuitive progress on User(Admins/Creator)** having any interactions on accept member page or on members page. 
 

- [x] **Auto filled textfields** on update organization page **with previous settings.** 

- [x] **Reduction of API calls wherever it could be avoided by using prefetched data.** 

**Did you add tests for your changes?**
Not now.

**If relevant, did you update the documentation?**
Not needed, to update the documentation.
**Summary**
This PR is created in order to dissolve all the issues which were encountered relating to admin and creator right's which were earlier checked through the creator name and user name but not we have the admins field to check the same and id in creators field to be precise now admin right's are checked with user id which is unique so no chance of admin access getting into wring hands.

**Does this PR introduce a breaking change?**
No, this PR does not bring breaking changes

**Other information**
#355

### CODE REVIEW

**Comment by Sagar2366** [comment]
@CyberWake break down the issue as suggested in related issue as well.
Do not add any file which should not be part to fix this issue - no formatting, no code refactoring through same PR.
It get's difficult to review large PR with unnecessary changes added and mixed multiple issues fix in single PR. Keep PR's small which helps to review PR faster and easily.

**Comment by CyberWake** [comment]
@Sagar2366 sir the refactoring this here implemented is making a common widget for toast, alert dialog boxes. Should I undo this thing and create a different issue.

**Comment by Sagar2366** [comment]
> @Sagar2366 sir the refactoring this here implemented is making a common widget for toast, alert dialog boxes. Should I undo this thing and create a different issue.

Leave it for now. I will review this PR today.

**Comment by CyberWake** [comment]
thank you @Sagar2366 sir for showing generosity towards me.

**Comment by Sagar2366** [comment]
@CyberWake I need this code unit tested before merging it to master.
Either you can break down this issue into small issues and send small PR with unit test done or you can add unit test in this PR . Both works for me but need unit testing.

**Comment by CyberWake** [comment]
Ok, I'll add unit test to this one.

**Comment by CyberWake** [comment]
@Sagar2366 please review this PR.

**Review by Sagar2366 — APPROVED** [review]

**Comment by Sagar2366** [comment]
@CyberWake really appreciate your excellent work on this PR/issue.

**Comment by CyberWake** [comment]
thank you @Sagar2366 sir. Learned new thing to like to breakdown issue pertaining to same domain further into sub issues which I lagged behind in. Really nice to work under your guidance. 😃

**Pull request merged**
