### PR TITLE
Tests for SignUpDetailsViewModel

### LINKED ISSUE #1006: Unittests for signup_details_view_model.dart
We will need unittests done for all methods, classes and functions found in this file.

Any widgets referenced in this file must also have unittests done

```
pre_auth_view_models/signup_details_view_model.dart
```

This file can be found in the `lib/view_model` directory

Parent Issue: 
- https://github.com/PalisadoesFoundation/talawa/issues/1002
### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base.
- [The current code coverage for the file can be found here](https://codecov.io/gh/PalisadoesFoundation/talawa/tree/develop/lib/view_model/pre_auth_view_models)
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide

### PR DESCRIPTION
**Pull request by ahluwaliatikant**
**What kind of change does this PR introduce?**
Added tests for signup_details_view_model

**Issue Number:**
Fixes #1006 

**If relevant, did you update the documentation?**
No

**Does this PR introduce a breaking change?**
No

**Other information**
I have generated an extra mock class MockSignupViewModel for stubbing

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by ahluwaliatikant** [comment]
@rutvik11062000 I am able to build the app for Android locally, but here in the checks, the Build for Android check is failing.

**Review by palisadoes — APPROVED** [review]

**Comment by ahluwaliatikant** [comment]
Sure @palisadoes ! Looking forward to contributing more to the project.

**Comment by palisadoes** [comment]
Please fix the conflicts with `test/helpers/test_helpers.mocks.dart` so that we can merge

**Comment by patrickwitter** [comment]
@ahluwaliatikant How did you generate a mock for your signup details view model. Did you use mockito's code generation as I do not see the annotation in the test helpers file?

**Comment by ahluwaliatikant** [comment]
Hey @patrickwitter, yes I had used mockito's code generation only. I think I forgot to commit that change with the annotation somehow.

**Comment by patrickwitter** [comment]
Hey @ahluwaliatikant could you add the annotation as it is necessary for me to regenerate the file to add my mock without causing errors in your files.

**Comment by palisadoes** [comment]
Try using slack to work this out. It would be quicker as you seem to both online now.

**Comment by ahluwaliatikant** [comment]
Yeah sure, @patrickwitter, shall I first raise a PR directly or first create an issue for this , @palisadoes?

**Comment by palisadoes** [comment]
Yes

**Comment by ahluwaliatikant** [comment]
@palisadoes I have raised a PR with the required changes.

**Pull request merged**
