### PR TITLE
Built Support for Offline User Actions

### LINKED ISSUE #2528: Build Support for Offline User Actions
**Is your feature request related to a problem? Please describe.**

### Offline Support for Talawa Mobile

Currently, Talawa Mobile is barely usable in offline situations, often crashing when the device is not connected to the internet. To enhance user experience and reliability, we need to develop support for offline user actions, similar to other popular social media apps. 

### Objectives:
- Implement a system to cache user actions when the device is offline.
- Ensure these cached actions are pushed back and synced with the API once the device is back online.
- Improve overall app stability and prevent crashes in offline mode.

By addressing these objectives, we aim to make Talawa Mobile more robust and user-friendly, providing a seamless experience regardless of network connectivity.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Approach to be followed (optional)**
A clear and concise description of approach to be followed.

**Additional context**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by Azad99-9**
**What kind of change does this PR introduce?**

The PR adds support for Offline User Actions making the user to perform actions even in offline situations on cached data.
Deliverables:
**Constants**
1. AppStrings

**Models**
1. CachedUserActons
2. OfflineActionQueue

**Services**
1. CacheService
2. UserActionHandlerService
3. UserProfileService

**Exceptions**
1. CriticalActionException
2. GraphqQl Exception resolver

**Issue Number:**

Fixes #2528

**Did you add tests for your changes?**

Yes

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**

- Written a ActionHandler wrapper service which gets wrapped around all the existing functions in the app and decides whether to process the offline action or not.
- Classified all the actions in the mobile app into 2 broad categories : Optimistic, Critical.
1. Optimistic - Not so critical and the UI will be refreshed irrespective of the API call result. If device is offline this action will be cached else will be executed as it is. eg: liking a post, commenting a post, registering an event etc.
2. Crtical - The UI will be refreshed iff the API call is success eg: Login, Signup etc.
- Cached User actions will be used to cache the Optimistic user actions using Hive.
- Offline action queue is used to store,  prioritise and execute the cached user actions on re-establishment of internet connection.
- CacheService checks the device network status and then decides whether to cache or not the user action.

**Does this PR introduce a breaking change?**

No

**Other information**

- Upgraded the dart SDK version to 3.4.4.
- Fixed the ClientAuth not initialised bug.
- Fixed the !debugLocked bug.

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by Azad99-9** [comment]
Under progess writing tests for listed files.

**Comment by Azad99-9** [comment]
@noman2002 pleas have a look, I have fixed all the tests and raised code coverage. The above lines being shown as uncovered are related to auto generated hive.g files by build_runner. In my local the code coverage is 100% for above files but some how they are not being updated in the pr.

Screenshot from 2024-07-28 14-14-39
Screenshot from 2024-07-28 14-15-07

**Comment by palisadoes** [comment]
@noman2002 PTAL

**Review by noman2002 — APPROVED** [review]
LGTM

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
