### PR TITLE
[ENHANCEMENT] Added the comments and removed unused variables

### LINKED ISSUE #103: [Enhancement] Not proper comments to understand the code
I would like to work on it and make the project look more readable along with the changes in UI can you please assign me this

### LINKED ISSUE #127: Code requires formatting, for readability.
**Description**
A code that is well formatted with proper indentation in accordance with conventional guidelines, is more readable. Going through the code, I found it as an enhancement, for all of us out there.

**Am I doing this?**
I have formatted the code and will be making a pull request for the same.

### LINKED ISSUE #325: Improving Code Quality
**Description:** The Import statements on projects need to be organized which can be helpful in the future if someone wants to go through the codebase and can be helpful for future developments

Fixing this issue will add comments on all .dart files regarding import statements and improve the code quality.

@jordanliu @Sagar2366 I'll create a separate branch and PR,  if this issue is approved as it changes all the .dart files specifically adds comments in the import statement or else will close this issue :)

**Problem:**

**Solution:** 

**Future Work:**
We can also implement,
- https://pub.dev/packages/pedantic
- https://pub.dev/packages/dart_code_metrics

### PR DESCRIPTION
**Pull request by yasharth291**
**What kind of change does this PR introduce?**

ENHANCEMENT

**Did you add tests for your changes?**

NO

**If relevant, did you update the documentation?**

NO

**Summary**

The main motive behind making this pull request was to make the code easier to understand and remove the things which are not used.

**Does this PR introduce a breaking change?**
no

**Other information**
Fixes #103 
Fixes #325 
Fixes #127

### CODE REVIEW

**Comment by Sagar2366** [comment]
@yasharth291, can you please take latest code and make sure you are not missing anything as part of this issue.

**Comment by yasharth291** [comment]
it is the latest code sir

**Comment by yasharth291** [comment]
All the changes are according to the new codebase and it is ready to be merged

**Review by Sagar2366 — APPROVED** [review]

**Comment by Sagar2366** [comment]
@yasharth291 can you quickly resolve conflicts in 2 files and send PR for review ?

**Comment by yasharth291** [comment]
> @yasharth291 can you quickly resolve conflicts in 2 files and send PR for review ?

sure sir on it

**Comment by yasharth291** [comment]
@Sagar2366  sir they are resolved

**Pull request merged**
