### PR TITLE
Fix overflow on org selection screen

### PR DESCRIPTION
**Pull request by Literal-Eval**
### Fixes - #1082 

- Before 
Screenshot_20211225-103108

- After 
Screenshot_20211225-120350

### Changes
- Changes flex values for more space
- Moved lock icon to the right, for better presentation.

### CODE REVIEW

**Comment by Literal-Eval** [comment]
I see that one of the tests failed due to code coverage criteria. What am I expected to do here ? Test doesn't exist for the widget I'm changing.

**Comment by palisadoes** [comment]
@Literal-Eval your pull request is failing as the minimum code coverage for testing has not been met. Please refer to our [CONTRIBUTING.md](https://github.com/PalisadoesFoundation/talawa/blob/develop/CONTRIBUTING.md) for details. We need to get to 33% coverage.

Please write tests for the code you just modified and include it in the PR

**Review by palisadoes — CHANGES_REQUESTED** [review]
@Literal-Eval your pull request is failing as the minimum code coverage for testing has not been met. Please refer to our [CONTRIBUTING.md](https://github.com/PalisadoesFoundation/talawa/blob/develop/CONTRIBUTING.md) for details. We need to get to 33% coverage.

Please write tests for the code you just modified and include it in the PR

**Comment by CyberWake** [comment]
@Literal-Eval please change code coverage to 31% in the workflow for the PR to pass all the test cases.

**Comment by Literal-Eval** [comment]
> @Literal-Eval please change code coverage to 31% in the workflow for the PR to pass all the test cases.

Okay Sir.

**Comment by Literal-Eval** [comment]
Changed coverage to 31% (hope I'm authorized to do so), and also added test for CustomListTile widget (not completed, but good for a starting point).

**Comment by CyberWake** [comment]
@Literal-Eval let me discuss this.

**Comment by palisadoes** [comment]
> @Literal-Eval your pull request is failing as the minimum code coverage for testing has not been met. Please refer to our [CONTRIBUTING.md](https://github.com/PalisadoesFoundation/talawa/blob/develop/CONTRIBUTING.md) for details. We need to get to 33% coverage.
> 
> Please write tests for the code you just modified and include it in the PR

@CyberWake We are trying to increase our code coverage with each PR. @Literal-Eval Please revert your workflow change and add tests for your code.

**Comment by Literal-Eval** [comment]
That's the issue. My proposed code doesn't has significant changes. It just rearranges widgets in the widget tree. 

So that means, before further PRs, I should write tests for existing code for my PR to get accepted :)

**Comment by palisadoes** [comment]
> That's the issue. My proposed code doesn't has significant changes. It just rearranges widgets in the widget tree.
> 
> So that means, before further PRs, I should write tests for existing code for my PR to get accepted :)

And add tests in this PR to cover the work you have done.

Please remember to revert the changes to the workflow file.

**Comment by Literal-Eval** [comment]
Sure.

**Comment by palisadoes** [comment]
@Literal-Eval How is the testing going?

**Comment by Literal-Eval** [comment]
Yeah. I'm working on increasing coverage to 35%. 
Actually there was total network down in my area for last 24 hrs, and I couldn't contribute anything yesterday. 

But I've committed a test today and working on next one.

**Comment by Literal-Eval** [comment]
Since test files have been added, kindly consider merging this PR

**Comment by palisadoes** [comment]
@Literal-Eval Did you update the widget test for this change?

**Comment by Literal-Eval** [comment]
This PR doesn't change anything in the data. All it does is, it shifts the widgets a bit. So there is no need to change the test for this. 

Having said that, since I'm working on getting coverage to 35%, I'll anyway review all the tests for all widgets. 

So kindly merge this for time being.

**Comment by palisadoes** [comment]
@CyberWake Please review

**Review by CyberWake — APPROVED** [review]
Ready for merge.

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
