### PR TITLE
Refactor/snackbar

### PR DESCRIPTION
**Pull request by sayannath**
Issue #77 solved.

### CODE REVIEW

**Comment by i-anuragmishra** [comment]
Hey @sayannath  I guess snack bar issue was still up to mentioners for it to be assigned. I think we need to wait for maintainers to assign issues and resolve conflicts as it is the **standard operation procedure** in open-source repositories.
But still thanks for trying to resolve. but the issue also contained API that weren't functional.

**Review by DeltaHarbinger — APPROVED** [review]

**Review by DeltaHarbinger — CHANGES_REQUESTED** [review]
Hey @sayannath, it seems like another person's changes to '.flutter-plugins-dependencies' are conflicting with yours. Can you resolve this and request a review when you're done. It is fine if you undo all changes since this file should be ignored in version control in the first place.

**Comment by sayannath** [comment]
Ok! Will do it for sure

**Comment by sayannath** [comment]
I have resolved the issue!

**Comment by Sagar2366** [comment]
@sayannath looks like there is still conflict in .flutter-plugins-dependencies and lib/main.dart file. Please resolve it and request again for review.

**Review by DeltaHarbinger — CHANGES_REQUESTED** [review]
Hey @sayannath. Recent changes to master invoked a few merge conflicts with your branch. You can try to fix them, but I think it would be wise to pull the updated master branch and re-implement your changes. There were a lot of fixes implemented in the last merge

**Comment by sayannath** [comment]
Somebody has deleted the activity controller file.

**Comment by DeltaHarbinger** [comment]
Hey @sayannath, a few files have been removed due to not being used anymore. It seems like all files that used the old way of showing SnackBars were vetoed. This was a part of #151 which had a lot of stability changes for everyone to be able to compile the master. I understand that this may be frustrating, but this means that this PR should be closed.

**Pull request closed without merging**
