### PR TITLE
Feature Request: Make new profile page UI for showcasing the personal post/new post UI Fixes #1970

### LINKED ISSUE #1970: [GSoC]Feature Request: Make new profile page UI for showcasing the personal post etc..
**Is your feature request related to a problem? Please describe.**
User currently cannot view his post, now he will be able to see them.
**Describe the solution you'd like**
Carousel solution will work I

**Describe alternatives you've considered**
single page option was also considered and others too

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by Ayush0Chaudhary**
**What kind of change does this PR introduce?**

**Issue Number:**

Fixes  #1970 #1972

**Did you add tests for your changes?**
YEs

**Snapshots/Videos:**
image

**If relevant, did you update the documentation?**
yes

**Summary**

**Does this PR introduce a breaking change?**
no

**Other information**
no

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**
yes

### CODE REVIEW

**Comment by Ayush0Chaudhary** [comment]
@palisadoes @noman2002 I also added new post ui in this PR

image

**Comment by Ayush0Chaudhary** [comment]
The Design was approved by Rishav and his suggested changes are also incorporated.

**Comment by palisadoes** [comment]
1. Please fix the failing test.
2. @noman2002 @muskan399 Please review

**Comment by palisadoes** [comment]
1. Please put the fixes statements on separate lines to that both issues will be fixed when the PR is merged
2. Please also fix the conflicting files

**Review by noman2002 — CHANGES_REQUESTED** [review]
Resolve the conflicts.

**Comment by Ayush0Chaudhary** [comment]
Can we merge this? I will run pass all the checks in [this](https://github.com/PalisadoesFoundation/talawa/pull/1955) PR. 
As we discussed in last meet, too much documentation required as I did minor changes in 89 files.
@palisadoes @noman2002

**Comment by palisadoes** [comment]
@Ayush0Chaudhary Please fix the conflicting file and then we'll merge.

**Comment by Ayush0Chaudhary** [comment]
fixed the conflicting files, can we merge @palisadoes @noman2002

**Comment by palisadoes** [comment]
@Ayush0Chaudhary  The checks are failing. Something seems to be wrong with the github action. Can you investigate further.

**Comment by palisadoes** [comment]
@Ayush0Chaudhary Any updates on the causes for failing tests?

**Comment by Ayush0Chaudhary** [comment]
@palisadoes corrected the failing CI/CD

**Review by noman2002 — APPROVED** [review]
Looks good to me, I think tests are failing due to documentation only.

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
