### PR TITLE
Solves #1031

### LINKED ISSUE #1031: [Terminological error]  Misplaced description in `set_url_page_test.dart`
**Describe the bug**
While checking out the test files, I found a bug. Here it is "Testing if login button works" while it should be for the signup button.
**To Reproduce**

1. Open test/widget_tests/pre_auth_screens/set_url_page_test.dart
2. find the bug in lines 277 and 488

**Screenshots**
Screenshot (120)

**Additional details**
I would like to work on the issue @palisadoes pls assign me.

### PR DESCRIPTION
**Pull request by Simran1604**
**What kind of change does this PR introduce?**
bugfix

**Issue Number:**
 
Fixes #1031

**Did you add tests for your changes?**
No

**Snapshots/Videos:**
No

**If relevant, did you update the documentation?**
No

**Summary**

**Does this PR introduce a breaking change?**
No

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by palisadoes** [comment]
@Simran1604 your pull request is failing as the minimum code coverage for testing has not been met. Please refer to our [CONTRIBUTING.md](https://github.com/PalisadoesFoundation/talawa/blob/develop/CONTRIBUTING.md) for details. We need to get to 33% coverage.

Please write tests for the code you just modified and include it in the PR

**Review by palisadoes — CHANGES_REQUESTED** [review]
Your pull request is failing as the minimum code coverage for testing has not been met. Please refer to our [CONTRIBUTING.md](https://github.com/PalisadoesFoundation/talawa/blob/develop/CONTRIBUTING.md) for details. We need to get to 33% coverage.

Please write tests for the code you just modified and include it in the PR

**Comment by Simran1604** [comment]
> Your pull request is failing as the minimum code coverage for testing has not been met. Please refer to our [CONTRIBUTING.md](https://github.com/PalisadoesFoundation/talawa/blob/develop/CONTRIBUTING.md) for details. We need to get to 33% coverage.
> 
> Please write tests for the code you just modified and include it in the PR

@palisadoes Sir, but the file is itself a unit test?

**Comment by palisadoes** [comment]
> > Your pull request is failing as the minimum code coverage for testing has not been met. Please refer to our [CONTRIBUTING.md](https://github.com/PalisadoesFoundation/talawa/blob/develop/CONTRIBUTING.md) for details. We need to get to 33% coverage.
> > Please write tests for the code you just modified and include it in the PR
> 
> @palisadoes Sir, but the file is itself a unit test?

That's true, but we are trying to get the code coverage increased with every pull request to improve the reliability of the app. [Our coverage is at 32.29%](https://app.codecov.io/gh/PalisadoesFoundation/talawa). Getting it to 33% for this pull request is achievable. 

Please assist us in getting to our goal of 100% coverage.

**Comment by Simran1604** [comment]
> 

sure sir, on it.

**Comment by palisadoes** [comment]
@Simran1604 How is progress on this? The current code coverage is 33.48% You will need it to reach 33.5% for the tests to pass. The threshold to reach this goal is low.

**Comment by Simran1604** [comment]
> @Simran1604 How is progress on this? The current code coverage is 33.48% You will need it to reach 33.5% for the tests to pass. The threshold to reach this goal is low.

Yes sir, will do that in the next commits.

**Review by palisadoes — APPROVED** [review]

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
