### PR TITLE
implement quick_fix for talawa_good_doc and enforce tab before None of params block

### PR DESCRIPTION
**Pull request by literalEval**
**What kind of change does this PR introduce?**

1. Adds quick_fix feature for the `talawa_api_doc` custom lint rule. Now a template can be inserted with a few clicks to document the code easily.
2. Enforces a `tab` space before the `None` of empty param list.
3. Adds URL to `Talawa Docs` in the error message itself.

**Issue Number:**

Part of: #1646 

**Snapshots/Videos:**

https://user-images.githubusercontent.com/62198564/230409919-8f9c1ee2-a34b-4a01-9f1d-3bdff6736a4e.mp4

### CODE REVIEW

**Comment by literalEval** [comment]
@palisadoes please merge :)

**Comment by palisadoes** [comment]
1. This `a_line_ending_with_end_punctuation.` text will not be meaningful to the user. It doesn't tell them why they should add it. The user needs to understand the rationale so that they can act responsibly when adding documentation.
2. Similarly with the `more_info_if_required` text. An explanation needs to be given.

This may make sense to you as the developer, but the user will be ignorant of the requirement.

@anwersayeed Please review this PR.

**Comment by palisadoes** [comment]
Also, does the new auto-inserted text comply with the DartDoc standard?

**Comment by literalEval** [comment]
> 1. This `a_line_ending_with_end_punctuation.` text will not be meaningful to the user. It doesn't tell them why they should add it. The user needs to understand the rationale so that they can act responsibly when adding documentation.
> 2. Similarly with the `more_info_if_required` text. An explanation needs to be given.
> 
> This may make sense to you as the developer, but the user will be ignorant of the requirement.
> 
> @anwersayeed Please review this PR.

That's a good point. I'll quickly modify it.

**Comment by literalEval** [comment]
@palisadoes we already have the docs for our lint rules in Talawa-docs. The errors generated are descriptive too. We can also add a file to the codebase which shows all the possibilities of declarations and how to document them.
Moreover, the next step I have planned is to add a link to the corresponding Talawa-docs page in the error messages. So that users can click on them and a very descriptive page opens up for them. I think this much spoonfeeding is good enough even for beginners. We can't do everything.

What is your opinion?

**Comment by literalEval** [comment]
@palisadoes added URL to `Talawa Docs` in the error message. Now it will lead directly to the docs page.

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
