### PR TITLE
Added Pedantic Dependency

### LINKED ISSUE #400: Add Lint dependency
I would like to work on this issue. Kindly assign this issue to me @Sagar2366.

### PR DESCRIPTION
**Pull request by Neha62-lit**
Fixes #400 

**What kind of change does this PR introduce?**
Feature

**Did you add tests for your changes?**
No

**If relevant, did you update the documentation?**
No

**Summary**
Linting is the process of checking the source code for programmatic as well as Stylistic errors and unformatted code. It's helpful in identifying some common and uncommon mistakes that are made during coding like logical errors, unused variables etc.
Here, I have added the Pedantic Dependency and one new file i.e. analysis_options.yaml in root of the project and in that file I added all the lint rules.

**Does this PR introduce a breaking change?**
No

### CODE REVIEW

**Comment by Neha62-lit** [comment]
@Sagar2366 Please review and merge this PR.

**Comment by Sagar2366** [comment]
@Neha62-lit Thank you for this work. Can you please share video demo of what will be the result on merging this PR ?

**Comment by Neha62-lit** [comment]
> @Neha62-lit Thank you for this work. Can you please share video demo of what will be the result on merging this PR ?

Yes.

**Comment by Sagar2366** [comment]
@Neha62-lit any update on this ?

**Comment by Neha62-lit** [comment]
> @Neha62-lit any update on this ?

Sorry for late, I'll send you demo video by tomorrow.

**Comment by Sagar2366** [comment]
@Neha62-lit any update on this ?

**Comment by Neha62-lit** [comment]
All these are warnings we got after adding the Pedantic dependency, it shows that dependency is working properly and showing such warnings if the rules aren't followed correctly. Also we can change those rules according to our requirements. We have to solve these warnings. Anyone who will work on any file, he will solve all the warnings in that file. So it will be easier to solve all these warnings and making the code clean.

Video Demo:

https://user-images.githubusercontent.com/70088044/112531590-c18d3100-8dcd-11eb-8712-f16b884e3e4d.mp4

**Comment by Neha62-lit** [comment]
@Sagar2366 Please review and merge this PR.

**Comment by Sagar2366** [comment]
@Neha62-lit is it possible to apply pedantic dependency rules through Github action or any CI tool ?
Problem - We are assuming, someone who is raising PR will always fix the warnings coming in project files.

If we enable it to Github,  we can enable check to follow code guidelines/rules to pass the PR.

**Comment by Neha62-lit** [comment]
> @Neha62-lit is it possible to apply pedantic dependency rules through Github action or any CI tool ?
> Problem - We are assuming, someone who is raising PR will always fix the warnings coming in project files.
> 
> If we enable it to Github, we can enable check to follow code guidelines/rules to pass the PR.

Okay, I'll search about it and apply pedantic dependency rules through GitHub actions ASAP.

**Comment by Neha62-lit** [comment]
@Sagar2366  I added the ci.yml file in the .github/workflows/ directory in the project. 
It is working properly now because my one check of CI / lint is not successful after PR. What can I do now, Should I fix the all warnings in the code or not?

**Comment by Sagar2366** [comment]
@Neha62-lit please check error once, why is it failing ?

**Comment by Neha62-lit** [comment]
> @Neha62-lit please check error once, why is it failing ?

I added the pedantic dependency rules through GitHub actions in the project,  Now when someone raising the PR, that person should be follow the all rules of pedantic dependency. 
Now, I'm getting this errors because in the Code so many issues/warnings are found. That's why it is failing.

**Comment by Neha62-lit** [comment]
> @Neha62-lit is it possible to apply pedantic dependency rules through Github action or any CI tool ?
> Problem - We are assuming, someone who is raising PR will always fix the warnings coming in project files.
> 
> If we enable it to Github, we can enable check to follow code guidelines/rules to pass the PR.

This problem is solved now.

**Review by Sagar2366 — APPROVED** [review]

**Comment by Sagar2366** [comment]
Screenshot 2021-03-30 at 10 49 45 PM

CI check is failing, have a look.

**Comment by Neha62-lit** [comment]
> Screenshot 2021-03-30 at 10 49 45 PM
> 
> CI check is failing, have a look.

Okay, I'll solve the all warnings in the code.

**Comment by Sagar2366** [comment]
@Neha62-lit, this will a major change to codebase and may break app in some parts if not fully tested.
Let's keep this PR on hold until code freeze period.

**Comment by Neha62-lit** [comment]
> @Neha62-lit, this will a major change to codebase and may break app in some parts if not fully tested.
> Let's keep this PR on hold until code freeze period.

Okay, No issues!

**Comment by Neha62-lit** [comment]
> @Neha62-lit, this will a major change to codebase and may break app in some parts if not fully tested.
> Let's keep this PR on hold until code freeze period.

Okay, No problem!

**Comment by palisadoes** [comment]
This has been resolved with #693 Thanks for working on this and bringing it to our attention.

**Pull request closed without merging**
