### PR TITLE
(Revert 999 ) video player fixes

### LINKED ISSUE #997: Video on the feed is playing even when scrolled up or tab changed
**Describe the bug**
Videos embed on the feed is playing continuously even when page is scrolled up or even when the active tab on the bottom navigation bar is changed. 

**Expected behavior**
The video should stop when scrolled up or the tab is changed.

**Actual behavior**
The video is playing the background.

**Additional details**
N/A

### PR DESCRIPTION
**Pull request by aman-singh7**
**What kind of change does this PR introduce?**
-Bug Fixes in Video post.

**Issue Number:**
Fixes #997 

**Video/Screenshot:**

https://user-images.githubusercontent.com/77198905/142408219-2a9cb10e-d56b-4452-9505-a9e454a9cc47.mp4

https://user-images.githubusercontent.com/77198905/142407600-b1c95f9d-de57-47d3-b261-16cd1730476e.mp4

**Summary**
There is some bug in the existing `InView` implementation due to which only the first video is playing and does not pause when scrolled or the bottom navigation tab is changed.

**Does this PR introduce a breaking change?**
No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by aman-singh7** [comment]
@palisadoes is it fine??

**Review by palisadoes — CHANGES_REQUESTED** [review]
@aman-singh7 You exceeded the maximum filesize count for ` lib/views/after_auth_screens/events/explore_events.dart`

We have limit of 300 lines to help make the code readable and testable. The aim is to create widget files that can be reused. 

Please find a way to reduce the size of the file using the strategy above.

@CyberWake @sumitra19jha @rutvik11062000 Am I correct in this assessment?

**Comment by aman-singh7** [comment]
> @aman-singh7 You exceeded the maximum filesize count for ` lib/views/after_auth_screens/events/explore_events.dart`
> 
> We have limit of 300 lines to help make the code readable and testable. The aim is to create widget files that can be reused.
> 
> Please find a way to reduce the size of the file using the strategy above.
> 
> @CyberWake @sumitra19jha @rutvik11062000 Am I correct in this assessment?

@palisadoes but I haven't touched that file. And CI didn't even fail for that as well?

**Comment by aman-singh7** [comment]
> @aman-singh7 You exceeded the maximum filesize count for ` lib/views/after_auth_screens/events/explore_events.dart`
> 
> We have limit of 300 lines to help make the code readable and testable. The aim is to create widget files that can be reused.
> 
> Please find a way to reduce the size of the file using the strategy above.
> 
> @CyberWake @sumitra19jha @rutvik11062000 Am I correct in this assessment?

@palisadoes but I haven't touched that file. And CI didn't even fail for that as well?

**Comment by CyberWake** [comment]
> @aman-singh7 You exceeded the maximum filesize count for ` lib/views/after_auth_screens/events/explore_events.dart`
> 
> We have limit of 300 lines to help make the code readable and testable. The aim is to create widget files that can be reused.
> 
> Please find a way to reduce the size of the file using the strategy above.
> 
> @CyberWake @sumitra19jha @rutvik11062000 Am I correct in this assessment?

the file was exceeding the line limit of 300 before the revert I guess due to which pushing to which test was failing. Gone through the current PR the file has a line count under the limit of 300.

**Review by CyberWake — DISMISSED** [review]
Good to merge.

**Review by palisadoes — APPROVED** [review]

**Review by palisadoes — CHANGES_REQUESTED** [review]
@aman-singh7  Please merge this into the `develop` branch

**Comment by palisadoes** [comment]
@aman-singh7 Please resubmit your pull request against the develop branch.
I've deleted the branch that was created due to reverting the PR

>

**Pull request merged**
