### PR TITLE
Created greetings for first time Issues and PRs

### PR DESCRIPTION
**Pull request by DeltaHarbinger**
QoL changes for first-time contributors 

Created greetings for first-time Issues and PRs

Some users may be unsure of how to contribute or whether or not they're creating Issues and PRs correctly. These messages will direct first-time contributors to appropriate documents outlining our guidelines

### CODE REVIEW

**Comment by jordanliu** [comment]
Could you remove the first interaction task from this, please: 
https://github.com/PalisadoesFoundation/talawa/blob/master/.github/workflows/issue.yml

**Comment by Sagar2366** [comment]
> Could you remove the first interaction task from this, please:
> https://github.com/PalisadoesFoundation/talawa/blob/master/.github/workflows/issue.yml

@jordanliu you mean tagging issues with unapproved label ?
I think we should keep it as it will help maintainers to track which issues they have reviewed/assigned to students or not.
Would like to hear yours point of view on this also.

**Comment by jordanliu** [comment]
> > Could you remove the first interaction task from this, please:
> > https://github.com/PalisadoesFoundation/talawa/blob/master/.github/workflows/issue.yml
> 
> @jordanliu you mean tagging issues with unapproved label ?
> I think we should keep it as it will help maintainers to track which issues they have reviewed/assigned to students or not.
> Would like to hear yours point of view on this also.

Not that, there's a task in that yml that does greeting
` - uses: actions/first-interaction@v1.1.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: 'Thank you for your contribution to Talawa, please read our [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)'
          pr-message:  'Thank you for your contribution to Talawa, please read our [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)'
`

**Comment by DeltaHarbinger** [comment]
Forst interaction removed from issues yml

**Review by jordanliu — APPROVED** [review]

**Pull request merged**
