### PR TITLE
100% coverage for Pinned carousel widget tests

### LINKED ISSUE #1177: Unittests for widget pinned_carousel_widget.dart
We will need unittests done for all methods, classes and functions found in this file.

Any widgets referenced in this file must also have unittests done

```
pinned_carousel_widget.dart
```

This file can be found in the `lib/widgets` directory

Parent Issue: 
- https://github.com/PalisadoesFoundation/talawa/issues/1125

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base.
- [The current code coverage for the file can be found here](https://codecov.io/gh/PalisadoesFoundation/talawa/tree/develop/lib/widgets)
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide

### PR DESCRIPTION
**Pull request by sudo-saksham**
**What kind of change does this PR introduce?**

100% test coverage for pinned_carousel_widget.dart

**Issue Number:**

Fixes #1177 

**Did you add tests for your changes?**

Yes

**Does this PR introduce a breaking change?**

No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by palisadoes** [comment]
Please fix the conflicting files

**Comment by sudo-saksham** [comment]
Done.

**Comment by palisadoes** [comment]
Please fix the failing formatting:
- https://github.com/PalisadoesFoundation/talawa/runs/5801659135?check_suite_focus=true

**Comment by palisadoes** [comment]
Why are so many files being submitted for the testing of one file. Updates to tests not related to the pinned carousel are included. Please fix.

**Review by palisadoes — CHANGES_REQUESTED** [review]
Why are so many files being submitted for the testing of one file. Updates to tests not related to the pinned carousel are included. Please fix.

**Comment by sudo-saksham** [comment]
There needs to be changes in Pinned Carousel to test the methods via widget tests. For ex. the variable pindex is accessible when State is accessible, that's why some changes need to be made in PinnedCarouselWidget to make it accessible for testing.

**Comment by sudo-saksham** [comment]
Let me close this and make a clean Pull Request.

**Pull request closed without merging**
