### PR TITLE
Infinite loading issue fixed on all screens.

### PR DESCRIPTION
**Pull request by AniketSindhu**
**What kind of change does this PR introduce?**
#298 issue fixed. Now CircularProgressIndicator shows only for 10 seconds, after that error screen is shown (only If the data is empty).

## Error Page
drawing

### CODE REVIEW

**Comment by Sagar2366** [comment]
@AniketSindhu this works only for the first time loading.
But on next call of API [For example, if we switch between tabs -from events to  members to newsfeed, and back to events],  it does not show circularprogressindicator indicating it is trying to load data and making API call instead it shows error screen you added.

**Comment by AniketSindhu** [comment]
@Sagar2366 I will look into that

**Comment by Sagar2366** [comment]
@AniketSindhu any update on this ?

**Comment by AniketSindhu** [comment]
will submit the fix in 2-3 hrs

**Comment by AniketSindhu** [comment]
@Sagar2366 API is only called in the initState which is only called once, that's why the page does not rebuild when you navigate using the bottom nav bar. I have added Unique key to the loading widget because of this whenever the parent widget is rebuild using setSate the loading widget will also rebuild (will show CircularProgressIndicator).

**Review by Sagar2366 — APPROVED** [review]

**Comment by Sagar2366** [comment]
@AniketSindhu travis ci is failing have a look.

**Comment by pr4nshul** [comment]
Hey, @AniketSindhu if you need help let me know :)

**Comment by AniketSindhu** [comment]
@Sagar2366 there was one test that checks for the loading widget I just commented out that test because I created a new widget for loading with error handling so it won't be detected by that test.

**Comment by AniketSindhu** [comment]
@pr4nshul can you help me write tests for the new loading widget I created?

**Comment by pr4nshul** [comment]
Yes, let's discuss it on slack @AniketSindhu

**Comment by AniketSindhu** [comment]
@Sagar2366 All the tests are now passing now.

**Comment by Sagar2366** [comment]
@AniketSindhu Thank you for work on this PR. can you please remove changes which are already there in master ? Also keep the changes you added to resolve the issue [disable auto-formatter] while pushing changes to PR.

**Comment by AniketSindhu** [comment]
@Sagar2366 All done !

**Pull request merged**
