### PR TITLE
Implemented MVVM on update_profile_page_view.dart

### PR DESCRIPTION
**Pull request by rutvik11062000**
**What kind of change does this PR introduce?**
Structurally added Model-View-ViewModel layers in "Update Profile" page.

**Did you add tests for your changes?**
Yes, Updated the update profile page test.
**If relevant, did you update the documentation?**

**Summary**
For ease of testing and separation of different layers to make a logical data flow and error handling.

**Does this PR introduce a breaking change?**
No.

**Other information**
There was an exception of` updateUserProfile" on type mutation` even before these PR changes.
Once develop and master branch merges this error will be not there and user can update their profiles.
Resolves: #758

### CODE REVIEW

**Comment by palisadoes** [comment]
@dellyjm
@DeltaHarbinger
@Sagar2366
@TheHazeEffect

Please review this

**Comment by Sagar2366** [comment]
@rutvik11062000 linter check is failing, resolve conflicts on PR.

**Comment by palisadoes** [comment]
@Dev-Dominic please take a look

**Comment by palisadoes** [comment]
@rutvik11062000 please resolve the conflicts

**Comment by rutvik11062000** [comment]
> @rutvik11062000 please resolve the conflicts

Done sir.

**Comment by palisadoes** [comment]
@rutvik11062000 `lib/views/pages/organization/join_organization.dart` has a conflict

**Comment by palisadoes** [comment]
@rutvik11062000 The Travis integration is failing.

**Comment by rutvik11062000** [comment]
> @rutvik11062000 The Travis integration is failing.

Yes sir, I just fixed it.

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
