### PR TITLE
Fixes #1757 implement Proper error handling for ( getaddrinfo ENOTFOU…

### LINKED ISSUE #1757: [Bug Report] Proper error handling for ( getaddrinfo ENOTFOUND metadata.google.internal.)
**Describe the bug**
This error occurs sometime when trying to make events

**To Reproduce**

1. Complete setup
2. Try to make a event

**Expected behavior**
Should atleast give proper error handling when the error occur 

**Actual behavior**
Give the following error message
 getaddrinfo ENOTFOUND metadata.google.internal.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by Ayush0Chaudhary**
…ND metadata.google.internal.)

**What kind of change does this PR introduce?**
When we try to trigger Notification from talawa-api and our setup for notification is not complete then we use to return anonymous reply to our user, now i return proper error when this problem occur

**Issue Number:**

Fixes #1757

**Snapshots/Videos:**
Screenshot from 2023-04-12 02-27-58

**If relevant, did you update the documentation?**
Yes

**Does this PR introduce a breaking change?**
no

**Other information**
nill

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by palisadoes** [comment]
1. I noticed that the error may message doesn't have translations. Is this the case?
2. Please also remove any unnecessary `print` statements in the file.

**Comment by Ayush0Chaudhary** [comment]
@palisadoes @noman2002 
I didn't make any changes in app_localization, still the tests are failing

**Comment by palisadoes** [comment]
[app_localization.dart](https://github.com/PalisadoesFoundation/talawa/blob/develop/lib/utils/app_localization.dart) was modified last month. You seem to have triggered a bug or inadvertently added an edge case.

Please investigate

**Comment by Ayush0Chaudhary** [comment]
@palisadoes I'll do it ASAP
My exams are near so it will take a bit of time.

**Comment by noman2002** [comment]
@Ayush0Chaudhary Any update on this PR ?

**Comment by noman2002** [comment]
@Ayush0Chaudhary Please close this PR if its not needed anymore.

**Comment by Ayush0Chaudhary** [comment]
> @Ayush0Chaudhary Please close this PR if its not needed anymore.

Can we merge this now? @noman2002 @palisadoes

**Comment by palisadoes** [comment]
Please get the code coverage up or should we reduce the value in the check?

**Comment by noman2002** [comment]
@palisadoes We need to reduce the value in check.

**Review by noman2002 — APPROVED** [review]

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
