### PR TITLE
Test for router.dart

### LINKED ISSUE #1473: Unittest for router.dart
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

Router is important part of the app, it makes sure that correct screen shows up when asked for.

I'll like to have 100% coverage in this file

### PR DESCRIPTION
**Pull request by Azad99-9**
**What kind of change does this PR introduce?**

This PR adds unit tests to the router.dart file

#1473 

Fixes #1473 

**Did you add tests for your changes?**

Yes

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

No

**Summary**

The motive is to make the router.dart file 100% code covered.

**Does this PR introduce a breaking change?**

No

**Other information**

Created a new file: test/router_test.dart

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by Azad99-9** [comment]
@palisadoes, @Ayush0Chaudhary could you please suggest me why is the above test failing.

**Comment by palisadoes** [comment]
It looks like a transient bug. Please do a minor commit to see whether it clears.

**Comment by Azad99-9** [comment]
@palisadoes  I followed your suggestion by making a minor commit, but unfortunately, the issue continues to persist. After further investigation, it appears that the problem is linked to the GitHub Actions workflow. I'm seeking guidance on the best course of action to resolve this. Could you kindly advise on the next steps I should take to address this issue related to the GitHub Actions workflow?

**Comment by palisadoes** [comment]
1. Yes it looks like the workflow isn't executing correctly for this PR, though it has been working for others in this and other repos. We use the workflow to let new contributors what to expect, so it's important.
2. Create a test PR and see whether it persists. We need to know if this issue is just related to this PR.

**Comment by Azad99-9** [comment]
Ok

**Comment by aashimawadhwa** [comment]
@noman2002 can you please look into this issue

**Comment by Azad99-9** [comment]
Pull request #2139 points this issue more clearyly.

**Comment by palisadoes** [comment]
The pull request target GitHub workflow has suddenly started to fail in this and other repos. The GitHub action hasn't been updated since September. A dependency has changed and the authors will need to fix it. We'll have to ignore it for now.

- https://github.com/actions/first-interaction

**Comment by palisadoes** [comment]
@Azad99-9 Please `dart format` your code and the PR workflow will work correctly

**Comment by Azad99-9** [comment]
got it @palisadoes .

**Comment by Azad99-9** [comment]
@aashimawadhwa please assign reviewers for this PR.

**Review by noman2002 — APPROVED** [review]

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
