### PR TITLE
added tests for waiting_view_model

### LINKED ISSUE #1005: Unittests for pre_auth_view_models/waiting_view_model.dart
We will need unittests done for all methods, classes and functions found in this file.

Any widgets referenced in this file must also have unittests done

```
pre_auth_view_models/waiting_view_model.dart
```

This file can be found in the `lib/view_model` directory

Parent Issue: 
- https://github.com/PalisadoesFoundation/talawa/issues/1002
### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base.
- [The current code coverage for the file can be found here](https://codecov.io/gh/PalisadoesFoundation/talawa/tree/develop/lib/view_model/pre_auth_view_models)
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide

### PR DESCRIPTION
**Pull request by guptapriyanshu7**
**What kind of change does this PR introduce?**
added tests for waiting_view_model

**Issue Number:**
Fixes #1005 

**Did you add tests for your changes?**
Yes

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by palisadoes** [comment]
Should we add this directory to .gitignore? It only has empty files in it.

https://github.com/PalisadoesFoundation/talawa/tree/develop/test/fixtures/core

**Comment by guptapriyanshu7** [comment]
Yes, those are helper files auto generated by Hive for testing. We can add that.

**Comment by palisadoes** [comment]
Please add the updated `.gitignore` file for the `fixtures/core` (or is it just `core`?) to the PR, and delete

**Comment by guptapriyanshu7** [comment]
Oh it's test/fixtures/core, sure i'll do that.

**Comment by palisadoes** [comment]
Please fix the conflicting file and update your commit

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
