### PR TITLE
test: adding test for org_info

### LINKED ISSUE #1419: Models: Tests for org_info.dart
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

We will need unittests done for all methods, classes and functions found in this file.

Any widgets referenced in this file must also have unittests done

```
lib/models/organization/org_info.dart
```

- Parent Issue: https://github.com/PalisadoesFoundation/talawa/issues/1414

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base.
- [The current code coverage for the file can be found here](https://codecov.io/gh/PalisadoesFoundation/talawa/tree/develop/lib/models/organization)
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide

### PR DESCRIPTION
**Pull request by arunavabasu-03**
👉 **What kind of change does this PR introduce?**

The test is being added to the org_info.dart file to check the functionality of the org model. This will ensure that the org_info model is working properly before it is integrated into the main branch.

👉 **Issue Number:**

Fixes #1419 

👉 **Did you add tests for your changes?**

👉 **Snapshots/Videos:**

👉 **If relevant, did you update the documentation?**

👉 **Summary**

This pr adding test for org_info model 

👉 **Does this PR introduce a breaking change?**

👉**Other information**

👉**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**

yes

### CODE REVIEW

**Review by noman2002 — CHANGES_REQUESTED** [review]
Please fix the failing test.

**Comment by noman2002** [comment]
@arunavabasu-03 Any progress on this ?

**Comment by arunavabasu-03** [comment]
Semester exams are going to start , so progress is slow but try my best to solve this !!

**Review by TheHazeEffect — APPROVED** [review]

**Comment by palisadoes** [comment]
@arunavabasu-03 Please fix the failing tests

**Comment by noman2002** [comment]
@arunavabasu-03 closing this for now, as there is no activity. Please create a fresh PR once this is fixed.

**Pull request closed without merging**
