### PR TITLE
Bug Fix: Custom Lint

### LINKED ISSUE #2428: Bug Report: Fixing comment out Custom Lint code
**Describe the bug**
As mentioned in my previous PR https://github.com/PalisadoesFoundation/talawa/pull/2413
This Code have been commented by me to pass the checks in github workflows 

snippet

image

snippet (1)

The line /// @{nodoc} has been removed for now. Work a way out to keep that line and make the workflows running

**To Reproduce**

1. To pass the github/workflows by working out on a solution to tackle ///nodoc without removing it 
2. To make sure the custom lint checks work in github workflows and is uncommented out again 
3. 2 Files need to be changed as shown by the code snippet.

**Expected behavior**
The desired behaviour would be to make sure that the custom lint code is uncommented again to check for custom lint directives and it doesn't fail for /// {nodoc} . Idea would be to find a way since removing this line is still failing the workflows.

**Actual behavior**
Currently the code has been commented out to pass the custom lint checks. 

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by ArinNigam**
**What kind of change does this PR introduce?**

**Issue Number:**

Fixes #2428 

**Did you add tests for your changes?**
No

**Snapshots/Videos:**
image
snippet (19)

**If relevant, did you update the documentation?**
No, but apparently there was no documentation for ChatMessage which is why `check_ignore.py` was failing but it must be in some later PR that it was added in talawa-docs

**Summary**

**Other information**
NA

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by dhanagopu** [comment]
@ArinNigam Please fix failing checks

**Comment by ArinNigam** [comment]
@dhanagopu failing checks are due to the changes made in `check_ignore.py` file. A part of code was commented by me in #2413 because of failing workflows and was made as a separate issue to go ahead with the previous PR.

**Comment by Cioppolo14** [comment]
@ArinNigam Please let the queue monitors assign reviewers.

**Comment by Cioppolo14** [comment]
@CyberWake @Ayush0Chaudhary Can you review this PR ?

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
