### PR TITLE
Fixes #1688 Mobile-app polling the server multiple time per sec to ch…

### LINKED ISSUE #1688: Mobile-app polling the server multiple time per sec to check plugin change
**Describe the bug**
Although not a bug, the current approach for obtaining real-time upgrades through the mobile app is sub-optimal as it involves sending approximately 50-60 requests per second to check for any changes in the plugins.

**To Reproduce**

1.Complete the setuo of talawa-api, mobile and admin
2.run the app
3.See the logs of talawa-api

**Expected behavior**
To achieve real-time features without causing server overload, there are several techniques that can be employed. One such technique is the use of sockets, which allow the server to communicate with the client and inform it of any changes as they happen. This approach can reduce the number of unnecessary requests and improve the overall efficiency of the system.

Another approach is to reduce the frequency of updates, particularly for short-term needs. This can involve adjusting the polling frequency or employing caching mechanisms to avoid excessive requests to the server. Additionally, implementing server-side push notifications or utilizing WebSockets can enable real-time communication without overloading the server.

These techniques can be further optimized by implementing strategies such as load balancing, caching, and distributed computing, which can help distribute the workload and prevent any single component from becoming a bottleneck. Overall, the key is to strike a balance between real-time responsiveness and server performance, ensuring a seamless user experience while maintaining system stability.

**Actual behavior**
Making multiple request to server for now to get updates

**Screenshots**
**Additional details**
I opened the issue so that we can track this problem
**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by Ayush0Chaudhary**
**What kind of change does this PR introduce?**
It mobile app was making way too many server request, I added a timer to reduce the request numbers

**Issue Number:**

Fixes  #1688

**Did you add tests for your changes?**

**Snapshots/Videos:**
Screenshot from 2023-04-01 23-37-16

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**
yes, some what. 

**Other information**
no

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**
yes

### CODE REVIEW

**Comment by literalEval** [comment]
@Ayush0Chaudhary I think 5 minutes will be a more reasonable timeout. No one wants to refetch those plugins for now anyway.

**Review by noman2002 — CHANGES_REQUESTED** [review]
Please fix the failing test and conflicting files.

**Comment by literalEval** [comment]
@Ayush0Chaudhary you forgot to update the comment on the Timer. It says 100 seconds :)
Moreover, we recently enforced explicit return type declaration and typed all the functions. Please merge `develop` into your branch accordingly.

**Comment by Ayush0Chaudhary** [comment]
My custom_lint is not working
thus my PRs are getting delayed, and i am not able to make any contributions,
Me and literalEval connected on the meet and were not able to correct the issue

This issue is [faced by many people](https://github.com/invertase/dart_custom_lint/issues/115)

@palisadoes @noman2002 can you suggest what we should do? as these error message is also very vague

**Comment by literalEval** [comment]
@Ayush0Chaudhary have a look at [this guide](https://docs.talawa.io/docs/developers/talawa/talawa-lint). It already covers all the possibilities of documentation.

**Comment by Ayush0Chaudhary** [comment]
Yes the docs exist, but help me with these errors _with the help of docs_

**for example**:

- lib/view_model/main_screen_view_model.dart:143:3 • Wrong doc format.
Add a blank line between the end of 'params:' block
and start of 'returns:' block. • talawa_good_doc_comments
- lib/view_model/main_screen_view_model.dart:33:41 • Prefer documentation for fields. • talawa_api_doc`   


All I have is the error line number and a small error message. Hope you understand my issue.

**Comment by literalEval** [comment]
@Ayush0Chaudhary seems like you figured it out :)

**Comment by Ayush0Chaudhary** [comment]
@palisadoes removed the test for now as I am implementing a temporary fix. Whoever will work on this during GSoC should write the test

Writing test as of now is redundant as webhooks should be a correct implementation of this feature.

**Comment by Ayush0Chaudhary** [comment]
@noman2002 @palisadoes @CyberWake @AdityaBirangal please review the PR

**Comment by Ayush0Chaudhary** [comment]
@noman2002 @palisadoes can you please merge this PR.
It been pending for 2 weeks now!

as mentioned earlier 
I removed the test for now as I am implementing a temporary fix. Whoever will work on this during GSoC should write the test with his implementation.

Writing test as of now is redundant as webhooks should be a correct implementation of this feature.

**Comment by Ayush0Chaudhary** [comment]
@palisadoes @CyberWake @AdityaBirangal @DMills27
 resolved the conflicts

**Comment by literalEval** [comment]
@palisadoes merging this will allow us to deploy our instances of talawa API. The current codebase unnecessarily polls the server and overruns the deployment (and they start asking for money :( ). This PR will surely help to simplify the development for people like me. Please consider merging this.

**Comment by palisadoes** [comment]
@Ayush0Chaudhary Please fix the failing tests. This is a valuable PR, but we also need to be sure it creates code that won't fail. Our reviewers will typically only look at PRs that are passing.

**Comment by Ayush0Chaudhary** [comment]
No test are failing @palisadoes. The action is failing because the code coverage is reduced.
I removed some tests because they were written just to increase the code coverage and were failing on timer implementation.

As we have discussed in the meet too, a new implementation to handle plugins should be implemented, so writing tests for this file now will be redundant.

If you still want me to write the tests. I'll do it.

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
