### PR TITLE
Chore: redesign the select organisation screen.

### PR DESCRIPTION
**Pull request by Ayush0Chaudhary**
Fixes https://github.com/PalisadoesFoundation/talawa/issues/1894
**What kind of change does this PR introduce?**
redesign the select organisation screen.

**Did you add tests for your changes?**

**Snapshots/Videos:**

https://github.com/PalisadoesFoundation/talawa/assets/95746190/1d16c489-6a06-4259-9038-a650423c88ad

image

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**
no

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**

### CODE REVIEW

**Comment by Cioppolo14** [comment]
@Ayush0Chaudhary Is there an issue associated with this PR?

**Comment by palisadoes** [comment]
@Ayush0Chaudhary Please create an issue for this PR. Please follow the procedure.

**Comment by Ayush0Chaudhary** [comment]
> @Ayush0Chaudhary Is there an issue associated with this PR?

Apologies missed your message!
No, but I will create it ASAP.


> @Ayush0Chaudhary Please create an issue for this PR. Please follow the procedure.

Understood, creating the issue.

**Comment by palisadoes** [comment]
Please fix the failing tests

**Review by noman2002 — APPROVED** [review]
Looks good to me. This can be merged. 
Code coverage acceptance level need to be updated @palisadoes .

**Review by palisadoes — APPROVED** [review]

**Comment by palisadoes** [comment]
What level do you think we should set?

**Pull request merged**
