### PR TITLE
Fixes #2098 Fix:Overflow Error on PostWideget

### LINKED ISSUE #2098: Bug Report: Overflow Error on Post Widget.
**Describe the bug**

Upon Creating a post from Post Page 
Post widget is throwing overflow error. 

This is due to the sizedBox declared of size not dependent to the screen in the Post widget

**To Reproduce**

1. Run this App on the Pixel 3A_API 34 Extension_level 7 Emulator
2. Create a New Post
3. Check on Feeds Page

**Expected behavior**
The Sized Box which is used to create white space is expected to be dependent on Screen width

**Actual behavior**
Constant Size SizedBox is used, which is causing this overflow error

**Screenshots**
image

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by AyushRaghuvanshi**
**What kind of change does this PR introduce?**

Previously Post Widget was showing overflow error on phones with smaller width. This PR makes the Post Widget Dynamic. so that it is compatible with all the phone sizes

**Issue Number:**

Fixes #2098

**Did you add tests for your changes?**
No, There was no need

**Snapshots/Videos:**
Previously
image

Now
image

**Does this PR introduce a breaking change?**
No,

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by noman2002** [comment]
@AyushRaghuvanshi Please fix the failing test.

**Review by noman2002 — CHANGES_REQUESTED** [review]
Please reduce the size of like and comment icon as per screen size.

**Comment by AyushRaghuvanshi** [comment]
Ohkay working on it.

**Comment by noman2002** [comment]
> Ohkay working on it.

Thanks.

**Review by noman2002 — APPROVED** [review]
Looks good to me.

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
