### PR TITLE
fixed select image on add_post_page.dart #1569

### PR DESCRIPTION
**Pull request by Omegaviv**
Looks like the #1569 feature was already there, there was some issue with the image picker, which I solved. 
If this looks good let me know, I am attaching a video for reference. 

https://user-images.githubusercontent.com/86337946/221771633-1e6b15ad-9278-4879-9cfd-2ade448beb1b.mp4

### CODE REVIEW

**Comment by Omegaviv** [comment]
Before writing the test, I was thinking of completing all the features of the add_post_page.dart, then I will create an issue to write the test for the complete page altogether, does that sounds good @noman2002?

**Review by palisadoes — DISMISSED** [review]
Please write the respective tests for this feature as part of this PR.

Then write the remaining tests when the rest is updated.

Typically tests get forgotten and reduce our code base's reliability which has been a historically poor

**Comment by Omegaviv** [comment]
okay I will write the test, and push it here

**Comment by Omegaviv** [comment]
@palisadoes @noman2002 does this looks good?

**Comment by Omegaviv** [comment]
I ran flutter format --set-exit-if-changed . still it is failing test

**Comment by palisadoes** [comment]
Upgrade to the latest version of flutter. That should fix it

**Comment by palisadoes** [comment]
Please fix the failing test.

**Comment by palisadoes** [comment]
If you click on the error link, the answer to what to do is there.

**Comment by Omegaviv** [comment]
> If you click on the error link, the answer to what to do is there.

it says to me to run dart format --set-exit-if-changed . 
I did but still facing the same issue

**Comment by palisadoes** [comment]
Upgrade to the latest version of flutter and try again. We recently upgraded

**Comment by palisadoes** [comment]
Run "dart format" and commit the changes to this PR

**Comment by Omegaviv** [comment]
@TheHazeEffect @noman2002 could you please help? I would also like to work on other issues after this is closed

**Comment by palisadoes** [comment]
@Omegaviv Are you still working on this? Fixing the failing workflow requires you to run flutter format, then submit the changes as a commit to this PR.

Let me know soon. I'll have to close this in a day so that others can get a chance to work on the issue.

**Comment by TheHazeEffect** [comment]
Hey @Omegaviv We'd love to get these changes in. Could you run 'dart format' to fix the formatting errors

**Comment by Omegaviv** [comment]
@TheHazeEffect I did run dart format and flutter format both, but there was no change in the file with those, I have already tried before and pushed. I still don't get where is the formatting issue

**Comment by palisadoes** [comment]
- Are you using the latest version of flutter?
- Please check the #talawa slack channel for further assistance.

**Comment by palisadoes** [comment]
Please ask the #talawa channel too. You are more likely to get a quick response there.

**Comment by palisadoes** [comment]
We have a new check in place. All Talawa mobile app methods, classes and functions need to have suitable comments. Please refer to this issue as  reference for what is now required. The aim is to help us improve the quality of our automated documentation on docs.talawa.io.
 
- https://github.com/PalisadoesFoundation/talawa/issues/1479

To fix this issue:

1. You will be required to remove a line containing `ignore_for_file`
1. After doing so you'll be requested to update the comments appropriately

We have also tried to make the documentation step automatically update your IDE with a custom Linter. If you have any comments, please contact @literalEval who worked on this code.

**Comment by CyberWake** [comment]
@Omegaviv please run the `flutter format .` inside the root folder update the commit and push the new changes so that the workflow proceeds with the following checks.

**Review by noman2002 — CHANGES_REQUESTED** [review]
Fix the failing test.

**Comment by Omegaviv** [comment]
> @Omegaviv Please write valid documentation for your files. Can look [here](https://docs.talawa.io/docs/developers/talawa/talawa-lint) and also at INSTALLATION.md and CONTRIBUTING.md

okay

**Comment by Omegaviv** [comment]
@literalEval I have tried to give documentation to all the files I have worked on, but I am not sure about add_post_page.dart file can you have a look and tell if it's correct?

**Comment by literalEval** [comment]
@Omegaviv don't use `params:` and `returns:` for classes. You can document the arguments its constructor takes without these blocks.

**Comment by Omegaviv** [comment]
> @Omegaviv don't use `params:` and `returns:` for classes. You can document the arguments its constructor takes without these blocks.

so right now there won't be any issue if I don't give any documentation to add_post_page.dart file, right?

**Comment by literalEval** [comment]
That's not right. You'll need the documentation for the class. It's just that you don't need to write `returns:` there and write the stuff in `params:` without it.

**Comment by palisadoes** [comment]
@Omegaviv This is an important feature. Do you think you'll be able to achieve it in the next few days?

**Comment by literalEval** [comment]
@Omegaviv do you need help ?

**Comment by CyberWake** [comment]
@Omegaviv please try fixing the following files stated in the attachment which cause the things to break in workflow.
 Screenshot 2023-03-12 at 9 05 15 PM

**Comment by palisadoes** [comment]
@Omegaviv I'm going to have to close this issue in a few hours. This is an important bug that needs to be fixed. I'll have to assign it to someone else.

**Comment by Omegaviv** [comment]
> @Omegaviv do you need help ?

that would be great, can you please tell me what changes should I make to multi_media_pick_service.dart and add_post_page.dart file to make this work?

**Comment by literalEval** [comment]
@Omegaviv remove the two `/// ignore:...` lines from both files.
Then write documentation for the fields wherever necessary. Refer [this guide](https://docs.talawa.io/docs/developers/talawa/talawa-lint) for more information.

**Comment by palisadoes** [comment]
@Omegaviv I'm going to close this PR. We need to get this feature deployed shortly. I'll also unassign you from the issue. Please comment in the issue if you want to be reassigned, but only if you have found a solution and it is not already assigned.

**Pull request closed without merging**
