### PR TITLE
test added for explore_events_view_model

### LINKED ISSUE #1011: Unittests for explore_events_view_model.dart
We will need unittests done for all methods, classes and functions found in this file.

Any widgets referenced in this file must also have unittests done

```
after_auth_view_models/event_view_models/explore_events_view_model.dart
```

This file can be found in the `lib/view_model` directory

Parent Issue: 
- https://github.com/PalisadoesFoundation/talawa/issues/1023
### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base.
- [The current code coverage for the file can be found here](https://codecov.io/gh/PalisadoesFoundation/talawa/tree/develop/lib/view_model/after_auth_view_models/event_view_models)
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide

### PR DESCRIPTION
**Pull request by ItsAdityaKSingh**
**What kind of change does this PR introduce?**

Added test for explore_events_view_model

**Issue Number:**

Fixes #1011 

**Did you add tests for your changes?**

Yes

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by palisadoes** [comment]
Please fix the failing tests

**Comment by ItsAdityaKSingh** [comment]
@palisadoes analyze tests are not failing on my local system. Any idea what is wrong?

**Comment by palisadoes** [comment]
Click on the Details link and you will see.

**Comment by palisadoes** [comment]
[Here is the link](https://github.com/PalisadoesFoundation/talawa/runs/5057308571?check_suite_focus=true)

**Comment by ItsAdityaKSingh** [comment]
Yes, @palisadoes. I saw the details and ran the linting tests locally but saw no errors.
Here's a snapshot:

Screenshot 2022-02-04 at 4 28 35 PM

**Comment by palisadoes** [comment]
You may have to upgrade your version of flutter. [PrimaryVariant and SecondaryVariant are deprecated features according to the documentation](https://api.flutter.dev/flutter/material/ColorScheme/ColorScheme.html). Please replace these in the use of the ColorScheme constructor in the code base.

**Comment by ItsAdityaKSingh** [comment]
I am running the latest Flutter version, and the issues are arising on files I haven't changed and are from the original codebase. Changing those would cause other tests to fail.

**Comment by palisadoes** [comment]
I've created this issue to fix it. This and future PRs will be dependent on fixing the error.

- https://github.com/PalisadoesFoundation/talawa/issues/1190

Is anyone interested in working on this?

**Comment by ItsAdityaKSingh** [comment]
Yup! I would like to solve it to further work on my issues without any problems :)

**Comment by palisadoes** [comment]
Please fix the failing tests

**Comment by ItsAdityaKSingh** [comment]
Hey @palisadoes. I am new to writing tests, and I can't figure out why my tests fail here. Trying though!

**Comment by palisadoes** [comment]
Ask @DeltaHarbinger, @utkarshshendge, @CyberWake Ritik or @rutvik11062000 They should be able to assist. They are all in slack. Check their GitHub profiles for their names.

**Comment by palisadoes** [comment]
@Sagar2366 Can also assist. I spoke to him a few minutes ago.

**Comment by Sagar2366** [comment]
@ItsAdityaKSingh there are few TC's failing -

1>>
01:42 +128: /home/runner/work/talawa/talawa/test/widget_tests/home_page_test.dart: HomePage Widget Test Testing if Events Screen Shows up                                                              
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following assertion was thrown running a test (but after the test had completed):
The finder "zero widgets with icon "IconData(U+0E241)" (ignoring offstage widgets)" (used in a call
to "tap()") could not find any matching widgets.

When the exception was thrown, this was the stack:
#0      WidgetController._getElementPoint (package:flutter_test/src/controller.dart:900:7)
#1      WidgetController.getCenter (package:flutter_test/src/controller.dart:839:12)
#2      WidgetController.tap (package:flutter_test/src/controller.dart:273:18)
#3      main.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///home/runner/work/talawa/talawa/test/widget_tests/home_page_test.dart:79:24)
<asynchronous suspension>
════════════════════════════════════════════════════════════════════════════════════════════════════

2>>
02:09 +165 -1: loading /home/runner/work/talawa/talawa/test/view_model_tests/after_auth_view_model_tests/event_view_model_tests/explore_events_view_model_test.dart [E]                                
  Failed to load "/home/runner/work/talawa/talawa/test/view_model_tests/after_auth_view_model_tests/event_view_model_tests/explore_events_view_model_test.dart":
  'package:get_it/get_it_impl.dart': Failed assertion: line 372 pos 7: 'instanceFactory != null': Object/factory with  type EventService is not registered inside GetIt. 
  (Did you accidentally do GetIt sl=GetIt.instance(); instead of GetIt sl=GetIt.instance;
  Did you forget to register it?)
  dart:core                                                                                                           _AssertionError._throwNew
  package:get_it/get_it_impl.dart 372:7                                                                               _GetItImplementation._findFactoryByNameAndType
  package:get_it/get_it_impl.dart 393:29                                                                              _GetItImplementation.get
  package:get_it/get_it_impl.dart 430:12                                                                              _GetItImplementation.call
  package:talawa/view_model/after_auth_view_models/event_view_models/explore_events_view_model.dart 12:32             new ExploreEventsViewModel
  test/view_model_tests/after_auth_view_model_tests/event_view_model_tests/explore_events_view_model_test.dart 41:40  main

Please check details in "PR Workflow / Testing codebase (pull_request) Failing after 4m — Testing codebase"

Also, can you try to run test suite only for the file in which you added new tests for your code change and share report.

**Comment by ItsAdityaKSingh** [comment]
@Sagar2366 I have checked the error message, but I'm quite not sure what's the issue. Also, it shows an issue on a test that I haven't changed. I have pinged you on Slack with the details!

**Comment by palisadoes** [comment]
Are you still working on this?

**Comment by ItsAdityaKSingh** [comment]
> Are you still working on this?

Didn't get any reply of my problem :( 
Currently working on another issue.

**Comment by palisadoes** [comment]
OK, I'm going to close this PR and unassign the issue.

**Pull request closed without merging**
