### PR TITLE
Add Multi-reaction functionality.

### LINKED ISSUE #2039: [GSoC] Add multi-reaction feature on mobile app
**Is your feature request related to a problem? Please describe.**
Adding multireaction feature for post

**Describe the solution you'd like**
add multireaction on the app side, whenever the user click on the like button.

**Additional context**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by Ayush0Chaudhary**
**What kind of change does this PR introduce?**
https://github.com/PalisadoesFoundation/talawa/issues/2039
Added multireaction to the mobile side

**Issue Number:**

Fixes #2039

**Did you add tests for your changes?**
yes

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

**Other information**
[Uploading Screen_recording_20231005_131653.zip…]()

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**
yes

### CODE REVIEW

**Comment by palisadoes** [comment]
Please check the code coverage

**Review by noman2002 — COMMENTED** [review]
Looks good to me. Can we get the coverage up by 2% so that it passes the minimum acceptable threshold.

**Comment by Ayush0Chaudhary** [comment]
> Please check the code coverage

the code coverage is increasing right?

**Comment by noman2002** [comment]
@palisadoes Can we reduce the min acceptable coverage to 76%. ?

**Comment by palisadoes** [comment]
> @palisadoes Can we reduce the min acceptable coverage to 76%. ? or may be 76.5%. Currently, its 78%.

Done

**Comment by noman2002** [comment]
@Ayush0Chaudhary Take a pull from develop and push it here. Then I think the tests will pass.

**Comment by Ayush0Chaudhary** [comment]
@palisadoes can we merge it?

**Pull request merged**
