### PR TITLE
added the autofill option in the form and made the Docker container for the same and made the instruction.

### PR DESCRIPTION
**Pull request by yasharth291**
added autofill option in the form and updated the packages and made the errors go away

### CODE REVIEW

**Comment by yasharth291** [comment]
the readme file is all set to be merged

**Review by DeltaHarbinger — CHANGES_REQUESTED** [review]
Hey @yasharth291, it seems that the file .flutter-plugins-dependencies needs to be added to the .gitignore. This needs to be added before we can accept it

**Comment by yasharth291** [comment]
ok sure I am adding it

**Comment by yasharth291** [comment]
actually  its added already as .packages
i can add dockerignore as the file

**Comment by Sagar2366** [comment]
@yasharth291, flutter-plugins-dependencies is auto generated file as per comment. Adding its name to .gitignore will skip it from copying it to local system whenever someone clones the repo and also it's not required to be copied as its going to auto-generate. Adding this file name into .dockerignore will skip it to be part of build context in docker build. You can add .dockerignore file with all file names which are not required to be present in build context.

**Comment by yasharth291** [comment]
yeah i know about it and was asking whether to add it in the dockerignore file or not, that was my question not the thing you answered

**Comment by yasharth291** [comment]
Capture
and its already present in the gitignore file

**Comment by yasharth291** [comment]
@DeltaHarbinger  i have added the .dockerignore file now this pr can be merged i guess

**Comment by yasharth291** [comment]
Here i added the Camera feature and it is  working for both ios and android

**Comment by Sagar2366** [comment]
@yasharth29, my advice is raise separate PR's for different issues or for different contributions. Don't mix everything in single PR.

**Comment by yasharth291** [comment]
yeah i totally agree and do the same from next time

**Pull request merged**
