### PR TITLE
corrected tasks in event detail

### PR DESCRIPTION
**Pull request by pr4nshul**
**What kind of change does this PR introduce?**
See issue #507 

**Did you add tests for your changes?**
No
**If relevant, did you update the documentation?**
No
**Summary**
There was a typo , while retrieving tasks. I corrected it and the error was solved.
I also added a **"No Tasks found"** and **"No Registrants found"** if `eventsLength` is 0.

**Does this PR introduce a breaking change?**
No

**Other information**

### CODE REVIEW

**Comment by pr4nshul** [comment]
Screenshot_20210325-220727

I know, I wasn't assigned this @Sagar2366  but as I resolved my previous issue and this was also a minor bug, I worked on it. And as you can see there wasn't any major issue here.

**Comment by pr4nshul** [comment]
And as I have added in summary if you think I should add that enhancement to this page as well , let me know I would push the commit for that.

**Comment by Sagar2366** [comment]
Closing this PR as it is covered in recent master changes.

**Comment by pr4nshul** [comment]
@Sagar2366  If you add a tasks it will show this error, I am still getting it on the latest master. You need to add a task first.

**Comment by pr4nshul** [comment]
If the lists of tasks would be empty, it will show a blank screen. And as you can see on the changes itself there is typo.

**Comment by pr4nshul** [comment]
Btw, do want me to push no tasks and no registrants enhancement?

**Comment by Sagar2366** [comment]
> Btw, do you want me to push the no tasks and no registrants enhancement?

Yes, please update the issue and PR title, description accordingly.

**Comment by pr4nshul** [comment]
Hey @Sagar2366  can you please review it again?

**Review by Sagar2366 — APPROVED** [review]

**Pull request merged**
