### PR TITLE
Fixes #1256 : Removed hard coded Heroku instance URL from code base and improved documentation.

### LINKED ISSUE #1256: Remove hard coded Heroku instance URL from code base
**Describe the bug**

The Talawa App's default URL points to our Heroku test instance at  [talawa-graphql-api.herokuapp.com/graphql](https://talawa-graphql-api.herokuapp.com/graphql). This is not sustainable as real organizations should not be using our test instance for their members.

This needs to be fixed before we can do Alpha testing.

**To Reproduce**

Install Talawa. The default Heroku instance URL will be populated in the opening screen.

**Expected behavior**

1. The hard coded Heroku instance URL needs to be removed from the code base
1. The test cases need to be updated to reflect the change
1. A Talawa INSTALLATION.md document needs to be created to let new developers know:
    1. How to install and run Talawa
    1. The API URLs to use for the most common use cases. (ie developers on a local machine, developers on a local machine using Docker, a remote machine) References to the API documentation may be useful here.
1. Existing instructions in the README.md file should be moved to the new INSTALLATION.md file. 
1. A reference to the new installation document must be maintained.

**The documentation needs to be FLAWLESS.** Time will need to be taken to ensure that all new users understand what to do to make the app work. Step by step instructions will need to be provided.

Anyone must be able to run Talawa without incident when this bug issue is resolved.

**Actual behavior**

The URL defaults to our test Heroku instance.

**Screenshots**

N/A

**Additional details**

N/A

### PR DESCRIPTION
**Pull request by noman2002**
**What kind of change does this PR introduce?**
Refractoring

**Issue Number:**

Fixes #1256 

**Did you add tests for your changes?**
All tests passed, no changes were required.

**Snapshots/Videos:**
N/A

**If relevant, did you update the documentation?**

**Summary**
 Removed hard-coded Heroku instance URL from the code base and improved documentation.

**Does this PR introduce a breaking change?**
No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**
YES

### CODE REVIEW

**Comment by noman2002** [comment]
The test is failing here but all tests are passed on my local machine.
Screenshot from 2022-03-11 16-16-08

**Comment by palisadoes** [comment]
It looks like it's failing on test 44:

- [Details](https://github.com/PalisadoesFoundation/talawa/runs/5509542319?check_suite_focus=true)

**Comment by noman2002** [comment]
> It looks like it's failing on test 44:
> 
>     * [Details](https://github.com/PalisadoesFoundation/talawa/runs/5509542319?check_suite_focus=true)

Please re-run the tests, it was failing earlier also in the previous PR.

**Comment by palisadoes** [comment]
OK. It's working now. Please try to get the code coverage on `set_url.dart` to 100%. The code coverage test should pass then.

**Comment by noman2002** [comment]
For increasing the test coverage do I have to improve the test cases?

**Comment by palisadoes** [comment]
> For increasing the test coverage do I have to improve the test cases?

Yes

**Comment by noman2002** [comment]
I have increased the test coverage on `set_url.dart`. All checks are passed now. @palisadoes

**Comment by palisadoes** [comment]
Why have you modified INSTALLATION.md and README.md? Please remove those from the PR.

If changes need to be made to these files, please create another issue for these changes.

**Review by palisadoes — CHANGES_REQUESTED** [review]
Why have you modified INSTALLATION.md and README.md? Please remove those from the PR.

If changes need to be made to these files, please create another issue for these changes.

**Comment by noman2002** [comment]
> Why have you modified INSTALLATION.md and README.md? Please remove those from the PR.
> 
> If changes need to be made to these files, please create another issue for these changes.

It is mentioned in the issue #1256  to create INSTALLATION.md and move the installation guide from READM.md

**Comment by palisadoes** [comment]
OK. @Sagar2366 @TheHazeEffect @DeltaHarbinger Please review.

**Review by TheHazeEffect — APPROVED** [review]
Covers all the issue acceptance criterias 

Good job, looks good to me

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
