### PR TITLE
added the camera feature for taking the profile photo

### PR DESCRIPTION
**Pull request by yasharth291**
it is pull request regarding the enhancement of a feature from #135

### CODE REVIEW

**Comment by Sagar2366** [comment]
@yasharth291 resolve the conflicts on this PR.

**Comment by yasharth291** [comment]
it is not allowing me to do so only those having write access can do 

Screenshot_20210313-142853

**Comment by yasharth291** [comment]
@DeltaHarbinger @heyjordn @jordanliu  all the conflicts has been resolved now it is ready to be merged

**Review by DeltaHarbinger — CHANGES_REQUESTED** [review]
Hey @yasharth291, it seems like another request that got merged conflicts with this one. Once the issue in 'events.dart' is resolved, we can merge this

**Comment by yasharth291** [comment]
this is resolved @DeltaHarbinger

**Review by DeltaHarbinger — APPROVED** [review]
Thanks for resolving your issues. Your changes will be merged

**Pull request merged**
