### PR TITLE
New User signup home screen issue after successful login. #288

### PR DESCRIPTION
**Pull request by CyberWake**
**What kind of change does this PR introduce?**
Perfect navigation on new user successful signup and create or join organization

**Did you add tests for your changes?**
Yes, have tested it on both android and iOS simulator

**If relevant, did you update the documentation?**
No, need to update the documentation
**Summary**
Major functionality of app came to live because without bottom navbar app was almost dead or void.

**Does this PR introduce a breaking change?**
No, this does not bring breaking changes

**Other information**
#288 #287

### CODE REVIEW

**Comment by CyberWake** [comment]
please someone review this PR.😊

**Comment by CyberWake** [comment]
This one also resolves #287 which is a issue not described the same as #288 before the edit.

**Comment by sumitra19jha** [comment]
Hey @CyberWake 
You made a change in orgURL
```
orgUrl = "${dropdownValue.toLowerCase()}://${urlController.text}/talawa/graphql/";
```

While your graphql client has no change added in it.
```
  static HttpLink httpLink = HttpLink(
    uri: "${orgURI}graphql",
  );
```

This will make following http link during call:
```
${dropdownValue.toLowerCase()}://${urlController.text}/talawa/graphql/graphql
```

**Comment by CyberWake** [comment]
Closing this one as this branch contains commits from other branches. Will create a new PR against the issue #288.

**Comment by CyberWake** [comment]
Please review the new PR #310

**Pull request closed without merging**
