### PR TITLE
[Fix] Event list shows wrong data after deleting an event

### LINKED ISSUE #781: [Bug] Event list shows wrong data after deleting an event
**Describe the bug**
After deleting events marked as _Today_ the event list updates normally, but the timeline does not change from _Today_ to _All_

**To Reproduce**
1. Delete an event that comes under the _Today_ list. 
2. You can observe that the 

timeline does not change from _Today_ to _All_

**Expected behavior**
The timeline should change from _Today_ to _All_ after the event list is updated.

**Screenshots**

https://user-images.githubusercontent.com/57677520/118015202-a6708380-b371-11eb-963c-413585bb1a9e.mp4

**Additional details**
If you are interested in working on this issue, please ask mentors/maintainers to assign this issue to you.

### PR DESCRIPTION
**Pull request by Raunakk02**
**What kind of change does this PR introduce?**
Fixes after deleting events marked as Today the event list updates normally, but the timeline does not change from Today to All

**Did you add tests for your changes?**
No

**If relevant, did you update the documentation?**
No

**Summary**
Resolves #781 

**Does this PR introduce a breaking change?**
No

### CODE REVIEW

**Comment by palisadoes** [comment]
@Raunakk02  `flutter test` is not working correctly on your code. This is causing Travis CI to fail. 

1. Follow the steps in the GitHub site's [Checking out pull requests locally](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/reviewing-changes-in-pull-requests/checking-out-pull-requests-locally) web page.
2. Resolve the conflicts, which appear related to `pubspec.yml`
3. Resubmit your pull request.

The error can be seen below

image

**Comment by Sagar2366** [comment]
@Raunakk02 any progress on this issue ?

**Comment by Raunakk02** [comment]
> @Raunakk02 any progress on this issue ?

I have fixed the issue now @Sagar2366.

**Review by palisadoes — APPROVED** [review]

**Comment by palisadoes** [comment]
@dellyjm
@DeltaHarbinger
@Sagar2366 

Please take a look and merge

**Review by Sagar2366 — APPROVED** [review]

**Pull request merged**
