### PR TITLE
Fixes #1030

### LINKED ISSUE #1030: [Bug report] Inconsistencies in Password RegEx
**Describe the bug**
when I'm signing myself for he app it says invalid password but doesn't say why, i looked in code there's a regex pattern it should follow. It will be helpful for user if shows u what's wrong with password for eg :- If i wrote my password as "Hello@123"
Which is wrong it shouldn't have uppercase letter, and  that it should show to the user. Currently it's just showing INVALID PASSWORD.

**Expected behavior**
It should show user what's the issue in the password.

**Actual behavior**
Right now its just showing "Invalid Password"

Can You assign it to me? Thanks

### PR DESCRIPTION
**Pull request by M-A-D-A-R-A**
Fixes #1030 

So,I'm Successfully able to get the correct error for a given password.
WhatsApp Image 2021-12-13 at 22 23 21

But now it's not showing on the test form validation i checked it's returning the value to the sign up page but not showing the message regarding that password.

image

Will Fix that in next commit.

### CODE REVIEW

**Comment by palisadoes** [comment]
@M-A-D-A-R-A Tests are failing. The code base has been updated with a more recent pull request that should have fixed the issue. Please merge your branch with the lastest `upstream/develop` and push to your repo. GitHub should detect the changes and re-run the tests on the updated code.

**Comment by M-A-D-A-R-A** [comment]
> @M-A-D-A-R-A Tests are failing. The code base has been updated with a more recent pull request that should have fixed the issue. Please merge your branch with the lastest `upstream/develop` and push to your repo. GitHub should detect the changes and re-run the tests on the updated code.

I actually did `git pull` before commiting and pushing and creating a PR i dont know why that i case is still failling.

**Comment by palisadoes** [comment]
@M-A-D-A-R-A [Please resolve the errors that are causing Travis CI to fail](https://app.travis-ci.com/github/PalisadoesFoundation/talawa/builds/243449525)

**Comment by M-A-D-A-R-A** [comment]
PR failing i think the issue is fixed closing this PR.

**Pull request closed without merging**
