### PR TITLE
Fixes #1347: Added feature to see, accept and decline membership request from the app.

### LINKED ISSUE #1347: Feature Request: Member Management Feature through mobile app
**Is your feature request related to a problem? Please describe.**
Add feature for accepting and declining membership request from the app.

**Describe the solution you'd like**
Having a screen which is only visible to admin to where they can see pending requests and then accept and decline it.

### PR DESCRIPTION
**Pull request by noman2002**
**What kind of change does this PR introduce?**
Feature

**Issue Number:**

Fixes #1347 

**Did you add tests for your changes?**
Yes

**Snapshots/Videos:**
drawing   drawing
 drawing   drawing

**Summary**
I have created a page which can only be accessed by admin and superadmin where they can find pending requests with some description about the person and then accept or decline the request from the mobile itself.

**Does this PR introduce a breaking change?**
No

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**
yes

### CODE REVIEW

**Comment by palisadoes** [comment]
@noman2002 Please fix the failing tests. I'd like to merge this into the code base soon.

**Comment by palisadoes** [comment]
The code coverage has declined significantly. How can you restore it back to 71% of better?

**Comment by noman2002** [comment]
@palisadoes should I close this PR?. As we have planned not to keep any admin features in the mobile app. This PR includes various admin features in the mobile app. I think we should close this for now. 
What's your thought on this ?

**Comment by palisadoes** [comment]
Yes we should close it.

**Pull request closed without merging**
