### PR TITLE
Make update event more intuitive/discoverable

### LINKED ISSUE #1588: Create a more intuitive design for editing a given event
**Is your feature request related to a problem? Please describe.**
In the events details page there are some edit options in the hamburger menu at the bottom right-hand side of the page. This is unintuitive can could be better design with better iconography.

Screenshot at Feb 27 07-23-59

Screenshot at Feb 27 07-24-33

See the video below till 6:42

[Follow the steps outlined here till the 50 second mark](https://www.youtube.com/watch?v=ix3eSReJj2k?t=372)

**Describe the solution you'd like**
We need a more useful way of describing the edit functionality such as using a pencil icon rather than a hamburger menu, and perhaps placing it in a better area on the screen. 

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by ikjot-2605**
**What kind of change does this PR introduce?**

Makes the edit event option more discoverable for the event creator. 

**Issue Number:**

Fixes #1588 

**Did you add tests for your changes?**

Yes

**Snapshots/Videos:**

image

**If relevant, did you update the documentation?**

N/A

**Does this PR introduce a breaking change?**

No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by DMills27** [comment]
You haven't removed the hamburger menu with the edit details, so the options to edit the page will appear twice on this page. Also, the placement of the pencil icon is arguably less intuitive because it suggests you want to edit the name of the event and not the details.

**Comment by palisadoes** [comment]
Please provide screenshots

**Comment by palisadoes** [comment]
The last option

**Comment by DMills27** [comment]
you still need to remove the hamburger menu, the pencil icon superceded the hamburger menu for making edits. It serves no purpose to keep it there.

**Comment by ikjot-2605** [comment]
> you still need to remove the hamburger menu, the pencil icon superceded the hamburger menu for making edits. It serves no purpose to keep it there.

Yes, I'm on it.

**Comment by ikjot-2605** [comment]
@DMills27 I've made the changes, please review.

**Comment by palisadoes** [comment]
Please upload the new screenshots

**Comment by ikjot-2605** [comment]
> Please upload the new screenshots

image

Here it is @palisadoes

**Comment by palisadoes** [comment]
- @DMills27 please take a look. 
- @ikjot-2605 where is the back button?

**Comment by ikjot-2605** [comment]
> * @DMills27 please take a look.
> 
>     * @ikjot-2605 where is the back button?

Apologies, this screenshot was taken before the latest commit - where I was testing out the page with `demoEventData`. The back button is still there, and I have verified the same as well(with the tests also).

**Comment by palisadoes** [comment]
Please add the latest screenshot

**Comment by ikjot-2605** [comment]
> Please add the latest screenshot

image
@palisadoes

**Comment by ikjot-2605** [comment]
> Please add the latest screenshot
image

@palisadoes

**Comment by DMills27** [comment]
Don't let the trash can icon simply delete the event but rather prompt the user with a 'yes' or 'no' if the event should be deleted and delete it if they choose 'yes'.

**Comment by ikjot-2605** [comment]
> Don't let the trash can icon simply delete the event but rather prompt the user with a 'yes' or 'no' if the event should be deleted and delete it if they choose 'yes'.
@DMills27 
That is already implemented from before. In the current behavior, when the user presses the "Delete" FAB, a dialog box shows up.

**Review by palisadoes — APPROVED** [review]

**Review by DMills27 — APPROVED** [review]
LGTM

**Pull request merged**
