### PR TITLE
Splash Screen Added

### PR DESCRIPTION
**Pull request by ahluwaliatikant**
**What kind of change does this PR introduce?**
This PR fixes issue #814 . Earlier whenever the app is opened, a blank white screen was being displayed for a few seconds.
I have added a splash screen with white background and centered talawa logo.

**Did you add tests for your changes?**
No.

**If relevant, did you update the documentation?**
No, updation of documentation was not required.

**Does this PR introduce a breaking change?**
No, it isn't a breaking change.

### CODE REVIEW

**Comment by palisadoes** [comment]
@ahluwaliatikant  `flutter test` is not working correctly on your code. This is causing Travis CI to fail. 

1. Follow the steps in the GitHub site's [Checking out pull requests locally](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/reviewing-changes-in-pull-requests/checking-out-pull-requests-locally) web page.
2. Resolve the conflicts, which appear related to `pubspec.yml`
3. Resubmit your pull request.
4. [Here is the link to the error](https://travis-ci.org/github/PalisadoesFoundation/talawa/builds/771823418?utm_source=github_status&utm_medium=notification)

The error can be seen below:

image

**Comment by ahluwaliatikant** [comment]
@palisadoes Sir, I have fixed the issue which was causing the Travis CI build to fail.

**Comment by TheHazeEffect** [comment]
Nice Job @adithyaakrishna 

Tested and it resolved the issue, merging

**Review by TheHazeEffect — APPROVED** [review]

**Comment by adithyaakrishna** [comment]
Hey @TheHazeEffect 
I guess it was intended for @ahluwaliatikant 😶

**Comment by ahluwaliatikant** [comment]
Thanks @TheHazeEffect !

**Pull request merged**
