### PR TITLE
Add tests for Progress Dialog View Model

### LINKED ISSUE #1019: Unittests for progress_dialog_view_model.dart
The Talawa code base needs to be 100% reliable. This means we need to have 100% unittest code coverage.

We will need unittests done for all methods, classes and functions found in this file.

Any widgets referenced in this file must also have unittests done

```
widgets_view_models/progress_dialog_view_model.dart
```

This file can be found in the `lib/view_model` directory

Parent Issue: 
- https://github.com/PalisadoesFoundation/talawa/issues/1018

### PR DESCRIPTION
**Pull request by SriramPatibanda**
**What kind of change does this PR introduce?**

- Uses get_it for injecting connectivity service as a dependency in the project
- Unit tests for Progress Dialog View Model 
- Ignore files generated by mockito for linting

**Issue Number:**

Fixes #1019 

**Did you add tests for your changes?**

Yes

**Snapshots/Videos:**

N.A.

**If relevant, did you update the documentation?**

N.A.

**Does this PR introduce a breaking change?**

No.

**Other information**

N.A.

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by SriramPatibanda** [comment]
@palisadoes please review this PR whenever possible.

**Comment by palisadoes** [comment]
@SriramPatibanda Please investigate why your the PR tests are failing and modify your code to make sure all the tests pass.

**Comment by SriramPatibanda** [comment]
> @SriramPatibanda Please investigate why your the PR tests are failing and modify your code to make sure all the tests pass.

@palisadoes I've looked into the issue and it's caused due to unrequired package imports at 8 diff files that are there in the project. Therefore, even the tests on other pull requests are failing.

I've made the necessary changes and can push a commit here itself. But, since the tests are failing for other PR's also, I would recommend you to review and merge this first so that the problem is solved for every PR.

**Comment by SriramPatibanda** [comment]
As you can see, all the checks have passed.

**Comment by palisadoes** [comment]
OK, @rutvik11062000, @TheHazeEffect, @sumitra19jha, @CyberWake please take a look at the tests in this PR.

**Comment by palisadoes** [comment]
@rutvik11062000 @sumitra19jha @CyberWake @TheHazeEffect Please review

**Comment by palisadoes** [comment]
@sumitra19jha  Please review.

**Comment by palisadoes** [comment]
@rutvik11062000, @TheHazeEffect, @sumitra19jha, @CyberWake please take a look at the tests in this PR. This is PR needs to be approved and merged to fix our GitHub actions that are failing.

**Review by sumitra19jha — APPROVED** [review]

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
