### PR TITLE
FixCroppingImageBug

### LINKED ISSUE #1681: MultiMediaPickerService : Exception occurred while cropping Image
**Describe the bug**
on the `add new post screen`,  clicking to the `image Icon` after selecting an image from gallery then clicking the **done button**, unfortunately the `getImageFromGallery/cropImage` function, does not return any XFile or any path, that's mean that the function is not working properly, where is should return some path which i can use for adding or previewing the image inside the app so the user could be sure that the image is selected.
somehow this issue is related to **#1569** as we should fix this issue before trying to work on **#1569** because it depends on this issue

**To Reproduce**

1.making the `getImageFromGallery `return a xfile path (after applying the crop function)

**Expected behavior**
returning the image path

**Actual behavior**
no path is returned after the async function **completes**
**Screenshots**
Screen Shot 2023-03-19 at 21 07 55
WhatsApp Image 2023-03-19 at 9 08 31 PM

### PR DESCRIPTION
**Pull request by khaledmurtaja**
**What kind of change does this PR introduce?**
  `bugfix `

**Issue Number:**

Fixes: #1681 ,#1569
This PR Closes #1681,#1569

**Did you add tests for your changes?**
Tested manually, there is no  big change.

**Snapshots/Videos:**
i will post an image of the path of the file returned after the `cropImage` function completes , **another image  to prove that #1569 was solved  too.**

**If relevant, did you update the documentation?**
no

**Summary**

**Explain the **motivation** for making this change. What existing problem does the pull request solve?** 

The bug was preventing the user from uploading images with his posts, now after the change the user is able to interact with community and upload images with his/her posts make them more interactive and intresting.
The upload image is a feature which is well documented in the Talawa docs, with this change we will make our source code meet the docs at the point of `uploading images with posts`
**Does this PR introduce a breaking change?**
No.

**what was causing the BUG**
The `cropImage` Function was returning the image after the crop operation ends as a `File` and that is wrong cause it will damage the encoding of the image with respect to the cropImageFunction which should return `CroopedFile` not `File`.

WhatsApp Image 2023-03-20 at 12 31 18 PM

**FUN FACT**
issue #1569 which is labeled as a `featureRequest` was already implemented in the code base, but other developers think its not there because there was no image previewing, but the real problem was with encoding of the file returned.

### CODE REVIEW

**Comment by khaledmurtaja** [comment]
> Please fix the failing tests. Our test code coverage system will fail if either of these two conditions occur:
> 
> 1. The overall code coverage drops below the target threshold of the repository
> 2. Any file in the pull request has code coverage levels below the repository threshold
> 
> We do this to ensure the overall reliability of the code base is maintained.

i am working on them  right now we got 5/7 success rate, the overall code coverage will not be affected
can i still push commits to this PR?  because i can not test in my local machine

**Comment by palisadoes** [comment]
Go ahead and let us know when you are finished

**Comment by palisadoes** [comment]
1. Why can't you test on your local machine? It will be much faster if you can do it there.
2. Are you editing the files in your GitHub account using your web browser on the GitHub site?  If you are this will not work. You will need find an alternative solution. We have a limit on the testing resources we use on GitHub. We only have 2000 minutes per month. Please stop immediately if this is your situation. You will jeopardize the whole project.

**Comment by khaledmurtaja** [comment]
> 

i am pushing the edits Form the IDE(android studio), not directly from browser.

**Comment by khaledmurtaja** [comment]
> 1. Why can't you test on your local machine? It will be much faster if you can do it there.
> 2. Are you editing the files in your GitHub account using your web browser on the GitHub site?  If you are this will not work. You will need find an alternative solution. We have a limit on the testing resources we use on GitHub. We only have 2000 minutes per month. Please stop immediately if this is your situation. You will jeopardize the whole project.

okay i will stop. 
i am not familiar with testing, i have 3 lines which is not covered, everything else working fine

**Comment by palisadoes** [comment]
1. You should be able to test in your system.
1. The CONTRIBUTING.md file will have instructions.

**Comment by khaledmurtaja** [comment]
> 1. You should be able to test in your system.
> 2. The CONTRIBUTING.md file will have instructions.

It would be better if you add a visual content about how to test your app on codecov(linking repo to code cov) i have followed instructions but i did not touch the target.

**Comment by khaledmurtaja** [comment]
@palisadoes 
 i can not test locally, my machine is macBook pro with `os10.13 high serria` which is not supported by flutter after the updates. 
 i can use it for **development** purposes, not for **deployments** or **testing**(building an apk or running tests). 
 The min version supported by flutter team right now is **os10.14** and its not supported on my machine. 
 unfortunately, i can not keep working on this PR as long as it needs testing.
  should i close the PR or what is the right thing to do?
[see this](https://docs.flutter.dev/development/tools/sdk/release-notes/supported-platforms)
Screen Shot 2023-03-23 at 12 58 52

**Comment by palisadoes** [comment]
Unfortunately yes. Please ask for advice on what to do on the slack channels. I'll close this and unassign the issue

**Pull request closed without merging**
