### PR TITLE
Fix: Proper State Management (Removal of Pull to Refresh Feature) #334

### PR DESCRIPTION
**Pull request by StrangeNoob**
**What kind of change does this PR introduce?**
Removes the Pull to Refresh Feature. 

**Did you add tests for your changes?**
No
**If relevant, did you update the documentation?**
No.
**Summary**
Need order to Remove the Pull to Refresh, I have to create a proper state management and some changes in API.  But have created a workaround to this a temporary fix. Will Implement this  near future.

**Does this PR introduce a breaking change?**
No.

**Issue No.** #334 
**Snapshot/Videos**

https://user-images.githubusercontent.com/42904343/112524264-a28aa100-8dc5-11eb-907f-a73c93d69f05.mp4

**Other information**

- Have to create a model for the posts.
- After a successful Post Creation, the response should be as the post that are being display. Otherwise, it will give an error generally null value exception.

### CODE REVIEW

**Comment by Sagar2366** [comment]
@StrangeNoob disable auto formatter before raising PR and send PR again with only changes to fix the issue.

**Comment by StrangeNoob** [comment]
@Sagar2366 I am closing this PR and sending it again, Sorry for the inconvenience.

**Comment by ishan0805** [comment]
@Sagar2366 State Management is typically  done so that the whole tree is not rebuild again and again . This PR as I can understand ,doesn't serves that purpose . Whenever user post a news then the whole list is cleared and is rebuild again . In that process the Flutter tree is also build again from scratch .  I would highly recommend using Streams or listener to solve this . 
@StrangeNoob I am not trying to pull you down . Honesty I have not seen such cleaver use of Navigator .
But if you try to implement it using the above mention methods you will definitely learn some thing new .   Peace !!

**Comment by StrangeNoob** [comment]
> @StrangeNoob I am not trying to pull you down . Honesty I have not seen such cleaver use of Navigator .
Thanks, @ishan0805, for the compliment, I am working on the ChangeNotifierProvider. That change will take time that's why I made a workaround for now being.  Thanks for the input @ishan0805 will definitely look into it.

**Comment by StrangeNoob** [comment]
> @StrangeNoob I am not trying to pull you down . Honesty I have not seen such cleaver use of Navigator .


Thanks, @ishan0805, for the compliment, I am working on the ChangeNotifierProvider. That change will take time that's why I made a workaround for now being.  Thanks for the input @ishan0805 will definitely look into it.

**Pull request closed without merging**
